### ISSUE TITLE
Web Discussion

### ISSUE THREAD

**Issue by mberg** [opensrp/fhircore#1]
As we look to a migration to FHIR there are several things we need to explore on the web front.

First, we will need to potentially support two versions of OpenSRP web.  One that we can use to support current projects and one that runs fully off a FHIR backend like HAPI.

**Current Functionality**

- User management - need to work on both OpenSRP web and HAPI
- Locations - need to work on both OpenSRP web and HAPI
- User permissions - ??

**Patient Data View**

We will use FHIR to view data for all OpenSRP projects.  This mean patient views will be powered by a FHIR backend (eg. HAPI). 

For existing projects, we will create a beam process to extract data from OpenSRP and into HAPI.  

For the patient view we should explore multiple strategies:
- I recommend we first setup the [SMART Patient Browser](https://github.com/smart-on-fhir/patient-browser) - [https://github.com/smart-on-fhir/patient-browser](https://github.com/smart-on-fhir/patient-browser).  Goal here would be set it up pointing to HAPI and see if it support a form of authentication.  Ideally, we could connect to Keycloak.
- IHRIS - This is a Vue app developed by intrahealth that is able to view provider data pointing at a HAPI server.  They use SDC configs to configure views I believe.  We should evaluate if we want to borrow from this approach or potentially even build off their app (note would require us switching to Vue).  Here is a [writeup](https://docs.google.com/document/d/1Pr34c_HL5FWuG4X8pjIHGHy9iB5IU8WZWiuk7Xp6-08/edit) Craig did on this.
- We roll on own.  There are a number of interesting FHIR react libraries
 - https://github.com/1uphealth/fhir-react (storybook of components: http://storybook-fhir-react-lib.s3-website-us-east-1.amazonaws.com/?path=/story/allergyintolerance--default-visualization-dstu-2)
 - https://github.com/symptomatic/fhir-starter
 - https://github.com/Vermonster/fhir-kit-create-react (this one looks pretty nice) http://fhir-kit-react.herokuapp.com/ - note example uses Ant too. 
 - https://github.com/Vermonster/fhir-kit-client

- Data Editing and form collection - Need to fill this out but there is a smart on fhir app that links data lookup to web FHIR questionnaires.  

**Reveal**

- If we migrate Reveal to the FHIR SDK - we we'll need to evaluate how plan definitions would work in the future and if we would need to rebuild the UI for those.
- we need to verify how team assignment would work and if the current opensrp web interface would support the plan location assignment.

**Comment by mberg** [comment]
@dubdabasoduba Here is a first draft.  Please feel free to flesh out the stuff above.  In particular, it would be good to work with a front end engineer to research some of the different patient browser options.  Getting the one by vermonster looks pretty cool from an app standpoint.  Let's start by gettin the patient browser setup (we can implement basic auth like .htaccess to start if needed) then look at options.

**Comment by dubdabasoduba** [comment]
https://docs.google.com/document/d/1uwEvvn21Gag6fbTx2PufbJn-ezJ78QvRsH57JixRVQM/edit#

**Comment by dubdabasoduba** [comment]
Already have a functional patient viewer
