### ISSUE TITLE
P2P - Create SyncPayload class for P2P Sync data transfer

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1000]
**Payload**
A new class is needed to encapsulate the data which is exchanged between the sender and receiver during sync.

The class needs to be serializable so that it can be sent over different communication channels such as a socket.

It will need to include:
- The locally updated version of resource.
- The list of local changes which have been made to the resource. The list could be empty for newly created resources, or resources which have not been updated since they were synced from the server. A new class containing only the relevant fields from the `LocalChangeEntity` should probably be used instead of the `LocalChangeEntity` class itself since fields other than `type` and `payload` are not relevant, but this can be decided during development.

```kotlin
data class SyncPayload(val resource: Resource, val patches: List<LocalChangeEntity>)
```

1. This should get all data tied to a Patient with the referenced resources 
2. Data to be synced should be from the same Location Hierarchy i.e.
    - A CHA can only sync to a CHA of the same location 
    - A CHA can only sync to a  CHS of the same location 

The patient data can be sent as FHIR Bundles 

NB. The Practitioner details will help to query which jurisdiction they belong too, but this can be made to be configurable

**Comment by f-odhiambo** [comment]
@dubdabasoduba Check this out

**Comment by Rkareko** [comment]
Shell of SyncPayload class [here](https://github.com/opensrp/p2p/blob/main/app/src/main/java/com/trevorgowing/android/p2p/SyncPayload.kt)

Update the SyncPayload class to handle json data as modeled [here](https://github.com/opensrp/android-p2p-sync/blob/master/p2p-sync/src/main/java/org/smartregister/p2p/sync/data/JsonData.java) . Rename `highestRecordId` param to  `highestValue` (could either be a timestamp or rowId).

LOE 1 - 2 hours
