### ISSUE TITLE
Quest/G6PD - Add photo as a thumbnail instead for photo capture process 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1026]
**Name of feature to enhance**
Add a photo as a thumbnail instead for the photo capture process when adding a photo of the G6PD observation readings from the test device 

**Describe the enhancement**
Allow the extraction/ saving process to be much more efficient than is now 

**Screenshot**
<img src="https://user-images.githubusercontent.com/4540684/152498653-8dd196e4-b62f-4732-aee7-ccdae3010625.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
@FikriMilano we can look into this once you are done with your ticket. Ping me

**Comment by FikriMilano** [comment]
@f-odhiambo Could you elaborate more on "Add a photo as a thumbnail" ?
If I'm not wrong, I think we already did that.

**Comment by f-odhiambo** [comment]
> @f-odhiambo Could you elaborate more on "Add a photo as a thumbnail" ?
> If I'm not wrong, I think we already did that.

Are we currently saving a full size thumbnail?

**Comment by FikriMilano** [comment]
Not anymore

**Comment by f-odhiambo** [comment]
@maimoonak Any Additions to this , I guess if this is done the only items is just minor enhancements and test to check that the process is smooth on low end devices too

**Comment by maimoonak** [comment]
There were 2 items associated with this. 
1- Images when we are doing questionnaire add/edit /open
2- When we load Questionnaire/QuestionnaireResponse on list/details. We may want to use wrapper for Screens so that images loaded are garbage collected and do not sit into memory @shoaibmushtaq25

**Comment by FikriMilano** [comment]
@maimoonak I don't really understand how we will implement that wrapper for Screens, could you kindly explain?

**Comment by maimoonak** [comment]
@FikriMilano this is related to work Shoaib has done.. So simply what we do it we load questionnaires and responses and then send those to data display screen. This leads to data (with images) keep hanging around and can not be garbage collected unless activity and screen is finished. We actually want to use use smaller subset of data(DTO class for UI instead of questionnaire/questionnaireresponse itself) for screens/ui.

**Comment by FikriMilano** [comment]
oh i see, thanks for the explanation @maimoonak 

@f-odhiambo should we close this issue then?

**Comment by f-odhiambo** [comment]
Closing this ticket for now
