### ISSUE TITLE
Quest/G6PD - Save control mode test results as Questionnaire Responses 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1033]
Save control mode test results as Questionnaire Responses

- [x] 1. Add Device ID to control test questionnaire  - https://fhir.labs.smartregister.org/fhir/Questionnaire/14222
- [x] 2. Add landing page to view previous test results , once you click on control mode and `Add New Test` button
- [x] 3. Extract as save QuestionnaireResponses for Control mode tests
- [x] 4. View Previous calibration test results 

**Sample Screenshots**
Take note : 

1. Sample landing page  (copied from normal test page) initiated via the control mode button on bottom nav
2. We can reuse the fragment and only view Control mode test with previous results 

<img src="https://user-images.githubusercontent.com/4540684/152994494-8fffb78a-2ed1-4567-93ed-5b4904f9b3bc.png" width="200" height="400" />

**Add Test Page**
<img src="https://user-images.githubusercontent.com/4540684/152994504-f96d53c4-2354-4118-9880-6976246e5d31.png" width="200" height="400" />

**Acceptance criteria** 
On previous results show
1. Line 1 : Device ID :0009  | Calibration : Calibrated / Not Calibrated 
2. Line 2 : G6PD : 5 Hb : 8 |  Control mode : 1/ 2

**Comment by f-odhiambo** [comment]
**Update  - 8th Feb 2022**

1. Remove questionnaire from experimental mode 
2. Make edits CQL statement and not linked to any subject 
    - We may need to only save the questionnaire response, will check impact on syncing QR all the time 
3. Add a the QR to be able to sync and view previous test results given that its not linked to any subject

**Comment by maimoonak** [comment]
CQL Runner online is not able to understand and parse QuestionnaireResponse, probably due to the reason that its very old  (5 yrs) and does not support it. The code however works with following CQL. An issue is converting the DecimalType toString not working which needs to be figured out. If that`s done the rest is to create UI.

```
//Declare name and version of lib
library ControlTest version '1'

//FHIR as a data model and version of FHIR
using FHIR version '4.0.1'

//functions to help FHIR vs CQL primitives
include "FHIRHelpers" version '4.0.1' called FHIRHelpers

//System declarations  : Codable concept codes systems
codesystem "SNOMED": 'http://snomed.info/sct'
codesystem "ONA": 'http://fhir.ona.io'

//Code used as identifers
code "G6PD code": '86859003' from "SNOMED" display 'G6PD Enzyme'
code "Haemoglobin code": '259695003' from "SNOMED" display 'Haemoglobin'
code "g6pdResultTypeCode": '000001' from "ONA" display 'G6PD Result Type'
code "g6pdControl1": '410680006' from "SNOMED" display 'Control-mode 1'
code "g6pdControl2": '405358009' from "SNOMED" display 'Control-mode 2'

define "QR" : Last([QuestionnaireResponse] H)

define "Control1Obs": "QR".item.where(linkId='result_type').answer.value ~ "g6pdControl1"

define "Control2Obs": "QR".item.where(linkId='result_type').answer.value ~  "g6pdControl2"

define "HaemoglobinObs": "QR".item.where(linkId='haemoglobin').answer.value

define "G6PDObs": "QR".item.where(linkId='g6pd').answer.value

define "G6PD Value": "G6PDObs"+''
define "Haemoglobin Value": "HaemoglobinObs"+''

define "G6PD Normal":
    if "Control1Obs" is not null and "G6PDObs" between 0.0 and 3.0
    	then true
    else if "Control2Obs" is not null and "G6PDObs" between 6.0 and 10.0
    	then true
    else false

define "G6PD Conclusion":
    if "Control1Obs" is not null and "G6PD Normal"
    	then 'Value ('+ "G6PD Value"+') is in Normal G6PD Range 0-3'
    else if "Control2Obs" is not null and "G6PD Normal"
    	then 'Value ('+ "G6PD Value"+') is in Normal G6PD Range 6-12'
    else 'Value('+"G6PD Value"+') is Non Deterministic G6PD result'

define "Haemoglobin Normal":
    if "Control1Obs" is not null and "HaemoglobinObs" between 8.0 and 12.0
    	then true
    else if "Control2Obs" is not null and "HaemoglobinObs" between 13.0 and 17.0
    	then true
    else false

define "Haemoglobin Conclusion":
    if "Control1Obs" is not null and "Haemoglobin Normal"
    	then 'Value ('+ "Haemoglobin Value"+') is in Normal Haemoglobin Range 8-12'
    else if "Control2Obs" is not null and "Haemoglobin Normal"
    	then 'Value ('+ "Haemoglobin Value"+') is in Normal Haemoglobin Range 13-17'
    else 'Value('+"Haemoglobin Value"+') is Non Deterministic Haemoglobin result'

define "Conclusion":
  if "G6PD Normal" and "Haemoglobin Normal" then 'Correct result'
  else 'Invalid result'

define "Conclusion Details": '\nDetails:\n'+ "G6PD Conclusion" + '\n' + "Haemoglobin Conclusion"


define "OUTPUT": List { "Conclusion" , "Conclusion Details"}
```

**Comment by maimoonak** [comment]
Finally CQL below is working and 100% equivalent to current working version. The issue with ToString seems to be weird and I could not find a reason why converting it to decimal made it work. I think we should get in touch people who have developed CQL to make it better as we are aiming to make it usable by non-developers but some of the current challenges require a lot more than a developer

```
//Declare name and version of lib
library ControlTest version '1'

//FHIR as a data model and version of FHIR
using FHIR version '4.0.1'

//functions to help FHIR vs CQL primitives
include "FHIRHelpers" version '4.0.1' called FHIRHelpers

//System declarations  : Codable concept codes systems
codesystem "SNOMED": 'http://snomed.info/sct'

//Code used as identifers
code "g6pdControl1": '410680006' from "SNOMED" display 'Control-mode 1'
code "g6pdControl2": '405358009' from "SNOMED" display 'Control-mode 2'

define "QR" : Last([QuestionnaireResponse] H)

define "Control1Obs": "QR".item.where(linkId='result_type').answer.value ~ "g6pdControl1"

define "Control2Obs": "QR".item.where(linkId='result_type').answer.value ~  "g6pdControl2"

define "HaemoglobinObs": "QR".item.where(linkId='haemoglobin').answer.first().value

define "G6PDObs": "QR".item.where(linkId='g6pd').answer.first().value

define "G6PDTemp": decimal {value: "G6PDObs".value}
define "G6PDValue": ToString("G6PDTemp")
define "HaemoglobinTemp": decimal {value: "HaemoglobinObs".value}
define "HaemoglobinValue": ToString("HaemoglobinTemp")

define "G6PD Normal":
    if "Control1Obs" is not null and "G6PDObs" between 0.0 and 3.0
    	then true
    else if "Control2Obs" is not null and "G6PDObs" between 6.0 and 10.0
    	then true
    else false

define "G6PD Conclusion":
    if "Control1Obs" is not null and "G6PD Normal"
    	then 'Value ('+ "G6PDValue"+') is in Normal G6PD Range 0-3'
    else if "Control2Obs" is not null and "G6PD Normal"
    	then 'Value ('+ "G6PDValue"+') is in Normal G6PD Range 6-12'
    else 'Value('+"G6PDValue"+') is Non Deterministic G6PD result'

define "Haemoglobin Normal":
    if "Control1Obs" is not null and "HaemoglobinObs" between 8.0 and 12.0
    	then true
    else if "Control2Obs" is not null and "HaemoglobinObs" between 13.0 and 17.0
    	then true
    else false

define "Haemoglobin Conclusion":
    if "Control1Obs" is not null and "Haemoglobin Normal"
    	then 'Value ('+ "HaemoglobinValue"+') is in Normal Haemoglobin Range 8-12'
    else if "Control2Obs" is not null and "Haemoglobin Normal"
    	then 'Value ('+ "HaemoglobinValue"+') is in Normal Haemoglobin Range 13-17'
    else 'Value('+"HaemoglobinValue"+') is Non Deterministic Haemoglobin result'

define "Conclusion":
  if "G6PD Normal" and "Haemoglobin Normal" then 'Correct result'
  else 'Invalid result'

define "Conclusion Details": '\nDetails:\n'+ "G6PD Conclusion" + '\n' + "Haemoglobin Conclusion"


define "OUTPUT": List { "Conclusion" , "Conclusion Details"}


```

**Comment by mberg** [comment]
Hi Maimoona - thanks for sharing this.  Can we share this with Brynn? I think this is important feedback.

**Comment by maimoonak** [comment]
Yeah that would be great. 

Some problems or confusions we had on CQL are
- No direct mapping of CQL/FHIR types. We had to use `myVal: decimal {value: 3.0} ` instead of `myVal: 3.0`. [Sample CQL](https://github.com/opensrp/fhircore/blob/main/android/quest/src/test/resources/cql/pq-medication/cql.txt#L112) 
- FHIR inner static classes can not be initialized so we had to add a class to let CQL handle it explicitly. [Sample CQL](https://github.com/opensrp/fhircore/blob/main/android/quest/src/test/resources/cql/pq-medication/cql.txt#L112). We have added an extension to [R4FHIRModelResolver](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/cql/R4FhirModelResolverExt.kt) to accomplish this.
- [CQL Runner ](https://cql-runner.dataphoria.org/) is very helpful but a very old version of CQL and does not recognize `Now()`, and QuestionnaireResponse. The [CQL here](https://github.com/opensrp/fhircore/blob/main/android/quest/src/test/resources/cql/control-test/cql.txt) does not work on this IDE but works on code. I am not sure if Bryn can address this one.
- Related to point # 1 . Since FHIR Types are not recognized I had to us 
```
define "G6PDTemp": decimal {value: "G6PDObs".value} // G6PDObs=DecimalType
define "G6PDValue": ToString("G6PDTemp")
```
instead of 
```
define "G6PDValue": ToString("G6PDObs".value) 
// OR
define "G6PDValue": ToString("G6PDObs") 
```

**Comment by mberg** [comment]
Let’s share these on fhir chat tulip

**Comment by f-odhiambo** [comment]
@maimoonak I think lets's remove the view more from the Control mode Previous test list view 

<img src="https://user-images.githubusercontent.com/4540684/152994494-8fffb78a-2ed1-4567-93ed-5b4904f9b3bc.png" width="200" height="400" />
