### ISSUE TITLE
Fix failed test testTextOfSavedButtonForAncRegister

### ISSUE THREAD

**Issue by AbdulWahabMemon** [opensrp/fhircore#1037]
**Describe the bug**
Below referenced Unit Tests under ANC module is failing in PR.
testTextOfSavedButtonForAncRegister( ) in FamilyQuestionnaireActivityTest.kt

**To Reproduce**
1. Go to mentioned fun
2. remove @ignore annotation to this fun
3. submit new PR

**Expected behavior**
All unit test checks should pass 

**Additional context**
Its been observed that a unit test in Pull Request is failing, fun name = testTextOfSavedButtonForAncRegister() in 
FamilyQuestionnaireActivityTest class, I am not the only one face that my PR is not passing ANC module unit test due to this, another co developer also face the same failure.

**Comment by f-odhiambo** [comment]
@AbdulWahabMemon kindly add some description to the ticket and not just the title text, for better understanding of the required tasks for this ticket 

CC @maimoonak

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo this issue can be close, its working fine in PR,
