### ISSUE TITLE
Quest/ANC - Add ANC Register 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1041]
**Description of feature** 

1. Create an ANC based config on Quest 
2. Add an ANC practitioner with keycloack credentials 
3. Sync the ANC clients based on the Location hierarchy of the logged in CHW 
3. Based on the ANC config, swap the clients icon with the registers icon
4. On click Register, have ability to view the registers available for the CHW/ANC app
5. Update the default client list view to be able to  have ANC based list view properties such as patient demographics (Name, Age, Gender) and services icon
 

**ANC Register** 
<img src="https://user-images.githubusercontent.com/4540684/153551768-408508f2-334b-4533-a0ea-08e7859a6bd4.png" width="200" height="400" />

**Bottom Navigation - Change register list**
<img src="https://user-images.githubusercontent.com/4540684/153551765-0ca5020d-f731-4b47-991d-0fcab4b33fc0.png" width="200" height="400" />

**Acceptance  Criteria** 

- [ ] 1. Add the ability to view ANC clients on the Quest app based on a Config 
- [ ] 2. Sync the ANC clients based on the Location hierarchy of the logged in CHW 
- [ ] 3. Add the ability to add clients to the ANC register on Quest  
- [ ] 4. Add the ability to configure the Patient list view to view patient details on the list items based on the ANC profile loaded against the signed in practitioner 
- [ ] 5. Add the ability to Filter Due and Upcoming services . This can be accessible from the TopBar menu item

**Comment by pld** [comment]
Will the app config define the registers that should be visible when you go to the "select register" menu?

CC @ellykits
