### ISSUE TITLE
Quest/ANC - Add Family Register  

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1042]
**Description of feature** 

1. Create an ANC based config on Quest 
2. Add an ANC practitioner with keycloack credentials 
3. Based on the ANC config, swap the clients Icon with the registers icon
4. On click Register, have ability to view the registers available for the CHW/ANC app
5. Update the default client list view to be able to  have ANC based list view properties such as family demographics (Name, location, id) and services icon

**Family Register** 
<img src="https://user-images.githubusercontent.com/4540684/153771811-d36440df-9c3f-411c-b498-ac1d30d7cbc0.png" width="200" height="400" />

**Bottom Navigation - Change register list**
<img src="https://user-images.githubusercontent.com/4540684/153551765-0ca5020d-f731-4b47-991d-0fcab4b33fc0.png" width="200" height="400" />

**Acceptance  Criteria** 

- [ ] 1. Add the ability to  view Families register  on the Quest app based on a Config 
- [ ] 2. Add the ability to add a family to the Family register on Quest  
- [ ] 3. Sync the Families  based on the Location hierarchy of the logged in CHW 
- [ ] 4. Add the ability to configure the Family list view to view patient details on the list items based on the ANC profile loaded against the signed in practitioner 
- [ ] 5. Add the ability to Filter Due and Upcoming services . This can be accessible from the TopBar menu item

**Comment by pld** [comment]
This intersects w/other register issues:

https://github.com/opensrp/fhircore/issues/1041
https://github.com/opensrp/fhircore/issues/1046

I think these three issues should be combined into a single issue for the shared functionality. Then 3 non-code issues for the configurations that create the specific registers here
