### ISSUE TITLE
Quest  - Add a reference to the Practitioner while conducting a  Registration Encounter 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1057]
User story : Make sure the backend has information from the health worker profile (i.e., a new client is registered and associated with the health worker who added them).

**Prerequisite Task**
- [ ] https://github.com/opensrp/fhircore/issues/857

NB.
1. The keycloak id and practitioner id would be same based on the current practitioner details endpoint implementation
2. To add practitioner data into entity we would need to do it in questionnaire-viewmodel i.e. central to app.
3. An encounter can be created into current structure map (a reference can be taken from test-results structure map)

**Comment by f-odhiambo** [comment]
@RaaziaTarique Can we have a generic implementation of this Static Practitioner ID tagged to the extracted encounter from the QuestionnaireResponse generated post Client registration  before we have the server side work complete ?

CC @maimoonak

**Comment by pld** [comment]
How is this related to G6PD?
