### ISSUE TITLE
Quest - Add a reference to the Practitioner while creating a New Test Encounter

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1058]
User story : Make sure that we create an Encounter that will hold the information about the practitioner who initiated the test service request and the reference resources e.g Diagnosis of the patient

**Prerequisite Task**
- [ ] https://github.com/opensrp/fhircore/issues/857

NB.
1. The keycloak id and practitioner id would be same based on the current practitioner details endpoint implementation
2. To add practitioner data into entity we would need to do it in questionnaire-viewmodel i.e. central to app.
3. An encounter can be created into current structure map (a reference can be taken from test-results structure map)

**Comment by RaaziaTarique** [comment]
Closed with #1087
