### ISSUE TITLE
Quest/G6PD  - Disable / Remove visibility of the Menu Item in the Home screen , not functional the moment   

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1060]
User Story : Based on the client feedback, the menu item button in the homepage  does not currently have any functionality linked to it . 
We should be able to tweak the config to disable/hide this button until a function for its is defined in the application workflow 

**Screenshot** 
<img src="https://user-images.githubusercontent.com/4540684/154067296-58c810e0-1c92-4661-8118-64a6ca46cd48.png" width="200" height="400" />

NB. We can use the View Configs  - Control what to view on UI

**Comment by RaaziaTarique** [comment]
In register_view_configuration of Quest/G6PD we are setting `"showFilter": false` but still it's showing the filter icon. 
In the code when we are committing `registerFragment` we are overriding `filterRegisterButton` visibility.  
 
@f-odhiambo

**Comment by pld** [comment]
interesting, how do you think we should resolve this?

**Comment by RaaziaTarique** [comment]
> interesting, how do you think we should resolve this?

I need to check why we are overriding the visibility on the first place.
