### ISSUE TITLE
Quest  - Define position of icons in the bottom navigation via config 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1064]
**Description** 
Is there a way to order or make icon position static based on a config ? 

**Use case**  : Make the settings icon appear last on the bottom navigation Quest

<img src="https://user-images.githubusercontent.com/4540684/154097832-e923a7d1-4111-4a17-af2c-d40224b6410c.png" width="200" height="400" />

**Comment by pld** [comment]
I think even if the order of the icons listed in the config defines the order in the UI, that would be sufficient, perhaps ideal b/c of its simplicity

**Comment by dubdabasoduba** [comment]
@owais-vd  @ellykits What config will hold this data. I would like to start converting this to the Parameter resource. 

Also what new attributes and to be added and what do they control exactly? 

cc: @f-odhiambo

**Comment by owais-vd** [comment]
Hi @dubdabasoduba I've checked the current implementation of bottom navigation and saw how it's working with config. Currently, the bottom navigation looks not more consistent and mixes with hard-coded navigation i.e `Client` and `Settings`.

#### Propose solution:
To make it a more consistent way, I thought we can remove the hard-coded bottom navigation item from the code and add this to the `register_view_configuration.json` file with the `position` key. For example:

```JSON
[
  {
    "appId": "quest",
    "classification": "patient_register",
    "appTitle": "Clients",
    "filterText": "Show overdue",
    "searchBarHint": "Search for ID or client name",
    "newClientButtonText": "Register new client",
    "newClientButtonStyle": "rounded_corner",
    "showSearchBar": true,
    "showFilter": false,
    "showScanQRCode": false,
    "showNewClientButton": true,
    "showSideMenu": false,
    "showBottomMenu": true,
    "bottomNavigationOptions": [
      {
        "id": "menu_item_clients",
        "title": "Clients",
        "icon" : "ic_users",
        "position": 0
        "action": {}
      },{
        "id": "menu_item_settings",
        "title": "Settings",
        "icon" : "ic_settings",
        "position": 1
        "action": {}
      },{
        "id": "control_test",
        "title": "Control Test",
        "icon" : "ic_reports",
        "position": 2
        "action": {}
      }
    ],
    "registrationForm": "3435",
    "primaryFilter": {
      "key": "_tag",
      "system": "http://fhir.ona.io",
      "code": "000003"
    }
  }
]
```

We can add the `bottomNavigationOptions` option in each flavor it looks like a bit redundant but give us to more control over each flavor.

cc: @ellykits @f-odhiambo

**Comment by owais-vd** [comment]
@f-odhiambo @ellykits any feedback or we can go with above.

**Comment by owais-vd** [comment]
I've been skipping the `position` key in `bottomNavigationOptions` and the order of navigation will be the same as the order `bottomNavigationOptions` will have.

**Comment by dubdabasoduba** [comment]
> I've been skipping the `position` key in `bottomNavigationOptions` and the order of navigation will be the same as the order `bottomNavigationOptions` will have.

@owais-vd I think I am okay with this. Please make sure you document this behaviour. 

In your PR please add a `configurability` folder [here](https://github.com/opensrp/fhircore/tree/main/docs), then an `app-configurability.md` file. Please document this piece of information there. 

The aim is to keep detailed documentation of how to configure the different aspects of the app. I can update the documentation to a wiki-style once it's added. 

cc: @f-odhiambo @ellykits @maimoonak
