### ISSUE TITLE
[eCBIS] Pin Login Set not working as it should

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1070]
App: ecbis 
v.0.0.2
**Describe the bug**
- [ ] After the initial login, creation of a login page and syncing data. When the user logs out of the system, they are redirected to the main page and asked to select app afresh. 

**To Reproduce**
1. Log into the ecbis app with username and password. 
2. Set a pin for the CHA to use. 
3. Once data sync is completed, log out of the app. 
4. User is redirected to the 'select app' page. 

**Expected behavior**
When a user logs in the first time using a username and password and sets a pin when they log out of the app they should be redirected to the pin-login page. Login should then use the pin that was set both when the user is online and when offline. 

**Screenshots**
https://user-images.githubusercontent.com/58034047/154482727-784764e0-1b58-4b8f-a51b-f6871ac1ca8e.mp4

**Comment by dubdabasoduba** [comment]
**Logout functionality updates**
- If the logout action is clicked the following items need to happen.
    - [ ] The login data shared preference is not cleared.  This is to facilitate offline login. 
    - [ ] The appId shared preference should not be cleared. This is to facilitate offline login. 
    - [ ] The pin login data in the shared preference should not be cleared. This is to facilitate offline login. 
    - [ ] We might not need the remember me functionality after this change? @f-odhiambo thoughts? 

**Updates on how to change the appId**
- After the appId is set we will only allow the change of this to happen on the settings page. The following actions should be performed after the appId is changed
   - [ ] Clear all the shared preferences from the app. This means the user will be required to perform a remote login to the app
   - [ ] For apps with pin login enabled the users will be required to perform the pin login set up.

**Pin login logout functions**  
- [ ] When pin login is enabled and a pin set, clicking the logout button should always redirect the user to the pin login page.

**Comment by dubdabasoduba** [comment]
@AbdulWahabMemon This does not seem to work in the latest release.  Please look into it

**Comment by dubdabasoduba** [comment]
**Bug details**
- [ ] If you try the logout when remember was not selected the app returns you back to the configuration pages
- [ ] If you log out when remember was set, the app closes then resumes with the pin login screen. 

**Acceptance criteria** 
- [ ] Logout should always redirect to the login screen or pin login screen when set.

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba , here the bug # 2, If you log out when remember was set, the app closes then resumes with the pin login screen.
> 
> I fix that app is not closing and resume to login, but 1 issue is there that functionality is written with its Unit tests also, now its tests expecting to screen activity isFinishing, and its failing with my change,
> 
> I observe logout is handle from 2 different views, 1 is from profile view and other one is on side menu options, 1 is finishing the screen and other is not,,, this issue is requiring more functionality testing,,,

Please update the unit tests too. For the new change.
