### ISSUE TITLE
P2P - Implement sending and receiving data

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#1082]
- [ ] On clicking `Send Data` button we have `SyncSenderClass.initiate()` #1006
![send_data_screen](https://user-images.githubusercontent.com/47570855/154956253-2fe07bad-576c-46d4-9dd6-1df3e78fa0de.png)

- [ ] Implement sending data UI. Screen # 29 on [figma designs](https://www.figma.com/proto/kXJMqeQDyzfXp4urKCfE0R/LMH-eCBIS---focused?page-id=5010%3A38742&node-id=5277%3A39960&viewport=364%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=5277%3A38741)
  
![sending_data](https://user-images.githubusercontent.com/47570855/154975407-bcd08695-4328-4509-89a7-c5dc08edfdd5.png)

- [ ] Implement data sending complete UI  . Screen # 30 on [figma designs](https://www.figma.com/proto/kXJMqeQDyzfXp4urKCfE0R/LMH-eCBIS---focused?page-id=5010%3A38742&node-id=5277%3A39960&viewport=364%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=5277%3A38741)

![data_sent](https://user-images.githubusercontent.com/47570855/154975760-a0c70956-23c3-4f09-882d-8bb08b027269.png)

- [ ]

**Comment by ekigamba** [comment]
### Logic for sending and receiving
1. (Sender) - write a message to the socket requesting the receiver for acceptable data types and their last update times which can be sent using a simple string command e.g 'SEND_SYNC_PARAMS'.
1. (Receiver) - will respond with the acceptable data types each with its lastUpdated timestamp and batch size. I.e. some resources types are generally large and therefore will have a smaller batch size compared to others eg. Library vs Patient
     1. Socket implementation: this will be a JSON string as a single line
     1. The expected json will be a JSON Array of JSON Objects each with
          1. dataType -> JSON Object
          1. lastUpdated -> Long
          1. batchSize -> Integer
     1. Data type contains the following
          1. Name (e.g Patient or Resource.Patient)
          1. Filetype (text/json, image/png, image/jpeg)
          1. Position - This tells the receiver which data type to send first eg. In some apps, we have data that references other data therefore the referenced data needs to be sent first eg. in a case where observations are referencing a patient, the patient needs to be sent first.
1. (sender) Use the sync parameters to retrieve data from local db then collect the flow by serializing each payload and writing it to the underlying socket. Once the flow ends it will send a message to the receiver to notify it, and then close the socket
     1. The sender will order the data types and pick the first in order. The sender will fetch the records considering the batch size and the lastUpdated timestamp of the data type.
          1. This sender will iterate on a single data type for the remaining steps (ii) until the size of records returned from the db is 0
     1. The sender will generate a Manifest with the following
          1. DataType (Name, FileType and Position)
          1. Payload size (in bytes/chars)
          1. Records size
     1. The sender will send the manifest first as a single JSON string line
1. (Receiver) wait for the manifest. Read the manifest and have an idea on how much data to expect(bytes and records), how to convert it and save it.
1. (Sender) Sends the actual data collected in 3) (i)
     1. Do we need to worry about how to send this? Whether chunked or as a single JSON String line??
1. (Receiver) Wait for the data. Read the JSON Array, deserialize it and call the repository implementation to save the data
1. (Sender) Repeat step 3) (i) to 6) until all data is sent

**Comment by pld** [comment]
in 2.iii.c do we need to worry about order as long as we sync all the items?

**Comment by ekigamba** [comment]
Yes, in case of references, we will have crashes and/or unprocessed data.

Reason:
- We send data in batches
- Data sync might be interrupted
- Some systems add foreign keys and other perform other operations during inserts. If the data cannot be inserted in a transaction, then it's ignored

The design caters for FHIR core and any other apps

**Comment by f-odhiambo** [comment]
**Update - Apr 7th 2022**

- 1 - completed
- 2,3,4 - Most of the work for these steps has been done. Remaining bits anticipated to be completed this week.
- 5 - Issues to do with sending and receiving data on the client or server socket using wifi-direct have been sorted (initially data flow was uni-directional i.e client to server only ). Work in progress to complete the remaining section.
- 6 i) Work on saving data is in progress.
- 6 ii) This is yet to be done. Integration of the various pieces is targeted for mid next week

**Comment by f-odhiambo** [comment]
> ### Logic for sending and receiving
> 1. (Sender) - write a message to the socket requesting the receiver for acceptable data types and their last update times which can be sent using a simple string command, 'SEND_SYNC_PARAMS', and the **app_lifetime_key**. Also implement [P2P - Create P2P sync db #1088](https://github.com/opensrp/fhircore/issues/1088) (LOE: 1-2 FTE days)
> 2. (Receiver) - will respond with the acceptable data types each with its lastUpdated timestamp and batch size. I.e. some resources types are generally large and therefore will have a smaller batch size compared to others eg. Library vs Patient (LOE: 1 FTE day) **(Retrieval / saving of data from Fhir db will be an interface implementation on Fhir Core)**
>    
>    1. Socket implementation: this will be a JSON string as a single line
>    2. The expected json will be a JSON Array of JSON Objects each with
>       
>       1. dataType -> JSON Object
>       2. lastUpdated -> Long
>       3. batchSize -> Integer
>    3. Data type contains the following
>       
>       1. Name (e.g Patient or Resource.Patient)
>       2. Filetype (text/json, image/png, image/jpeg)
>       3. Position - This tells the receiver which data type to send first eg. In some apps, we have data that references other data therefore the referenced data needs to be sent first eg. in a case where observations are referencing a patient, the patient needs to be sent first.
> 3. (sender) Use the sync parameters to retrieve data from local db **(interface implemenation on fhircore)** then collect the flow by serializing each payload and writing it to the underlying socket **(interface implemention of wifi-direct on P2P)**. Once the flow ends it will send a message to the receiver to notify it, and then close the socket **(interface implemention of wifi-direct on P2P)**. (LOE: 2-3 FTE days)
>    
>    1. The sender receives the payload, deserialize it, order the data types by the **position** and pick the first in order. The sender will fetch the records considering the batch size and the lastUpdated timestamp of the data type.
>       
>       1. This sender will iterate on a single data type for the remaining steps (ii) until the size of records returned from the db is 0
>    2. The sender will generate a Manifest with the following **(interface implemention of wifi-direct on P2P)**
>       
>       1. DataType (Name, FileType and Position)
>       2. Payload size (in bytes/chars)
>       3. Records size
>    3. The sender will send the manifest first as a single JSON string line
> 4. (Receiver) wait for the manifest. Receive, deserialize and read the manifest to have an idea on how much data to expect(bytes and records), how to convert it and save it. (LOE: 0.5 FTE days) **(interface implemention of wifi-direct on P2P)**
> 5. (Sender) Sends the actual data collected in 3) (i) **(interface implemention of wifi-direct on P2P)** (LOE: 5-7 FTE days) [linked ticket](https://github.com/opensrp/fhircore/issues/1078)
>    
>    1. Do we need to worry about how to send this? Whether chunked or as a single JSON String line??
> 6. 1. (Receiver) Wait for the data. Read the JSON Array, deserialize it **(interface implemention of wifi-direct on P2P)** and call the repository implementation to save the data **(interface implemention of wifi-direct on Fhircore)**
>    2. (Sender) Repeat step 3) (i) to 6) until all data is sent (Tentative LOE: 2 FTE days. Manual integrated testing will be done at this point)
> 
> Total LOE: 15.5 FTE days

Update - Apr 7th 2022

1 - completed
2,3,4 - Most of the work for these steps has been done. Remaining bits anticipated to be completed this week.
5 - Issues to do with sending and receiving data on the client or server socket using wifi-direct have been sorted (initially data flow was uni-directional i.e client to server only ). Work in progress to complete the remaining section.
6 i) Work on saving data is in progress.
6 ii) This is yet to be done. Integration of the various pieces is targeted for mid next week

**Comment by Rkareko** [comment]
Unit testing tracked under #1257

**Comment by Rkareko** [comment]
Will be closed by [this PR](https://github.com/opensrp/p2p/pull/12)
