### ISSUE TITLE
[eCBIS]  - Performance profiling of Sync 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1085]
**Name of feature to enhance**
Sync optimization to resolve slow loading of resources in-app 

**Description of feature**
1. Check on the performance on the initial sync and try to optimize the sync mechanism to be able to load data in the shortest possible time 
2. Loading LMH data in the current eCBIS app & ANC apps respectively takes several minutes. 

**Describe the enhancement**

1. Document the current sync mechanism criteria for loading resources in on the LMH app and pitfalls that have been identified 
2. Check what data is loaded from HAPI and confirm that we are only syncing data with the current tag and not the entire DB from HAPI
3. Add a fix to sync optimization on FHIR Core sync module 
4. If new enhancements on FHIR Engine is required document them here https://github.com/google/android-fhir/issues/1099

**Comment by pld** [comment]
duplicate? https://github.com/opensrp/fhircore/issues/949
