### ISSUE TITLE
P2P - Create P2P sync db

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#1088]
We need a p2p db that keeps track of devices and their last updated resources
a. Last update time table (History table)
1. app_lifetime_key (UUID)
i. Generated by the device during 1st p2p initialization
     Only generated once
ii. Sent to the other device during transfer
iii. It helps uniquely identify each device
2. resource_type
3. lastUpdatedAt

Tasks
1. Create db refer to [appDb implementation](https://github.com/opensrp/android-p2p-sync/blob/master/p2p-sync/src/main/java/org/smartregister/p2p/model/AppDatabase.java )
a. [P2pReceivedHistory] model (https://github.com/opensrp/android-p2p-sync/blob/master/p2p-sync/src/main/java/org/smartregister/p2p/model/P2pReceivedHistory.java model)
2. Create repository methods for performing CRUD operations
a. [P2pReceivedHistoryDao] (https://github.com/opensrp/android-p2p-sync/blob/master/p2p-sync/src/main/java/org/smartregister/p2p/model/dao/P2pReceivedHistoryDao.java)

**Comment by Rkareko** [comment]
1 - 1.5 FTE days

**Comment by pld** [comment]
why do we need this?
