### ISSUE TITLE
P2P - Refactor current repository to have a library and sample app

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#1089]
P2P repository [here](https://github.com/opensrp/p2p)

- [x] Rename package to org.smartregister.p2p
- [x] Refactor the current module from an android app to a library
- [x] Fix any resource exceptions due to the conversion
- [x] Setup CI build, jacoco tests and coverage reporting
- [x] Add a sample/demo app module that enables running app
- [ ] Add as a submodule to FHIR core (optional) since it can also be added as a dependency in `build.gradle`. Provide instructions  on this issue, to the developers on how to develop on FHIR core directly

**How to develop on Fhir Core directly**

1. Add the p2p repository as a submodule in the  `android` directory on Fhir Core using this command `git submodule add git@github.com:opensrp/p2p.git`
2. Initialize sub module using `git submodule init`
3. Update sub module using `git submodule update`
4. Add a new module by navigating to `File->Project Structure->modules` and clicking the `+` sign
5. Choose the `import` option. Set the `source directory` to point to the p2p directory of the submodule
6. Import only the module with the name `:p2p-lib`. 
7. Once the `p2p-lib` has been added as a module navigate to the project [settings.gradle file](https://github.com/opensrp/fhircore/blob/main/android/settings.gradle) and update the order of the newly added lines to 
```
include ':p2p-lib'
project(':p2p-lib').projectDir = new File(rootDir, 'p2p/p2p-lib/')
```
8. Add the project dependency to the module build file e.g quest using this command `implementation(project(":p2p-lib"))`
9. Update the `compileSdkVersion` and `compileSdkVersion` to 31. This resolves dependency errors that crop up after integrating the p2p library project

**Comment by Rkareko** [comment]
1 - 2 FTE days [Tentative]

**Comment by Rkareko** [comment]
There is a bug with affecting view binding when running the sample app. The fix for this will be tracked on [this ticket](https://github.com/opensrp/p2p/issues/9) .
