### ISSUE TITLE
MeasureReporting Refactor 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1090]
We need to package the measure reporting module for mADX before the closing of the project that is Feb 28th 2022. We have a hard deadline for this. @ellykits had made some refactoring to the reporting module and we can use this to complete the remaining work to do measure reporting based on the $evalute_measure API via PR https://github.com/google/android-fhir/pull/1092 to be merged later today. 

This will also be reused for the e-CBIS pieces on demonstrating measure reporting in-app before loading  the required libs for measure reporting for the eCBIS use case which can start off by testing Immunization indicator for BCG

**Tasks** 

1. Clean up PR #965 , resolve the TODOs and merge it into the `main` branch 
2. Updated the Gradle file to use the merged PR for measure reporting and not the published Sonatype version 

```
api('org.smartregister:workflow:0.1.0-alpha02-preview-SNAPSHOT') {
transitive = true
exclude group: 'xerces'
exclude group: 'com.github.java-json-tools'
exclude group: 'org.codehaus.woodstox'
exclude group: 'ca.uhn.hapi.fhir'
exclude group: 'org.opencds.cqf.cql'
exclude group: 'com.google.android.fhir', module: 'common'
//        exclude group: 'com.google.android.fhir', module: 'engine'
exclude group: 'org.smartregister', module: 'engine'
}
```

3. Add measure libs into assets folder before shipping and packaging mADX work  - 
Libs are ~54MB for 13 indicators and should not be pushed to the repo, this should be loaded from HAPI. Each ANC indicator can be downloaded and loaded to the assets folder via https://github.com/WorldHealthOrganization/smart-anc/tree/master/bundles/measure . For each indicator library folder, check for the file  named [ANCIND01-bundle.json](https://github.com/WorldHealthOrganization/smart-anc/blob/master/bundles/measure/ANCIND01/ANCIND01-bundle.json)
4. Test each indicator measure reporting for ANC Indicator 1-13 

**Later** 

1. Refactor all the work into a reusable reporting module 
2. Sync measure and Libs from HAPI, though for specific use cases it would be advisable to load from assets folder. To be Discussed (TBD)

**Comment by f-odhiambo** [comment]
CC @dubdabasoduba

**Comment by pld** [comment]
closed by https://github.com/opensrp/fhircore/pull/1105
