### ISSUE TITLE
[Quest] Enhance Authentication to support offline subsequent login

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1098]
**Context**
- All FHIR Core apps require to have offline capabilities. This means all subsequent logins after the initial login should be offline capable. 
- Right now we save more of the configuration and authentication data in the secure shared preferences. 
- The current logout clears out the secure shared preferences. This means after the logout a user cannot login offline. 

**Feature implementation** 
- [x] Update the logout functionality to not clear the secure share preference. 
- [x] Enable login from the shared preferences after logout.  
- [x] Enable accessing the settings/configurations page via the login and pin logins pages.  
    - [x] In case a user change the composition Id or app Id clear all the shared preferences and retrigger the configuration.
    - [x] After clicking save on the setting/configuration page 
        - [x]  If offline,  show a warning dialog warning them that the share preferences will be cleared and they would not be able to login offline again.  If they click yes proceed to clear the shared preferences and log out. If they click no do not save the changes. 
        - [x]  If online,  show a dialog asking them whether they are sure of the operation, If they click yes proceed to clear the shared preferences and log out. If they click no do not save the changes. 

**Acceptance criteria**
- [x] Ability to login offline for all subsequent logins
- [ ] Clearing all data after settings update on the settings page.

**Comment by maimoonak** [comment]
@dubdabasoduba for point _" In case a user change the composition Id or app Id clear all the shared preferences and retrigger the configuration."_
We also have data synced as a result of previous login. This data has different filters and ends up with a database with Patient Related and Questionnaire Related data and each entity have it own "last_sync_date" with that specific filtered dataset. Now hypothetically I can change the appId, keep or update preferences without any issue, BUT, the data that already has been synced would never fetch the data for new filters unless we clean up all existing data
For e.g.
- user username=mk, associated with organization=o1, and publisher=p1 logged in, synced data, and have a working app, with Patient data of organization o1, until date today, Questionnaire data of publisher p1 until date today.
- Now If we allow changing appId,
-  user username=ab, associated with organization=o2, and publisher=p2, logged in, syncing happens with new sync strategy, but it can not fetch ALL data for this user, as we have Patient and Questionnaire already synced until today with some other publisher, and location, organization.

So the driving factor here is the sync factor (organization, location, team, publisher....). Once synced with one, we can not change the sync factor and its filter values.

@f-odhiambo @pld any thoughts?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba for point _" In case a user change the composition Id or app Id clear all the shared preferences and retrigger the configuration."_ We also have data synced as a result of previous login. This data has different filters and ends up with a database with Patient Related and Questionnaire Related data and each entity have it own "last_sync_date" with that specific filtered dataset. Now hypothetically I can change the appId, keep or update preferences without any issue, BUT, the data that already has been synced would never fetch the data for new filters unless we clean up all existing data For e.g.
> 
> * user username=mk, associated with organization=o1, and publisher=p1 logged in, synced data, and have a working app, with Patient data of organization o1, until date today, Questionnaire data of publisher p1 until date today.
> * Now If we allow changing appId,
> * user username=ab, associated with organization=o2, and publisher=p2, logged in, syncing happens with new sync strategy, but it can not fetch ALL data for this user, as we have Patient and Questionnaire already synced until today with some other publisher, and location, organization.
> 
> So the driving factor here is the sync factor (organization, location, team, publisher....). Once synced with one, we can not change the sync factor and its filter values.
> 
> Unless two users or compositions have same sync factor they can not share same device
> 
> @f-odhiambo @pld any thoughts?

I see what you mean. The question then would be do we want users to changes `composition or app Id`? I would say no based on the information.  
- We can say for the appId or compositionId to change to you need the user to sync --> logout--> clear data --> then set the new ids and login.

**Comment by pld** [comment]
I agree, we could also clear data on appID change, and warn the user when they try to change the appID that this will clear any stored data -- guess that would be for a more advanced user, we might want to disallow changing at all unless all data was synced for less advanced users

**Comment by dubdabasoduba** [comment]
> I agree, we could also clear data on appID change, and warn the user when they try to change the appID that this will clear any stored data -- guess that would be for a more advanced user, we might want to disallow changing at all unless all data was synced for less advanced users

@maimoonak @pld I would want to have a general action for when the ids are changed that would save us the headache of trying to always figure out the user level then select the appropriate action. 

The flow here would be: - 
Users opens settings page --> changes the `appId` or `compositionId` --> We clear the existing shared preference and add the new ones --> truncate the tables (I think a [rawQuery](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase#rawQuery(java.lang.String,%20java.lang.String[],%20android.os.CancellationSignal)) on each table would work) --> redirect the user to the login page. 

The reason I am proposing the truncate is to avoid having to reinitialize the app to recreate the DB if we delete it.

**Comment by pld** [comment]
Makes sense

**Comment by maimoonak** [comment]
@dubdabasoduba @f-odhiambo @pld here is the PR that solves one part of the issue i.e. preserve credentials post logout.

Cleaning the database if tricky as we do not have any connection to database and that comes from SDK. Also the SDK kept all databases classes internal (not accessible outside SDK). The database name and its type is also selected based on some logic which we may want to avoid, plus database name is also not made public (although we know DB name but in case of change we would also need special handling). see some sample below

![Screenshot from 2022-03-04 22-20-38](https://user-images.githubusercontent.com/4829880/156811410-7249f733-f920-417e-ba4e-bb9e4dc9782c.png)

![Screenshot from 2022-03-04 22-20-46](https://user-images.githubusercontent.com/4829880/156811331-c4b1382b-8fdc-450b-ae3f-5908d298f90f.png)

The other part i.e. cleaning app data or database is not that straight forward. One way is to clean the data programmatically but that force closes app and our user would have to open app again post clean (This is similar to cleaning app data from Device Settings)

https://stackoverflow.com/questions/4856955/how-to-programmatically-clear-application-data/31531605#31531605

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba @f-odhiambo @pld here above is the PR that solves one part of the issue i.e. preserve credentials post logout.
> 
> Cleaning the database is tricky as we do not have any connection to database and that comes from SDK. Also the SDK kept all databases classes internal (not accessible outside SDK). The database name and its type is also selected based on some logic which we may want to avoid, plus database name is also not made public (although we know DB name but in case of change we would also need special handling). see some sample below
> 
> ![Screenshot from 2022-03-04 22-20-38](https://user-images.githubusercontent.com/4829880/156811410-7249f733-f920-417e-ba4e-bb9e4dc9782c.png)
> 
> ![Screenshot from 2022-03-04 22-20-46](https://user-images.githubusercontent.com/4829880/156811331-c4b1382b-8fdc-450b-ae3f-5908d298f90f.png)
> 
> The other part i.e. cleaning app data or database is not that straight forward. One way is to clean the data programmatically but that force closes app and our user would have to open app again post clean (This is similar to cleaning app data from Device Settings)
> 
> https://stackoverflow.com/questions/4856955/how-to-programmatically-clear-application-data/31531605#31531605

@pld Does it make sense to advise to the users to sync, log out then clear data if they would like to use new composition Ids?  We currently do this when a user changes the server URL on the old OpenSRP.

**Comment by f-odhiambo** [comment]
@dubdabasoduba can we have @owais-vd pick this up from @maimoonak?

**Comment by f-odhiambo** [comment]
Closing this and marked as completed
