### ISSUE TITLE
QA - features for R1 and R2

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1099]
Qa the eCBIS app for the following:
- [ ] All items on done and in QA columns on this board: https://github.com/opensrp/fhircore/projects/17
- [ ] Additional context: release notes: https://docs.google.com/document/d/13PA7HrNc8A2tRgqAl5qUBoB3iy9b8JkmPSr_wovA_r0/edit#heading=h.1ppwff3y8wby

**Comment by pld** [comment]
Can we do the QA after we move eCBIS to Quest? That way we don't have to repeat it?

**Comment by AnnieMungai** [comment]
@dubdabasoduba when are we hoping to have this done?

**Comment by dubdabasoduba** [comment]
> Can we do the QA after we move eCBIS to Quest? That way we don't have to repeat it?

This makes sense.  @AnnieMungai  The Idea was to try to move ecbis into quest in R4. Let me review this possibility of that and then give a concrete answer

**Comment by AnnieMungai** [comment]
@dubdabasoduba do we have a timeline on when eCBIS will be moved to quest?

**Comment by AnnieMungai** [comment]
Marking as done to track on a separate issue.
