### ISSUE TITLE
Quest - sync fails after staying idle in the app for a short period of time

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1106]
**Describe the bug**
If the user has been idle for some time in the app, and then tries to synchronize, it fails with a 401 error i.e. unauthorized request. I'm not sure exactly how long this length of time is but it seems somewhere between 5 and 10 minutes of being idle. The user isn't signed out, they are still within the app. So in order to synchronize, the user needs to log out, then log back in again and then synchronize. In addition, the toast message doesn't specify that the user needs to do this, it's something I observed in the logs. The toast message simply says "Sync failed. Please check internet connection or try again later".

**To Reproduce**
1. Log into the Quest app
2. Wait for 10 minutes
3. Go to the settings tab
4. Click sync
5. An error message should appear shortly

**Expected behavior**
I expect to be able to sync as long as I am logged into the app.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
N/A

**Comment by f-odhiambo** [comment]
@KhumboLihonga Looking into this
