### ISSUE TITLE
V.0.0.3 - app closure when using previously set pin 

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1112]
eCBIS: v.0.0.3
**Describe the bug**
V.0.0.3 
- [x] When I upgraded app from v 0.0.2 to 0.0.3, the app was able to redirect me to the pin login page. However, the app crashed the moment I entered the pin previously set. This is happening for the first 3 or so times I try to log in. 
Other observations: this did not occur when I used the password and set the pin login again. 
- [x] When I logged in using the password, I was prompted to set pin again, even though I had set this in the previous logins. 

**Expected behavior**
- [x] When a user upgrades from any previous version of the app, if they had set the pin for login, they should be redirected to the pin log-in page. The app should not crash if the user enters a previously set pin. 
- [x] If a user opts to use a password after setting the pin, once they are redirected to the username/password page, they will be required to enter the username and password. Once they enter the correct username and password, they are redirected to the register main page. 
![image](https://user-images.githubusercontent.com/58034047/156346149-841a1ba3-a327-4965-9cf3-28804bb4057f.png)

**Comment by RaaziaTarique** [comment]
@AnnieMungai I tested first part of the issue, It's not occurring in the new build. and for the the second I have created a PR for that. CC: @dubdabasoduba
