### ISSUE TITLE
[Sync Optimization] Update all API call to use a count of 100

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1119]
**Description of feature**
- The current API `_count` when querying the server is 20.  This takes Approx 7mins to sync.  
- Increasing the count to 100 increases the amount of data we receive per call and reduces the sync period to approx 3 mins

**Describe the enhancement**
- [x] Update all FHIR core calls to the API to default to a 100 count. 
- [x] Make the count definition configurable, this will enable other implementations to change their count settings if need be.  This can be defined via configs.  
     - [x]  If it's not defined then the default is 100
     - [x] If defined the default becomes the new number set on the configs. 

- We can use the [application configuration](https://github.com/opensrp/fhircore/blob/main/android/anc/src/main/assets/configurations/app/application_configurations.json) to hold the count config

@pld @maimoonak What do you think about making the count definition configurable.

**Comment by FikriMilano** [comment]
We need to refactor QuestConfigService and AncConfigService so that it could take multiple parameters in a single URL path.
And it will be cool to make it more generic as well, since those 2 are pretty much the same.

**Comment by FikriMilano** [comment]
@dubdabasoduba we can make the count param configurable, it's nice to have. We can change the value with minimal effort.
