### ISSUE TITLE
[eCBIS/Quest] Update the remove family to open a form and collect data.

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1141]
**Description of feature**
- Currently, we have the remove family functionality which just pop-ups a confirmation dialog to confirm the action. 
- We would like to change this behaviour to open up a form/questionnaire.  

**Describe the enhancement**
- [ ] Open the remove family questionnaire by clicking the remove family menu. 
     - [ ] Here is a link to the [eCBIS remove family form](https://github.com/opensrp/fhir-resources/blob/main/ecbis/questionnaire/remove_family.json). 
- [ ] After all the fields in the form are filled and `remove family/save` clicked pop up a dialog confirming whether the user actually wants to remove the family.  
    - [ ] Here is the message to show on the dialog  `Removing {family_name} will remove their entire health record from your device. This action can’t be undone.`
- [ ] We do not have to perform any extraction for now. Save the Questionnaires response.

**Comment by AbdulWahabMemon** [comment]
<img width="400" alt="Screen Shot 2022-03-17 at 11 21 18 AM" src="https://user-images.githubusercontent.com/66945489/158841228-390d4ef8-ce5b-4418-b1d3-81848506f1fa.png">
<img width="416" alt="Screen Shot 2022-03-17 at 11 21 02 AM" src="https://user-images.githubusercontent.com/66945489/158841425-eeeb4969-cb73-4db0-94b5-4aca10937a80.png">

https://user-images.githubusercontent.com/66945489/158841519-7351025b-6ffe-433d-bc83-6a202b20cd44.mp4

**Comment by AbdulWahabMemon** [comment]
above attached are working snaps for this remove family action. I am facing crash when remove family action completed. I will be resolving this with PR#[1145](https://github.com/opensrp/fhircore/pull/1145)

@f-odhiambo

**Comment by dubdabasoduba** [comment]
> above attached are working snaps for this remove family action. I am facing a crash when the remove family action is completed. I will be resolving this with PR#[1145](https://github.com/opensrp/fhircore/pull/1145)
> 
> @f-odhiambo

@AbdulWahabMemon I think this might be because the file does not have a StrucutreMap to extract the data. Please confirm that we can save the Questionnaire response without the need to extract it. 

I would say if we always need a StructureMap then update the functionality to have it default to looking a StructureMap and when it does not find it, it then saves the Questionnaireresponse alone.
