### ISSUE TITLE
[eCBIS/Quest] Update the remove family member function to open a form and collect data.

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1142]
**Description of feature**
- Currently, we have the remove family member functionality which just pop-ups a confirmation dialog to confirm the action.
- We would like to change this behaviour to open up a form/questionnaire.

**Describe the enhancement**
- [ ] Open the remove family questionnaire by clicking the remove family member menu.
    - [ ] Here is a link to the [eCBIS remove family form](https://github.com/opensrp/fhir-resources/blob/main/ecbis/questionnaire/remove_family_member.json).
- [ ]  After all the fields in the form are filled and `remove family member/save` clicked pop up a dialog confirming whether the user actually wants to remove the family.
    - [ ] Here is the message to show on the dialog here `Removing {family_member_name} will remove thier entire health record from your device. This action can’t be undone.`
    - [ ] We do not have to perform any extraction for now. Save the Questionnaires response.
- [ ] If the family member in question is the household head then prompt the user to select a new family member head. This means the following
   - [ ] Redirect to the following screen after form filling.
    ![Screenshot from 2022-03-12 14-40-48](https://user-images.githubusercontent.com/4817531/158022387-492d6941-8a91-4ffb-85d2-389514071982.png)
   - [ ] If the user does not select a head of household then cancel the form saving and redirect but to the family profile.
   - [ ] If the user selects a head of household then remove the family member and redirect to the family profile. Remember to save the QuestionnaireResponse and mentioned above.

**Comment by aurangzaibumer** [comment]
form is not attached (https://github.com/opensrp/fhir-resources/blob/main/ecbis/questionnaire/remove_family_member.json).
@f-odhiambo

**Comment by dubdabasoduba** [comment]
> form is not attached (https://github.com/opensrp/fhir-resources/blob/main/ecbis/questionnaire/remove_family_member.json). @f-odhiambo @dubdabasoduba

What do you mean by it's not attached? Do you have access to the repo?

**Comment by f-odhiambo** [comment]
I think we need to add this to HAPI and not reference it from the assets folder, which I have already added http://turn-fhir.smartregister.org/fhir/Questionnaire/101643

So, I propose in the list of Questionnaires being loaded/synced and, when you are on this page use it to complete the remove patient criteria

**Comment by dubdabasoduba** [comment]
Meeting with @aurangzaibumer 
- After the user fills in the questionnaire, they should be redirected to the select family head if the patient being removed is a family head. 
    - We hold the saving of the questionnaire until save on the family selection page is clicked.  
- In case the family has no family members to add as family heads or the user clicks cancel then we abort the whole operation and go back the the family profile

**Comment by ellykits** [comment]
Closing this. The remove family functionality was refactored with the new family representation implementation.
