### ISSUE TITLE
[Quest] App failing to move to login page post submitting config-id , user need to press submit twice to receive action 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1147]
**Describe the bug**
App fails to progress to the login screen after submitting the correct config id 

**To Reproduce**
Steps to reproduce the behaviour:

1. Fresh install app
2. Enter config ID: quest
3. Add correct credentials and press submit 
4. See an error 

**Expected behaviour**
Once a user enters the config id, it should be validated as a correct config id, if valid proceed to login in screen, if not toast/alert and error for the user to resubmit a correct config id 

**Screenshots/Videos**
https://user-images.githubusercontent.com/4540684/159156328-eef592f2-73a1-4f6d-872a-bb7a7192a5c6.mp4

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - Android version: 12
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version : SQ1A.220205.002

**Additional context**

**Comment by dubdabasoduba** [comment]
@ellykits How far are we with this?

**Comment by dubdabasoduba** [comment]
Am I right to assume it's on the configurability refactor PR?

**Comment by ellykits** [comment]
Yes that's correct.

**Comment by ellykits** [comment]
This was fixed and merged to main. There is now a progress indicator displayed when load configuration button is pressed. The button is also disabled until the load configs succeeds or fails.
