### ISSUE TITLE
[Quest] App toasts failed sync but still continues to sync data in  the background 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1148]
**Describe the bug**
The app throws a failed sync toast on the first install but still proceed to complete and sync data 

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh install app
2. Enter config ID: quest 
3. Add correct credentials and proceed to login 
4. Check on sync progress and after a while, a sync failure toast is given 

**Expected behaviour**
If the sync fails user should be alert on on successful retry, then the user should also be notified that sync has resumed 
message: "Sync failed but is now resumed" as an example alert/prompt  

**Screenshots/Video**
https://user-images.githubusercontent.com/4540684/159156463-a02be9c7-c97f-474c-ac13-34304878ac7e.mp4

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - Android version: 12
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version : SQ1A.220205.002

**Additional context**
Might need to agree on the appropriate syn behaviour and approval of the implementation design

**Comment by f-odhiambo** [comment]
@ellykits Kindly give some more additional insight on this

**Comment by dubdabasoduba** [comment]
@f-odhiambo Does this re-try immediately or after the 15mins scheduled time.

**Comment by f-odhiambo** [comment]
> @f-odhiambo Does this re-try immediately or after the 15mins scheduled time. 

No it does not. This happens during the initial 1st time sync after installing the app

**Comment by ellykits** [comment]
@f-odhiambo FHIR Sync API provides different statuses during sync. One is `State.Glitch` that is emitted when an exception is encountered when when syncing any resource. We receive a list of exceptions from this state and react to them by showing toast notification [see the function here](https://github.com/opensrp/fhircore/blob/933f070baa7d68ee662a2ba9aafd85ce0fd3d4fb/android/engine/src/main/java/org/smartregister/fhircore/engine/ui/register/BaseRegisterActivity.kt#L698). Solution would be to make the toast notification to target specific exception(s).
