### ISSUE TITLE
[eCBIS] Add the CarePlan & Task Generation for Child family members. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1151]
**Is your feature request related to a problem? Please describe.**
- If a family member who is  is < 5yrs old is registered then generate a Child Routine visit CarePlan and the routine visit Tasks 

**Describe the solution you'd like**
- [x] If a family member who is < 5yrs is registered generate a Child Routine Visit CarePlan off the base CarePlan defined [here](https://github.com/opensrp/fhir-resources/blob/main/ecbis/care_plan/child_routine_visit.json). 
- [x] Also define Child routine visit tasks based on the CarePlan above. The Tasks base can be found [here](https://github.com/opensrp/fhir-resources/blob/main/ecbis/task/child_routine_visit.json#L23). 
- [ ] The task generation should follow the following rules. 
     - [x] A task should be generated for every month starting from the 1st day after the month of registration i.e if a child is born on the 20th of March the task generation should be generated starting the 1st of April. The total number of tasks should be 60. The tasks can be < 60 depending on the age the child is registered.  
          - All the tasks at this point should have the status [Requested](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-requested)
     - [ ] Each task should last 30days before it expires i.e the start & end date should be 30days apart. 
     - [x] On clicking each task the form linked using the [reasonReference](https://github.com/opensrp/fhir-resources/blob/9dc42664b9a586dd253fd555be403a68781cedff/ecbis/task/child_routine_visit.json#L23) attribute should be opened
     - [x] A task should only become [Ready](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-ready)  and activated on the `start date of the task. 
     - [x] The tasks should remain [Ready](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-ready)  and open until it's due if this is before its `end date`. 
     - [x] If a Task is 1 day past its `end date` then the Task status should be updated to [failed](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-failed)
     - [ ] Once a task is completed the status should change to [Completed](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-completed)

Status summary
---
-  [Requested](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-requested) : Immediately the tasks are generated. They move from this state only when the date today is == the start date. 
- [Ready](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-ready) : This is a task that has both it `start date` & `end date` with in the 30days and hasn't been completed. 
- [failed](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-failed) : This is a tasks whose `end date` is -1 of the date today. 
-  [Completed](https://www.hl7.org/fhir/codesystem-task-status.html#task-status-completed) : This is a task that has been completed.

**Comment by dubdabasoduba** [comment]
This tasks are to be displayed in the UI [here](https://github.com/opensrp/fhircore/issues/1150)

**Comment by ellykits** [comment]
@dubdabasoduba Kindly add to the checklist items the action that should be performed to complete the task.

**Comment by dubdabasoduba** [comment]
Actions checklist

- [ ] Generate a CarePlan for each patient < 5yrs old
     - [ ] The `count` attributte [here](https://github.com/opensrp/fhir-resources/blob/43046a283af1d92cd40b5ac203551d234e1580ac/ecbis/care_plan/child_routine_visit.json#L52) should be a calculation of `patient_date_of_registration - patient_date_ofbirth` in month then `60 (total_number_of visits) - (patient_date_of_registration - patient_date_ofbirth)`
- [ ] The `outcomeReference` should be a JSONArray referencing the Tasks generated fr each visit.  The number of Tasks generated should and the `count` calculated above.
- [ ] The CarePlan `active` status should be marked as `complete` if no referenced Tasks have the `status = Requested or status = Ready`
- [ ] The Tasks [lastModified](https://github.com/opensrp/fhir-resources/blob/43046a283af1d92cd40b5ac203551d234e1580ac/ecbis/task/child_routine_visit.json#L22) should change when a Tasks changes status. 
- [ ] The Tasks completed should be set after the Questionnaires provided [here](https://github.com/opensrp/fhircore/issues/1150) are filled.

**Comment by maimoonak** [comment]
@ellykits @dubdabasoduba the PR https://github.com/opensrp/fhircore/pull/1174 fixes part the ticket where it generates CarePlan and tasks via StrutureMap. A StrcureMap/105121 is created on server as well. 
Fhir allows CQL/StrctureMap  as scripting language for dynamic data generation and considering the urgency, I have used structure-map approach instead cql. The https://hl7.org/fhir/plandefinition.html transfom part allows this, and the library allows cql. We can add cql handling once we are done with demo.

Some changes to give model into files
- identifier -> not added as it is uuid and 'id' is serving this purpose
- description in task is not needed and can not be made dynamic via fhir-path(would look into it again)
- authoredOn -> date when it is running instead of picking patient registration date from patient

TASK
- requester and owner -> do we need both, added although
- scheduledTiming ->  date when it is running instead of picking patient registration date from patient
- timing.event is not added as we do not have specific dates rather it is dynamically generated

**Comment by dubdabasoduba** [comment]
> description in task is not needed and can not be made dynamic via fhir-path(would look into it again)

We need this because this is what we show as the task name on the tasks display.

**Comment by dubdabasoduba** [comment]
> Is the CarePlan created on registration?

Yes, @pld Sorry I missed this before.

**Comment by dubdabasoduba** [comment]
This is already on the configuration refactor PR @dubdabasoduba to link the PR
