### ISSUE TITLE
[Malawi Core] Clinic Registration

### ISSUE THREAD

**Issue by Gental-Giant** [opensrp/fhircore#1158]
**Background**
Registration is the process of enrolling HIV positive new clients at a facility who may either be a newly diagnosed or a transfer in client. Every new registration is given a new ART Number. The ART number is a combination of the health facility code + five digits. To ensure that there is no duplication of the ART number, the ART provider or the data clerk, who gives the ART number, checks the new number suggested in the EMR against the numbers in the ART register.
There are several ways in which a newly diagnosed client may come to be registered:

- _**Exposed Infant**_: A child 2 years and below undergoing MIP who tests HIV positive either at 6 weeks, 1 year or at 2 years.

- **_Contact_**: This could be a sexual contact or a client’s child, both of whom have an unknown HIV status. When the sexual contact or child is traced and they are tested; they are registered as an ART client if they test HIV positive.

- **_Routine checks_**: When a woman is pregnant, she is encouraged to take an HIV test when she comes for her antenatal visit. If she tests positive, she is enrolled into HIV care. This is also true for routine checks at the Out Patient Department (OPD) when a CHW checks the people who have come to the clinic for other services but are screened to see if they qualify for HIV testing.

- **_Walk in and Referrals_**: A person may just, of their own volition, decide to be tested. Other people may be referred to the ART clinic by other organizations, departments and clubs. If they test HIV positive, they are enrolled into HIV care.

**Feature Description**
Clinic Registration of the following persons:
 - ART Clients
 - Exposed Infants
 - Contacts of HIV positive clients

**Registration Requirements**
Registration workflow is as follows:

- [ ]  Search for client

    - If client already exists in system follow "_Already on ART and in the system_"
    - If client does not exist in the system but is already on ART follow "_Already on ART Reg_"
    - If client is a newly diagnosed person follow "_Newly Diagnosed Client Reg_"

- [ ] Beginning registration
    - CHW will select the category of the person being registered. 
    - Each category leads to a workflow specific for that person.
    - If the client is ‘Already on ART,’ they will be asked if they are a transfer client

**Additional context**

- Questionnaires
- Workflow
- UI Designs

**Comment by dubdabasoduba** [comment]
@Gental-Giant Do we need to differentiate the 2 types of clients on this issue? If so this needs a bit of technical scoping.

**Comment by f-odhiambo** [comment]
Can we close this @AbdulWahabMemon @LZRS ?

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo , 
for clinic registration, @LZRS or @Gental-Giant  can better comment
though registration is working in malawi. 
other linked stories are also working
This was referenced on Apr 12
https://github.com/opensrp/fhircore/issues/1187
 Open
https://github.com/opensrp/fhircore/issues/1186

**Comment by LZRS** [comment]
Yes, features in this issue have been implemented and so I think it makes sense to close

**Comment by LZRS** [comment]
Closing, since most features have been implemented
