### ISSUE TITLE
[eCBIS] Subsequent sync fails 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1161]
**Describe the bug**
- Currently, if you try to sync the app after the subsequent sync it breaks and returns a sync fail error.

**To Reproduce**
Steps to reproduce the behaviour:
1. log in to the app and complete the initial sync. 
2. Log out and re-login. 
3. You will see the app throwing a `Sync failed error`

**Expected behaviour**
1. log in to the app and complete the initial sync. 
2. Log out and re-login. 
3. The app should sync all the data from the app to the server and viceversa.

**Screenshots**
![Screenshot_20220322_152959](https://user-images.githubusercontent.com/4817531/159521718-ebfe79fb-3d5a-4500-854c-293a56b36c7b.png)

**Smartphone (please complete the following information):**
 - Device: Nexus 4 emulator
 - Android version: 10 
 - Current code on `main` branch

**Comment by FikriMilano** [comment]
@dubdabasoduba 
Additional context:
This is a timeout error, we can try to increase the timeout duration.

```
I/BaseRegisterActivity: Sync state received is Glitch(exceptions=[ResourceSyncException(resourceType=QuestionnaireResponse, exception=java.io.InterruptedIOException: timeout)])
I/BaseRegisterActivity: Sync state received is Failed(result=Error(exceptions=[ResourceSyncException(resourceType=QuestionnaireResponse, exception=java.io.InterruptedIOException: timeout)]))
```

**Comment by FikriMilano** [comment]
A simple fix would do, need me to create a PR?
https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/di/NetworkModule.kt#L94

**Comment by pld** [comment]
Is that 120s timeout for the entire sync?

Does this mean any sync that takes more that 120s will timeout and fail?

**Comment by FikriMilano** [comment]
It's 120s per API call and yes it will fail if the call takes longer

**Comment by pld** [comment]
Cool, so I believe we made this type of timeout user land configurable in other projects, @ndegwamartin is that what we did in WCaro?

There are times when we'll want to instruct users, or techs to set this high because we know a certain area they're working in has low latency.

**Comment by FikriMilano** [comment]
Yeah, actually that's better
cc @ndegwamartin

**Comment by dubdabasoduba** [comment]
> A simple fix would do, need me to create a PR? https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/di/NetworkModule.kt#L94

@FikriMilano Can we have this configured from the `build.gradle`. I also tested with 600s and I still got the timeout. Might it be related to something else?

**Comment by FikriMilano** [comment]
> @FikriMilano Can we have this configured from the `build.gradle`. I also tested with 600s and I still got the timeout. Might it be related to something else?

Ah that's odd, 180s fixed the timeout error for me.
Is it perhaps your internet connection? have you try to re-install the app as well?

I don't think it's something else, unless it's a different error.

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba Ah that's odd, 180s fixed the timeout error for me. Is it perhaps your internet connection? have you try to re-install the app as well?
> 
> I don't think it's something else, unless it's a different error.

Left me try this.

**Comment by dubdabasoduba** [comment]
> > @dubdabasoduba Ah that's odd, 180s fixed the timeout error for me. Is it perhaps your internet connection? have you try to re-install the app as well?
> > 
> > I don't think it's something else, unless it's a different error.
> 
> Left me try this. 

@FikriMilano I every time sync fails with an error that's not `401` the the sync failed error is through.

Here it's was thrown because the app could not sync a patient to the server.

**Comment by FikriMilano** [comment]
@dubdabasoduba 
Could you send some logs?

**Comment by f-odhiambo** [comment]
@dubdabasoduba is this still an issue on the current codebaase?

**Comment by dubdabasoduba** [comment]
@f-odhiambo I think this is fixed on the current release.
