### ISSUE TITLE
Add a new slim apps folder on fhir core

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1167]
**Name of feature to enhance**
- Based on the description [here](https://github.com/opensrp/fhircore/issues/1165) add a new folder named `slim_apps`
- Add an MWCore android project to the folder

**Comment by pld** [comment]
can we call it `slim-apps` to match the folder names under `docs`, or will Java have problems reading that?

**Comment by dubdabasoduba** [comment]
This is no longer required with the flavours approach.
