### ISSUE TITLE
Update quest to be a library that the slim apps can implement

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1168]
**Name of feature to enhance**
- Based on the discussion [here](https://github.com/opensrp/fhircore/issues/1165), update quest to be a library that the slim apps can implement. 
- These apps should only do the following
    - Add the correct project icon
    - Add the correct project name.

**Comment by pld** [comment]
We also want to be able to optionally add a default app id

- if you set this you cannot see the app id in the apk you build,
- if you don't it functions as is

**Comment by RaaziaTarique** [comment]
@dubdabasoduba what are slim apps here?.
According to this issue https://github.com/opensrp/fhircore/issues/1165 , do we need to create a new module for them?
CC: @f-odhiambo
