### ISSUE TITLE
[COVAX demo app] Display immunization info on the Patient Profile

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#118]
Add functionality to retrieve Immunization data from the local repository and display it on the patient profile.

- [x] Fetch immunization records for a particular patient
- [x] Display immunization info on profile page

**Comment by pld** [comment]
Can we use a FHIR Resource to configure all/most/some of this?

**Comment by Rkareko** [comment]
> Can we use a FHIR Resource to configure all/most/some of this?

@pld The initial approach is to use an immunization Resource to fetch and load the data. Then after this is working, we can research on how to use a generic FHIR Resource to configure this
