### ISSUE TITLE
[Malawi Core] - Search functionality to find a person by searching using their unique number or their name

### ISSUE THREAD

**Issue by Gental-Giant** [opensrp/fhircore#1186]
**Is your feature request related to a problem? Please describe.**
Add functionality that allows a CHW to search a person using either their name or unique number.

**Describe the solution you'd like**

1. The CHW will search the ART/HCC/HTS number or the person’s name.
2. They may not find a number like it at all as in 1a
3. They may find some numbers that start with the same numbers they are looking for as in 1b
4. The more numbers that are entered, the shorter the list becomes
5. The list will show only numbers that appear in the order typed as shown in 1b. Only numbers beginning with 89 are displayed. A number like 589 will not be displayed.
6. Numbers appear in ascending order
7. If the number or name is not found, select the + sign to register the person

![image](https://user-images.githubusercontent.com/52551080/161724777-814fb928-8ed8-4a2c-8cc3-735596219825.png)

**Additional context**
[Desired workflow](https://docs.google.com/presentation/d/1A4e98GVesRpeygbctCLvbAH9tghP8Mpk/edit#slide=id.p4)

**Comment by dubdabasoduba** [comment]
This issue depends on https://github.com/opensrp/fhircore/issues/1158

**Comment by LZRS** [comment]
This has been resolved and is currently working for patients register page list. Part of this work has also been moved to tracing
