### ISSUE TITLE
[COVAX demo app] Add patient search

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#119]
- [x] Implement patient search by filtering patient results on the Patient View Model.
- [x] Filter the collection based on searched values or we filter the patient list

**Comment by pld** [comment]
Is this (or the logic for it) something that we can store in a syncable configuration file?

**Comment by ekigamba** [comment]
> Is this (or the logic for it) something that we can store in a syncable configuration file?

No. The generic and ideal implementation is blocked by work on the Google FHIR SDK on issues https://github.com/google/android-fhir/issues/431, https://github.com/google/android-fhir/issues/376 and   https://github.com/google/android-fhir/issues/292

**Comment by pld** [comment]
> > Is this (or the logic for it) something that we can store in a syncable configuration file?
> 
> No. The generic and ideal implementation is blocked by work on the Google FHIR SDK on issues [google/android-fhir#431](https://github.com/google/android-fhir/issues/431), [google/android-fhir#376](https://github.com/google/android-fhir/issues/376) and [google/android-fhir#292](https://github.com/google/android-fhir/issues/292)

ok understood
