### ISSUE TITLE
[Quest/G6PD] - Bug : Issue selecting input for thresholds inputs,  after 1st time app load for G6PD and Hemoglobin levels 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1191]
**Describe the bug**
on 1st time load of the G6PD test questionnaire, the app fails to recognise inputs while trying to enter either G6PD or Hemoglobin levels while conducting a G6PD test for a Patient 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Patient list 
2. Select a Patient 
3. Add G6PD Test 
4. Try to enter thresholds levels 
5. See an error 

**Expected behaviour**
Users should be able to enter any threshold level without an input freeze 

**Screenshots**
Adding a screenshot and video recording 

<img src="https://user-images.githubusercontent.com/4540684/161907457-5b4a8c79-15c5-4c38-a140-755114fb6836.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/161907461-68872d9a-58de-4d49-9aea-f5a6e1f58d76.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/161907464-e268b42e-d03e-4d2c-954c-0dcb680adb1b.png" width="200" height="400" />

Recirding  : 

https://user-images.githubusercontent.com/4540684/161908944-85d156df-d8d1-4f29-9170-d59b30831d40.mp4

**Smartphone (please complete the following information):**
 - Pixel 5 Emulator, Android 12, API 31 
 - Pixel 4a, Build Number SQ1A.220205.002, Android Version 12

**Additional context**
N/A

**Comment by roywanyaga** [comment]
I tested to reproduce the bug on the following devices:
- Samsung Galaxy Tab A7 - Build #: RP1A.2000720.012.T225NDXU1AVB1 - Android version 11
- Nexus 4 Emulator Android 10 API 29
- Pixel 4a Emulator Android 12 API 31Steps to reproduce the behavior:

**Steps Attempted**
1. Go to the Patient list
2. Select a Patient
3. Add G6PD Test
4. Try to enter thresholds levels

The input TextViews works fine for all devices allowing input of thresholds on the first attempt.

**Comment by pld** [comment]
@roywanyaga what about in Pixel 5 Emulator, Android 12, API 31?
