### ISSUE TITLE
[COVAX demo app] Generate Patient barcodes

### ISSUE THREAD

**Issue by vincent-karuri** [opensrp/fhircore#120]
We need to generate a barcode on the device after a Patient is registered. It should contain Patient demographic data.

A few things:

1. Is the [Patient Identifier](https://www.hl7.org/fhir/patient-definitions.html#Patient.identifier) what we expect to encode into the barcode as e.g. a JSON String?
2. In this case, do we have a specific format in mind for the [Identifier value](https://www.hl7.org/fhir/datatypes-definitions.html#Identifier.value)?
3.  I'm assuming we use the `Identifier value` above as a unique ID to identify the Patient across the system?
4. Will we persist the barcode on the device? If so, is this supported via the SDK?
5. Do we need to display/retrieve the barcode at some point within the device. If so, do we need mockups for this interaction?

cc @f-odhiambo @pld

**Comment by vincent-karuri** [comment]
Also to consider is the extraction process from Patient resource to barcode.

**Comment by f-odhiambo** [comment]
A quick response to this. I will give another update with more comprehensive feedback 
1. It's a QR code, not a barcode. Yes the data will be represented using a JSON string 
2. Looking at the IG it does not state which format to use  it but will get back to you on this 
3. Yes that's correct
4. I think we should. I think based on the code which Jing has shared we only have a QR code reader, will revert back on generation and persistence 
5. We can ask @rowo to create something for this

**Comment by pld** [comment]
For demo we don't need any generation, only reading of a QR code

**Comment by pld** [comment]
for the demo, we can have a fixed set of IDs we assign to newly created patients, have some demo QR codes w/those IDs so that you can create a patient, then read a QR code to bring up the patient

should be the exact same as the RDT use case — w/the QR identifying a patient not a device

**Comment by vincent-karuri** [comment]
We can close this since we won't be generating IDs
