### ISSUE TITLE
[Quest/eCBIS] Update the Family register to display a Group resource

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1200]
**Name of feature to enhance**
---
- Family representation

**Description of feature**
----

- We currently use the Head of family patient resource to represent a family
- We are moving this to use the [Group resource](https://www.hl7.org/fhir/group.html). 

**Describe the enhancement**
----
- [x] Query all the Groups with the following attributes. 
   - [x] `type` -- Find all Groups with type `person`
   - [x]  `code` -- Find all Groups with the following code
          ```json
          {
            "system": "https://www.snomed.org",
            "code": "35359004",
            "display": "Family"
          }
           ```
- [x] Display the `name` attribute on the name UI position. 
     - [x]  Always Append the name text `Family` at the end of every name. 
- [x] Only query and display the `active` Groups.  This can be checked on the `active` attribute
- [x] On clicking the family row proceed to the [Family Profile.](https://github.com/opensrp/fhircore/issues/1201) 

**Depends on**  -- https://github.com/opensrp/fhircore/issues/1199 
- Can be done concurrently

**Comment by dubdabasoduba** [comment]
@ellykits How far are you with the Quest Configurability pieces? Can we use your branch for this?

**Comment by FikriMilano** [comment]
@ellykits @dubdabasoduba 
Which branch should I pull from?

**Comment by dubdabasoduba** [comment]
https://github.com/opensrp/fhircore/issues/1183 The sample group.

**Comment by FikriMilano** [comment]
Blocked by #1207

**Comment by FikriMilano** [comment]
Closed by https://github.com/opensrp/fhircore/pull/1216
