### ISSUE TITLE
[Quest/eCBIS] Update the Individual profile to display a Patient referenced in a Group resource. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1202]
**Name of feature to enhance**
---
- Family representation

**Description of feature**
----

- We currently use the Head of family patient resource to represent a family
- We are moving this to use the [Group resource](https://www.hl7.org/fhir/group.html). 

**Describe the enhancement**
----
- [ ] Load the Patient Resouce representing the [Patient clicked here](https://github.com/opensrp/fhircore/issues/1201) 

**Depends on**  -- https://github.com/opensrp/fhircore/issues/1200 
- Can be done concurrently

**Comment by dubdabasoduba** [comment]
@ellykits How far are you with the Quest Configurability pieces? Can we use your branch for this?

**Comment by ellykits** [comment]
Closing this. The implementation now available on `main`. Family representation was refactored to use `Group` resource instead and the UI also updated.
