### ISSUE TITLE
[Quest/eCBIS] Remove a Family member represented in the  Group Resource.

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1205]
**Name of feature to enhance**
---
- Family representation

**Description of feature**
----

- We currently use the Head of family patient resource to represent a family
- We are moving this to use the [Group resource](https://www.hl7.org/fhir/group.html). 

**Describe the enhancement**
----
- [x] The individual Patient profile will have a `Remove Person` menu. By clicking this menu a form should be launched to remove the person. 
- [x] If the person is a family head then do the following
    - [x] Remove the RelatedPerson reference on the `managingEntity` attribute on the Group resource representing the family
    - [x] Remove the Patient reference on the `members` attribute on the Group resource representing the family
    - [x] Update the RelatedPerson resource and set the `active` attribute to `false`
    - [x] Update the Patient resource and set the `active` attribute to `false`
    - [x] NB :- We will not be selecting a new family head at this point. 
 - [x] If the person is a normal family member then do the following
    - [x] Remove the Patient reference on the `members` attribute on the Group resource representing the family
    - [x] Update the Patient resource and set the `active` attribute to `false`

**Depends on**  -- https://github.com/opensrp/fhircore/issues/1202
- Can be done concurrently

**Comment by FikriMilano** [comment]
@dubdabasoduba 
Code breakdown:
- [ ] Implement overflow in PatientProfileScreen
- [ ] Add action for remove person in patient profile PatientProfileScreen
- [ ] Implement functionality for launching the RemoveFamilyQuestionnaireActivity (available in FamilyProfileViewModel)
- [ ] Add logic for remove patient loaded from family/individual member

**Comment by FikriMilano** [comment]
Closed by #1235 and #1236
