### ISSUE TITLE
[Quest/eCBIS] - Infrastructure diagram 

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1220]
- [ ] Create an infrastructure diagram for eCBIS project. The diagram to how the relationship between the eCBIS components.

**Comment by dubdabasoduba** [comment]
![fhir_product_architecture_diagram (4)](https://user-images.githubusercontent.com/4817531/165567782-bce043f5-a471-442f-b459-be6d46a2ed6b.png)

**Comment by dubdabasoduba** [comment]
@mberg @AnnieMungai What do you think about this iteration? 

![fhir_product_architecture_diagram_client_](https://user-images.githubusercontent.com/4817531/165591767-bf19d968-272f-4222-aa9c-16fab697a6f5.png)

**Comment by AnnieMungai** [comment]
@dubdabasoduba this is much clearer now.

**Comment by pld** [comment]
Looks pretty good, I don't think we need to show the client endpoints connected to the "Internet", I think we should add a "DNS <-> Internet" section connected to "Akuko/Canopy Dashboards", I also think we should rename "Akuko/Canopy Dashboards" to just "Dashboards", make that generic

**Comment by AnnieMungai** [comment]
On FHIR Core

![Untitled](https://github.com/opensrp/fhircore/assets/58034047/7a4242d7-58b2-4f91-86d7-bc416fc5001a)
