### ISSUE TITLE
[eCBIS FHIR] Create a Measure for eCBIS Indicator 1 - Household Registration 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1233]
Create a measure for eCBIS Measure 1  - Household Registration 

Reference Link: https://docs.google.com/spreadsheets/d/1Kfp0rRYlksrBoSIecAuovZ8Y3k8yH9mkmgHcpQbMtXI/edit#gid=446158820

Each household or a family is represented using a group resource as outlined below 
```
{
  "resourceType": "Group",
  "id": "107759",
  "meta": {
    "versionId": "3",
    "lastUpdated": "2022-04-14T13:54:41.656+00:00",
    "source": "#2f77c0c4a5d11f1e"
  },
  "identifier": [ {
    "use": "official",
    "value": "7bb7fa82-59e4-4744-a6d2-96722afca23b"
  }, {
    "use": "secondary",
    "value": "656766"
  } ],
  "active": true,
  "type": "person",
  "code": {
    "coding": [ {
      "system": "https://www.snomed.org",
      "code": "35359004",
      "display": "Family"
    } ]
  },
  "name": "Kamwana Rao",
  "managingEntity": {
    "reference": "RelatedPerson/2e2c9d4e-b67f-4673-8e83-e3f576046296"
  },
  "member": [ {
    "entity": {
      "reference": "Patient/c535f2e6-a17a-4b2a-913e-30e8b42553d0",
      "display": "Rao Kamwana"
    },
    "inactive": false
  }, {
    "entity": {
      "reference": "Patient/d0612f01-01c3-467e-9fbc-4e6ebe8bf9e6",
      "display": "Magarita Rao"
    },
    "inactive": false
  } ]
}
```

**Narrative** 
1. Numer of households registered in the app
2. Number of Household members registered, disaggregated by age and gender for each age group. 
3. Age disaggregation will be (0-11, 1-5, 6-14, 15-49, 50+)
4. Gender (Male, Female)

**Pre-requisite** 
1. Add a household registration encounter e.g http://hl7.org/fhir/encounter-example-home.json.html

**Comment by f-odhiambo** [comment]
WIP CQL Script : https://github.com/opensrp/fhir-resources/blob/main/cql/eCBIS-CHA-reports/cha-measure-1.cql

**Comment by f-odhiambo** [comment]
**Get all families**
Query  HAPI - https://fhir.labs.smartregister.org/fhir/Group/?code=35359004

**Results**

Bundle of families 

```
{
    "resourceType": "Bundle",
    "id": "17d6be40-6546-4a20-b45f-38badc4e9edc",
    "meta": {
        "lastUpdated": "2022-05-06T07:09:57.104+00:00"
    },
    "type": "searchset",
    "total": 15,
    "link": [
        {
            "relation": "self",
            "url": "https://fhir.labs.smartregister.org:443/fhir/Group/?code=35359004"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/107759",
            "resource": {
                "resourceType": "Group",
                "id": "107759",
                "meta": {
                    "versionId": "5",
                    "lastUpdated": "2022-05-05T07:38:49.542+00:00",
                    "source": "#efccd100be26aa12"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "7bb7fa82-59e4-4744-a6d2-96722afca23b"
                    },
                    {
                        "use": "secondary",
                        "value": "656766"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "Kamwana Rao",
                "managingEntity": {
                    "reference": "RelatedPerson/194ee240-fdd8-4b35-988d-bf0210e06766"
                },
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/c535f2e6-a17a-4b2a-913e-30e8b42553d0",
                            "display": "Rao Kamwana"
                        },
                        "inactive": false
                    },
                    {
                        "entity": {
                            "reference": "Patient/1742d6b6-1615-4365-8a3c-cf2ad1cc0304"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/0f302aec-5d4f-49ba-a233-a591452c021b",
            "resource": {
                "resourceType": "Group",
                "id": "0f302aec-5d4f-49ba-a233-a591452c021b",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-04-21T13:46:25.660+00:00",
                    "source": "#9fe80dc68301aed6"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "32343254"
                    },
                    {
                        "use": "secondary",
                        "value": "a05ff632-9b8d-45f7-81df-1f5a7191d69d"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "managingEntity": {
                    "reference": "Organization/362"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/e6155347-539c-4b15-98c3-c92a6290ba9b",
            "resource": {
                "resourceType": "Group",
                "id": "e6155347-539c-4b15-98c3-c92a6290ba9b",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-04-27T06:09:31.033+00:00",
                    "source": "#0f7561c504765f24"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "2343232"
                    },
                    {
                        "use": "secondary",
                        "value": "48947c82-2636-47a1-aaea-4a3956da0580"
                    }
                ],
                "active": false,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "Meme Loard",
                "managingEntity": {
                    "reference": "Organization/362"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/4d7150e0-99ac-476c-aad8-87cf69b27855",
            "resource": {
                "resourceType": "Group",
                "id": "4d7150e0-99ac-476c-aad8-87cf69b27855",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-04-28T22:42:26.471+00:00",
                    "source": "#c09496a36aa5351e"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "234234324"
                    },
                    {
                        "use": "secondary",
                        "value": "1d07150b-714d-4dc9-93ed-2650e07d9a07"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "Elon Musk",
                "managingEntity": {
                    "reference": "Organization/362"
                },
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/f117e2e2-91ac-4345-9892-6e0aae785b39"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/1511ef3c-2c1e-459e-8cee-251186cec303",
            "resource": {
                "resourceType": "Group",
                "id": "1511ef3c-2c1e-459e-8cee-251186cec303",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-04-28T07:23:03.684+00:00",
                    "source": "#4a300d905a43fb48"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "9897980"
                    },
                    {
                        "use": "secondary",
                        "value": "4c497584-94c0-45c6-8aaa-4bdaa50ca467"
                    }
                ],
                "active": false,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "Family 001",
                "managingEntity": {
                    "reference": "Organization/105"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/95567a4a-7852-43a4-b99e-942bb86b2f5f",
            "resource": {
                "resourceType": "Group",
                "id": "95567a4a-7852-43a4-b99e-942bb86b2f5f",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-04-27T13:33:36.714+00:00",
                    "source": "#710f6f59942640e5"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "989675645"
                    },
                    {
                        "use": "secondary",
                        "value": "653942b7-9308-414d-b168-2b2613db8d7f"
                    }
                ],
                "active": false,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "Munge",
                "managingEntity": {
                    "reference": "Organization/105"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/1122f50c-5499-4eaa-bd53-a5364371a2ba",
            "resource": {
                "resourceType": "Group",
                "id": "1122f50c-5499-4eaa-bd53-a5364371a2ba",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-04-28T22:16:26.172+00:00",
                    "source": "#9b1b6371db49d9bb"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "124"
                    },
                    {
                        "use": "secondary",
                        "value": "c90cd5e3-a1c4-4040-9745-433aea9fe174"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "new family",
                "managingEntity": {
                    "reference": "Organization/105"
                },
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/7d84a2d0-8706-485a-85f5-8313f16bafa1"
                        }
                    },
                    {
                        "entity": {
                            "reference": "Patient/0beaa1e3-64a9-436f-91af-36cbdaff5628"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/4e3d671d-83f3-4439-985c-7c679f25fd4a",
            "resource": {
                "resourceType": "Group",
                "id": "4e3d671d-83f3-4439-985c-7c679f25fd4a",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-04-29T18:04:38.885+00:00",
                    "source": "#349ec6e940ec076d"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "123"
                    },
                    {
                        "use": "secondary",
                        "value": "b8794278-a7d0-4690-9979-7fb8511b52e3"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "skyfall",
                "managingEntity": {
                    "reference": "Organization/105"
                },
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/83ca19e1-123a-42c1-8a74-342a85c41f20"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/1f8c354b-7633-4f2b-af6c-c0ac54ccfa32",
            "resource": {
                "resourceType": "Group",
                "id": "1f8c354b-7633-4f2b-af6c-c0ac54ccfa32",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-05-05T13:40:54.082+00:00",
                    "source": "#2be79f5cd6b71909"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "9134"
                    },
                    {
                        "use": "secondary",
                        "value": "798ca6ca-b04c-4a4a-8571-c14bfe15a45f"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "umer",
                "managingEntity": {
                    "reference": "Organization/105"
                },
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/8628a228-15ea-47fb-9459-662145e9e19d"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/194a72a2-4d94-4202-b806-9fafc2cd6b8c",
            "resource": {
                "resourceType": "Group",
                "id": "194a72a2-4d94-4202-b806-9fafc2cd6b8c",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-04-27T15:41:15.835+00:00",
                    "source": "#398cefae23489a2a"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "56545"
                    },
                    {
                        "use": "secondary",
                        "value": "c4c150a3-d104-448a-be68-5b88c1a9aea4"
                    }
                ],
                "active": false,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "Munge 2 Family"
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/e8ed1bb3-b1d5-40ad-9415-908d3fc237f0",
            "resource": {
                "resourceType": "Group",
                "id": "e8ed1bb3-b1d5-40ad-9415-908d3fc237f0",
                "meta": {
                    "versionId": "3",
                    "lastUpdated": "2022-04-28T18:43:13.601+00:00",
                    "source": "#bff6eca6dec85d4c"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "12822"
                    },
                    {
                        "use": "secondary",
                        "value": "3c8ffef8-a8ec-4f32-868f-a92338f52cbc"
                    }
                ],
                "active": false,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "RothRock",
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/d213fa70-c6a6-4f64-8d13-ef147cc9a7b5"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/1083",
            "resource": {
                "resourceType": "Group",
                "id": "1083",
                "meta": {
                    "versionId": "3",
                    "lastUpdated": "2022-05-05T07:04:45.662+00:00",
                    "source": "#bb75a5d4ca0f8ec4"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "32123151"
                    },
                    {
                        "use": "secondary",
                        "value": "3e2c6126-fd25-4089-96cf-4999bf50d278"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "Test Group Family Edited",
                "managingEntity": {
                    "reference": "RelatedPerson/5e1a435b-26cc-4d30-ac52-e1901d9c434e"
                },
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/8f730a53-12c1-4ac8-bbf6-07076ab70ea4"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/1818d503-7226-45cb-9ac7-8c8609dd37c0",
            "resource": {
                "resourceType": "Group",
                "id": "1818d503-7226-45cb-9ac7-8c8609dd37c0",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-05-05T07:40:49.168+00:00",
                    "source": "#3d54ef467387e718"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "42152245"
                    },
                    {
                        "use": "secondary",
                        "value": "c61ca325-9508-47d8-a435-ddd982a556c1"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "The Royal"
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/335de157-0142-4c8e-9e2d-f94473a6ba0d",
            "resource": {
                "resourceType": "Group",
                "id": "335de157-0142-4c8e-9e2d-f94473a6ba0d",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-05-05T16:08:35.222+00:00",
                    "source": "#85e16df61029cada"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "123234"
                    },
                    {
                        "use": "secondary",
                        "value": "4e71c1b3-ed84-448b-844c-324319941181"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "Randiki",
                "managingEntity": {
                    "reference": "Organization/105"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://fhir.labs.smartregister.org:443/fhir/Group/ea15c389-0472-472e-b674-6eb6f1182410",
            "resource": {
                "resourceType": "Group",
                "id": "ea15c389-0472-472e-b674-6eb6f1182410",
                "meta": {
                    "versionId": "2",
                    "lastUpdated": "2022-05-05T16:32:05.679+00:00",
                    "source": "#f053ff6bd084f0c1"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "182199"
                    },
                    {
                        "use": "secondary",
                        "value": "dda9b513-ff50-4be2-aec9-6a5917afdfae"
                    }
                ],
                "active": true,
                "type": "person",
                "code": {
                    "coding": [
                        {
                            "system": "https://www.snomed.org",
                            "code": "35359004",
                            "display": "Family"
                        }
                    ]
                },
                "name": "David",
                "managingEntity": {
                    "reference": "Organization/105"
                },
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/bb91218f-c4c5-40df-9b57-82277fc6e2ea"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}
```

**Comment by maimoonak** [comment]
The branch https://github.com/opensrp/android-fhir/tree/kt/evaluateMeasurewithObservation has the working cql and test. The output  in logs for test data is 

```
POPULATION - groups: [initial-population = 17, denominator = 17, numerator = 17]
SCORE      - 1.0
STRATIFIER - null:
[]
POPULATION - males: [initial-population = 17, denominator = 17, numerator = 7]
SCORE      - 0.4117647058823529
STRATIFIER - by-age:
[P0Y -- [initial-population=1, denominator=1, numerator=1] 
, P50Y -- [initial-population=1, denominator=1, numerator=0] 
, P15-49Y -- [initial-population=2, denominator=2, numerator=1] 
, P6-14Y -- [initial-population=2, denominator=2, numerator=0] 
, P1-5Y -- [initial-population=11, denominator=11, numerator=5] 
]
POPULATION - females: [initial-population = 17, denominator = 17, numerator = 10]
SCORE      - 0.5882352941176471
STRATIFIER - by-age:
[P0Y -- [initial-population=1, denominator=1, numerator=0] 
, P50Y -- [initial-population=1, denominator=1, numerator=1] 
, P15-49Y -- [initial-population=2, denominator=2, numerator=1] 
, P6-14Y -- [initial-population=2, denominator=2, numerator=2] 
, P1-5Y -- [initial-population=11, denominator=11, numerator=6] 
]
```
The way evaluate measure runs is not performant when run on huge data set. We can talk with CQL team on this.
The Groups as main subject is not supported, but still it works by having a joined query on Patient table.

**Comment by f-odhiambo** [comment]
Final output TBD

,,,
{
  "resourceType": "MeasureReport",
  "extension": [
    {
      "url": "http://hl7.org/fhir/5.0/StructureDefinition/extension-MeasureReport.population.description",
      "valueString": "???????????"
    }
  ],
  "status": "complete",
  "type": "summary",
  "measure": "Measure/group-measure",
  "date": "2022-05-20T14:17:20+03:00",
  "period": {
    "start": "2019-01-01T00:00:00+03:00",
    "end": "2022-12-31T23:59:59+03:00"
  },
  "improvementNotation": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/measure-improvement-notation",
        "code": "increase"
      }
    ]
  },
  "group": [
    {
      "id": "groups",
      "population": [
        {
          "id": "initial-population",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "initial-population"
              }
            ]
          },
          "count": 17
        },
        {
          "id": "denominator",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "denominator"
              }
            ]
          },
          "count": 17
        },
        {
          "id": "numerator",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "numerator"
              }
            ]
          },
          "count": 17
        }
      ],
      "measureScore": {
        "value": 1
      }
    },
    {
      "id": "males",
      "population": [
        {
          "id": "initial-population",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "initial-population"
              }
            ]
          },
          "count": 17
        },
        {
          "id": "denominator",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "denominator"
              }
            ]
          },
          "count": 17
        },
        {
          "id": "numerator",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "numerator"
              }
            ]
          },
          "count": 7
        }
      ],
      "measureScore": {
        "value": 0.4117647058823529
      },
      "stratifier": [
        {
          "id": "by-age",
          "stratum": [
            {
              "value": {
                "text": "P0Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 1
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 1
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 1
                }
              ],
              "measureScore": {
                "value": 1
              }
            },
            {
              "value": {
                "text": "P50Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 1
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 1
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 0
                }
              ],
              "measureScore": {
                "value": 0
              }
            },
            {
              "value": {
                "text": "P15-49Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 2
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 2
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 1
                }
              ],
              "measureScore": {
                "value": 0.5
              }
            },
            {
              "value": {
                "text": "P6-14Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 2
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 2
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 0
                }
              ],
              "measureScore": {
                "value": 0
              }
            },
            {
              "value": {
                "text": "P1-5Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 11
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 11
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 5
                }
              ],
              "measureScore": {
                "value": 0.45454545454545453
              }
            }
          ]
        }
      ]
    },
    {
      "id": "females",
      "population": [
        {
          "id": "initial-population",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "initial-population"
              }
            ]
          },
          "count": 17
        },
        {
          "id": "denominator",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "denominator"
              }
            ]
          },
          "count": 17
        },
        {
          "id": "numerator",
          "code": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                "code": "numerator"
              }
            ]
          },
          "count": 10
        }
      ],
      "measureScore": {
        "value": 0.5882352941176471
      },
      "stratifier": [
        {
          "id": "by-age",
          "stratum": [
            {
              "value": {
                "text": "P0Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 1
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 1
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 0
                }
              ],
              "measureScore": {
                "value": 0
              }
            },
            {
              "value": {
                "text": "P50Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 1
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 1
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 1
                }
              ],
              "measureScore": {
                "value": 1
              }
            },
            {
              "value": {
                "text": "P15-49Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 2
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 2
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 1
                }
              ],
              "measureScore": {
                "value": 0.5
              }
            },
            {
              "value": {
                "text": "P6-14Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 2
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 2
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 2
                }
              ],
              "measureScore": {
                "value": 1
              }
            },
            {
              "value": {
                "text": "P1-5Y"
              },
              "population": [
                {
                  "id": "initial-population",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "initial-population"
                      }
                    ]
                  },
                  "count": 11
                },
                {
                  "id": "denominator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "denominator"
                      }
                    ]
                  },
                  "count": 11
                },
                {
                  "id": "numerator",
                  "code": {
                    "coding": [
                      {
                        "system": "http://terminology.hl7.org/CodeSystem/measure-population",
                        "code": "numerator"
                      }
                    ]
                  },
                  "count": 6
                }
              ],
              "measureScore": {
                "value": 0.5454545454545454
              }
            }
          ]
        }
      ]
    }
  ]
}
,,,

**Comment by f-odhiambo** [comment]
NB. This work requires us to add an update the $measure_report API and on Android FHIR SDK

**Comment by pld** [comment]
is there an issue on the Android FHIR SDK repo for this?

**Comment by f-odhiambo** [comment]
@pld The related Issue https://github.com/google/android-fhir/issues/1107 and PR https://github.com/google/android-fhir/pull/1280 on Android SDK
