### ISSUE TITLE
[Quest/eCBIS] - P2P Sync is taking too long - initial and subsequent

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1249]
**Describe the bug**

- [ ] Sync is taking too long to complete. Initial sync took more than 20minutes to complete. 
- [ ] Subsequent sync period was over 5minutes to complete. 

**To Reproduce**
1. Download the app and log in.
2. Observe what happens with the initial sync. 
3. After the sync is complete, navigate to the side panel and initiate the manual sync process. Observe the time it takes to complete the sync.

**Expected behavior**
- The initial sync should be fast and take only a few minutes/seconds depending on the amount of data on the server. 
- The subsequent sync takes a few seconds. 

**Smartphone (please complete the following information):**
 - Device: Oppo F9 and Samsung Galaxy A2. 
 - Android: 10
 - Build number:  eCBIS v.0.0.5

**Comment by f-odhiambo** [comment]
**Update May 9th, 2022**
Looking  into this and some possible initial issues 
1. How are we currently authenticating/ passing tokens for each page sync for the paginated sync?
2. Getting the following errors `400` and `422` for some resources 
3. Failing `Valuesets` and `Bundles`  not being synced / multiple retries 
4. Linked resources and non-tagged resources per health vertical

**Comment by charlene-570** [comment]
@AnnieMungai 

Device to device sync takes longer than 20 minutes see recording attached

https://user-images.githubusercontent.com/85434942/176634598-2730219f-aa6a-47da-b5e4-34dc9a7c63f4.mp4

**Comment by f-odhiambo** [comment]
Take note @Rkareko @ekigamba on above issue

**Comment by ekigamba** [comment]
@f-odhiambo Could we split the sync issues into 2 issues so that it's easy to follow up on each issue? I believe we have the device-sync issue while the video above is on searching and pairing devices during p2p sync

**Comment by AnnieMungai** [comment]
@charlene-570 let's retest this.

**Comment by charlene-570** [comment]
@AnnieMungai   
See results after retest:
Initial sync complete takes ... and Manual sync process takes long plus the Date is wrong see screen recording attached
