### ISSUE TITLE
Land on family/household register on login

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1250]
App version: eCBIS v.0.0.5
**Describe the bug**

- [ ] Once a user logs into the app, they are redirected to the PNC register. 

**To Reproduce**
1. Log into the app and sync data. 
2. Observe what happens. 

**Expected behavior**
Once a user logs into the app, they should land on the Households page. This page displays all the households registered in the app. 
![image](https://user-images.githubusercontent.com/58034047/166236830-14e425a3-e675-49be-b4ca-6f2a5d6af08c.png)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oppo F9 an Samsung Galaxy
 - Android version: 10

**Additional context**

**Comment by FikriMilano** [comment]
Closed by #1261
