### ISSUE TITLE
[Quest/eCBIS] - Client profile - top right overflow menu items are missing

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1251]
**Describe the bug**
When you navigate to a client profile, the top right-hand side menu has only 1 option. Thus, user:
- [x] Cannot edit the client registration details. 
- [x] Cannot mark a client as pregnant (pregnant outcome)
- [x] Cannot mark as the deceased client. 

![image](https://user-images.githubusercontent.com/58034047/166250068-3b30ea77-18dd-4296-8c8d-41431dd03343.png)

**To Reproduce**
1. Log into the app. 
2. Register a female client over 15years. 
3. Navigate to their profile, and tap on the top right hand corner menu. The menu will open up. Observe the options available. 

**Expected behavior**
Once a user is registered, there should be the following options on their profile (top right menu)
- Edit info - to edit registration details for the client. Tapping on the "edit info" on the top right-hand corner menu will open up the client registration form. User should be able to edit any editable parts of the form and save them once completed. All changes updated should reflect on the client's profile. 
- Mark as deceased - this is accessed from the top-right menu. This shows on any client's profile. Tapping on this opens the person removal form. Filling this form and confirming removal will remove the person from that household's register. The name will still show on the register but marked as deceased. 
- Record pregnancy - If the client is a female over 15 years old (female of reproductive age) - the 'record pregnancy option should be displayed on the top-right menu. Tapping on this option opens the pregnancy recording form. 
![image](https://user-images.githubusercontent.com/58034047/166250462-e0effa8d-77ba-4eb5-bcef-3b5de43e3230.png)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Comment by FikriMilano** [comment]
@dubdabasoduba @f-odhiambo 
I'm picking this up.

**Comment by FikriMilano** [comment]
@dubdabasoduba 
I have questions:

1. What is the indicator that a family member is deceased? Attributes or coding system perhaps?

2. Do you have the Questionnaire form for marking a family member as deceased?

3. What is the indicator that a family member is pregnant? Attributes or coding system perhaps?

4. Do you have the Questionnaire form for marking a family member as pregnant?

**Comment by dubdabasoduba** [comment]
@FikriMilano 

> What is the indicator that a family member is pregnant? Attributes or coding system perhaps?
> Do you have the Questionnaire form for marking a family member as pregnant?

This will be handled in the following issue https://github.com/opensrp/fhircore/issues/1345

**Comment by FikriMilano** [comment]
Got it

**Comment by AnnieMungai** [comment]
v.0.0.7
Marking this as closed as the items are now available on the top-right menu. 
cc @dubdabasoduba
