### ISSUE TITLE
[Quest/eCBIS] - Child visit task/schedule not working correctly

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1252]
eCBIS v.0.0.5
**Describe the bug**
When a child is registered, the child monthly schedules onto the app. However, when you tap on the child visit task, it is inactive. 
Also, tapping on a child's profile shows the child visit tasks and nothing else. 

**To Reproduce**
1. Log into the application. 
2. Register a child who is under 5 years old. 
3. Once registered, the tasks for 3 child visits will load. 
4. Tap on any of the tasks and observe. The user is not able to record a child visit. 
![image](https://user-images.githubusercontent.com/58034047/166270012-1390519a-38f6-4cda-978a-b694eb5d7072.png)

**Acceptance Criteria**
Context: A child under 5 years is supposed to be visited every month y the CHA as per the schedule shown [here](https://docs.google.com/spreadsheets/d/1zi1ELaSCebXfNjMsu9ODAxKeAODy_8LLpPuVqqysa4E/edit#gid=1757872948). 
- [ ] If a child is not visited during the month, the task becomes overdue at the start of the next month and shows as red.
- [ ] If a child visit is due this month, it will show in blue. 
- [ ] If a child's task is not yet due - say it becomes due next month, then it shows in gray. 
- [ ] If a visit is completed, the child visit will show green in color (see example below from v.0.0.4). 

![image](https://user-images.githubusercontent.com/58034047/166274968-37dc2392-548a-4b7f-974c-985325e52d72.png)

**Comment by dubdabasoduba** [comment]
@ellykits Currently the popup shows all the tasks which makes it hard to go to the screen @AnnieMungai mentioned. Could we makes sure the bottom sheet only shows 2 tasks of each type

**Comment by dubdabasoduba** [comment]
We can show the due or overdue tasks only. The others can either be listed out on the patient profile or appear when they are due.

**Comment by AnnieMungai** [comment]
v.0.0.7
Due, overdue, not yet due buttons working correctly.
