### ISSUE TITLE
Barcode issue and search in covax use case 

### ISSUE THREAD

**Issue by isabelcshaw** [opensrp/fhircore#126]
UPDATED 5.14 

This issue has been updated to describe the needed workflows for the covax demo. Please note @f-odhiambo that the WHO confirmed today that this will be a barcode, not a QR code. 

We need to build two barcode workflows: 
1. Patient registration 
2. Patient search  

~~@rowo will add visuals in the comments to guide the UI~~ EDIT: Roger added images below and here's a link to clickthrough: https://www.figma.com/proto/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?page-id=1001%3A5305&node-id=1002%3A5506&viewport=699%2C624%2C0.25&scaling=min-zoom

**Workflow 1: Registration** 
1. Hit "register new client"
2. Open registration form 
3. Scan barcode button will be the top of the form
4. Scan barcode 
5. When successfully scanned, show confirmation in form field   

<img src="https://user-images.githubusercontent.com/1584163/118430679-9b379380-b6a2-11eb-88b0-1df78d2bba43.png" width="200">
<img src="https://user-images.githubusercontent.com/1584163/118430684-9f63b100-b6a2-11eb-879a-82bf5cda077e.png" width="200">
<img src="https://user-images.githubusercontent.com/1584163/118430688-a12d7480-b6a2-11eb-87de-a5b5aa96ee99.png" width="200">

**Workflow 2: Patient Search Happy Path** 
1. User is on home view 
2. Hit search by barcode code button 
3. Launches barcode scanner (searches locally and the server when online - for the demo, we could just build local search if that saves time) 
4. Successful scan results in the profile view with the patient profile
[This is the same for both online and offline scenarios]

<img src="https://user-images.githubusercontent.com/1584163/118430679-9b379380-b6a2-11eb-88b0-1df78d2bba43.png" width="200">
<img src="https://user-images.githubusercontent.com/1584163/118430865-0d0fdd00-b6a3-11eb-9da0-87b7216db6c5.png" width="200">
<img src="https://user-images.githubusercontent.com/1584163/118430870-11d49100-b6a3-11eb-82f5-7763088dbc23.png" width="200">

---------
NOT for demo (but needs to be built after)

**Workflow 3: Patient Search Not Found Path** 
[Steps 1-3 above]
4. App is OFFLINE (aka the expectation is that the patient has been registered elsewhere): Unsuccessful message offering ways forward 
5. Hit record vaccine
6. Open vaccination form   

Though it is possible for there to be a scenario where the app is online and the barcode scan still does not return a result, this would be an edge case. We do not need to accommodate this in the short term.

**Comment by mberg** [comment]
Here is how I propose we handle the logic in the long term.

If the app is online, we will search the barcode.  If the user is not found, we will want to search the cloud to see if they are already registered in the system. If they are not found, we would then register them.   

If the app is offline, we do NOT want to register the patient for a vaccine.   All we want to do is take them to the vaccine form and capture their vaccine status.  We will submit that data along with their composition id (bar code ID) and the system can reconcile the record on the back end.

So summary of workflow

Registration
- Register client.  Scan in barcode (composition id) and link that to the account

Vaccine
- Search for client by name or with bar code
- Online
-- If found, launch form record vaccine
-- If not found, search online for person.  If found, launch form passing ID.  If not found, register client.
- Offline - launch vaccine form, pass composition id from search, record vaccine and submit.  We will reconcile on server.  If the patient is not registered, we will capture patient data later.  We need to talk through how this is supported.
