### ISSUE TITLE
[COVAX demo app] Build barcode scanner

### ISSUE THREAD

**Issue by vincent-karuri** [opensrp/fhircore#127]
We need to scan barcodes that contain Patient identifiers and use the identifiers in retrieving records.

- [x] Add `Scan Bar Code` button on register page
- [x] Build out barcode scanner logic (look at https://github.com/google/android-fhir/tree/jt/bar-code)
- [x] Wire barcode scanner results to existing search functionality

Mockups: https://www.figma.com/proto/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?page-id=1001%3A5305&node-id=1002%3A5506&viewport=699%2C624%2C0.25&scaling=min-zoom

User stories: https://github.com/opensrp/fhircore/issues/126#issue-891444397

**Comment by vincent-karuri** [comment]
<img width="1053" alt="Screen Shot 2021-05-14 at 1 05 55 PM" src="https://user-images.githubusercontent.com/33488286/118460224-28abcf80-b705-11eb-90de-3c058ffae29b.png">

sample barcode

**Comment by vincent-karuri** [comment]
@f-odhiambo as, discussed, we'll need to pin down the exact information that is going to be encoded into the barcode which will be essential for the extraction/post-scanning step.

**Comment by vincent-karuri** [comment]
https://github.com/google/android-fhir/tree/jt/bar-code works fine as an embedded Questionnaire widget. Only thing that may change is a bit of the UI. It also doesn't support re-scanning atm.

Need to evaluate the LOE in moving this to an independently-launchable feature e.g. from the register page.

**Comment by f-odhiambo** [comment]
> @f-odhiambo as, discussed, we'll need to pin down the exact information that is going to be encoded into the barcode which will be essential for the extraction/post-scanning step.

Based on the requirements we are going to generate a set of ids that are going to be printed on the patient's card as a barcode and also assigned to the patient details for reference in the app. So as an example a card will have a barcode that scans (001000225). The Id will also be tagged to a patients details as a reference to pull their details

**Comment by vincent-karuri** [comment]
closed by https://github.com/opensrp/fhircore/pull/129
