### ISSUE TITLE
[Quest/Malawi Core] -Append list of a Patient's general practitioners 

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1274]
**Name of feature to enhance**
Setting a general practitioner to a Patient post questionnaire extraction.

**Description of feature**
For the mw-core project, a CHW registering a Patient is not always the one who will be responsible for their care i.e. who will go and look for them when they need to be traced. As a result, in our patient registration questionnaire, the user is meant to select a CHW who will be responsible for the patient's care. Consequently, in our structure map, this CHW is extracted and set as the general practitioner of the patient. However, after syncing the patient to the server, the general practitioner is still the CHW who registered the patient i.e. the user signed into the app.

I followed this up and noticed that the code (appendPractitionerInfo function in QuestionnaireViewModel) is assigning the signed in user as a general practitioner after the extraction takes place. I guess this makes sense as you would want to know who registered the patient. The issue comes in where the appendPractitionerInfo isn't really appending, instead it is replacing the existing general practitioner list with a new list. I assume the function should just add to the existing general practitioners. 

**Describe the enhancement**
Instead of replacing existing general practitioner list, add the general practitioner to the existing list.

**Comment by pld** [comment]
Good catch, I'm labeling this as an error, I do not think this should be doing replacement.

**Comment by f-odhiambo** [comment]
A few questions 
1. Are we supposed to fetch the list of practitioners from SQLite DB  and then populate the questionnaire dynamically ? If so, we may need to look at the spec and see how this is done https://hl7.org/fhir/uv/sdc/stu3/populate.html . Not sure this is supported yet 

CC @KhumboLihonga @pld @Gental-Giant

**Comment by KhumboLihonga** [comment]
1. Ideally that would be the case (we should open a ticket for that if one doesn't exist) but for now, as a workaround, we will just statically add the list of CHWs to the questionnaire in a drop-down/auto-complete widget. Since they will be added as a list of Coding objects, the code will be their id on the server and the display will be their full name. So in the structure map we will extract the code, create a reference from it, and add them to the list of general practitioners.
2. Apologies, this wasn't in the initial mockups we shared. I've updated the [newly diagnosed client mockup](https://docs.google.com/presentation/d/1A4e98GVesRpeygbctCLvbAH9tghP8Mpk/edit#slide=id.p9) to reflect this discussion, please check slide 9. We will update the other mockups accordingly.

**Comment by AbdulWahabMemon** [comment]
linked PR is merged, this issue can be close

**Comment by f-odhiambo** [comment]
linked PR is merged
