### ISSUE TITLE
MWCore Navigation

### ISSUE THREAD

**Issue by Gental-Giant** [opensrp/fhircore#1276]
**Describe the Issue**

- [ ] Switch from bottom navigation bar to navigation drawer
- [ ] In the navigation drawer, Add 'Tracing' as an option
- [ ] In the navigation drawer, Add 'Appointments' as an option
- [ ] In the navigation drawer, Add 'Reports' as an option

**Comment by Gental-Giant** [comment]
Related to this [landing page issue](https://github.com/opensrp/fhircore/issues/1187)

**Comment by pld** [comment]
Can this all be managed through the configuration files?

**Comment by f-odhiambo** [comment]
> Can this all be managed through the configuration files?  
Yes they can

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo , FYI there is code changes required, added new HealthModule and registerDao implementation,

**Comment by pld** [comment]
Can you explain the changes in more detail?
