### ISSUE TITLE
[Quest] - Sync resources based on the publisher attribute 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1279]
**Name of feature to enhance**
Sync resources based on the publisher attribute retrieved from the practitioner/user credentials at login 

**Description of feature**
As part of sync profiling and enhancement, we need to limit the resources being synced to be only relevant to the health vertical we are configuring in order for the app to have only the relevant required resources 
 
**Describe the enhancement**

1. Link StructureMaps  using publisher fields

**Comment by pld** [comment]
Is the same as syncing based on the app id? If not, what is the relationship between this and the app id?

**Comment by f-odhiambo** [comment]
@pld We use the config ID to determine the health vertical we are building and then use it to sync resources based on the publisher attribute which should be the same as the app id/ config id 


NB. @ellykits @roywanyaga The StructureMaps has a [publisher](https://www.hl7.org/fhir/structuremap.html#:~:text=Date%20last%20changed-,publisher,-%CE%A3) attribute, however, the  Groups and Binary resources do not have a publisher attribute. For the group, we can make use of the [ManagingEntity](https://www.hl7.org/fhir/group.html#:~:text=Number%20of%20members-,managingEntity,-%CE%A3) although we might need to do some RnD to determine an applicable field for the Binary Resource

**Comment by f-odhiambo** [comment]
@pld  from my research we can have the same app config and [publisher](https://www.hl7.org/fhir/structuremap-definitions.html#StructureMap.publisher) id attribute similar,  both are strings. However, not all resources support the publisher attribute and in our use case, we just use it on Questionnaires and StrucutureMaps. 
We can use [ManagingEntity](https://www.hl7.org/fhir/group.html#:~:text=Number%20of%20members-,managingEntity,-%CE%A3) for Groups and [ManagingOrganisation](https://www.hl7.org/fhir/patient-definitions.html#Patient.managingOrganization) for Patients and then filter using [Tags](https://www.hl7.org/fhir/search.html#tag) possible to only sync patients for a specific health vertical/managing organization to filter health data for a specific org.

**Comment by pld** [comment]
OK so as discussed today I think it makes sense to add app-id consistently to every single resource associated with a particular app, so we can prefilter on it and so we have a clean way to split data if we do multi-tenant, or just for staging

How/where we store that on some resources, not sure

**Comment by pld** [comment]
For non-patient composition, do I need to know the official identifier, is that all? Like `93bc9c3d-6321-41b0-9b93-1275d7114e22` to get the content?

Also Matt asked about how we could track versions in there, I think that's a good question worth addressing

**Comment by dubdabasoduba** [comment]
> For non-patient composition, do I need to know the official identifier, is that all? Like `93bc9c3d-6321-41b0-9b93-1275d7114e22` to get the content?
> 
> Also Matt asked about how we could track versions in there, I think that's a good question worth addressing

The FHIR server has a Version attribute on the metadata. Anytime a resource changes then this is updated. We can also use the same to fetch the resources. So if the version hasn't changed then we don't download it. 

the referencing of the different resources in the composition uses the resource id. So the user would need to know the ID. We could eventually make it easier fr users to copy-paste these IDs on the FHIR web UI. 

Maybe later still on FHIR web we could be the wizard @pld had suggested this way the composition is built as you upload the resources through the platform

**Comment by dubdabasoduba** [comment]
> I think it would be worthwhile to also figure out how far back we want to sync related data eg. Encounters that are more than 3 months old are not synced else we shall be still syncing the entire DB

I think for health data it might be hard to cut off active data. I think if we have a plan to mark data as inactive and closed then we can use that to only sync active data.

**Comment by roywanyaga** [comment]
> @f-odhiambo @pld Based on my current understanding of sync we have 2 phases and several approaches as outlined below.
> 
> ## **Non-patient data sync**
> **1. Publisher tagging approach (Currently being deprecated)**
> 
> * Here we tagged the different resources with a publisher id e.g `g6dp` for G6PD questionnaires and associated resources.
> 
> **2. Composition resource approach (Final SAA approach)**
> 
> * This approach is described [here](https://github.com/opensrp/fhircore/discussions/594#discussioncomment-1635591).
> * We reference all the non-patient data resources to be synced to the device. These are referenced on the `section` attribute of the composition resource.
> * Some of the most likely resources to have here include
>   
>   * Questionnaires
>   * StructureMaps
>   * Binary resources (for configs)
>   * Parameter resources (if we get to use them)
> 
> ## **Patient/Household data sync**
> * Here we combine two ideas
>   
>   * When creating any patient/household tag them with the app ID. This will help reduce the dataset to search through incase the server holds multiple app data.
>   * Figure out the correct sync approach based on the conversations going on [here](https://github.com/opensrp/fhircore/discussions/746).

Attempting to implement the second approach "**Composition resource approach (Final SAA approach)**" resulted in a FHIR JSON parsing error when I included the Questionnaires and/or StructureMaps explicitly in the Composition resource under the section attribute:
 
```
 {
      "title": "Add Family Member",
      "focus": {
        "reference": "Questionnaire/82953",
        "identifier": {
          "value": "family-member-registration"
        }
      },
      "mode": "working"
    }
```

`/AppSettingViewModel: ca.uhn.fhir.parser.DataFormatException: Failed to parse JSON encoded FHIR content: Content does not appear to be FHIR JSON, first non-whitespace character was: '<' (must be '{')`

**The following approach works:**
Adding an `_id` Search Parameter the **sync config** Binary/Parameter Resource and explicitly specifying the IDs of the resources (StructureMaps, QuestionnaireResponse, Questionnaires etc) that are needed for a particular app instance.

```
        {
            "resource": {
                "resourceType": "SearchParameter",
                "name": "_id",
                "code": "_id",
                "base": [
                    "StructureMap"
                ],
                "type": "token",
                "expression": "103346,5667cfbd-13c4-4111-b952-7cee58bdb9d5"
            }
        }
```

cc @f-odhiambo  @dubdabasoduba @pld 

Also, is there any reason why the approach for using the publisher (app-id) tag is being deprecated?

**Comment by dubdabasoduba** [comment]
@roywanyaga What is the actual response. Also, have we checked that the fetch of the Questionnaires & StructureMap is done after login. The 2 endpoints require authentication. 

We are deprecating the `publisher` pieces because we can't use them for other resources without the attribute. Also, the configuration of this includes updating per user based on keycloak. The configuration that uses compositions will be app wise.

The composition resource is also used to provide the entry point and direction of the configurable app.

**Comment by roywanyaga** [comment]
> `AppSettingViewModel: ca.uhn.fhir.parser.DataFormatException: Failed to parse JSON encoded FHIR content: Content does not appear to be FHIR JSON, first non-whitespace character was: '<' (must be '{')`
This is the response. But now I know it's because the response is in HTML (404). 

The composition resource is loaded before login. Thus, the approach to have the Questionnaire, StructureMap, and QuestionnaireResponse in the sync config **(that is included as a Binary/Parameter resource in the Composition)** and using `_id `as the SearchParameter will be ideal because they are synced after login.

**Comment by roywanyaga** [comment]
Based on discussion with @dubdabasoduba, 
1. The Non-Patient Data (Non-Patient Data (Questionnaire, StructureMaps, QuestionnaireResponse, Binary and Parameter Resources) will be synced through the Composition Resource. We however will need to only load the Binary and Parameter Resources. Issue [#1307](https://github.com/opensrp/fhircore/issues/1307) will be used to track this enhancement.

2. StructureMaps will be updated to include the app-id tag for patients and households. A separate Issue will be created for this.

**Comment by roywanyaga** [comment]
If our immediate and ongoing projects will not be deployed individually, we could de-prioritize the addition of app-id tags for patients and household-related resources. 
This would give enough time for R&D on a solution that would be deterministic in applying these tags.

**Comment by pld** [comment]
Agree, let's deprioritize that, get confirmation before we begin work on it again, thanks

**Comment by dubdabasoduba** [comment]
@pld Do you think we should close this issue and open a new one about tagging resources with the app Ids?

**Comment by pld** [comment]
Yes
