### ISSUE TITLE
[P2P] - Sync bugs on latest release v.0.0.6

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1280]
**Describe the bug**
- [ ] P2P sync not functioning properly. The device gets stuck at scanning for the available devices. 
![IMG20220516112930](https://user-images.githubusercontent.com/58034047/168584664-dd9521c7-5cf1-4359-9fc3-ac649fa21754.jpg)
- ~~[ ] Sync taking 7 minutes to complete.~~

**Comment by dubdabasoduba** [comment]
https://user-images.githubusercontent.com/4817531/168792356-dc8e5efb-8f33-4a01-8d22-59cc30dd3da6.mp4

**Comment by dubdabasoduba** [comment]
@Rkareko @ekigamba Here are my initial thoughts on the issues. 

1. Can we close the connection when our app force closes? WifiDirect will create a group when pairing is done. Does the android OS allow us to delete this group if the process exits successfully or due to an error? 
    - I think this will help with the issue where both devices are waiting for fr data transfer instead of trying to establish a connection first. 
    - We need to check the force close to gracefully handle fatal errors. We could redirect to the main P2P page in case the process has a fatal error.

**Comment by ekigamba** [comment]
@dubdabasoduba I agree.We'll need to replicate this to fix the specific issue.

 We are going to handle some of these issues here https://github.com/opensrp/p2p/issues/30 as part of Phase II. We handled some of these issues below :disappointed: 
- https://github.com/opensrp/p2p/pull/17
- https://github.com/opensrp/p2p/pull/19

**Comment by AnnieMungai** [comment]
@ekigamba its server >> device sync.
