### ISSUE TITLE
[eCBIS] Complete authoring questionnaires that support various CBIS schedules

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1281]
[CBIS schedules](https://docs.google.com/spreadsheets/d/1zi1ELaSCebXfNjMsu9ODAxKeAODy_8LLpPuVqqysa4E/edit#gid=1757872948)
- Create eCBIS questionnaires that are aligned with the CBIS monthly visits:
- [x] Routine HH visit - All module 1 forms
- [x] Update ANC visit - ANC registration and follow-up
- [x] Update child visit - child reg and follow-up
- [x] Disease registration and follow-up (HIV, TB, mental health, CM-NTD)
- Create eCBIS questionnaires that are aligned with other CBIS visits:
- [x] Sick child visit - Sick child reg + follow-up
- [x] PNC follow-up - Pregnancy outcome + PNC follow-up
- [x] FP follow-up - FP reg + follow-up 
- [x] Counter referrals

**Comment by pld** [comment]
cool @AnnieMungai do you know the timeline for this? should it go in one of the upcoming milestones? (they have dates)

**Comment by dubdabasoduba** [comment]
@AnnieMungai @pld the plan to achieve this is as follows. 

1. Add the forms that register patients to the different programs e.g. Marking patients as ANC, Mental Health e.t.c
2. Add the scheduling pieces for this through the [$lite functionality](https://github.com/opensrp/fhircore/labels/Scheduling%20%26%20Tasking%20%28%24lite%29). 

@AnnieMungai The following content is a priority for now. 
- All the forms used to register the patients to the different programs. 

**Next action points**
- Complete all the PlanDefinitions for the schedules in the app. 
- Complete all the forms to be filled up when the practitioner is performing any tasking generated for the scheduling pieces.

**Comment by f-odhiambo** [comment]
Any update on this task? CC @AnnieMungai @dubdabasoduba

**Comment by AnnieMungai** [comment]
@dubdabasoduba  @f-odhiambo I would say all the eCBIS forms are uploaded.
