### ISSUE TITLE
[Documentation] - Create Documentation of Single APK Approach Configuration

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1284]
Add documentation that will allow us to easily understand
1. The structure of SAA app configs 
2. How the config is interpreted and used in-app 
3. How to add production and development/local configs
4. How to use local configurations in development mode. All you have to do is append the /debug suffix to an appId that is available in the assets directory. E.g. usage: quest/debug, anc/debug

Acceptance Criteria/Output

1. Create a markdown document that can be saved in the docs for FHIR Core

**Comment by FikriMilano** [comment]
Documentation layout

- [ ] Single APK Approach diagram and description
- [ ] Composition config description and structure
- [ ] Binary config description and common structure
- [ ] Each Binary config structures for `classifications`
        - application
        - login
        - app_feature
        - pin
        - data_filters
        - forms
        - patient_register
        - sync
- [ ] How to create a new full set of configs
- [ ] How to add configs to server
- [ ] How to add configs to local and use them with `/debug` suffix

**Comment by pld** [comment]
@FikriMilano great to hear progress here, where are you putting these docs?

**Comment by FikriMilano** [comment]
@pld @f-odhiambo @dubdabasoduba 

The WIP docs
https://github.com/opensrp/fhircore/blob/documenting-configurable-app/docs/configuration.md

**Comment by pld** [comment]
@dubdabasoduba what do you think about @roywanyaga adding regsiter and profile config docs to this based on the implementation plan we have?

**Comment by FikriMilano** [comment]
@pld are those newly introduced configs?

**Comment by pld** [comment]
Yea, still in scoping and they don't have code written for them yet, we're thinking writing the docs first as part of the scoping before/as we write the code will make the implementation clearer

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba what do you think about @roywanyaga adding regsiter and profile config docs to this based on the implementation plan we have?

I think this would be a nice addition. Maybe we can create an issue to track their addition once the implementation plan is ironed out.

**Comment by FikriMilano** [comment]
@ellykits @f-odhiambo @dubdabasoduba 
I have some concerns about old config attributes we no longer use, those attributes can't integrate well with Single APK Approach.
Most of the attributes are from patient_register config.
I'm thinking of deprecating them. 

For now I won't include those old attributes in the documentation, to avoid inconsistency.

**Comment by ellykits** [comment]
I am okay with this.
