### ISSUE TITLE
[Quest] - Trailing space bug after submitting appID

### ISSUE THREAD

**Issue by charlene-570** [opensrp/fhircore#1287]
@AnnieMungai 

*Description*
Once the user enters Application ID with space after ecbis-saa the "Application ecbis-saa not found" error is displayed

**Steps To Reproduce**
1. Open the App
2. Enter Application ID as ecbiss-saa with space after saa
3. Click on Login

**Expected behavior**
User should be redirected to the Login page 

**Smartphone (please complete the following information):**
 -Android version: 10
-Build number: eCBIS v.0.0.6

See screencast attached

https://user-images.githubusercontent.com/85434942/169021284-82f68dbd-b12d-4acc-9e52-267f4426929a.mp4

**Comment by FikriMilano** [comment]
@f-odhiambo 
This bug is caused by trailing space at the end of "ecbis-saa " though it works for "ecbis-saa"

Adding a function to remove trailing space should be able to fix this.

**Comment by AnnieMungai** [comment]
v.0.0.7
Looks good!
