### ISSUE TITLE
[Quest] Create a scheduling workflow config.  

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1288]
**Description of feature**
- $Lite currently uses the StructureMap to create the CarePlan and Task for different Visits
- We run the StructureMaps against the PlanDefinition. We would like to write a scheduling workflow config that tells the app which PlanDefinition to use for the different visit schedule evaluations. 

**Describe the enhancement**
- [ ] Write a `scheduling workflow config` to hold the PlanDefinition references. This should contain the following information. 
    - [ ] The IDs for each PlanDefinition to be used on all schedule generation points of the app.
    - [ ] The correct reference of trigger conditions for the PlanDefinition linked above is to be used on code.

**Acceptance criteria**
- [ ] Get a config that can be used to define the scheduling and tasking points for the app. 

**Depends on**
- [ ] https://github.com/opensrp/fhircore/issues/1285

**Comment by pld** [comment]
What are the "schedule generation points" and what are the "trigger points"?

**Comment by dubdabasoduba** [comment]
> * scheduling workflow config

@pld I think I just need to find better wording. 

- "schedule generation points" - I would say this is the point in code where we identify that it's time to use the Plandefition defined on the config for extracting the CarePlan and Task
- "trigger conditions/points" - These are the conditions described for each activity in the PlanDefinition to be executed.

**Comment by pld** [comment]
Cool the wording's not bad, we need to work through the scenarios, let's get even more explicit, I'm trying to come up with an exhaustive list.

For "schedule generation points" is this the same as the points at which we call $lite? Since that is what will execute the PlanDefinition to extract the CarePlan and Tasks. I'll list the points I can think of below, are there others?
- completing a patient registration Questionnaire, checking that the patient matches some criteria (or are those criteria defined in the PlanDefinition?), assigning the PlanDefinition
- editing/updating the Patient data

For the "trigger conditions/points" are these wholly contained within the PlanDefinition? That is to say, is writing the PlanDefinition all you have to do to?

**Comment by dubdabasoduba** [comment]
> For "schedule generation points" is this the same as the points at which we call $lite? Since that is what will execute the PlanDefinition to extract the CarePlan and Tasks. I'll list the points I can think of below, are there others?
> 
> * completing a patient registration Questionnaire, checking that the patient matches some criteria (or are those criteria defined in the PlanDefinition?), assigning the PlanDefinition
> * editing/updating the Patient data

Yes, agreed. 
PlanDefitions have a target patient or group. From code, we can just check if the patient satisfies that. E.g [The Child Routine PlanDefinition](https://github.com/opensrp/fhir-resources/blob/main/ecbis/plan_definition/child_routine_visit.json) only target Patients < 5yrs old. We need a way to call $lite and provide the correct PlanDefition. 

> For the "trigger conditions/points" are these wholly contained within the PlanDefinition? That is to say, is writing the PlanDefinition all you have to do?

NB: - A PlanDefinition can have multiple actions. Some actions will have the **_"trigger conditions/points"_** being the same as the **_"schedule generation points"_**. 

Each action will have its own **_"trigger conditions/points"_** even if the target resources is the same. 

For FHIR Core $lite we need to figure out how to evaluate these "trigger conditions/points". They are expressions. These can be CQL or FHIRPath. The action extraction on happens of the expression here is `true` e.g https://github.com/opensrp/fhir-resources/blob/fe9e640e0d1123eba99b5179f0656a9b86304230/ecbis/plan_definition/child_routine_visit.json#L67

**Comment by maimoonak** [comment]
resolved in #1305 .

@pld does it make sense to associate PlanDefinition with Questionnaire Config as in PR. https://github.com/opensrp/fhircore/pull/1305/files#diff-884c321990eff25ab3a6d01bf3a3e80661c116ab74736f663d2901b00fa35f3fR306

**Comment by pld** [comment]
I'm not sure, does this mean that a PlanDef has to be associated with the submission of a Questionnaire? That's definitely a common use case but we'll have cases (in the future, do we have them for eCBIS, MWCore or AY @dubdabasoduba ?) where we'll want a button click or other conditions to trigger a plan def

**Comment by maimoonak** [comment]
Rightnow in QuestionnaireConfig we have PlanDefinitions mapped. The CarePlan generator is generic and can be called from anywhere with PlanId, the subject, and the data.
We can identify a different usecase and can implement that as well to test how feasible current code is for diverse usecases

**Comment by pld** [comment]
OK that sounds good for now

CC @jingtang10 and @vitorpamplona, related to the triggering plandefs conversation we touched on today
