### ISSUE TITLE
[Quest] Execute PlanDefinition extraction via StructureMap(s) to generate CarePlans & Tasks for each visit

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1289]
**Description of feature**
- $Lite currently uses the StructureMap to create the CarePlan and Task for different Visits
- We would like to execute the extraction using the Plandefition and Patient/Group as the parameters. This will depend on the [scheduling workflow config](https://github.com/opensrp/fhircore/issues/1288) and the type of Patient/Group added

**Describe the enhancement**
- [ ] Execute extraction based on the schedule generation points referenced on the [scheduling workflow config](https://github.com/opensrp/fhircore/issues/1288). 
- [ ] The full extraction should also evaluate the condition triggers defined in the PlanDefinition action. 

**Acceptance criteria**
- [ ] Trggier extractions based on the correct PlanDefinition and Patient/Group resources
- [ ] The full extraction should take into account the condition triggers defined on the PlanDefinition.  

**Depends on**
- [x] https://github.com/opensrp/fhircore/issues/1288

**Comment by pld** [comment]
Does this still use the StructureMap to conduct the extraction? This is about when that is conducted?

**Comment by dubdabasoduba** [comment]
> Does this still use the StructureMap to conduct the extraction? This is about when that is conducted?

Yes, the StructureMap still conducts the extraction. Yes, this is about the when the extraction is triggered

**Comment by maimoonak** [comment]
resolved in #1305
