### ISSUE TITLE
[Quest/Afya Yangu] -  Family Register

### ISSUE THREAD

**Issue by Gental-Giant** [opensrp/fhircore#1292]
**Describe the Issue**
As a Community Health Worker (CHW) I need to register households and add household members while at the community conducting visits. Household and household members registrations are made once and they are then referenced while providing the different services in the community

**Describe the solution you'd like**
- [x] Register a family/household
- [ ] Register a family member

**Acceptance criteria**

- [ ] Each of the listed households should provide a summary with the family name, the village where the family is located
- [ ] I would like to view all my registered households, under a common section “All Families”.
- [ ] I would also like to have an option to add a new household whenever I need to. Once a new household is added, it should immediately be available under the “All Families” listing
- [ ] I would like to have an option for searching for the families/households by their name or system ID
- [ ] I should have an option to initiate a call to the household member marked as the head of the household.

**Questionnaires**

- [Household](https://fhir.labs.smartregister.org/fhir/Questionnaire/128804) - Updated
- [Family Member Registration](https://fhir.labs.smartregister.org/fhir/Questionnaire/128806) - Updated

**Comment by RaaziaTarique** [comment]
The following fields are left that needs to be mapped from family/household registration questionnaire. I am unable to find fields in the group resource that can be used.

Village: string
Landmark/ description of house location: string
Nearest health facility: string
CC: @f-odhiambo @shoaibmushtaq25 @maimoonak

**Comment by shoaibmushtaq25** [comment]
Here is the updated [structure map] of family-member-registration questionnaire for afyayangu (https://github.com/opensrp/fhircore/blob/1e084e78a7da096b9c3b7125518513395753c8bb/android/quest/src/test/resources/structure-map-questionnaires/afyayangu/familymemberregistration/structure-map.txt) which is extracting correct date of birth based on given age or dob. 
The code changes are available in [structureMap branch here](https://github.com/opensrp/fhircore/tree/structureMap).

@RaaziaTarique will be uploading the [latest questionnaire](https://github.com/opensrp/fhircore/blob/1e084e78a7da096b9c3b7125518513395753c8bb/android/quest/src/test/resources/structure-map-questionnaires/afyayangu/familymemberregistration/questionnaire.json) on fhir-labs server to reflect the latest form in the app.
cc: @RaaziaTarique @f-odhiambo

**Comment by ageryck** [comment]
Thanks @RaaziaTarique I will take a review and reach out in case of anything

**Comment by dubdabasoduba** [comment]
> I have uploaded the questionnaire on fhir-labs server. Structure-Map for family and family-member registration are present in this branch https://github.com/opensrp/fhircore/tree/structureMap. CC: @f-odhiambo @shoaibmushtaq25

@RaaziaTarique & @shoaibmushtaq25  Please upload the StructureMaps here https://github.com/opensrp/fhir-resources

**Comment by RaaziaTarique** [comment]
> > I have uploaded the questionnaire on fhir-labs server. Structure-Map for family and family-member registration are present in this branch https://github.com/opensrp/fhircore/tree/structureMap. CC: @f-odhiambo @shoaibmushtaq25
> 
> @RaaziaTarique & @shoaibmushtaq25 Please upload the StructureMaps here https://github.com/opensrp/fhir-resources

@dubdabasoduba  I have uploaded questionnaireResponses and structureMaps to this repo CC: @f-odhiambo @shoaibmushtaq25

**Comment by RaaziaTarique** [comment]
@dubdabasoduba we have updated the questionnaires and form configurations as well, should I update them too in this repo?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba we have updated the questionnaires and form configurations as well, should I update them too in this repo? CC: @f-odhiambo @shoaibmushtaq25

Yes, please. thanks.

**Comment by RaaziaTarique** [comment]
> > @dubdabasoduba we have updated the questionnaires and form configurations as well, should I update them too in this repo? CC: @f-odhiambo @shoaibmushtaq25
> 
> Yes, please. thanks.

Done.

**Comment by Gental-Giant** [comment]
> The following fields are left that needs to be mapped from family/household registration questionnaire. I am unable to find fields in the group resource that can be used.
> 
> * `Village: string`
> * `Landmark/ description of house location: string`
> * `Nearest health facility: string`
> 
> CC: @f-odhiambo @shoaibmushtaq25 @maimoonak

@f-odhiambo @ageryck Did we manage to map the above fields as well?

**Comment by f-odhiambo** [comment]
> > The following fields are left that needs to be mapped from family/household registration questionnaire. I am unable to find fields in the group resource that can be used.
> > 
> > * `Village: string`
> > * `Landmark/ description of house location: string`
> > * `Nearest health facility: string`
> > 
> > CC: @f-odhiambo @shoaibmushtaq25 @maimoonak
> 
> @f-odhiambo @ageryck Did we manage to map the above fields as well?



We did not manage to map these fields that require extensions to the patient resource.
The data captured in these fields will be stored in the QuestionnaireRespnse and not extracted to the Patient resource . Further discussion can be held ok this to deliberate/clarify the use case

**Comment by Gental-Giant** [comment]
With the current implementation can we use the fields in other parts of the app such as displaying the village information on the family member profile?

**Comment by f-odhiambo** [comment]
> With the current implementation can we use the fields in other parts of the app such as displaying the village information on the family member profile?

One possibility would be to save this to the [Location](https://hl7.org/fhir/location.html) resource but the location resource does not have any reference to the [Patient](https://www.hl7.org/fhir/patient.html) resource. So will need to figure out how to connect these resources  

**For Location** 
This resource is referenced by [UsageContext](https://hl7.org/fhir/metadatatypes.html#UsageContext), [Account](https://hl7.org/fhir/account.html#Account), [ActivityDefinition](https://hl7.org/fhir/activitydefinition.html#ActivityDefinition), [AdverseEvent](https://hl7.org/fhir/adverseevent.html#AdverseEvent), [Appointment](https://hl7.org/fhir/appointment.html#Appointment), [AppointmentResponse](https://hl7.org/fhir/appointmentresponse.html#AppointmentResponse), [AuditEvent](https://hl7.org/fhir/auditevent.html#AuditEvent), [CarePlan](https://hl7.org/fhir/careplan.html#CarePlan), [Claim](https://hl7.org/fhir/claim.html#Claim), [ClaimResponse](https://hl7.org/fhir/claimresponse.html#ClaimResponse), [Contract](https://hl7.org/fhir/contract.html#Contract), [CoverageEligibilityRequest](https://hl7.org/fhir/coverageeligibilityrequest.html#CoverageEligibilityRequest), [Device](https://hl7.org/fhir/device.html#Device), [DeviceRequest](https://hl7.org/fhir/devicerequest.html#DeviceRequest), [DiagnosticReport](https://hl7.org/fhir/diagnosticreport.html#DiagnosticReport), [Encounter](https://hl7.org/fhir/encounter.html#Encounter), [ExplanationOfBenefit](https://hl7.org/fhir/explanationofbenefit.html#ExplanationOfBenefit), [Flag](https://hl7.org/fhir/flag.html#Flag), [HealthcareService](https://hl7.org/fhir/healthcareservice.html#HealthcareService), [ImagingStudy](https://hl7.org/fhir/imagingstudy.html#ImagingStudy), [Immunization](https://hl7.org/fhir/immunization.html#Immunization), [InsurancePlan](https://hl7.org/fhir/insuranceplan.html#InsurancePlan), [List](https://hl7.org/fhir/list.html#List), itself, [MeasureReport](https://hl7.org/fhir/measurereport.html#MeasureReport), [Media](https://hl7.org/fhir/media.html#Media), [MedicationDispense](https://hl7.org/fhir/medicationdispense.html#MedicationDispense), [Observation](https://hl7.org/fhir/observation.html#Observation), [OrganizationAffiliation](https://hl7.org/fhir/organizationaffiliation.html#OrganizationAffiliation), [PractitionerRole](https://hl7.org/fhir/practitionerrole.html#PractitionerRole), [Procedure](https://hl7.org/fhir/procedure.html#Procedure), [Provenance](https://hl7.org/fhir/provenance.html#Provenance), [ResearchStudy](https://hl7.org/fhir/researchstudy.html#ResearchStudy), [Schedule](https://hl7.org/fhir/schedule.html#Schedule), [ServiceRequest](https://hl7.org/fhir/servicerequest.html#ServiceRequest), [Specimen](https://hl7.org/fhir/specimen.html#Specimen), [SupplyDelivery](https://hl7.org/fhir/supplydelivery.html#SupplyDelivery), [SupplyRequest](https://hl7.org/fhir/supplyrequest.html#SupplyRequest) and [Task](https://hl7.org/fhir/task.html#Task)

**Comment by ageryck** [comment]
> > > The following fields are left that needs to be mapped from family/household registration questionnaire. I am unable to find fields in the group resource that can be used.
> > > 
> > > * `Village: string`
> > > * `Landmark/ description of house location: string`
> > > * `Nearest health facility: string`
> > > 
> > > CC: @f-odhiambo @shoaibmushtaq25 @maimoonak
> > 
> > 
> > @f-odhiambo @ageryck Did we manage to map the above fields as well?
> 
> We did not manage to map these fields that require extensions to the patient resource. The data captured in these fields will be stored in the QuestionnaireRespnse and not extracted to the Patient resource . Further discussion can be held ok this to deliberate/clarify the use case

@f-odhiambo did you mean the Group resource, the items are from the HH registration form. Can the resulting Locations resource share identifiable [managingOrganization](https://hl7.org/fhir/location-definitions.html#Location.managingOrganization) with its corresponding Group Resource?

**Comment by f-odhiambo** [comment]
> maybe you could also store these as characteristics in the Group resource

Let me see if we can get the codable concept codes to use for the items and also give feedback on the [characteristics](http://hl7.org/fhir/group-definitions.html#Group.characteristic) portion of the Group resource can be used for this 

CC @ageryck @pld

**Comment by ageryck** [comment]
@f-odhiambo I have looked around but did not find appropriate codable concepts for `village`, `landmark`, and `nearest facility`. What would be the possible downside of creating them as a free text-only representation of the concept without any coding? This can possibly work for us but may not be easily interpretable by other systems should there be a need for integration.

**Comment by pld** [comment]
As discussed mentioned on today's sprint call, let's use our own concepts for this round of building and note them in a new location (I suggest a file somewhere in https://github.com/opensrp/fhir-resources/, but am open to other ideas and don't have a strong opinion right now) for all concepts that we add (so we can keep them aligned)

**Comment by ageryck** [comment]
proposed storing of the additional variables on the `Group.characteristic as below;
```
[
  {
    "coding": {
      "code": {
        "system": "http://ona.io/codes",
        "code": "hh_village",
        "display": "Household Village"
      }
    },
    "valueCodeableConcept": {
      "text": "villagename"
    },
    "exclude": false
  },
  {
    "coding": {
      "code": {
        "system": "http://ona.io/codes",
        "code": "hh_landmark",
        "display": "Household Landmark"
      }
    },
    "valueCodeableConcept": {
      "text": "landmarkdesc"
    },
    "exclude": false
  }
]
```

**Comment by pld** [comment]
This looks good, except for the system value, what is normal for that? we need to use a URI that exists or something otherwise more descriptive

**Comment by ageryck** [comment]
attempt to map the above to characteristics proved difficult because no direct supported types that maps to characteristics [IMO - could be wrong]. Using extensions results as below (actual extraction results) though these are unsupported extensions as well.
```
"extension": [
					{
						"url": "Village",
						"valueCodeableConcept": {
							"coding": [
								{
									"system": "http://ona.io/",
									"code": "hh_village",
									"display": "Household Village"
								}
							],
							"text": "Kerio"
						}
					},
					{
						"url": "Landmark",
						"valueCodeableConcept": {
							"coding": [
								{
									"system": "http://ona.io/",
									"code": "hh_landmark",
									"display": "Household Landmark"
								}
							],
							"text": "Escapement "
						}
					},
					{
						"url": "Health Facility",
						"valueCodeableConcept": {
							"coding": [
								{
									"system": "http://ona.io/",
									"code": "hh_nearest_hf",
									"display": "Household Nearest Health Facility"
								}
							],
							"text": "Kerio Valley Hospital"
						}
					}
				]
```

**Comment by pld** [comment]
Cool, wait sorry what's wrong with using the characteristics defined in this comment? https://github.com/opensrp/fhircore/issues/1292#issuecomment-1148412913

I don't know what's normally used for the coding and system, do we have any examples of custom codings we can use?

**Comment by ageryck** [comment]
> Cool, wait sorry what's wrong with using the characteristics defined in this comment? [#1292 (comment)](https://github.com/opensrp/fhircore/issues/1292#issuecomment-1148412913)
> 
> I don't know what's normally used for the coding and system, do we have any examples of custom codings we can use?

@pld this would be a characteristic based group [resource](https://build.fhir.org/group-example.json.html), our coding can be anything that make sense for us. Current challenge is that both the `Group.characteristic.code` and `Group.characteristic.value[x]` support type `[CodeableConcept](https://build.fhir.org/datatypes.html#CodeableConcept)` however if I create a mapping of that type then it throws an error `class org.hl7.fhir.r4.model.CodeableConcept cannot be cast to class org.hl7.fhir.r4.model.Group$GroupCharacteristicComponent`

**Comment by ageryck** [comment]
Maybe I need to explore other transform options on the mapping [language](https://www.hl7.org/fhir/mapping-language.html)

**Comment by pld** [comment]
Can you share the WIP for this? Definitely get help from someone on the dev team, this should be doable.

For the system, I'm wondering what other groups do when they are making their own custom codings, can you find some examples of that?

**Comment by ageryck** [comment]
> @ageryck Where are you running these StructureMaps so that you can get the error?

Using this [guide](https://github.com/opensrp/fhircore/wiki/Authoring-Questionnaires---Registration-Questionnaires-with-StructureMaps-for-extraction#how-to-generate-the-structuremap-json-workaround) @ekigamba

**Comment by ekigamba** [comment]
This is going to need some quick code changes. Additionally, you'll need to create an instance of `class org.hl7.fhir.r4.model.Group$GroupCharacteristicComponent` and assign the appropriate values to the `code` or `value` property of this instance and assign this `org.hl7.fhir.r4.model.Group$GroupCharacteristicComponent` back to the `Group.characteristic` like in this line https://github.com/opensrp/fhircore/blob/main/android/eir/src/test/resources/structure-map-questionnaires/eir/immunization/structure-map.txt#L37

**Comment by ekigamba** [comment]
The PR is up https://github.com/opensrp/fhircore/pull/1349

You will use the model name `Group_Characteristic` to create a new instance

**Comment by ageryck** [comment]
Support mapping for `Group.characteristic` now works, sample extracted as below;
```
"characteristic": [
					{
						"code": {
							"coding": [
								{
									"system": "http://ona.io/codes",
									"code": "hh_village",
									"display": "Household Village"
								}
							],
							"text": "Kerio"
						},
						"exclude": false
					}
				]
```

**Comment by ageryck** [comment]
We will decide on the hyper link to include on this codes, for AY we are able to fully extract all form variables as per now. Other workflows to be tracked on separate issue. Closing this

**Comment by pld** [comment]
OK sounds good, @ageryck can you please open an issue in https://github.com/opensrp/fhir-resources/ about the codes

**Comment by ageryck** [comment]
> OK sounds good, @ageryck can you please open an issue in https://github.com/opensrp/fhir-resources/ about the codes

@pld lets [chat](https://github.com/opensrp/fhir-resources/discussions/81) about it and get ideas before from other team members first
