### ISSUE TITLE
[QA/Test] - Add tests on various Quest modules 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1299]
Add test for the following modules 

What's required : 
1. Test on Family Registration module for eCBIS 
2. Test on Syncing of StrucutureMaps, Questionnaire &  QuestionnaireResponse 

Acceptance Criteria 
1.  Unit testing for item 1
2. RnD Test  and a set of recommendations  for item no.2

**Comment by roywanyaga** [comment]
Tests recommendations updated on issue [#1279 ](https://github.com/opensrp/fhircore/issues/1279#issuecomment-1139553179)

Issue #1307 was created to address the recommendations.
