### ISSUE TITLE
[Quest/Malawi Core] - Failing to log in after being logged out for the first time

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1327]
**Describe the bug**
After logging in from a fresh install, I'm unable to log in again after I've voluntarily logged out or any other reason why I need to log in again (e.g. the app has crashed). The only way to log in is to clear the app data and log in.

**To Reproduce**
1. Clear app data
2. Enter username, enter password and log into the app
3. Log out
4. Repeat step 2
5. The login button is disabled as normal, but the spinning wheel widget just spins indefinitely

**Expected behavior**
I expect to be logged back into the app

**Screenshots**
N/A

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
When trying to log in again, the last log output is - I/LoginViewModel$responseBodyHandler: No error

**Comment by ellykits** [comment]
I've resolved this in a separate PR.

**Comment by ellykits** [comment]
I've cherry-picked the commit from the branch with the fix (it's PR is failing on CI) and created a new PR[#1347](https://github.com/opensrp/fhircore/pull/1347)
