### ISSUE TITLE
[COVAX demo app] Extract and assign Patient ID from Questionnaire field

### ISSUE THREAD

**Issue by vincent-karuri** [opensrp/fhircore#133]
See if we can specify the barcode id as the Patient ID when creating the Patient Resource. The barcode widget reads a barcode String that is then embedded into the QuestionnaireResponse. This String should be used as the logical ID for the Patient.

Mockups: https://www.figma.com/proto/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?page-id=1001%3A5305&node-id=1002%3A5506&viewport=699%2C624%2C0.25&scaling=min-zoom

**Comment by vincent-karuri** [comment]
@ekigamba please provide the feedback you had on the approach we should take here.

**Comment by ekigamba** [comment]
Add this to the barcode reader question as a property

```
"definition": "http://hl7.org/fhir/StructureDefinition/Patient#Patient.id"
```

**Comment by vincent-karuri** [comment]
cool @ekigamba , we'll we need to remove this line https://github.com/opensrp/fhircore/blob/b81ff08c56b1daf185ccbb1cd637dbc168dcbb3e/android/app/src/main/java/org/smartregister/fhircore/activity/QuestionnaireActivity.kt#L89?

**Comment by ekigamba** [comment]
Yes, we can fill in the `Patient.id` with a UUID if it doesn't have a value

**Comment by vincent-karuri** [comment]
@ekigamba doesn't seem to work. Getting: 

```
java.lang.NoSuchMethodException: setIdElement [class org.hl7.fhir.r4.model.StringType]
```

any ideas?

**Comment by vincent-karuri** [comment]
Found this method ` public Resource setIdElement(IdType value)` I guess it takes `IdType` not `StringType`?

**Comment by vincent-karuri** [comment]
Seems like the `0.0.5` version of the `datacapture` lib doesn't match what is on android-fhir master. The master version seems to be broken in the `ResourceMapper` extraction phase.

Getting:

```
java.lang.NoSuchMethodException: setGivenElement [class org.hl7.fhir.r4.model.StringType]
```
I'm unable to register a Patient with the master version of android-fhir (published locally).

**Comment by ekigamba** [comment]
Yea, that's correct.  `datacapture 0.0.5` is ahead of master. `datacapture` is the unofficial test artefact for the Resource Mapper extraction changes. `data-capture` is the official release of the library as seen (here)[https://github.com/google/android-fhir/blob/master/datacapture/build.gradle.kts#L12] . The official release are found [here](https://maven.google.com/web/index.html?#com.google.android.fhir:data-capture)

**Comment by vincent-karuri** [comment]
closed by https://github.com/opensrp/fhircore/pull/129
