### ISSUE TITLE
[Quest/Afya Yangu] - App Name & App Icon

### ISSUE THREAD

**Issue by ageryck** [opensrp/fhircore#1334]
- [ ] Create an app flavor for Afya Yangu with the name `afya yangu`
- [ ] Load app login icons attached here - for login page and startup icon. Design screens are [here](https://www.figma.com/file/1eFjPDM29Ky41J9Ycduq82/FHIR---Afya-Yangu?node-id=0%3A1), App configuration is labeled `"appLogoIconResourceFile": "ic_afyayangu",`
![afyayangu](https://user-images.githubusercontent.com/23252704/172119964-180ec239-4502-43a5-88ef-4bc57c330b7c.png)
![image](https://user-images.githubusercontent.com/23252704/172122776-2892df9f-f8d4-4e2f-864a-d8b58c8279fe.png)

**Comment by dubdabasoduba** [comment]
@ageryck the Figma link attached does not seem to work. However, here are the login screen designs currently supported. https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-Apps-~-Design-System?node-id=4310%3A48293

My assumption is the first image will be used in place of the logo and the second one in place of the app icon.

**Comment by ageryck** [comment]
> @ageryck the Figma link attached does not seem to work. However, here are the login screen designs currently supported. https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-Apps-~-Design-System?node-id=4310%3A48293
> 
> My assumption is the first image will be used in place of the logo and the second one in place of the app icon.

@dubdabasoduba  you are right [on your assumptions], the request is not super urgent only wanted to have them taken care of ahead of product release

**Comment by pld** [comment]
this feels like a good first issue, added label
