### ISSUE TITLE
[Quest] - Sync not updating the patient registration questionnaire

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1354]
**Describe the bug**
When I update the patient registration questionnaire on the server and I use the sync in the navigation drawer or the automated sync when I sign out and sign back in, no changes are reflected in the questionnaire when I open it once again.

**To Reproduce**
1. Update the patient registration questionnaire
2. Tap the sync option in the navigation drawer or sign out and sign back in
3. Wait for the sync to be completed
4. Once completed, open the patient registration questionnaire
5. The new changes won't be visible even though the sync has been completed

**Expected behavior**
I expect the new changes to have been synced and as a result, be visible to the user.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
When I clear the app data, the updated questionnaire is downloaded after the initial sync.

**Comment by dubdabasoduba** [comment]
@f-odhiambo This is affected by the following SDK issuehttps://github.com/google/android-fhir/issues/1420

**Comment by dubdabasoduba** [comment]
@KhumboLihonga Based on the bug above, all consecutive syncs after the initial sync are breaking. 

I would advise clearing the data and re-trying the initial sync. This should get your questionnaire loaded.

**Comment by KhumboLihonga** [comment]
@dubdabasoduba yes, clearing the data and re-trying the initial sync is working.

**Comment by f-odhiambo** [comment]
> @dubdabasoduba yes, clearing the data and re-trying the initial sync is working.

Closing this issue then @KhumboLihonga. Fel free to reopen if the issue persists CC @dubdabasoduba

**Comment by dubdabasoduba** [comment]
@f-odhiambo this depends #1420 SDK issue
