### ISSUE TITLE
[Quest/Malawi Core] - No pagination available on patient register

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1355]
**Describe the bug**
Our server has more than 10,000 patients in it and yet the patient register only shows the first 20 patients with the label 'Page 1 of 0'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Sign in to the app
2. View the patient register
3. Scroll to the bottom of the page
4. Notice the pagination label that says 'Page 1 of 0'

**Expected behaviour**
I expect it to say 'Page 1 of n' where n is the total number of pages.

**Screenshots**

<img src="https://user-images.githubusercontent.com/90775548/173590522-1ba4629b-8c80-44bd-8a1f-0b8d64a13bcc.jpg" width="200" height="400" />

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**

**Comment by f-odhiambo** [comment]
@KhumboLihonga I think the current page limit is about 12 records per page (will confirm), so yes  I would propose

1. Add pagination if the limit is passed else leave it as page 1 of 1 if records are not more than count. 

I hope that works, else add any more details herein CC @AbdulWahabMemon @LZRS
