### ISSUE TITLE
[Quest/Malawi Core] - App crashes when signing in using the main branch

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1357]
**Describe the bug**
When using the main branch (regardless of the server being used), after entering the app id and signing in, the app crashes.

**To Reproduce**
1. Build and run the main branch
2. Enter the app id
3. Enter the username and password and sign in
4. The app will crash

**Expected behavior**
I expect to be signed into the app

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
This is the error: kotlinx.serialization.SerializationException: org.smartregister.fhircore.engine.appfeature.model.HealthModule does not contain element with name 'HOME_TRACING'

**Comment by AbdulWahabMemon** [comment]
HealthModule for separating Home and Phone tracings are added later 1277-patient-profile branch, once that PR is merged in main it wont be crashing.
@Gental-Giant 
cc: @KhumboLihonga

**Comment by KhumboLihonga** [comment]
@Gental-Giant do we have an idea on when this will be merged?

**Comment by pld** [comment]
Can we build an APK from that branch, one that doesn't crash?

**Comment by Gental-Giant** [comment]
@KhumboLihonga Can you build from this branch? [1277_malawi-patient-profile](https://github.com/opensrp/fhircore/tree/1277_malawi-patient-profile)

**Comment by KhumboLihonga** [comment]
@Gental-Giant yes, I can build from that branch. Should we just keep using that branch until this is merged?

**Comment by pld** [comment]
@KhumboLihonga yes please
