### ISSUE TITLE
Run some PlanDefinitions against this PR for $apply tests

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#1358]
**Describe the issue to be researched**
This PR let's you execute $apply the same way it will work when implemented the the Android FHIR SDK, https://github.com/google/android-fhir/pull/1395

**Describe the goal of the research**
See how the outputs of running PlanDefs on this PR, or on it's resources in main after it's merged, differ from the outputs of $lite and discuss the differences w/Vitor so we can figure out what to do

**Comment by f-odhiambo** [comment]
Copying this here for reference https://github.com/google/android-fhir/issues/656#issuecomment-1158686610

CC @pld @maimoonak @dubdabasoduba

**Comment by f-odhiambo** [comment]
Marked as Done
