### ISSUE TITLE
[Quest] - Add Progress bar for Sync in Progress for Quest app on 1st time load/sync  

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1375]
**Description** 
On the initial launch, the current Quest app does not have a progress Dialog for showing sync progress, though it's being done in the background on initial sync. 
User may need some feedback on Sync in Progress thus wait for all resources to load on 1st launch before initiating any work flows 

**Acceptance Criteria** 
- [ ] 1. Initiate 1st-time sync and prompt user on sync 
- [ ] 2. Add progress bar 
- [ ] 3. Once done show a success alert 
- [ ] 4. In case of failure show an error alert and reinitiate sync

**Comment by f-odhiambo** [comment]
@ellykits You can add feedback on this based on the current PR refactor where this was noted

**Comment by ellykits** [comment]
Yes we do.

**Comment by pld** [comment]
Cool thanks let's focus on config can come back to this issue
