### ISSUE TITLE
[Quest] - New Reporting Interface for initiating In-App reports for eCBIS Indicators based on FHIR Measures &  MeasureReporting

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1378]
**Description :** 
The current In-App reports may not conform to the nature of in-app reporting desired by the project teams and previous OpenSRP implementations. 

**Proposal :** 
Need to obscure selection of 
1. Date - Start date and End Date 
2. Selection of Subjects 
which are present in the mADX approach for measure reporting here  - mADX - https://www.figma.com/file/bH9zok2Yvu6xQ7vGxY8jiC/FHIR-ANC?node-id=1907%3A59174

Reporting page should have 
1. Type of Reports
2. Months  - Jan through Dec
4. Then just select a month and then invoke the report 

**Designs :**
Some close designs to fulfil this requirement  - https://www.figma.com/file/Gan8PFBKHYjRd6zSPvfhnQ/WCARO---Design-edit?node-id=614%3A854

**Comment by f-odhiambo** [comment]
@HenryRae @rowo we can plan to have an intro and a check in on this item CC @AnnieMungai

**Comment by pld** [comment]
I'd like to join that

**Comment by f-odhiambo** [comment]
Marked as done
