### ISSUE TITLE
How to implement Configurability via CQL 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#14]

**Comment by f-odhiambo** [comment]
Related and being tracked in issue #15

**Comment by f-odhiambo** [comment]
Related to #15

**Comment by vincent-karuri** [comment]
@f-odhiambo is there more information on this issue?

**Comment by f-odhiambo** [comment]
I think we can track this on #81

**Comment by pld** [comment]
these look like 2 separate issues?
