### ISSUE TITLE
[Navigation Drawer] Update the dynamic menus to use the configuration form the config_navigation_drawer.json

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1400]
**Description of feature**
- After updating the [navigation drawer UI](https://github.com/opensrp/fhircore/issues/1366), we would like to make sure the menus on the Navigation drawer adhere to the rules defined on the `config_navigation_drawer.json`

**Describe the enhancement**
- [ ] Update the following menu functionality to adhere to the rules defined on the `clientRegister` and `otherClients.bottomSheetRegister` attributes on the `config_navigation_drawer.json`
     - [ ] Each object in the above-mentioned arrays represents a register menu to be displayed on the navigation menu or the bottom sheet. 
         - [ ] `id` --> This should be unique. It represents the id of each register menu object.
         - [ ] `display` --> This represents the name to be shown to the user. i.e this is the register menu name
         - [ ] `icon` --> This should represent the icon to be shown on the register menu. This should be the asset name on the `res` folder in the flavours. 
         - [ ] `showCount` --> This tells the menu whether to show the count against each menu item. If `true` then the count should be shown. 
         - [ ] `actions` --> Describes different actions that can happen `onClick`, `onClose` or `count` 
             - [ ] `type` --> This denotes the type of action to be peformed. 
                 - `onClick` --> [defines what happens when the menu is clicked](https://github.com/opensrp/fhir-resources/blob/ebd4cfe6f873288fc4dc4826c395fa8d1fcb31a9/sample_project/app_configurations/config_navigation_drawer.json#L47-L51). This is mostly launching a register. 
                     - `workflow` --> This is pre-defined on the application. It tells the app the functionality to trigger
                     - `id` --> This is the Id of the register to load from the register config. e.g the [All Household register](https://github.com/opensrp/fhir-resources/blob/c0267a07786a4720bf9439cd23019289d8aba879/sample_project/app_configurations/register_configurations/all_household_register_configuration.json#L3)
                 - `count` --> This defines menu count formulas. If this is not defined and the `showCount` is set to true then we automatically disable the count i.e `showCount` becomes `false`
                     - `rules` --> defines the use rules engine instructions to calculate the count. 

[**Navigation Drawer Configuration Discussion**](https://github.com/opensrp/fhircore/discussions/1304)

**Depends On**
- [ ] https://github.com/opensrp/fhircore/issues/1371

**Comment by f-odhiambo** [comment]
Marked as DONE
