### ISSUE TITLE
[Register] Update the registers UI

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1402]
**Description of feature**
- We have new designs from the ona Design team. Here are the designs mock up https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-Apps-~-Design-System?node-id=10351%3A80950

**Describe the enhancement**
- [x] Update the registers look and feel to look like the one on the mock-up above. 

[**Navigation Drawer Configuration Discussion**](https://github.com/opensrp/fhircore/discussions/1340)

**Comment by f-odhiambo** [comment]
@dubdabasoduba can I close this issue? I see its marked as DONE in the Quest board

**Comment by dubdabasoduba** [comment]
@f-odhiambo Yes, this is done. We can fix any bugs that come up on other issues.
