### ISSUE TITLE
[Quest/Malawi Core] Search results prompt is in the wrong position

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1411]
**Describe the bug**
When a patient is being searched, the number of search results appears in the top left corner of the screen.

**To Reproduce**
1. Go to the patients register
2. Type "Chi" in the search bar
3. You'll see a prompt that says "6 RESULT(S)" in grey in the top left corner

**Expected behavior**
The number of search results should appear centered below the search bar and above the list of patients that have been found.

**Screenshots**
![Screenshot_20220705-131212_Quest](https://user-images.githubusercontent.com/90775548/177316731-33d15a81-3556-402e-bf2c-b7793b6572cb.png)

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
N/A

**Comment by f-odhiambo** [comment]
This is a bug , got the desing docs , I think we can fix this FIgma designs https://www.figma.com/file/QZ4cdpgBNy86XTOUnrnLap/COVID19-FHIR-Future-Design-System?node-id=1063%3A14329

**Comment by KhumboLihonga** [comment]
This has been resolved
