### ISSUE TITLE
Last sync date feaure

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#142]
Add last sync date on initial sync or prompted sync on the navigation drawer. The date should update once the sync is successfully complete. 

**For discussion, should the status show either Error/Bad sync increase of bad connectivity, dirty read or merge/duplicates?

**Comment by f-odhiambo** [comment]
<img width="381" alt="Screen Shot 2021-05-25 at 10 39 24 AM" src="https://user-images.githubusercontent.com/4540684/119459624-87e19380-bd46-11eb-87f6-d93d89d1375c.png">

**Comment by f-odhiambo** [comment]
This is also tagged to In-app messaging/broadcast framework and approach #175

**Comment by pld** [comment]
is data exists and this issue is about exposing it? if so cool.

If not, this sounds like data to be exposed by the SDK API

**Comment by f-odhiambo** [comment]
What's the status of this issue? @syedowaisali90 @maimoonak

**Comment by syedowaisali90** [comment]
@f-odhiambo I have didn't work on this @maimoonak can update more

**Comment by maimoonak** [comment]
This one, i.e. #142, #175 , [#554](https://github.com/google/android-fhir/issues/554) all are related. The details on the progress can be tracked on [#554](https://github.com/google/android-fhir/issues/554) and the PR [#648](https://github.com/google/android-fhir/pull/648). There were back and forth discussions with Jing and now need a review and feedback on this PR

**Comment by f-odhiambo** [comment]
Update: This issue was blocked, but now we can work on it as soon as we get the latest SDK release with 

1. Provide a StateFlow for sync status [#554](https://github.com/google/android-fhir/issues/554)
2. Flow API for one-time and periodic tasks [#648](https://github.com/google/android-fhir/pull/648)

**Comment by mwkhan1983** [comment]
Update: still blocked by SDK release

**Comment by pld** [comment]
can't we cut our own release of the sdk to unblock this?

**Comment by maimoonak** [comment]
Martin has released it last week (i.e. own preview snapshot). Currently I am on it
