### ISSUE TITLE
ParentBirth Date must not be null error

### ISSUE THREAD

**Issue by charlene-570** [opensrp/fhircore#1422]
**Describe the bug**

**To Reproduce**
1. Login 
2. Verify sync i.e wait for App o syn to server
3. Click on ADD Family button
4. Click on Save
5. Add member to Family i.e child
6. Select date of birth as Unknown
7. Select Gender as Male
8. Click Save

**Smartphone (please complete the following information):**
 - Device:-Nokia/Oppo ]
 - Android version: version 10
 - Build number: kes-H6124ABC-QGo-GL-2204413v517
 - App Version 0.0.9 -Though on the app it says 0.0.8

**Actual behavior **
1.App closes down
2.Once you relaunch the App this error is shown

see screen cast attached

https://user-images.githubusercontent.com/85434942/177978517-244db00b-56c7-4320-ab96-7328235d0894.mp4

**Comment by NaveenZehra11** [comment]
@f-odhiambo this is fixed now

FYI @charlene-570

**Comment by f-odhiambo** [comment]
Issue sorted in latest release
