### ISSUE TITLE
Fix flakey ConfigResources tests

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#1423]
**Describe the Issue**

The following 2 tests are flaky and need to be fixed or removed,

https://github.com/opensrp/fhircore/blob/main/android/engine/src/test/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistryTest.kt#L214

https://github.com/opensrp/fhircore/blob/main/android/engine/src/test/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistryTest.kt#L230

**Comment by f-odhiambo** [comment]
Closing this issue. Can be reopened if issue is recurrent
