### ISSUE TITLE
[Quest/eCBIS] - Unique Household ID check while adding new Household/Family

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1426]
**Name of feature to enhance**

1. Add a Unique Household ID check while adding a new Household/Family

**Description of feature**

1. Add a check to validate that the given ID has not been used for another household 

**Describe the enhancement**

1. Users should not reuse previously added ID while enrolling a household in the app

**Comment by dubdabasoduba** [comment]
@pld @f-odhiambo could we scope this issue abit. This is related to having unique IDs all across the app and the server. i.e the apps should generate the unique IDs but they should be unique even when synced to the server

**Comment by f-odhiambo** [comment]
@dubdabasoduba Also pointing out that this should be the Identifier ID and not the Resource ID

**Comment by pld** [comment]
By ID are you talking about the generated UUID or a user entered ID number?

**Comment by dubdabasoduba** [comment]
Yes, the human readable ID right? This is the one with a field provided on the form for data entry

**Comment by pld** [comment]
Do households have existing IDs? Or is the user expected to create their own unique ID when they enter the household data? Or is the system supposed to assign a human readable but unique ID?

**Comment by AnnieMungai** [comment]
@pld @f-odhiambo @dubdabasoduba the user assigns the HH IDs. During Household registration, each household based on the location on the map (village map), the CHW assigns the numbers. No 2 households would have the same number. However, these numbers are only unique to the Households that the CHW is assigned to. 

The system does not need to assign these IDs. They are assigned by the CHW. However, these numbers can be used by the CHW to search (local search) for a particular household in their village/jurisdiction.

**Comment by f-odhiambo** [comment]
Closing this issue based on above comments
