### ISSUE TITLE
[Quest/eCBIS] - App crashes on select Family member profile (Individual Detail)

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1434]
**Describe the bug**
App crashes on select Family member profile (Individual Detail)

**To Reproduce**
1. Go to a household 
2. Select a family memebr 
3. Select menu item to view Individual Detail
4. See an error

**Expected behavior**
1. Go to a household 
2. Select a family member 
3. Select the menu item to view Individual Detail
4. View the family member's profile

**Screenshots**
<img src="https://user-images.githubusercontent.com/90256461/177769015-04677c10-ca19-4712-8f5a-a178b6b579ea.png" width="200" height="400" />

**Comment by dubdabasoduba** [comment]
@AnnieMungai @f-odhiambo Is this still an issue? If not please close this issue

**Comment by AnnieMungai** [comment]
Not an issue anymore.
