### ISSUE TITLE
[Quest/eCBIS] - On Edit,  Household details Village Town is empty

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1436]
**Describe the bug**
There is missing data for a family village or town in family details profile view, wrong labels on edit family details 

**Acceptance criteria**

- [x] 1. Click on a family from the family register 
- [x] 2. Click on the menu items 
- [x] 3. Select on the menu - Family details 
- [x] 4. The title of the page should be Edit Family details 
- [x] 5. All fields should be populated i.e Famil name, Household ID, and Village or Town
- [x] 6. Change the button text from Add family to Edit family 
- [x] 7. On save update family details 

**Screenshots**

<img src="https://user-images.githubusercontent.com/4540684/179257914-7530142d-9c40-4b3e-bc32-705853ec2ae1.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/4540684/179257898-018bb7d7-b6e3-49a7-bc15-5b87f6e13496.png" width="200" height="400" />

**Comment by FikriMilano** [comment]
<img src="https://user-images.githubusercontent.com/62053304/179890122-3b01a151-b6ce-4d51-883d-b48b0b907988.png" width="300" />

@f-odhiambo 
- [x] Change title to "Edit Family details"
- [x] Change button text to "EDIT FAMILY"
- [ ] Fix "Village or Town" pre-filling issue (stuck, will reach out to someone)
  - ~Might be the QuestionnaireItem expression extension~
  - Might be the StructureMap
  - Other reasons

**Comment by FikriMilano** [comment]
Yeah, most likely it's the StructureMap.
This guy is missing a Patient extraction.
https://fhir.labs.smartregister.org/fhir/StructureMap/5667cfbd-13c4-4111-b952-7cee58bdb9d5
https://github.com/opensrp/fhir-resources/blob/main/ecbis/structure_map/text/family_registration.txt

**Comment by dubdabasoduba** [comment]
@FikriMilano I don't thin the Village or town is extracted

THis might be the reason it's not prepopulated. Is there a way we can prepopulate from the QuestionaireResponces + the extracted resources?

**Comment by FikriMilano** [comment]
Yeah, we can just get the complete response from db.
It already includes the Village or Town answer.

**Comment by FikriMilano** [comment]
Let me try both solutions

**Comment by FikriMilano** [comment]
<img src="https://user-images.githubusercontent.com/62053304/180357621-3fcd27e4-48af-4874-8fa2-86a79839f6c5.png" width="300" />

@f-odhiambo it works, retrieving response from DB.
But it will require to create a new Family then attempt to edit it.

NOTE: 
it's in a different branch, that's why the Edit title is not there.

**Comment by FikriMilano** [comment]
@f-odhiambo @dubdabasoduba 
Found another bug as well.
For some reason, other QuestionnaireResponse of family registration, doesn't exist in the DB, but exist in the server.
This is even after a fresh install and a successful initial sync.

I tried to solve it, but doesn't found the solution.

It's related to sync bug.
@roywanyaga might be able to help w this.

**Comment by FikriMilano** [comment]
We can close this after merging these 2
https://github.com/opensrp/fhircore/pull/1451
https://github.com/opensrp/fhircore/pull/1459

**Comment by dubdabasoduba** [comment]
Other than the sync-up and the edit questionnaire rendering enhancements the other pre-population of data has been solved by updating the structure maps on the forms.

**Comment by NaveenZehra11** [comment]
LGTM!

https://user-images.githubusercontent.com/90256461/199562795-5af3fe51-5a74-434b-8a89-8e047f7939ee.mp4

apk : https://github.com/opensrp/fhircore/releases/tag/v0.1.6-ecbis-rc1
preview apk
config id = cha
cc @AnnieMungai
