### ISSUE TITLE
[Quest/eCBIS] - Fix Search results count label

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1443]
**Describe the bug**
Search result count label is displaced in the landing page view

**To Reproduce**
1. Go to Household or ANC  register 
2. Search for a Family or ANC Patient
3. On search results, see error

**Expected behavior**

**Screenshots**
<img src="https://user-images.githubusercontent.com/4540684/179399772-5d012e51-1b27-4a42-8a7f-9aa4fe377fbf.png" width="200" height="400" />

**Suggested  view** 
<img width="373" alt="Screenshot 2022-07-06 at 10 40 49" src="https://user-images.githubusercontent.com/31955469/177496609-34936736-2baf-4628-99f2-4ee65dca5053.png">

**Comment by f-odhiambo** [comment]
@qaziabubakar-vd you can link the PR to this fix CC @ellykits so that once merged we can close this

**Comment by LZRS** [comment]
@f-odhiambo @qaziabubakar-vd  Here's a pr porting the changes made on mwcore to main https://github.com/opensrp/fhircore/pull/1438

**Comment by ellykits** [comment]
This issue has been resolved. You can close the Pr Laz
