### ISSUE TITLE
[Quest/eCBIS] - Add to Child Register

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1444]
**Name of feature to enhance**
1. Add a child register to eCBIS 

**Description of feature**
1. Discussed  in thread 

**Describe the enhancement**
1. Designs of the Patient list view for children to be shared by the design team

**Comment by f-odhiambo** [comment]
Defining terms. The World Health Organization (WHO) defines adolescents as those people between 10 and 19 years of age. The great majority of adolescents are, therefore, included in the age-based definition of “child”, adopted by the Convention on the Rights of the Child, 4 as a person under the age of 18 years.

1. 0-6 yrs
2. 7-12 yrs
3. 13-17 yrs (Teenagers)
4. Over 18 yrs (Adults)

CC @dubdabasoduba @AnnieMungai to validate if the above is true or if we have additional criteria. what are the different age groups for children?

**Comment by AnnieMungai** [comment]
@f-odhiambo 
- In eCBIS, and I believe most child registers, children are defined as persons between 0 - 5 years (0 - 60 months). within the child group, these are other core groupings (note that these could vary by country). 
   - 0-28days - new borns (neonate)
   -Under 2 months
   - Under 1yr olds
   - Under 2 years old
- I do not think we have adults defined in any of our programs. However, we have: women of reproductive age - In Liberia, these are women between 15-49years. This definition varies in different countries. 
- There is also the definition of young girls between 9 - 12yrs who receive HPV vaccines.

**Comment by dubdabasoduba** [comment]
The configs here https://github.com/opensrp/fhir-resources/blob/main/ecbis/app_configurations/ecbis_cha_preview/navigation_config.json add the child register. This should be tested against this release https://github.com/opensrp/fhircore/releases/tag/v0.1.5-ecbis-rc2
