### ISSUE TITLE
[Quest/eCBIS] - Sync Up records from Android SQLite not working for newly created Households with no family members 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1445]
**Describe the bug**
Only families with family members being synced up to HAPI FHIR Server and not added Groups with no family members 

**To Reproduce**
1. Go to Household register
2. Click on Add family 
3. Enroll a family with no members
4. Sync 
5. On a secondary device only Groups with Patients appear on a secondary device 

**Expected behavior**
1. All newly created families (Groups) should be synced with or without members (Patients)

**Screenshots**
<img src="https://user-images.githubusercontent.com/4540684/180389202-47a55f22-b59d-4f91-aa04-f1ef2f2aaa3a.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/180389221-c7469d56-9bed-4ea2-b94f-1c70d0a23bea.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
From @roywanyaga 
```
I don't think this is a bug.
The setting below in the sync config filters Groups (families) for sync based on the ManagingEntity's (family head) organization (which should be the organization that the practitioner who's logged in belongs to)
Sync will thus not happen for a family without a family head.
```

![image](https://user-images.githubusercontent.com/4540684/179532171-ae5be97b-5d69-46c8-a972-612e908dbf47.png)

**Comment by f-odhiambo** [comment]
Q. Where do the families with no members disappear to? Are they in the background?

**Comment by AnnieMungai** [comment]
@f-odhiambo was this already fixed?

**Comment by f-odhiambo** [comment]
Looking into this should be resolved via https://github.com/opensrp/fhircore/issues/1574 . Will need to triage this before close though CC @AnnieMungai

**Comment by f-odhiambo** [comment]
Closing this as resolved
