### ISSUE TITLE
[Quest/eCBIS] - On Add Family member, refresh the patient list view to view latest addition to the family 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1446]
**Describe the bug**
On Add Family member, refresh the patient list view to view the latest addition to the family

**To Reproduce**
1. Go to Household register
2. Click on  a family 
3. Add a family member 
4. Newly created member does not appear on the family member list 

**Expected behavior**
1. Go to Household register
2. Click on  a family 
3. Add a family member 
4. Refresh family member list to view newly created member as you add other family memebrs

**Comment by AnnieMungai** [comment]
@f-odhiambo was this completed? I noted during QA that the family list is updated with the latest family that was visited.

**Comment by f-odhiambo** [comment]
> @f-odhiambo was this completed? I noted during QA that the family list is updated with the latest family that was visited.

@AnnieMungai What you are describing here may be a separate issue, there is refreshing the Task list once a task is created or status changes vs and refreshing the family member list once a new member to the household is added. Can you share feedback if this is the case ?

**Comment by AnnieMungai** [comment]
v.0.1.5- preview
Looks good to me!
