### ISSUE TITLE
[eCBIS] - Add the PNC StructureMap and profile menu

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1499]
Use the following issues to add the PNC-created content to the app. This requires StructureMap writing and code to show the `Register birth outcome` menu

- https://github.com/opensrp/fhir-resources/issues/42
- https://github.com/opensrp/fhir-resources/issues/58
- https://github.com/opensrp/fhir-resources/issues/57

**Comment by pld** [comment]
With the profile config merge, does this still require coding?

**Comment by dubdabasoduba** [comment]
@pld we haven't done any profile configs yet. But this won't require code after we do. This will be handled by the profile menus configuration

**Comment by dubdabasoduba** [comment]
This is already added to the app.
