### ISSUE TITLE
[Roadmap] Beta release of SDK with documentation

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#151]
[Tracking issue only]

Beta release with mostly completed features across core-SDK, data-capture and CQL-libraries. SDK will provide an example of deploying Smart Guidelines content

Reference to Android FHIR SDK [here](https://github.com/google/android-fhir/projects/7#card-55257050)

**Comment by pld** [comment]
https://github.com/google/android-fhir/issues/256
