### ISSUE TITLE
[Sync Optimization] Define the sync strategy on the Application Config

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1512]
**Is your feature request related to a problem? Please describe.**
- Sync Optimization
    - This will cater for configurability on what attributes defined [here](https://github.com/opensrp/fhircore/issues/1509) will be used for sync on the FHIR core app.  
- Discussion can be found [here](https://github.com/opensrp/fhircore/discussions/746#discussioncomment-2331432)

**Describe the solution you'd like**
- [x] Update the App config to an attribute named `syncStrategy`. 
- [x] The `syncStrategy` should be a JSON array. 
     - [x] This should hold strings that explain the resource types to sync by i.e `Location`, `Organization`, `CareTeam` & `Practitioner` 
     - [x] Here is a sample of the config `"syncStrategy":["Organization","Location","CareTeam","Practitioner"]`
- [x] Update the Application Config Model the incorporate the new `syncAttribute`

**Acceptance Criteria**
- [x] An updated `application_config.json` to include the `syncStrategy` attribute. 
- [x] FHIR Core should be able to understand the new attribute.

**Comment by dubdabasoduba** [comment]
**Technical points to note**
1. The sync strategy will be conjunctive i.e if you give 2 sync strategies then we will search for the resources that have both sync strategies.

**Comment by FikriMilano** [comment]
@dubdabasoduba 
So the `syncStrategy` represents whether to sync based on the available tags?

**Comment by dubdabasoduba** [comment]
The `syncStrategy` tells the app what tags to use will syncing e.g `Organization` will mean we sync using the Organization IDs

**Comment by FikriMilano** [comment]
Cool, that's clear
