### ISSUE TITLE
[Sync Optimization] Use the syncStrategy to identify the IDs of the resources required for sync

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1513]
**Is your feature request related to a problem? Please describe.**
- Sync Optimization
    - This issue is to guide FHIR Core on what IDs it should fetch during sync.  
- Discussion can be found [here](https://github.com/opensrp/fhircore/discussions/746#discussioncomment-2331432) 

**Describe the solution you'd like**
- [ ] Using the `syncStrategy` settings added [here](https://github.com/opensrp/fhircore/issues/1512) to identify the IDs to during sync. 
- [ ] Fetch all the IDs for the configured `syncStrategy`. This will involve the following
     - [ ] Generate sync params based on the fetched Ids. These IDs become the value for the sync params. 
     - [ ] Pass the sync params to all the patient data-related sync calls made by the app. Here is a sample param `?_tag=123&_tag=345`

**Acceptance Criteria**
- [ ] Match the correct resource ids to the correct `syncStrategy`. 
- [ ] Generate correctly defined params for the different FHIR endpoints
- [ ] Add all the sync params to all the GET endpoints. 

**Depends on** 
- [x] https://github.com/opensrp/fhircore/issues/1512

**Comment by pld** [comment]
Can you explain why the resource names being prefixed by `practitioner` when they are stored or matched in the user preferences?

**Comment by dubdabasoduba** [comment]
> Can you explain why the resource names being prefixed by `practitioner` when they are stored or matched in the user preferences?

@pld These IDs are related to the practitioner. It's a way to easily identify the resources tried to the practitioner assignment functionality.  They really don't have any tech implications. We can change the naming to something else.

**Comment by pld** [comment]
I think I’m missing some context on what makes this practitioner specific, is that because the practitioner is usually the user of the device, so they’ll be the one making this setting?

**Comment by dubdabasoduba** [comment]
Closing this in Favour of
- https://github.com/opensrp/fhircore/issues/1661
- https://github.com/opensrp/fhircore/issues/1662
- https://github.com/opensrp/fhircore/issues/1663
- https://github.com/opensrp/fhircore/issues/1664
