### ISSUE TITLE
[Quest] - Re-Sync App configs once a user logs back into the  app post logout 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1546]
**Describe the bug**
Subsequent sync do not re-sync application configurations. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Update config via postman
2. Logout current user
3. Login
4. Confirm if the app config is updated.

**Expected behaviour**
App configs should be resynced when the user re-logs in

**Screenshots**
N/A

**Additional context**
N/A

**Comment by pld** [comment]
This sounds like a sub-problem of the more general problem that is when do we update the app configs? Even if a user stays logged in we might want to force the app configs to resync, or let the user manually resync the app configs, the former is probably better since the server will know the app configs are updated before the user.

**Comment by ellykits** [comment]
In the current setup, Binary resources are synced first time after providing **appId**, on post login syncs that Binary resources are ignored whereas other resource types are synced. One of the solution would be to have an action somewhere in the app settings UI for manually triggering configs re-sync, the alternative is to use some sort of push notification from the HAPI FHIR server to notify the client app when configs are updated.

**Comment by ellykits** [comment]
Or we can support both approaches, the manual trigger being the easier route.

**Comment by dubdabasoduba** [comment]
@ellykits Does Compose need a reload for the state to change? i.e if we sync the configs while the app is in use how to effectively diasble|enable functionalities based on the configs?

If it doesn't then I would rather we leave it at login.  So every time we log in the app tries to fetch any config changes before moving to the home/registers
