### ISSUE TITLE
[App configuration] Implement click actions for Profile overflow menu 

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#1547]
- [x] Implement click action for `Change Managing Entity` menu item
- [x]  Implement click action for `Remove Family` menu item

**Comment by f-odhiambo** [comment]
Can we close this @ellykits @Rkareko ?

**Comment by pld** [comment]
good call, closing, reopen if there's something specific remaining

**Comment by pld** [comment]
that's not content
