### ISSUE TITLE
[Sync Optimization] Implement multi Organization sync

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#1550]
**Name of feature to enhance**
Sync resource from server

**Description of feature**
The latest concept of Sync based on Practitioner Details endpoint, allows the app to sync on multiple Organization, this is a TODO that needs to be done.

**Describe the enhancement**

- [ ] Update sync implementation to support multi Organization

cc @dubdabasoduba @f-odhiambo

**Comment by pld** [comment]
Is this a change on the client or server?

**Comment by FikriMilano** [comment]
This is for client side.

We already have it for the server side
https://fhir.labs.smartregister.org/fhir/practitioner-details?keycloak-uuid=34f0d616-afc8-4446-ae87-bb60be4bdbc9

**Comment by dubdabasoduba** [comment]
@FikriMilano Was this about syncing or about the tagging of resoruces?

**Comment by FikriMilano** [comment]
@dubdabasoduba it's about syncing

**Comment by dubdabasoduba** [comment]
Closing this in Favour of
- https://github.com/opensrp/fhircore/issues/1661
- https://github.com/opensrp/fhircore/issues/1662
- https://github.com/opensrp/fhircore/issues/1663
- https://github.com/opensrp/fhircore/issues/1664
