### ISSUE TITLE
[App Configuration] Add the Floating Action Button (FAB) on the different registers. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1559]
**Name of feature to enhance**
- We currently, haven't added the FAB to the register. It's a requirement for some of our current applications.  

**Describe the enhancement**
Add the FAB design to the registers.  This is should have the functionality
   - [x] The FAB should be defined through the register configuration file
   - [x] It should allow for visibility enabling & disabling.  
   - [x] It should allow the definition of a FAB that can have multiple actions on them
   - [x] The FAB design should account for the following possibilities
       - [x] A FAB with test only. 
       - [x] A FAB with Icon only. 
       - [x] A FAB with both icon and text.  
   - [x] The click action should be able to redirect to a specific page or redirect to open a Questionnaire page based on the configurations specified on the configurations. 

**Configuration sample from the profile configs**
```JSON
{
	"fabActions": [
		{
			"id": "ActionButton",
			"visible": true,
			"display": "{{ add.member }}",
			"actions": [
				{
					"trigger": "ON_CLICK",
					"workflow": "LAUNCH_QUESTIONNAIRE",
					"questionnaire": {
						"id": "82953",
						"title": "Add family member",
						"saveButtonText": "ADD MEMBER",
						"setPractitionerDetails": true,
						"setOrganizationDetails": true
					}
				}
			]
		}
	]
}
```

**Design Mockups**
![Home 1 0](https://user-images.githubusercontent.com/4817531/185804889-d485f4fe-9c52-4e22-a631-2beecec512c9.png)

**Items to discuss**
- With our current architecture can we different FABs for every register? @ellykits

**Comment by pld** [comment]
https://github.com/opensrp/fhircore/pull/1566
