### ISSUE TITLE
[App Configuration] Add the a message when a register has 0 results. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1560]
**Name of feature to enhance**
- Currently, if our registers fetch o results they just show a blank page with nothing written on them. 
- Update this behaviour to function as the mock-up suggest.

**Describe the enhancement**
- [ ] Add a section on the register configs to capture a message to be displayed in case the register has 0 items to display.
- [ ] This message should have a title & body. Both of these should be configurable. 
- [ ] This page should also have a button to add the resource expected on the register. This button however should have the following properties. 
    - [ ] Should be configurable i.e can be hidden or shown. 
    - [ ] Should have a property to configure the text to be shown? 
    - [ ] Should have an `actions` property to configure the Questionnaire load.  

**Configuration section sample**
```json
{
	"noResults": {
		"id": "noResults",
		"visible": true,
		"title": {
			"display": "{{title}}"
		},
		"body": {
			"display": "{{body}}"
		},
		"button": {
			"id": "noResultsButton",
			"visible": true,
			"display": "{{text}}",
			"actions": [
				{
					"trigger": "ON_CLICK",
					"workflow": "LAUNCH_REGISTER",
					"id": "householdRegister",
					"questionnaire": {
						"id": "82952",
						"title": "{{add.family}}",
						"saveButtonText": "ADD FAMILY",
						"setPractitionerDetails": true,
						"setOrganizationDetails": true
					}
				}
			]
		}
	}
}
```

**Design Mockups**
![Home - empty list](https://user-images.githubusercontent.com/4817531/185805157-3e4fe971-7f8d-46f6-811c-ca5607d9b7fd.png)

NB: - This should part of the register configs and not a config on it's own.

**Comment by ellykits** [comment]
Technical Scoping:

1. Create a new domain/mode data class 
```kotlin 
NoResultsConfig(val title:String = "", val message: String = "",val actionButton: NavigationMenuConfig? = null)
 ````
2. Update `RegisterConfiguration` by adding new property `noResults` of type `NoResultsConfig`
3. Update the `RegisterScreen` Composable view by rendering a `Column` of view above views (The bold text - title; the text in the middle - message and a button that uses `actionButton`) when paginItems is empty.
4. Otherwise render the `RegisterCardList`.

**Comment by ellykits** [comment]
Proposed JSON

```json
{
  "noResults": {
    "title": "{{title}}",
    "message": "{{body}}",
    "actionButton": {
      "id": "noResultsButton",
      "visible": true,
      "display": "{{text}}",
      "actions": [
        {
          "trigger": "ON_CLICK",
          "workflow": "LAUNCH_REGISTER",
          "id": "householdRegister",
          "questionnaire": {
            "id": "82952",
            "title": "{{add.family}}",
            "saveButtonText": "ADD FAMILY",
            "setPractitionerDetails": true,
            "setOrganizationDetails": true
          }
        }
      ]
    }
  }
}
```
NOTE: Should be part of `RegisterConfiguration`

**Comment by qaziabubakar-vd** [comment]
@dubdabasoduba  Can I please get a link to Figma for this design mockup?
