### ISSUE TITLE
[Quest/eCBIS] - Fix issues affecting Remove family functionality

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#1561]
- [ ] Ensure `Remove family` profile menu action removes family. Currently clicking `Remove Family` button in the questionnaire activity causes a crash.
- [ ] Ensure families that are not active are filtered out of the house hold register
- [ ] Refactor `remove family` and `remove family member` functionality to use `QuestionnaireActivity` and `QuestionnaireViewModel` classes
- [ ] Delete all classes in `family.remove` package

**Comment by dubdabasoduba** [comment]
@Rkareko Can we make the remove functionality configurable? We will need this functionality for other resources too.

**Comment by Rkareko** [comment]
@dubdabasoduba currently working on removing the custom classes that handle `remove family` and `remove family member` funtionality.

Will have a better understanding of the extent to which this can be configurable after this is done.

**Comment by pld** [comment]
@Rkareko any update on this?
