### ISSUE TITLE
[Quest] Sync-Up records to HAPI not working

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1574]
**Describe the bug**
Newly created resources in app are not being synced to HAPI

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Family register 
2. Add a new family with new members 
3. Press sync 
4. On Sync complete , reinstall app and search for newly previously created family plus members 

**Expected behavior**
All new resources should be synced to HAPI and synced back to the app 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
Check both on Emulator and Physical Device 

**Additional context**
- Newly created patients (family members) in Household and ANC register also applicable to this bug issue

**Comment by ndegwamartin** [comment]
@f-odhiambo is this for Family entities only or any type of data collected?

**Comment by f-odhiambo** [comment]
I think this one is specific for Patient resources. I think it will extend to CarePlans and Tasks, given these resources are only generated to be attached to an existing patient or group(household). Might be a tricked dow effect that also neds to be validated

**Comment by dubdabasoduba** [comment]
> I think this one is specific for Patient resources. I think it will extend to CarePlans and Tasks, given these resources are only generated to be attached to an existing patient or group(household). Might be a tricked dow effect that also neds to be validated

Do we have any errors thrown by the app?

**Comment by f-odhiambo** [comment]
> > I think this one is specific for Patient resources. I think it will extend to CarePlans and Tasks, given these resources are only generated to be attached to an existing patient or group(household). Might be a tricked dow effect that also neds to be validated
> 
> Do we have any errors thrown by the app?

At the moment, the app syncs, gives a correct success message but on interrogation the resources are not resident in HAPI FHIR server  in use

**Comment by qaziabubakar-vd** [comment]
@f-odhiambo According to my findings on this, once we are downloading the data from sync, we are filtering households on the basis of their managing entity but in our current flow when we are creating a new household, we don't have any household members assigned and hence no managing entity.

Later on, I tested by creating a household and then adding a member inside that household and making that member the family head as well, however on inspection of the database, I can see that even though we created a member for that household and made it the family, our Group is not updated and our group has no Patient or Managing entity assigned to it.

Here is our Group after I've added a member  to it as well

`{"resourceType":"Group","id":"7a7ce3b8-6b3c-4867-a989-ee1cc1f26e62","meta":{"lastUpdated":"2022-09-02T15:55:14.094+05:00"},"identifier":[{"use":"official","value":"12345","period":{"start":"2022-09-02T15:54:59+05:00"}},{"use":"secondary","value":"948fa815-92de-4e5f-96cd-60f194a90136","period":{"start":"2022-09-02T15:54:59+05:00"}}],"active":true,"type":"person","code":{"coding":[{"system":"https://www.snomed.org","code":"35359004","display":"Family"}]},"name":"Jim"}`

We can notice that it is not saving any information of the newly added member, the json for the newly added patient is as follows:

`{"resourceType":"Patient","id":"0e57d831-0b95-470d-a5b0-aafd467b18ca","meta":{"lastUpdated":"2022-09-02T15:56:58.550+05:00"},"identifier":[{"use":"official","value":"1122","period":{"start":"2022-09-02T15:56:58+05:00"}},{"use":"usual","value":"2211","period":{"start":"2022-09-02T15:56:58+05:00"}},{"use":"secondary","value":"02fe36cf-91f1-4fa7-89d2-50cd233304d9","period":{"start":"2022-09-02T15:56:58+05:00"}}],"active":true,"name":[{"use":"official","text":"A","family":"B","given":["JIm Head"]}],"gender":"male","birthDate":"1994-09-23","address":[{"use":"home","type":"physical"}]}`

I think @Rkareko worked on fixing a related issue in [this PR](https://github.com/opensrp/fhircore/pull/1562) where we needed to refresh the household profile with the newly added member but I'm not sure how much progress we made on that so far. 

So with these recent finding it looks like our Group resource is not updating once we are assigning it a new member and managing entity, and on sync download, we are filtering groups based on the their managing entities

**Comment by dubdabasoduba** [comment]
@qaziabubakar-vd this is interesting. I think what you just described above is a bug.  Does the app UI display the Family members?

**Comment by dubdabasoduba** [comment]
@f-odhiambo am I right to assume that this is on main?

**Comment by f-odhiambo** [comment]
@dubdabasoduba this issue is on `main`. Also, @Rkareko was working on the issue on refresh the family profile once a new member is created
