### ISSUE TITLE
[App configuration] Navigation side-menu icons implementation

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1575]
**Name of feature to enhance**

1. Navigation menu icons implementation

**Description of feature**

1. Add menu icons to the different menu items on the Navigation drawer

**Describe the enhancement**

1. Via configs we can either enable or disable menu icons as defined in the app configs

**Comment by f-odhiambo** [comment]
We need to do some RnD on how to sync icons as base64 in app config synced from HAPI 

CC @ellykits

**Comment by dubdabasoduba** [comment]
@f-odhiambo We have 2 steps for implementation 

1. Load icons from the assets folder. 
    - [ ] We will save the images in the assets folder. 
        - [ ] Only have the images needed on the engine move the rest to Quest
    - [ ] Then use the names of the icons on the configuration files. 
    - [ ] Update Quest to read the icon names from the configuration files and reference the correct icons on the assets folder. 

2. Loading icons form HAPI
   - [ ] Update the Icons as a binary of document reference resources.
   - [ ] Reference the binary or document reference resource on the composition resources
   - [ ] Download the icons to the app. 
   - [ ] Reference the binary files from the navigation configs
       - [ ] Write some functionality to load the binary as the icon when the views are loaded. 

NB: - For us to support both the local assets and server stored files we might want to tweak the icon property on the configs a little. Here are the proposed changes
```json
{
	"icon": {
		"type": "local|remote",
		"name": "local file name|resource id"
	}
}
```

**Comment by FikriMilano** [comment]
Just to take a note.

Based on my experience, decoding a base64 image is an expensive process.

So it's important for that process to happen outside the composable function, since it will affect the UI rendering.

**Comment by pld** [comment]
> Just to take a note.
> 
> Based on my experience, decoding a base64 image is an expensive process.
> 
> So it's important for that process to happen outside the composable function, since it will affect the UI rendering.

that's a good point, let's make sure to keep an eye on the performance esp on different lower power phones, we can switch to an alternative (no base64 encoded) approach if we're seeing this problem

**Comment by f-odhiambo** [comment]
How is the progress on this @FikriMilano ?

**Comment by FikriMilano** [comment]
@f-odhiambo 
Still in the implementing process, was mostly doing meetings yesterday

**Comment by dubdabasoduba** [comment]
@FikriMilano @ellykits Are we supporting both approaches? If not which one are we supporting?

**Comment by FikriMilano** [comment]
At the moment, yes

**Comment by FikriMilano** [comment]
- [x] Load local icons
- [x] Load base64 icons (non debug mode)
- [ ] Load base64 icons (debug mode)
- [ ] Fix tricky base64 icon scaling

**Comment by dubdabasoduba** [comment]
Nice! thanks
