### ISSUE TITLE
[Quest/Malawi Core] Struggling to enter a long username when logging in

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1577]
**Describe the bug**
As you are typing a username, the field gets erased before you finish.

**To Reproduce**
1. Go to the login page
2. Click on the username field
3. Start typing

**Expected behavior**
The username should be typed without any erasing happening

**Screenshots**
https://user-images.githubusercontent.com/90775548/187173173-ac366d41-8164-4a45-8a13-bdfa19afde1f.mp4

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
N/A

**Comment by f-odhiambo** [comment]
@KhumboLihonga Can you provide examples of usernames to replicate this? CC @Gental-Giant  

Not able to reproduce this. Current example `elizabeth` is working fine in current `main`

**Comment by KhumboLihonga** [comment]
@f-odhiambo that's odd. I've tested it on `main` and you're right, it seems to be working fine on that branch. Must be something on our branch but I don't recall us ever making changes on the login page. Will need to double check.
