### ISSUE TITLE
[Quest/Malawi Core] Update to the latest version of the SDC library

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1586]
**Name of feature to enhance**
SDC library

**Description of feature**
Allows us to create questionnaires & structure maps

**Describe the enhancement**
Update to the latest version so that we can start using features that have been fixed or added such as [this](https://github.com/google/android-fhir/pull/1560), [this](https://github.com/google/android-fhir/pull/1310) and [this](https://github.com/google/android-fhir/issues/1187).

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo this task can be closed, as PR merged
