### ISSUE TITLE
[Authentication] Update access/auth token renewal workflow

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1592]
**Context**
- Currently, FHIR Core authenticates with Keycloak. An access token is then generated. 
- This access token has an expiry configured on the Keycloak realm. 
- Currently, if it expires It doesn't try to automatically renew the token, nor does it redirect the user to the login page. This leads to the following error when the user tries to sync. 
```log
I/AppMainActivity: Sync state received is Failed(result=Error(exceptions=[ResourceSyncException(resourceType=Bundle, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Patient, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Group, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Encounter, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Observation, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Condition, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=CarePlan, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Task, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Questionnaire, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Questionnaire, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=StructureMap, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=PlanDefinition, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Library, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Measure, exception=retrofit2.HttpException: HTTP 401 )]))
E/AppMainActivity: HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 
I/okhttp.OkHttpClient: <-- 401 https://ecbis-preview.smartregister.org/fhir/QuestionnaireResponse?_count=100&_sort=_lastUpdated (314ms, 437-byte body)
I/okhttp.OkHttpClient: --> GET https://ecbis-preview.smartregister.org/fhir/Questionnaire?_count=100&_sort=_lastUpdated&_lastUpdated=gt2022-09-02T18%3A05%3A42.217Z
V/TokenManagerService: Checking local storage for access token
I/okhttp.OkHttpClient: <-- 401 https://ecbis-preview.smartregister.org/fhir/Questionnaire?_count=100&_sort=_lastUpdated&_lastUpdated=gt2022-09-02T18%3A05%3A42.217Z (359ms, 437-byte body)
I/okhttp.OkHttpClient: --> GET https://ecbis-preview.smartregister.org/fhir/StructureMap?_count=100&_sort=_lastUpdated&_lastUpdated=gt2022-09-02T18%3A53%3A39.391Z
V/TokenManagerService: Checking local storage for access token
I/FhirTaskPlanWorker: Starting task scheduler
I/FhirTaskPlanWorker: Done task scheduling
I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=77fe4d61-8ed7-4b19-9e02-7b701520c49c, tags={ org.smartregister.fhircore.engine.task.FhirTaskPlanWorker } ]
I/okhttp.OkHttpClient: <-- 401 https://ecbis-preview.smartregister.org/fhir/StructureMap?_count=100&_sort=_lastUpdated&_lastUpdated=gt2022-09-02T18%3A53%3A39.391Z (294ms, 437-byte body)
I/okhttp.OkHttpClient: --> GET https://ecbis-preview.smartregister.org/fhir/PlanDefinition?_sort=_lastUpdated&_lastUpdated=gt2022-09-02T18%3A56%3A37.342Z
V/TokenManagerService: Checking local storage for access token
I/okhttp.OkHttpClient: <-- 401 https://ecbis-preview.smartregister.org/fhir/PlanDefinition?_sort=_lastUpdated&_lastUpdated=gt2022-09-02T18%3A56%3A37.342Z (284ms, 437-byte body)
I/okhttp.OkHttpClient: --> GET https://ecbis-preview.smartregister.org/fhir/Library?_sort=_lastUpdated
V/TokenManagerService: Checking local storage for access token
I/okhttp.OkHttpClient: <-- 401 https://ecbis-preview.smartregister.org/fhir/Library?_sort=_lastUpdated (289ms, 437-byte body)
I/okhttp.OkHttpClient: --> GET https://ecbis-preview.smartregister.org/fhir/Measure?_sort=_lastUpdated
V/TokenManagerService: Checking local storage for access token
I/okhttp.OkHttpClient: <-- 401 https://ecbis-preview.smartregister.org/fhir/Measure?_sort=_lastUpdated (286ms, 437-byte body)
I/AppMainActivity: Sync state received is Glitch(exceptions=[ResourceSyncException(resourceType=Patient, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Group, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Encounter, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Observation, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Condition, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=CarePlan, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Task, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Questionnaire, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Questionnaire, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=StructureMap, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=PlanDefinition, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Library, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Measure, exception=retrofit2.HttpException: HTTP 401 )])
W/AppMainActivity: HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 
I/AppMainActivity: Sync state received is Failed(result=Error(exceptions=[ResourceSyncException(resourceType=Bundle, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Patient, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Group, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Encounter, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Observation, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Condition, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=CarePlan, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Task, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Questionnaire, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Questionnaire, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=StructureMap, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=PlanDefinition, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Library, exception=retrofit2.HttpException: HTTP 401 ), ResourceSyncException(resourceType=Measure, exception=retrofit2.HttpException: HTTP 401 )]))
E/AppMainActivity: HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 , HTTP 401 

```
- The idea is to get this token auto renewed and if the expiry period is very long then redirect to the login page

**Token renewal Workflow**
- Initial Login
    - User logs in to the app for the first time. 
    - We save the login credentials on the account manager. This includes the username/password & authentication token returned by keycloak
- Sync to the server
    - The implementation will set a `maxExpiry` time on the `application_config`. This time will be used to determine when a user must re-login for a new auth token to be assigned. 
        - This value is set in days. 
        - If this value is not set then the app will not auto-renew the auth token. It will always send the user back to the login page for a fresh login.  
    - On triggering sync we first check whether the device is connected to the network. If yes we proceed to the next step. If not, we stop the sync and notify the user to connect to a network that has internet access. 
    - If the user is connected we then attempt the sync. If the server returns a 401 then we have 2 options. Auto-renew the token or redirect the user to the login page. 
    - Auto-renew
        - The auth token has an `exp` date on it. This is the date the token should expire after it is issued by KeyCloak. 
        - We check whether the user is eligible for token auto-renew using the following formula `today() - exp`. 
        - If the difference is less than the `maxExpiry` time we auto-renew the token using the credentials saved on the Account Manager.  
        - After auto-renewal we need to update the account manager with the new auth token and re-trigger sync. 
    - Redirect to the login page
       - The user will be notified about their authentication status.
       - They will then redirect to the login page
       - After login, the sync is automatically triggered. 

**Technical Implementation**
- [x] Initial login
     - [x] make sure all the credentials are correctly saved on the user account in the Android account manager. Credentials to save include
         - [x] Authentication details (username/password)
         - [x] Auth token from KeyCloak. 
         - [x] Any other relevant auth details. 
- [x] Sync data server. 
    - [x] Use the auth token stored in the account manager on the server requests. 
    - [ ] Check for connectivity before trying to sync. 
    - [x] Check whether the user is eligible for auto-renewal or not. 
    - [x] Saved the correct auth token to the account manager in case auto-renewal happens. 

**Acceptance Criteria**
- [ ] Check the internet connection before any sync. 
- [x] Return the appropriate messages on sync failure. 
- [x] Auto renew or redirect to login when the access/auth token is expired.

**Questions**
- What is the appropriate time to allow for auto-renewal of the access/auth token?

**Comment by dubdabasoduba** [comment]
Marking this as a high priority since all our applications are affected on sync to the server when the access/auth token is not renewed correctly.

**Comment by allan-on** [comment]
Hi @dubdabasoduba 
Based on conversations with Martin and his recommendations around storing credentials on the device (see https://github.com/opensrp/fhircore/issues/1606#issuecomment-1246650223), the approach favoured is where we don't save credentials on the device. 
To achieve auto-renewal of the access token with the current codebase, I'd propose using the refresh token to get the access token
  - The refresh token lifetime is controlled by the SSO Session Idle Setting on Keycloak. 
  - The assumption is that the refresh token lifespan is/will be longer than the access token such that it can be used to request the access token multiple times. This value is set in Keycloak and the `Revoke Refresh Token` has to be disabled in the Token's tab
  - The implementation in the referenced PR #1656 leverages the existing implementation to get the refresh token when the access token is inactive/expired and use it (the refresh token) to request a new access token
  - In the event the refresh token is expired, then the user is logged out so that they supply their credentials and a new access token requested

**Comment by dubdabasoduba** [comment]
@allan-on How far are we with reviewing this?

**Comment by dubdabasoduba** [comment]
@allan-on so did you configure the refresh token expiry time on keycloak? If yes do you mind writing a `.md` of all the items that need configuration on keycloak for the authentication to work well? 

Are letting the users know that the config is missing in case the configuration is not done? i.e can the app check the refresh and auth token to know whether the expiry dates/time is set  and not `null`

Are we now saving the auth and refresh token on the `account.db`?
