### ISSUE TITLE
[Quest/Malawi Core] Sync fails after being idle in the app for a short period of time

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1597]
**Describe the bug**
When the app is idle for a short period of time, when you attempt to sync, the sync fails with the error "Sync failed. Check internet connection or try again later". This was initially resolved in this [issue](https://github.com/opensrp/fhircore/pull/1126) but it's still happening.

**To Reproduce**
1. Log into the app
2. Wait for 10 minutes
3. Try to sync

**Expected behavior**
The app should still successfully sync.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
N/A

**Comment by LZRS** [comment]
Relates to https://github.com/opensrp/fhircore/issues/1592
