### ISSUE TITLE
[Authentication] Update the subsequent logins to account for PIN login configurations

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1606]
**Describe the bug**
- FHIR Core allows users to configure the app to log in via PIN. 
- The workflow starts with the username/password login for the initial login. A PIN is then set for the device. The expectation is for the PIN login to be used for all subsequent logins.  

**To Reproduce**
Steps to reproduce the behaviour:
1. log in to any Quest variant with PIN login enabled
2. Set the pin during the initial login. 
3. Close the app and reopen it again. 
4. You will notice if the app will not redirect you to the pin login screen. 

**Expected behaviour**
- [ ] If the PIN login is set to `true` and the PIN has been set after the initial login, the app should always redirect the user to the PIN login in the subsequent log attempts.

**Comment by f-odhiambo** [comment]
Reassigning this ticket to @Rkareko

**Comment by ellykits** [comment]
@dubdabasoduba @Rkareko  Have we considered a scenario when the login access token expires even if we will be able to login and move to the main screen we will not be able to sync anything to/from the server. Do we want to save the initial user credentials to use them later for token renewal? what would be the security implications of doing so?

**Comment by Rkareko** [comment]
@dubdabasoduba @allan-on @ellykits will the token renewal referred to in the previous comment be handled by the work on `Update access/auth token renewal workflow` #1592 ticket?

**Comment by allan-on** [comment]
@ellykits Regarding the user credentials, we (with @dubdabasoduba) looked at having them available through the `AccountManager`.

**Comment by ndegwamartin** [comment]
Storing credentials directly on the mobile app might have some negative security implications. It is recommended to only store a hash per user and probably one which is salted such that users with the same credentials get a different hash

This hash is then compared with one generated in real time when a user attempts to log in.

**Comment by ndegwamartin** [comment]
For our current set up where we intend to fully replace username/password with pin we’d need an implementation that interfaces with Keycloak directly, otherwise the user will always at one time need to remember/use their actual credentials from Keycloak to log in e.g. when the refresh token expires.

Might be worthwhile investigating/researching on ways of adding support  for _pin login on Keycloak_ e.g. this may be feasible by implementing a Service Provider Interface(SPI) for this custom authentication . 

See documentation on [Keycloak Authentication SPI](https://www.keycloak.org/docs/latest/server_development/index.html#_auth_spi)

**Comment by dubdabasoduba** [comment]
> For our current set up where we intend to fully replace username/password with pin we’d need an implementation that interfaces with Keycloak directly, otherwise the user will always at one time need to remember/use their actual credentials from Keycloak to log in e.g. when the refresh token expires.
> 
> Might be worthwhile investigating/researching on ways of adding support for _pin login on Keycloak_ e.g. this may be feasible by implementing a Service Provider Interface(SPI) for this custom authentication .
> 
> See documentation on [Keycloak Authentication SPI](https://www.keycloak.org/docs/latest/server_development/index.html#_auth_spi)

@ndegwamartin Thanks for this. added to a discussion for more R&D https://github.com/opensrp/fhircore/discussions/1646
