### ISSUE TITLE
[Quest/Malawi Core] Date entry format always defaults to month/day/year

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1623]
**Describe the bug**
When using the entryFormat extension on a date field, the date does not get formatted accordingly. A sample of this extension is used in the android FHIR catalog app [here](https://github.com/google/android-fhir/blob/master/catalog/src/main/assets/date_picker_questionnaire.json).

**To Reproduce**
1. Go on the patients register
2. Select an ART client
3. On their profile, select Viral Load Results
4. Check the date of the viral load sample collection

**Expected behavior**
The date should be formatted accordingly i.e. for today's date, it should show 12/09/2022 (day/month/year) but even with the extension added, the date always defaults to 9/12/22 (month/day/year).

**Screenshots**
![Screenshot_20220912-134955_Malawi Core](https://user-images.githubusercontent.com/90775548/189646831-88856ee5-4fea-4b86-b441-dff1c65f6db2.jpg)

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
This works in the android FHIR catalog app as shown below. I also tried it on the ecbis app and it doesn't seem to be working there either.

![Screenshot_20220908-153422_Structured Data Capture Catalog](https://user-images.githubusercontent.com/90775548/189646883-5b5ea932-2006-4129-adeb-6709bd499913.jpg)

**Comment by f-odhiambo** [comment]
We may need to check on SDC on the support for this extension. I will review based on the shared details. Adding Triage label for this

**Comment by KhumboLihonga** [comment]
This was implemented in this [PR](https://github.com/google/android-fhir/pull/1276) but it doesn't seem to be working correctly

**Comment by dubdabasoduba** [comment]
@f-odhiambo @Gental-Giant We might want to create an SDK ticket for this (if we don't have one)

**Comment by Gental-Giant** [comment]
@f-odhiambo @dubdabasoduba Here is the sdk ticket [for this](https://github.com/google/android-fhir/issues/1623)

**Comment by KhumboLihonga** [comment]
To be closed with https://github.com/opensrp/fhircore/issues/1764
