### ISSUE TITLE
[Quest] Add Ordering to Registers

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1638]
**Name of feature to enhance**
Add Ordering of Registers

**Description of feature**
Order the Family/Patient Register
1. Ascending/Descending by Given name
2. Ascending/Descending by Family name
3. Ascending/Descending by Registration date
4. Ascending/Descending by Last Encounter

**Comment by pld** [comment]
We could do this by letting the user define a set of [name, query] pairs in an order key field in the config, where the query is defining the order, and have convention for asc/desc, so we'd support asc/desc for every order query they define

**Comment by f-odhiambo** [comment]
Good point  @pld

> We could do this by letting the user define a set of [name, query] pairs in an order key field in the config, where the query is defining the order, and have convention for asc/desc, so we'd support asc/desc for every order query they define

Good point @pld

**Comment by f-odhiambo** [comment]
Closing this in favor of #1789
