### ISSUE TITLE
[UX] Update from Spinner to Progress bar for Data Sync on FHIR Core

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1639]
**Required Enhancements** 

1. Replace the current Spinner to Progress bar for Data Sync
2. Related  - Sync progress and status issue  [#1484](https://github.com/google/android-fhir/issues/1484) and PR [#1572](https://github.com/google/android-fhir/pull/1572) 

**Sample screenshot**
<img width="803" alt="181654058-04ef3d11-e250-4768-aaeb-89f49b6fedae" src="https://user-images.githubusercontent.com/4540684/190400690-c1eb6ded-ab82-4657-9448-2c4b270f8be3.png">

**Comment by pld** [comment]
Cool, this looks good, for the first draft let's do the minimal UI focusing on the functional requirements, then we'll do another pass with input from the design team on the UI.

This is different from the screenshots, in that the screenshots are for a task specific load and we are doing this to replace our blocking full screen load, but the concept is the same: percent number and color changing bar.

**Comment by pld** [comment]
@f-odhiambo to me this is sufficiently described to remove the draft tag and add to the milestone, what do you think?

**Comment by f-odhiambo** [comment]
Cool @pld updated
