### ISSUE TITLE
[Quest/Malawi Core] Initial selection for choice item being reset on moving to next page

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1640]
**Describe the bug**
When the user opens the registration [questionnaire](https://github.com/opensrp/fhir-resources/blob/main/mwcore/questionnaire/registration/patient_demographic_registration.json), the first page has a radio group with the first option pre-selected. If the user selects a different option and moves to the next page, the radio group on the first page is reset back to the initial option.

**To Reproduce**
1. On the patients register, click 'REGISTER NEW PERSON'
2. When the questionnaire opens, select 'exposed infant' from the list of options
3. Press next
4. When the next page opens, tap previous
5. When the first previous opens, you will notice newly diagnosed client has been selected once again

**Expected behavior**
Exposed infant should remain selected

**Screenshots**
https://user-images.githubusercontent.com/90775548/190397585-6f48f5c9-ada9-457f-bbb0-3e58238cb4ef.mp4

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
This started happening after the most recent [update](https://github.com/opensrp/fhircore/pull/1618) of the android-fhir sdk. Before this update, the questionnaire worked just fine as shown below:
https://user-images.githubusercontent.com/90775548/190397542-ded13838-4099-47a1-a04c-278a2c8896a9.mp4

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo , this issue can be closed, as its PR also merged,
