### ISSUE TITLE
[Quest/Malawi Core] Optimize the search functionality

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1648]
**Name of feature to enhance**
Search

**Description of feature**
Allows the user to find patients by name or ART number

**Describe the enhancement**
We need to optimize the search be able to find the patient within a matter of seconds. It is currently far too slow to be used in a real world setting. View the example below:

https://user-images.githubusercontent.com/90775548/190600191-28ac60ab-7473-4664-8e1a-dc08493de68a.mp4

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo , this can be close as PR merged,
