### ISSUE TITLE
[Quest/eCBIS] - Searching and unsuccessful pairing devices during p2p sync  

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1649]
**Describe the bug**
Pairing of devices not successful even after nearby detection

**Steps to reproduce the behavior:**
1. Launch app 
2. Go to P2P menu 
3. Launch P2P Sync menu 
4. Initiate a pairing session 
5. Two things will happen 
- App will crash 
- App will try to connect but not successful  

**Expected behavior**
1. App should be able to pair with secondary device and sync data with the peer , data should be successfully sent to the peer as expected 

**Smartphone (please complete the following information):**
- Device: Oppo F9 and Samsung Galaxy A2.
- Android: 10
- Build number: eCBIS v.0.0.5

**Video**
https://user-images.githubusercontent.com/85434942/176634598-2730219f-aa6a-47da-b5e4-34dc9a7c63f4.mp4

**Comment by f-odhiambo** [comment]
Related ticket - #1249

**Comment by madrinekariuki** [comment]
@AnnieMungai 
APK : https://github.com/opensrp/fhircore/releases/tag/v0.1.9-ecbis-rc5A
Devices: Android 11 4GB RAM -- CHA
              Android 9 2GB RAM -- CHSS

Observation:
search and Pairing is successful for P2P sync
