### ISSUE TITLE
[Quest] Sync timestamp is incorrect

### ISSUE THREAD

**Issue by charlene-570** [opensrp/fhircore#1651]
**Bug Description**
The sync time is constantly  "06:06 PM, Sep 16" 

**Steps To Reproduce**

1. Login the App
2. Make sure sync is complete

See screenshot attached
<img src="https://user-images.githubusercontent.com/85434942/190635652-45277e4e-c377-42bf-8100-b91eca703007.jpg" width="200" height="400" />

 - Android version:10
 - Version:0.0.3

**Comment by pld** [comment]
cool, we might as well fix the formatting while we're at it.

is the sync time supposed to be when the last sync occurred where data was changed or the when the last sync occurred regardless of whether was data changed or not?

**Comment by f-odhiambo** [comment]
@DebbieArita Kindly have a look at this

**Comment by f-odhiambo** [comment]
> cool, we might as well fix the formatting while we're at it.
> 
> is the sync time supposed to be when the last sync occurred where data was changed or the when the last sync occurred regardless of whether was data changed or not?
@pld 

1. On formatting can we just leave it as a timestamp ? What formatting option are you proposing here ?
2. On time  - We should update this based on the sync both user initiated and background sync every 15 mins (on resume show latest sync timestamp)

**Comment by dubdabasoduba** [comment]
> > cool, we might as well fix the formatting while we're at it.
> > is the sync time supposed to be when the last sync occurred where data was changed or the when the last sync occurred regardless of whether was data changed or not?
> > @pld
> 
> 1. On formatting can we just leave it as a timestamp ? What formatting option are you proposing here ?
> 2. On time  - We should update this based on the sync both user initiated and background sync every 15 mins (on resume show latest sync timestamp)

@f-odhiambo for formatting we need to have it as a human-readable data & time.

**Comment by dubdabasoduba** [comment]
> cool, we might as well fix the formatting while we're at it.
> 
> is the sync time supposed to be when the last sync occurred where data was changed or the when the last sync occurred regardless of whether was data changed or not?

We previously showed the last time sync occurred regardless fo whether data changed. I would suggest we keep that. It helps give confidence that the users are using the app with the latest data based on the time sync was triggered

**Comment by f-odhiambo** [comment]
Cool I think we are aligned.

**Comment by ellykits** [comment]
> We previously showed the last time sync occurred regardless of whether data changed. I would suggest we keep that. It helps give confidence that the users are using the app with the latest data based on the time sync was triggered

I can confirm that this is what is happening.

**Comment by AnnieMungai** [comment]
Tim stamp updated! Lgtm
