### ISSUE TITLE
Back space arrow on the Reports page is unresponsive

### ISSUE THREAD

**Issue by charlene-570** [opensrp/fhircore#1652]
**Bug Description**

Clicking the backspace arrow 

**To Reproduce**
1. Login the App
2. Navigate to Reports 
3. Click on the back arrow

**See screenshot attached**
![reports](https://user-images.githubusercontent.com/85434942/190647228-48c6b2a0-4ec0-4024-a45a-92e91c22628e.jpg)

**Comment by NaveenZehra11** [comment]
app crashing while click on Report

https://user-images.githubusercontent.com/90256461/203273641-6105f9b1-5661-4d9f-b1c8-f66177b08d00.mp4

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.7-ecbis-rc1
preview apk
cc @AnnieMungai

**Comment by AnnieMungai** [comment]
@NaveenZehra11 closing and addressing in the in-app reporting work ongoing.
