### ISSUE TITLE
[Tech Debt] Update the placement of the `display` and `system` keys on the user assignment `meta.tags`

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1657]
**Name of feature to enhance**
- We tag all the app-generated resources with the user assignments. 
- The `meta.tag` is a FHIR Code which contains the following keys `system`, `code` & `display`.
- We don't expect the `display` & `system` keys to change but we still want to make it easy for engineers to change them if they wanted to.  
- This means either declaring them on the `build.grable` or the `strings.xml`
- This issue is to facilitate the discussion and get the placement agreed upon. 
- The configuration is not user-facing. It's just for the engineering teams' benefit. 

**Description of feature**
- [ ] Declare the `system` & `display` keys of the `meta.tag` codes in a configurable way for engineers to easily change if need to. This can be on the `build.gradle` or `string.xml`.

**Comment by dubdabasoduba** [comment]
@ellykits @FikriMilano I have moved the pending discussion here allowing merging of this PR https://github.com/opensrp/fhircore/pull/1576

**Comment by FikriMilano** [comment]
@ellykits @dubdabasoduba
What do you think of using `build.gradle`?

Actually I prefer this way, because:
1. We can avoid the `ApplicationUtil`
2. `strings.xml` should only for string that is displayed into the app, that's why they are translatable

**Comment by dubdabasoduba** [comment]
@FikriMilano I am okay with that. The only question is what happens in case they are removed. Do we stop the app from building?

**Comment by FikriMilano** [comment]
@dubdabasoduba 
Had a discussion w @ellykits , let's do the `strings.xml`.
It's easier to do the flavoring, will be getting the context from config service, strings.xml can also be marked as non translatable.

**Comment by dubdabasoduba** [comment]
@ellykits @FikriMilano should we close this after the [tagging](https://github.com/opensrp/fhircore/pull/1576) PR?

**Comment by FikriMilano** [comment]
@dubdabasoduba yeah
