### ISSUE TITLE
[Client Side | Sync Enhancement] Identify resources to sync from the server. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1658]
**Context**
- The app needs to know what patient data-related resources we need to fetch from the server. 
- We would like to automate this process. This process is to run every time the user login using the `username`/`password`
   - This is to account for changes on the config files. 

**Description of enhancement**
- [x] Fetch all the `register` and `profile` configs from the SQLite DB. These are references by the Composition Resource. We can use it to identify the Binary Resources holding the said resources. 
     - [x] Traverse each fo the `register` & `profile` configs checking the `baseResource` & `relatedResource` keys. These keys define the resources the register or profile uses. 
     - [x] Get the ResourceTypes referenced in the 2 keys mentioned above and generate a JSON array of these Resource Types.
          - [x] The string entries in the array should unique.  
     - [x] Save this JSON array in the shared preferences of the app. We can use the key `remoteSyncResources` 
- Update the sync from server functionality to only request for the ResourceTypes on the `remoteSyncResources`

**Acceptance criteria**
- [ ] Sync resources identification should be triggered after every `username`/`password` login.  
- [x] All the ResourceTypes referenced on the `register` & `profile` configs should be part of the JSON array stored on the `remoteSyncResources` key in the shared preferences. 
- [x] The Patient data sync should only target the resources in the `remoteSyncResources`

**More information on why we need to make this change**
- https://github.com/opensrp/fhircore/discussions/1612

**Comment by pld** [comment]
Is there a way to force the user to logout based on their app id? Maybe managed by the sync process? I'm thinking of a use case where you change the composition on the server, so you want to force all the apps to reload their compositions, so you'd need to logout all the users of that app.

(This would obviously not be effective for offline users.)

**Comment by dubdabasoduba** [comment]
> Is there a way to force the user to logout based on their app id? Maybe managed by the sync process? I'm thinking of a use case where you change the composition on the server, so you want to force all the apps to reload their compositions, so you'd need to logout all the users of that app.
> 
> (This would obviously not be effective for offline users.)

@pld Could we do this on the device instead? The idea would be to check for any changes on the composition resource and then trigger a logout for that specific device. 

All the devices will eventually get logged out but the server doesn't have to care about it.

**Comment by pld** [comment]
Yea, good idea!
