### ISSUE TITLE
[Authentication] Add the Composition & Binary resources to the Allow-List of the Proxy server. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1659]
**Context**
- The FHIR core needs to access resources before the user logins in. 
- These resources are the Composition and Binary resources.
- We need to exempt them from authentication. 

**Description of enhancement**
- [ ] Add the Composition resources GET request to the allow-list on the proxy server. 
- [ ] Add the Binary resources GET request to the allow-list on the proxy server. 
- [ ] For the stage instances this will allow all the BInary and Composition resources. We however need to test the restriction to only allow specific resources. This will be used for Preview instances focusing on a specific implementation

**Acceptance criteria**
- [ ] The Composition & Binary resources should be accessible before login. 
     - [ ] This should only allow the GET HTTP request.

**Comment by rehammuzzamil** [comment]
I will be opening up a draft PR by EOD 26th September 2022 for an initial review to discuss how we have approached the issue and the solution. 
cc: @dubdabasoduba

**Comment by rehammuzzamil** [comment]
As per our discussion @dubdabasoduba, we have found out that the proxy **[AllowedQueriesChecker](https://github.com/opensrp/fhir-access-proxy/blob/3bf8a400e257f234f677154442f63570cd131307/server/src/main/java/com/google/fhir/proxy/AllowedQueriesChecker.java#L39)** only exempt end-points from the Authorization workflow. This means that Authentication still happens (a valid Bearer token is required). 

I've come up with a way to make it work by first handling the logic of end-point validation with the AllowedQueriesChecker plugin and then handling the authentication flow through BearerAuthorizationInterceptor.
Here is the [reference](https://github.com/opensrp/fhir-access-proxy/blob/3bf8a400e257f234f677154442f63570cd131307/server/src/main/java/com/google/fhir/proxy/BearerAuthorizationInterceptor.java#L220).
cc: @f-odhiambo

**Comment by ekigamba** [comment]
> Sounds good, I think we should be aware it's possible at some point, or for some clients, there may be sensitive or otherwise non-public information stored behind these end points that they may want to keep restricted.

I agree. We probably only want to allow specific Binary and Composition resources and not all. Most if not all attachments will be saved as single Binary resources on the Hapi FHIR server if not on an object server
