### ISSUE TITLE
[FHIR Server] Create a deployment pipeline and deploy the FHIR Proxy server

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1660]
- Proxy Server deployment and Pipeline creation https://github.com/onaio/infrastructure/issues/6197

**Make the following configurable on the pipeline**. 
- [ ] Keycloak and FHIR server configurations. This includes the Oauth configs
- [ ] The allow-list & the well-Known list.

**Comment by dubdabasoduba** [comment]
https://github.com/onaio/infrastructure/issues/6351

**Comment by f-odhiambo** [comment]
This is DONE
