### ISSUE TITLE
[Sync Enhancement | Data Access Checker] Data filtering based on the user assignments and the Sync by CareTeam

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1664]
**Context**
Sync by CareTeam means getting all the records that have a CareTeam tag equal to the CareTeam Id for the logged-in user.
  - E.G if a user is assigned 3 CareTeam(s) and wants to Query the Patient Resource then we will fetch the data from all 
    3 CareTeams.  

**Technical Description of enhancement**
- [ ] From the Patient Details endpoint response get the CareTeam Resource the User is assigned to. 
    - [ ] This can be found in the `fhir.careteams` array. 
- [ ] If the user is assigned to multiple CareTeams create a JSON Array to hold all the CareTeam IDs for the CareTeams on the `fhir.careteams` key. 
- [ ] We will then use this array to query the data that has a `meta.tag` code equal to each of the CareTeam IDs. This will happen by querying the requested resource endpoint n ( size of the CareTeam IDs array) times. i.e if we had 2 CareTeams then we will query the requested resource 2 times with the `_tag` param value being the ids of the 3 CareTeams. e.g 
    - https://fhir.labs.smartregister.org/fhir/Patient?_tag=137151 --CareTeam 1
    - https://fhir.labs.smartregister.org/fhir/Patient?_tag=136256 -- CareTeam 2
- [ ] Remember to add the other pagination request params to each request. 
- [ ] Bundle the responses from each of the queries to one response and send that back as the response to the Patient resource Request. 
   - [ ] This Bundle should match the FHIR resource Bundle specifications. 

**Acceptance Criteria**
- [ ] The code should be able to identify the CareTeam assignment of the user. 
- [ ] The code should be able to fetch the data for the assigned user CareTeams. 

**Pre-requisite**
- https://github.com/opensrp/fhircore/issues/1661

**More information on why we need to make this change**
- https://github.com/opensrp/fhircore/discussions/1604](https://www.hl7.org/fhir/practitionerrole.html)

**Comment by rehammuzzamil** [comment]
**LOE: 3.5 days**

**Provided that the basic structure is ready by [Issue  # 1662](https://github.com/opensrp/fhircore/issues/1662 ) and [Issue # 1661](https://github.com/opensrp/fhircore/issues/1661) .**

- [ ] Handle performance optimization while making calls to the next page and so on based on the data provided inside the meta.link.relation="next" //To be decided
- [ ] Including ASYNC logic (Separate threads) to run separate API calls if there is more than one careteam id present.

_Note: LOE is specified for a PR submission for an initial review._
cc: @dubdabasoduba @ekigamba @f-odhiambo
