### ISSUE TITLE
[Sync Enhancement | Permission Checker] Checking user permissions when requesting for data from the server.

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1665]
**Context**
- FHIR has a couple of resources which translate to the different ways data could be represented and retrieved. Each of these resources has an endpoint that accepts at least 4 HTTP method requests. These are POST, GET, PUT & DELETE.
- These methods will educate the permissions a user can have on any endpoint. We also have an additional Manage role
  which is a composite of the 4 HTTP methods-related roles.

| **HTTP Methods** | **Keycloak Roles** | **Examples**   |
|:-----------------|:-------------------|:---------------|
| GET              | GET Resource       | GET_PATIENT    |
| POST             | POST Resource      | CREATE_PATIENT |
| PUT              | PUT Resource       | UPDATE_PATIENT |
| DELETE           | DELETE Resource    | DELETE_PATIENT |
|                  | MANAGE Resource    | MANAGE_PATIENT |

- The above table shows how the HTTP methods will be mapped to the Keycloak roles. The role names are in the format of `HTTP_METHOD_RESOURCE_NAME`. This will be used to create the roles in Keycloak.
- These roles will be added to keycloak during deployment of the HAPI FHIR instance.
- We will use the Kycloak console to create any new roles created after the initial deployment.
- These permissions will be assigned via FHIR web during user creation.

#### How are the permissions used during authorization checks?
- We will be writing a permissions checker on the FHIR Proxy server. This will be a middleware that will be used to
  check the permissions of a user before allowing them to access the HAPI FHIR server.
- The workflow will be as follows.
  - The user tries to access a certain endpoint e.g `GET https://fhir.labs.smartregister.org/fhir/Patient`
  - The permission checker then gets the user's roles from the authentication token on the `authorization` header. This
    is found on the `realm_access.roles` key.
    - Here is a sample of the roles in the authentication token.
  ```json
  {
    "realm_access": {
      "roles": [
        "realm-admin",
        "OPENMRS",
        "EDIT_KEYCLOAK_USERS",
        "VIEW_KEYCLOAK_USERS",
        "PLANS_FOR_USER",
        "offline_access",
        "default-roles-fhir_android",
        "uma_authorization",
        "ALL_EVENTS"
      ]
    }
  }
  ```
  - The permission checker then gets the resource in question from the endpoint e.g `Patient`
  - Using the resource name, the permission checker then checks if the user has the `GET_PATIENT` role.
    - If the user has the role, the request is allowed to proceed to the HAPI FHIR server. If not, the request is denied
      and a `403` Permissions denied error is returned to the user.

**Technical Description of enhancement**
- [x] Check the KeyCloak roles the user has assigned. This can be found by checking the Auth token `realm_access.roles` key. 
- [x] Search for the ResourceType role in the `realm_access.roles` key.  How to generate the ResourceType role
    - [x] Find the HTTP method on the request. 
    - [x] Find the ResourceType on the request. 
    - [x] Combine the 2 to create the ResourceType e.g If the request is to GET the Patient then the ResourceType role will be GET_PATIENT.
    - [ ] Search for the ResourceType role on the `realm_access.roles` array. If the role is found then give access to the request. If the role is not found return a 403 error. 

**Acceptance Criteria**
- [x] The code should be able to get the roles from the Access token. 
- [ ] Should be able to validate the permissions and either allow the request to pass or return a 403 error if the permission can't be validated. 

**More information on why we need to make this change**
- https://github.com/opensrp/fhircore/discussions/1603

**Comment by rehammuzzamil** [comment]
**LOE: 2 days**

- [ ] To clean up code on the draft PR.
- [ ] Handle cases for all resource types and HTTP Methods. 
- [ ] Update Http Status Code to 403 instead of 401 in case access is denied.
- [ ] Add unit tests.

_Note: LOE is specified for a PR submission for an initial review._
cc: @dubdabasoduba  @ekigamba  @f-odhiambo

**Comment by ndegwamartin** [comment]
I think we’ll need some additional time to implement this fully, currently we have the implementation ready for `HTTP GET`, `HTTP DELETE` and `MANAGE_<RESOURCE>` for both GET & DELETE. Check out PR https://github.com/opensrp/fhir-access-proxy/pull/4

It gets a little complicated with the implementation of the (generic) POST and PUT requests which have various content passed as part of the requests that needs validation. Working on these next.

cc @rehammuzzamil @dubdabasoduba @f-odhiambo

**Comment by ndegwamartin** [comment]
Implemented permission checking for the **Bundle Resource** type as well. The Bundle resource can be POSTed with multiple resource entries that can be of different transaction types(POST, GET, DELETE, PUT). 

This is as defined in the [HL7 FHIR Bundle Spec here](https://www.hl7.org/fhir/bundle.html).

In this case we only support the _Transaction_ Bundle Type meaning we either grant access if all have access or deny if the permission check in any one of the the resources in the bundle fails.

cc @rehammuzzamil @dubdabasoduba

**Comment by dubdabasoduba** [comment]
> Implemented permission checking for the **Bundle Resource** type as well. The Bundle resource can be POSTed with multiple resource entries that can be of different transaction types(POST, GET, DELETE, PUT).
> 
> This is as defined in the [HL7 FHIR Bundle Spec here](https://www.hl7.org/fhir/bundle.html).
> 
> In this case we only support the _Transaction_ Bundle Type meaning we either grant access if all have access or deny if the permission check in any one of the the resources in the bundle fails.
> 
> cc @rehammuzzamil @dubdabasoduba

@ndegwamartin I think I am okay with this Plan. IS there a way to give the correct error messages with this? E.g let them know what resource permission failed in the bundle.

**Comment by ndegwamartin** [comment]
> > Implemented permission checking for the **Bundle Resource** type as well. The Bundle resource can be POSTed with multiple resource entries that can be of different transaction types(POST, GET, DELETE, PUT).
> > This is as defined in the [HL7 FHIR Bundle Spec here](https://www.hl7.org/fhir/bundle.html).
> > In this case we only support the _Transaction_ Bundle Type meaning we either grant access if all have access or deny if the permission check in any one of the the resources in the bundle fails.
> > cc @rehammuzzamil @dubdabasoduba
> 
> @ndegwamartin I think I am okay with this Plan. IS there a way to give the correct error messages with this? E.g let them know what resource permission failed in the bundle.

Yeah @dubdabasoduba we could, right now it returns after the very first failing resource - we could return that as part of the error. 

We can also take an extra performance hit to iterate over all the entries and get _all the resources_ that fail within the bundle, not sure if we want to do that.

**Comment by dubdabasoduba** [comment]
@ndegwamartin I agree with @pld Can we add the debug config in a way where we can turn it of an on in deployments. That way we can have it on for stage deployments. 

That means we don't add extra params to the requests.

**Comment by ndegwamartin** [comment]
@dubdabasoduba just to clarify, for the implementation of the above flag, do we want to add a Debug config to:

1. Configure returning the specific resource that violated the _Permission_ within the bundle
2. Configure returning all the resources that failed from within the bundle
3. Configure returning any type of information regarding the resources that violated a Permission in the FHIR proxy ([i.e. configure enabling this feature](https://github.com/opensrp/fhircore/issues/1665#issuecomment-1273276612) )

**Comment by dubdabasoduba** [comment]
@ndegwamartin I think we want te flag for number 2. 

My assumption is this is the piece that needs us to traverse the whole bundle and then return a 403 with the list of all Resource types and HTTP methods the user is not allowed to do. 

Number 3 Is the MVP for the error. We just let the user know that they can perform the HTTP method they want to because they don't have the rights.  I think what will happen in the bundle for this case it will return an error for every single request that fails then the users fix their roles and tries again. 

So number 3 goes to prod. Number 2 is only enabled for debugging.

**Comment by ndegwamartin** [comment]
@dubdabasoduba this was implemented by logging all the missing roles in the _POST bundle_ if one has set the `RUN_MODE` environment variable mentioned in the README here to **DEV**. This logic only kicks in in this mode otherwise for prod it returns immediately after the first failure.

**Comment by ndegwamartin** [comment]
@dubdabasoduba this was implemented by logging all the missing roles in the _POST bundle_ if one has set the `RUN_MODE` environment variable mentioned in [the README here](https://github.com/opensrp/fhir-access-proxy) to **DEV**. This logic only kicks in in this mode otherwise for prod it returns immediately after the first failure.
