### ISSUE TITLE
[Quest] Crash on getting practitioner details

### ISSUE THREAD

**Issue by maimoonak** [opensrp/fhircore#1666]
**Describe the bug**
Exception when fetching practitioner resource L#263 `practitionerDetails?.id`
```
MeasureReportViewModel: java.lang.RuntimeException: Unable to create instance of interface org.hl7.fhir.r4.model.EnumFactory. Registering an InstanceCreator or a TypeAdapter for this type, or adding a no-args constructor may fix this problem.
```

**To Reproduce**
1. Uncomment `practitionerDetails?.id` around L263
2. Run MeasureReport
3. Crashes with given exception

**Expected behavior**
Should not crash and fetch practitioner or return null

**Comment by dubdabasoduba** [comment]
@FikriMilano Wanna triage this?

**Comment by f-odhiambo** [comment]
@dubdabasoduba I think this is an issue on $evaluate `practitionerID`  input param CC @maimoonak

**Comment by ellykits** [comment]
I also think the measure report API currently works only with a null practitioner ID

**Comment by dubdabasoduba** [comment]
@ellykits @FikriMilano Did we fix this?

**Comment by dubdabasoduba** [comment]
@ellykits Can I close this issue?
