### ISSUE TITLE
[Quest] Data refresh not working on profiles

### ISSUE THREAD

**Issue by ellykits** [opensrp/fhircore#1667]
**Describe the bug**
Data not refreshing on profile especially after 

**To Reproduce**
1. Go to 'family profile (ecbis flavor)'
2. Click on 'add member'
3. Fill in questionnaire and submit 
4. You will be taken to family profile but new record for the registered family member is not displayed

**Expected behavior**
On load new content, profile screen should be updated

**Additional context**
Profile data should be refreshed after every action

**Comment by f-odhiambo** [comment]
I think this is a duplicate ticket to this https://github.com/opensrp/fhircore/issues/1446 @ellykits . We can close one
