### ISSUE TITLE
[Quest] Remove sync from Profile page 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1671]
**Name of feature to enhance**
Remove the sync menu items from users profile page

**Description of feature**
N/A

**Describe the enhancement**
Sync should be either trigger from the Navigation menu or Bottom nav and not in the Logged in users profile

**Wrong Position** 
<img src="https://user-images.githubusercontent.com/4540684/191261255-05627376-70f8-4740-bce4-fc76b8edbf47.png" width="200" height="400" />
**Correct Postion** 
<img src="https://user-images.githubusercontent.com/4540684/191261266-e37362ee-152d-4036-a381-a67ab11985b2.png" width="200" height="400" />

**Comment by dubdabasoduba** [comment]
Changed the approach to Comment out the piece of code showing the sync button but leave the code there for future use.
