### ISSUE TITLE
[Quest/Malawi Core] Wrong patient menu items being rendered

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#1694]
**Describe the bug**
In a patient's profile, the wrong menu items are being rendered in the overflow menu.

**To Reproduce**
1. Go to the patient's register
2. Select an ART client
3. In their profile, check the options in their overflow menu

**Expected behavior**
Currently, these are the options shown:
![Screenshot_20220927-151139_Tingathe](https://user-images.githubusercontent.com/90775548/192536453-bda57067-17b2-40c6-b0ec-3c8e606b8d9b.jpg)

I expect these options:
![Screenshot_20220927-145205_Tingathe](https://user-images.githubusercontent.com/90775548/192536529-1f3ea926-59d0-4479-9861-30ac421e15ca.jpg)

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
N/A

**Comment by AbdulWahabMemon** [comment]
fix and merged, 
@f-odhiambo
