### ISSUE TITLE
[Quest] Allow completion of Overdue Tasks

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1697]
**Enhancement context**
- We currently don't allow the completion of Overdue Tasks. 
- We would like to update this functionality to allow Overdue Tasks to be completed. 

**Implementation**
- [ ] Allow clicking on the Overdue Tasks and launching the Questionnaires tied to the Task. 

**Acceptance Criteria**
- [ ] Overdue tasks should be clickable.

**Comment by dubdabasoduba** [comment]
@f-odhiambo I am going to mark this as blocked because it will only be relevant once the actually tasks generation has been updated.

**Comment by dubdabasoduba** [comment]
Depends on:  https://github.com/opensrp/fhircore/issues/1696

**Comment by owais-vd** [comment]
closing as it's completed

**Comment by f-odhiambo** [comment]
Reported regression

What we have
`if (buttonEnabled && (status == ServiceStatus.DUE || clickable)) {`
This fix is missing
` if (buttonEnabled &&   (status == ServiceStatus.DUE || status == ServiceStatus.OVERDUE || clickable)) { '
