### ISSUE TITLE
[Client side] After adding new Household cannot showing at all household list

### ISSUE THREAD

**Issue by mahmud6390** [opensrp/fhircore#1705]
**Describe the bug**
After adding one household without member it's can't showing at all household list screen. But it's increase the count at navigation menu.Also at navigation menu total count not showing at household list window only 8 count showing but at navigation menu it's showing 19. 

**To Reproduce**
1. Go to 'Add household'
2. Click on 'save'
3. All household list showing
4. Not showing the saved household
5. Go to navigation menu it's showing count increase
6. Search with name now can see
7. All household register list only showing 8 count but in navigation it's showing 19

**Expected behavior**
It should be update the household list

**Screenshots**
<img src="https://user-images.githubusercontent.com/2793306/192954290-127adec2-ee17-4971-b63e-479692e5e4b1.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/2793306/192954300-bbe16b1d-fae2-4da4-a72e-83c9d608a40c.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/2793306/192954306-6ab37fbf-e097-47cf-a9b3-a34ad6e29c02.png" width="200" height="400" />

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**
app id : app/debug
branch: main

**Comment by ellykits** [comment]
We noted this bug @mahmud6390. Thanks for creating this issue.

**Comment by ellykits** [comment]
We confirmed the data is indeed saved to the DB. Issue could probably be related to the filtering of Group resources.

**Comment by mahmud6390** [comment]
seems it's fixed at latest main branch
