### ISSUE TITLE
[Quest] Publish a new version of the SDK with the calculated Expressions PR merged

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1723]
**Describe the Issue**
- Please merged the following PRs and publish SDK snapshots
    - [x] https://github.com/google/android-fhir/pull/1377
    - [x] https://github.com/google/android-fhir/pull/1380
    - [x] https://github.com/google/android-fhir/pull/1656

**Comment by ndegwamartin** [comment]
A migration to the FHIR SDK artifacts

```
Engine - 0.1.0-beta02-preview4-SNAPSHOT
SDC - 0.1.0-beta05-preview4-SNAPSHOT
Workflow - 0.1.0-alpha02-preview3-SNAPSHOT
Common - 0.1.0-alpha03-preview4-SNAPSHOT
Contrib - 0.1.0-beta3-preview3-SNAPSHOT
```

**Comment by f-odhiambo** [comment]
Issue has been completed
