### ISSUE TITLE
[Sender] Update the P2P sending data UI and workflow

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1728]
**Context**
- We have revised the P2P UI and customer flow. We would now like to implement the new changes to the current library. 
- Here is the full workflow definition. This issue is concerned with the sender pieces of the workflow. 
![Screenshot from 2022-10-11 10-51-04](https://user-images.githubusercontent.com/4817531/195072130-40085646-2384-4620-b21c-dc2a957a50e8.png)

**Implementation**
- [ ] Update the P2P landing screen to match the screen on the mockup
    - [x] Add the App TopBar to match the UI in the screenshot below
    - [x] Add the **Send Data** and **Receive Data** buttons.
![Share data](https://user-images.githubusercontent.com/4817531/195073231-9f4c4b3d-2cc1-4ed7-965e-f4f9f802fef0.png)
- [ ] On clicking the Send Data the following should happen. 
    - [x] The app should launch the search bottom sheet. This show follows the designs shown below.  
    - [x] Clicking **Pair** should initiate a pairing request with the selected device. 
![Screenshot from 2022-10-11 22-12-58](https://user-images.githubusercontent.com/4817531/195207820-db8822a4-abb5-421e-a80e-0b17560898f6.png)
- [ ] After pairing the following screens should show
    - [ ] Show a screen to tell the user that data receiving preparations are going on. This is shown in image 1 of the mockups below. 
    - [ ] Show a screen displaying the sync progress. This is shown in image 2 of the mockups below. 
        - [ ] This screen should also have a cancel button.  When clicked the following should happen.  
            - [ ] A confirmation dialog should load for the user to confirm whether they want to stop the sync. If the user clicks `Yes, Exit` to the confirmation dialog we proceed to stop the sync. Below is a sample dialog mockup. 
![dialog](https://user-images.githubusercontent.com/4817531/195210350-586d4e5c-9339-4581-9754-6726f5b2a195.png)
    - [x] Show success when the sync is complete. This is shown on screen 3 of the mockups below. 
![Screenshot from 2022-10-11 22-22-49](https://user-images.githubusercontent.com/4817531/195209969-11ea7706-c4ad-4280-a405-85b08ceec50c.png)
- [ ] In case the connection breaks for any given reason the screen below should be shown to the user. 
![Share data (5)](https://user-images.githubusercontent.com/4817531/195210167-2c2e03ea-3974-4e16-9985-95297a848f33.png)

**Acceptance criteria** 
- [ ] The new UI/UX should match the mockups provided. 
- [ ] The **Send Data** button should perform as narrated above.

**Comment by AnnieMungai** [comment]
v.0.1.8 - preview

- [ ] When trying to pair 2 devices - Blue G60, the connection was difficult to find and had to tried numerous times with different tests - the connection that worked was tapping receive on the supervisor device before pressing send data on the CHA app.
- [ ] Once the connection was established between the 2 devices, the CHA device read it was waiting to send data and the supervisor device was waiting to receive data. However, the CHA app force-closed before it could send the data. 
Restarting the CHA app while offline was successful, however, pressing on 'Send data' again gave the message 'waiting to receive data' - which is incorrect after pressing 'Send data'. 

https://user-images.githubusercontent.com/58034047/208728109-d46edd2b-4522-4b8b-a472-0a54d5b055cf.mp4


- [ ] The 2 devices did not disconnect at all and remained connected (I checked wifi settings >> wifi direct >> remembered groups. Manual disconnection from the wifi settings disconnected the 2 devices. 
![1671556568344](https://user-images.githubusercontent.com/58034047/208727978-86609f87-8e8b-4f39-bde1-5276359d65dd.jpg)

- [ ] When forgot the remembered groups and restarted the process, the 2 devices established connection and opened the waiting to receive/send data page, however, app on both devices force-closed at this point.

https://user-images.githubusercontent.com/58034047/208728021-d145cbfc-29f0-4db3-a95b-62423da455b1.mp4


- [ ] Data transfer was not successful at any given point.

**Comment by ekigamba** [comment]
@dubdabasoduba I noticed that the apps on the video device is using different logins for CHA & CHSS. Can you kindly share these and any other ECBIS specific configurations

**Comment by ekigamba** [comment]
There is a regression bug in the code that causes nearby Wifi direct devices not to be listed. The p2p features works on an older version of p2p. 
I'll be investigating what the specific bug is and fix it

**Comment by ekigamba** [comment]
### Remaining issues

- [ ] If you send p2p successfully once, then try again, the app crashes with the last exception as an NPE from java.lang.String java.net.InetAddress.getHostAddress(). The original error is that the socket was still attached. I'll need to close the socket once sending is done. I'll need to test if this error also happens when an exception occurs during sending/receiving and you start the p2p back up again
- [ ] Resuming and sending remaining records when transfer is interrupted or cancelled. Currently, it shows that records were sent
- [ ] If a socket exception occurs due to cancellation on one device, the other device is handling the cancellation but it might not be disabling wifi-direct. It shows busy, it might be that the crashing device did not close gracefully
- [ ]  Blank screen after sending/receiving and closing the complete info dialogs
- [ ]  Release the address and port after syncing fails or the it completes
    - [ ]  `java.net.BindException: bind failed: EADDRINUSE (Address already in use)`
- [ ]  During pairing, when the device name is long, it obscurs the pair button at the right
- [ ]  The apps acts weirdly if the you start p2p while the device are already connected
- [ ]  If the device process crashes or is switched and you reopen the p2p activity, it disconnects any ongoing connection and then show the sync complete dialog org/smartregister/p2p/search/ui/p2p/P2PViewModel.kt:147
- [ ]  A bug on Android FHIR SDK that does not remove previous search indexes therefore causing a bug on FHIR Core P2P
    - [ ]  Sending tasks for a device was sort of stalling because of the multiple indexes per task eg 44-144 indexes per task
- [ ]  If you connect to a different device by mistake it neither rejects nor approves, P2P searching fails and reports that it’s busy. Manually rejecting an invitation fixes the issue
- [ ]  As the sender is waiting for the connecting to be accepted, it force-closes because of an NPE
    
    ```java
    FATAL EXCEPTION: DefaultDispatcher-worker-5
    Process: org.smartregister.fhircore.ecbis, PID: 8185
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.getHostAddress()' on a null object reference
    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy.getGroupOwnerAddress(WifiDirectDataSharingStrategy.kt:352)
    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy.access$getGroupOwnerAddress(WifiDirectDataSharingStrategy.kt:53)
    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$send$1.invokeSuspend(WifiDirectDataSharingStrategy.kt:290)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@54e5064, Dispatchers.IO]
    ```
    
- [ ]  The sender device always shows “Pairing” after a failed pairing session and force-closing the app

**Comment by ekigamba** [comment]
@Rkareko Kindly test the socket closing and disconnection after an exception. I tend to get a p2p BUSY error or an `EADDRINUSE` exception on this commit [opensrp/p2p@`d199779` (#59)](https://github.com/opensrp/p2p/pull/59/commits/d199779b529970b389435e29132915e6f4178344)

**Comment by madrinekariuki** [comment]
test devices:
 samsung A12 android 11
oppo A3s 8.1.0

Observations:
 1. app not installing in some android versions. e.g `android version 7.1 `, we get the error, `there was a problem parsing the package`
2. when you try to send from the `chss` logged in device.  click on transfer, then click back to load the menu bar and then you click on transfer again, it keeps loading on` waiting to pair` and no transfer happens. See attached screenshot.

4. Transfer from the `cha`  logged device to the `chss` logged device is transferring successfully.

4 **sometimes** we are not sending data ,it loads  and then eventually says "disconnected" and then gives a notification of '`0 records sent successfully ' `and no data is transferred. see screenshot below


**2.**
![image](https://user-images.githubusercontent.com/84722169/213119052-39099c20-9e1d-441f-a216-9fc99814ac8b.png)


**4**
![image](https://user-images.githubusercontent.com/84722169/213117819-3f2be91a-c6c0-4e63-8fb9-fcbc05b61c16.png)

**Comment by Rkareko** [comment]
> 4. sometimes we are not sending data ,it loads and then eventually says "disconnected" and then gives a notification of '0 records sent successfully ' and no data is transferred. see screenshot below

@HenryRae cc @AnnieMungai @dubdabasoduba  @ekigamba How would the UI/UX look like when there are no records to be sent?

**Comment by Rkareko** [comment]
> During transfer, the phones image icon is not showing in the background its just blank.(This is in reference to the image designs shown in the thread above)

@madrinekariuki kindly show the mock up you are referring to for this section

**Comment by HenryRae** [comment]
> > 4. sometimes we are not sending data ,it loads and then eventually says "disconnected" and then gives a notification of '0 records sent successfully ' and no data is transferred. see screenshot below
> 
> @HenryRae cc @AnnieMungai @dubdabasoduba @ekigamba How would the UI/UX look like when there are no records to be sent?

@Rkareko can you please describe all cases we might have 0 records sent?
- is it that user-initiated transfer but there were 0 records to transfer? or
- is it when user pairs devices, and they eventually get disconnected for some reason?

**Comment by madrinekariuki** [comment]
@HenryRae 

> can you please describe all cases we might have 0 records sent?
> 
> is it that user-initiated transfer but there were 0 records to transfer? or
> is it when user pairs devices, and they eventually get disconnected for some reason?

The first prompt to send data is successfully sending data. however, consequent efforts to connect and send data(without adding new data  or even when you add new data) is when we get the message or we get an app crash. 
(This is after clicking on pair on both devices, the transfer device is the one with the disconnected prompt message and the receiver device goes back to the send and receive data page)

cc @Rkareko

**Comment by HenryRae** [comment]
okay, I think if there's no new data to sync with the other device, it should be communicated that "no new data to sync" or "synced data is up to date" on both devices. Is this something we are able to know?
@Rkareko 
cc: @madrinekariuki

**Comment by AnnieMungai** [comment]
@HenryRae  we should have 2 specific use cases:
1. When the CHA and CHSS data match up - in this case there will be no new records to transfer. 
2. When the devices disconnect without completing the data transfer. User should clearly be told the connection was lost without the data transfer having completed.

**Comment by HenryRae** [comment]
@AnnieMungai I've covered those cases here.

1. When the CHA and CHSS data match up. - no new records to sync with recipient
2. When the transfer gets cancelled - transfer is not complete because the sender or recipient cancelled the transfer
3. When the devices get disconnected and transfer gets cancelled - transfer is not complete because the devices got disconnected.

<img width="1157" alt="Screenshot 2023-01-26 at 14 01 06" src="https://user-images.githubusercontent.com/31955469/214819963-d0610866-b230-4057-b957-212f1c6186de.png">

cc: @madrinekariuki @Rkareko @rowo

**Comment by dubdabasoduba** [comment]
@f-odhiambo Closing this issue since the implementation was completed
