### ISSUE TITLE
[Receiving] Update the P2P receiving data UI and workflow

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1729]
**Context**
- We have revised the P2P UI and customer flow. We would now like to implement the new changes to the current library. 
- Here is the full workflow definition. This issue is concerned with the sender pieces of the workflow. 
![Screenshot from 2022-10-11 10-51-04](https://user-images.githubusercontent.com/4817531/195072130-40085646-2384-4620-b21c-dc2a957a50e8.png)

**Implementation**
- [ ] Update the P2P landing screen to match the screen on the mockup
    - [x] Add the App TopBar to match the UI in the screenshot below
    - [x] Add the **Send Data** and **Receive Data** buttons.
![Share data](https://user-images.githubusercontent.com/4817531/195073231-9f4c4b3d-2cc1-4ed7-965e-f4f9f802fef0.png)
- [x] On clicking the **Receive Data** the following should happen. 
    - [x] The app should launch the search bottom sheet. This show follows the designs shown below.  
![Share data (4)](https://user-images.githubusercontent.com/4817531/195208967-cb681ee9-8153-4ecd-a308-8b96925fd9e0.png)
- [ ] After pairing the following screens should show
    - [x] Show a screen to tell the user that data transfer preparation is ongoing. This is shown in image 1 of the mockups below. 
    - [x] Show a screen displaying the sync progress. This is shown in image 2 of the mockups below. 
        - [x] This screen should also have a cancel button.  When clicked the following should happen.  
            - [x] A confirmation dialog should load for the user to confirm whether they want to stop the sync. If the user clicks `Yes, Exit` to the confirmation dialog we proceed to stop the sync. Below is a sample dialog mockup. 
![dialog](https://user-images.githubusercontent.com/4817531/195210350-586d4e5c-9339-4581-9754-6726f5b2a195.png)
    - [ ] Show success when the sync is complete. This is shown on screen 3 of the mockups below. 
![Screenshot from 2022-10-11 22-33-52](https://user-images.githubusercontent.com/4817531/195210651-d9e97241-a969-404c-9d96-203ae489f829.png)
- [x] In case the connection breaks for any given reason the screen below should be shown to the user. 
![Share data (5)](https://user-images.githubusercontent.com/4817531/195210167-2c2e03ea-3974-4e16-9985-95297a848f33.png)

**Acceptance criteria** 
- [ ] The new UI/UX should match the mockups provided. 
- [ ] The **Receive Data** button should perform as narrated above.

**Comment by madrinekariuki** [comment]
@AnnieMungai 

test devices:
samsung A12 android 11
oppo A3s 8.1.0

see below observations on the receiver device.
1.  when transferring data, the transfer is happening successfully the first time, then consecutively it keeps crashing or showing `'0 records sent successfully' 'connection was disconnected'` on the send device, while on the receive device, keeps loading on waiting to pair, the eventually goes back to the send/receive data tab (see attached videos.)

2. From the mock up designs, during transfer, we should have image of the phones in the background as the data transfer is happening, this is currently not the case.

Others:
The app is crashing, when filling some forms e.g register pregnancy, there are some unresponsive radio buttons, and  when you click on them, the app crashes.

https://user-images.githubusercontent.com/84722169/213141260-57c94ab0-27d7-4f17-afeb-e6ef3067f01c.mp4


https://user-images.githubusercontent.com/84722169/213141298-f8dcee18-ccc7-45c7-a796-2ee2be686492.mp4

**Comment by f-odhiambo** [comment]
Closing this as the Roadmap item related to this has been closed

**Comment by AnnieMungai** [comment]
Closing ticket as arising issues are on a different ticket.
