### ISSUE TITLE
[In-App Reporting] Create an interface to consume and render  a bundle config that comprises of Indicators for each reporting module 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1757]
**Is your feature request related to a problem? Please describe.**
As an implementor, we need to find a way in which we can be able to bundle various indicators into modules and then render them on the UI for user selection. This should be done in a configurable way as some indicators are not necessarily grouped as modules as is in the case for LMH eCBIS 

**Example 1 -   LMH eCBIS Indicators bundled into modules ** 
**Module 1  - Routine household visits** 
> 1. Births (community/home)
> 2. Births (facility)
> 3. Stillbirths
> 4. Neonatal deaths
> 5. Post-neonatal deaths
> 6. Child deaths
> 7. Maternal deaths
> 8. Community triggers
> 9. Deaths > 5 years (community/home)

**Module 2 - RMNH**
> 1. Pregnant women visits
> 2. Referred for delivery
> 3. Referred for ANC
> 4. Postnatal visits
> 5. Referred for danger signs
> 6. HBMNC within 48 hours: Mother
> 7. HBMNC within 48 hours: Infant
> 8. Clients currently using modern FP

**Example 2 - WHO SMART DAK ANC Indicators  - No module** 
1. ANC-IND-01  - Percentage of pregnant women with first ANC contact in the first trimester (before 12 weeks of gestation) 
2. ANC-IND-02  - Percentage of pregnant women who received iron and folic acid (IFA) supplements for 90+ days 
3. ANC-IND-03  - Percentage of pregnant women screened for syphilis during ANC 
4. ANC-IND-04  -  Percentage of pregnant women with at least four ANC contacts 
5. ANC-IND-05  - Percentage of pregnant women with a minimum of eight antenatal care contacts 
6. ANC-IND-06  - Pregnant women who received counselling on danger signs (%) during at least one ANC contact 
7. ANC-IND-07  - Percentage of pregnant women with at least one blood pressure measure during ANC 
8. ANC-IND-08  - Percentage of pregnant women with at least one blood pressure measure in the third trimester during ANC 
9. ANC-IND-09  - Percentage of pregnant women whose baby’s heartbeat was listened to at least once during ANC 
10. ANC-IND-10  - Percentage of pregnant women with an ultrasound scan before 24 weeks 
11. ANC-IND-11  - Percentage of women who received three doses or more of intermittent preventive therapy for malaria (IPTp) during their last pregnancy  
12. ANC-IND-12  - Percentage of pregnant women counselled and tested for HIV 
13. ANC-IND-13  - Percentage of pregnant women who received oral pre-exposure prophylaxis (PrEP) 

**Describe the solution you'd like**
The Initial interface should show a listing of the different modules as depicted in the mock or just show a list of indicators if the indicators are not grouped into modules. 

**Screenshot of mock** 
<img width="200" height="400"  alt="Screenshot 2022-10-21 at 10 37 37 AM" src="https://user-images.githubusercontent.com/4540684/197140340-f756c15f-cc18-470e-93ce-4b5b7a17054e.png">

**Additional context**
We could write a config as described below to sync and render the above list as shown in the code snippet below 

```json
...
"reports": {
    "Household": [
		{
			"id": "1",
			"title": "ANC-IND-01 ",
			"description": "ANC-IND-01  - Percentage of pregnant women with first ANC contact in the first trimester (before 12 weeks of gestation) ",
			"url": "http://fhir.org/guides/who/anc-cds/Measure/HOUSEHOLDIND01"
		},
		{
			"id": "2",
			"title": " Births (facility)",
			"description": "Number of  Births at a facility",
			"url": "http://fhir.org/guides/who/anc-cds/Measure/HOUSEHOLDPREGNANCY"
		}
    ],
    ...
}
```
or just a list of indicators if not grouped into a module as

```json
...
"reports":  [
		{
			"id": "1",
			"title": "ANC-IND-01 - Pregnancy Trimetster 1 ",
			"description": "Number of Births in the community or recorded at Home",
			"url": "http://fhir.org/guides/who/anc-cds/Measure/HOUSEHOLDIND01"
		},
		{
			"id": "2",
			"title": " ANC-IND-02 - Folic Acid Deficiency",
			"description": "Percentage of pregnant women who received iron and folic acid (IFA) supplements for 90+ days",
			"url": "http://fhir.org/guides/who/anc-cds/Measure/HOUSEHOLDPREGNANCY"
		}
    ]
    ...
}
```

NB. We shall have a config to let the app know if our preferred mode of report generation is manually invoked or periodically done via scheduled work manager 

This can take the following approach 
**Scheduled approach** 

- [x] 1. Based on this approach we shall be generating MeasureReports in  the background based on the https://github.com/opensrp/fhircore/issues/1798
- [ ] 2. Query each MeasureReport (Indicator) and add it to a list as described above based on the period 
- [ ] 3. Pass the List to the reporting interface 

**Manual generation** 

- [x] 1. Select the Module of interest (Aggregated Indicators)
- [x] 2. Select the period 
- [x] 3. Invoke $evlaute_measure to generate each Indicator in the selected module and desired period (start date & end date)
- [x] 4. Add the results  of each indicator to a list as described above based on the period 
- [x] 5. Pass the List to the reporting interface

**Comment by f-odhiambo** [comment]
**Clarification required** 
1. Do we need to show what indicators comprise of each module ?

**Comment by pld** [comment]
Note that the format of these indicators is different now, there's no JSON, it's bundles of Measures (I think?)

**Comment by f-odhiambo** [comment]
Done
