### ISSUE TITLE
Filter patients whose second dose is overdue 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#176]
Ability to use a toggle filter to query and fetch all patients who have missed their second shot and are overdue for the second dosage of the vaccine. 
Screenshot attached. This should only return results of all patient who have an  overdue status without the need to search 

<img width="415" alt="Screen Shot 2021-05-28 at 12 54 21 PM" src="https://user-images.githubusercontent.com/4540684/119966367-e95a6a00-bfb3-11eb-82b5-9e84ae29a3ca.png">

<img width="415" alt="Screen Shot 2021-05-28 at 12 56 49 PM" src="https://user-images.githubusercontent.com/4540684/119966758-4d7d2e00-bfb4-11eb-85cd-ef8eb439562b.png">

**Some assumptions** 
1. Create a new patient on the registration page
2. Go to the profile page to record the first dose of the vaccine 
3. On record first dose, use current date as a start date when you received the 1st shot 
4. We shall use a 3-week window as the due date of the 2nd shot
5. On load patient list, if within the range before due date, show the user when you are due for the next shot, else show overdue status
6. Inpatient profile show when you were supposed to have received the 2nd shot - see screenshot. Label marked in red if overdue

<img width="733" alt="Screen Shot 2021-05-28 at 1 08 16 PM" src="https://user-images.githubusercontent.com/4540684/119968204-da74b700-bfb5-11eb-91bb-90b39e753e5a.png">

**Comment by f-odhiambo** [comment]
Added some QA check on this issue #195 cc @syedowaisali90

**Comment by pld** [comment]
it the case of covax it's not really overdue, but eligible, the restriction is more to not get the 2nd shot too early

**Comment by f-odhiambo** [comment]
What's window of duration should we use as a trigger ? e.g. 3 weeks cc.@pld

**Comment by pld** [comment]
﻿
We want to configure that with a fhir resource, we could hardcore 5 weeks for now but in reality it'll depend on the vaccine

**Comment by pld** [comment]
Need to cherry-pick from this branch to close this issue, https://github.com/opensrp/fhircore/pull/240

**Comment by f-odhiambo** [comment]
This implementation will need to be redone as it does not cater for dynamic editing of resources i.e it sets initial values against each question explicitly as opposed to doing it dynamically for each and every question , which would best require writing code only once based on @MuhammadSalman-7214 PR here https://github.com/google/android-fhir/pull/536

cc @pld @MuhammadSalman-7214 @ekigamba

**Comment by f-odhiambo** [comment]
cc @ndegwamartin

**Comment by f-odhiambo** [comment]
This feature is missing on the main branch
