### ISSUE TITLE
[Sync Strategies] Fix the resource tagging functionality

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1778]
**Describe the bug**
- We tag resources with practitioner's details in order to facilitate the sync of data down to the applications. 
- We have a couple of bugs with this sync piece i.e
- [ ] Currently, the sync strategies are read from the `gradle` files. This means if someone wanted to change the sync strategies they would have to generate a new APK. 
- [ ] Currently, the code tags resources based on the `syncStrategy` configuration  on `application_config.json`. i.e if the config has `Location` & `Organization` then it will tag the resources with the 2. If we only have the `Location` then it will tag the resources with the `Location` only. 

**Expected behavior**
- [x] All the resources should always be tagged by all 4 tags (Practitioner, Organization, CareTeam & Location). The `syncStrategy` configuration on the `application_config.json` should only be used for sync filtering.  e.g if you have the `Location` on the syncStrategy then the filter will use the practitioner Location to sync data down to the app.
- [x] The sync strategies should always be defined on the `application_config.json`

**Comment by FikriMilano** [comment]
I need time to revert it back from `build.gradle` to `application_config.json`
Will most likely write a new code

**Comment by FikriMilano** [comment]
@dubdabasoduba 
I refactored the tagging so that it will always be appended, not depending on sync strategy.
If an Organization / CareTeam / Location / Practitioner ID is somehow not defined in Practitioner Details, by default it will append "Not defined"

**Comment by FikriMilano** [comment]
Currently refactoring the sync strategy to go back to application config
