### ISSUE TITLE
[Remote Sync] Fix resources sync to the server. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1787]
**Technical implementation specific**
- [ ] Sync all the data found on the Local SQLite DB to the FHIR server when sync is automatically or manually triggered. 
- [ ] Confirm that QRs are correctly tagged based on this [issue](https://github.com/opensrp/fhircore/issues/1509). 

**NB: -** This issue does not need to handle sync down to the server since the [Remote Sync](https://github.com/opensrp/fhircore/issues?q=is%3Aissue+is%3Aopen+label%3A%22Remote+Sync%22) issues defined here will adress that.

_Originally posted by @dubdabasoduba in https://github.com/opensrp/fhircore/issues/1460#issuecomment-1275404837_

**Comment by dubdabasoduba** [comment]
@FikriMilano Please add the LOE on this

**Comment by dubdabasoduba** [comment]
@FikriMilano not really, this issue is to refactor sync to the server to sync all resources. We do not want to filter data synced to the server. We only want to filter data synced from then server

**Comment by FikriMilano** [comment]
Ah ok, you mean like, syncing the latest update from local DB to the server

**Comment by FikriMilano** [comment]
_Confirm that QRs are correctly tagged based on this issue._

I think this point can be solved by the resource tagging. Whatever resource, it will be tagged when inserted to the local DB.

If we do this point, then it's just repeating the same thing.

@dubdabasoduba

**Comment by dubdabasoduba** [comment]
> _Confirm that QRs are correctly tagged based on this issue._
> 
> I think this point can be solved by the resource tagging. Whatever resource, it will be tagged when inserted to the local DB.
> 
> If we do this point, then it's just repeating the same thing.
> 
> @dubdabasoduba 

@agreed! That point is more of a confirmation that the tagging is happening correctly
