### ISSUE TITLE
[App Configuration] Add sorting to the different List views

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1789]
**Name of feature to enhance**
- We have a couple of list views on the app the main ones being the registers and tasks lists on the app.
- The ability to sort them using a couple of resource attributes will be key for optimizing the UX.

**Description of feature**
- [ ] Add the ability to sort the different resources in a list based on certain attributes of the resources in question. 
    - [ ] We will support 2 sorting functionalities Ascending and Descending e.g [A-Z, 0-9] or [Z-A, 9-0]

**Describe the enhancement**
- [ ]  Ordering the resources in a list in Ascending or Descending order based on certain resource attributes.

**Comment by f-odhiambo** [comment]
**How would this tackle give a use case?**
1. Ascending/Descending by Given name
2. Ascending/Descending by Family name
3. Ascending/Descending by Registration date
4. Ascending/Descending by Last Encounter

**Would it be possible to** 
1. Allow the user to define a set of [name, query] pairs in an order key field in the config, where the query is defining the order, and have a convention for asc/desc, so we'd support asc/desc for every order query they define? 
2. How would we execute the above? What would be the structure of that config?

**Comment by f-odhiambo** [comment]
Blocker:  Need to check on wether to do a Sort from Db or to do it programmatically from code. TBD

**Comment by pld** [comment]
This will have to depend on how much data exists, but there'll definitely be a point when sort in code will be too slow, so I think regardless we have to do sort from DB.

Maybe later we could add an optimization where it sorts code if there are less than N elements, but if db queries are fast enough that won't be necessary.

**Comment by dubdabasoduba** [comment]
I agree with @pld supporting sorting from the DB based on the indexed attributes per resource (which I think are all the attributes. 
 I might need to confirm this) 

I think we can always review situations to filter or sort form code e.g We would need to sort the Groups by code if we wanted to sort or filter them by `name` since the `name` attribute is not an allowable search attribute for the Group. 

We already have sorted by some of these attributes and we are using ASC as the default sort order. The user can however decide to use a different sort like in this example. 

https://github.com/opensrp/fhir-resources/blob/273e5860d0ae710f4ea3ea45f324f68bbde69ebc/ecbis_liberia/app_configurations/ecbis_cha_preview/registers/household_register_config.json#L30-L36

**Comment by dubdabasoduba** [comment]
So I would say this issue has the following tasks. 

**Sort & FIlter from the DB**
- [ ] Write a generic filter function that can filter all the resources from the DB using the available indexes.  
- [ ] Write a generic sort function that can sort all the resources from the DB using the available indexes. 
- [ ] All the above methods should be triggered from the configs.  

**Sort and filter using code** - This can be a lower priority than the 2 above. 
- [ ] Write a function to filter and sort generic resources based on other attributes that are not indexed. 
    - This method should also be triggered from the configs.  


- NB we can decide to limit the above method to just a list of resources or we can leave it open and advise against using it because of the performance implications. 

@pld @f-odhiambo let me know what you think so I can extract the points above to individual issues that different people can pick up.

**Comment by pld** [comment]
Can we not do filter and sort for attributes that are not indexed? Is there a way to manually add an index? If you can do that, then we shouldn't need this, we just need docs that say, first add the index, then you can do the filter/sort

**Comment by dubdabasoduba** [comment]
@pld this is possible but I think we need to update the SDK so that it provides a way for implementors to easily define the extra attributes to cache.

We can also choose to add this to fhircore then make sure we maintain it.

**Comment by pld** [comment]
Ah ok yea that seems like a generally useful API feature to have: asking to index specific kvs

Is that something we need in the first version, like do we have known use cases where we'll want to filter or sort on an attribute that isn't indexed?

**Comment by dubdabasoduba** [comment]
We will need to sort Families (represented by the Group resource) using the name. The `name` attribute is not part of the searchable attributes of the Group resource.  

This means it's not indexed.

**Comment by pld** [comment]
OK, then this plan sounds good, we can add an issue for a create-index API to the Android FHIR SDK, and if we see queries on non-indexed fields going too slow maybe do that work in the SDK or in FHIRCore, depending on timing

**Comment by pld** [comment]
This seems like it will enable this functionality, https://github.com/google/android-fhir/pull/1778

**Comment by pld** [comment]
This test case seems like a good guide, https://github.com/aditya-07/android-fhir/blob/master/engine/src/test/java/com/google/android/fhir/MoreSearchParametersTest.kt

**Comment by ellykits** [comment]
We can close this issue. A separate GitHub issue can be created to track sorting _revinclude/forward included resources (the current workaround is to use RulesEngine sort functionality that leverages FHIRPath and Kotlin sort function). We partially support database sorting for base resources and code-level sorting that can be applied via Rules Engine.
