### ISSUE TITLE
[App Configuration] Move the download of the application specific resources  to the Composition resource. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1790]
**Name of feature to enhance**
- The Composition resource is used as the Application manifest. This means all the application-related configurations are supposed to be referenced here. 
- The download of these resources should only be triggered from this resource. 
- Right now we have some application-specific configs referenced on the `sync_config.json`.  We need to move these configurations and reference them on the Composition resource. 

**Description of feature**
- [x] Make sure the following resources can be downloaded from the composition resource reference, 
    - [x] Binary Resource. 
    - [x] Questionnaire Resource. 
    - [x] PlanDefinition Resource. 
    - [x] StructureMap Resource. 
    - [x] Library Resource. 
    - [x] Measure Resource. 

**Describe the enhancement**
- [x]  Ability to specify the resources mentioned above on the Composition Resource and download them for usage on the app. 
   - [x] This means removing the references on the `sync_config.json` and sill being able to download the resources since they are referenced on the  Composition resource.

**Comment by qaziabubakar-vd** [comment]
I have found and added these resources which are being synced using composition configs in the ecbis, the list is as follows:

**Questionnaires:** 

-  Add Family Member
- Add Family Member Confirmation
- Add Family
- Remove Family
- Remove Family Member
- New Pregnancy Registration
- Pregnancy Visit
- Pregnancy Outcome
- Sick child under 2 months
- Child Immunization Completion
- Sick child above 2 months
- Sick Child Follow Up
- Counter Referral
- New FP Registration
- FP Visit
- PNC Visit
- Under 2 Year Child Visit Form
- Over 2 Year Child Visit Form
- Diseases Registration Form
- Diseases Followup Form
- Household visit form
- Death Record Confirmation
- New FP Enrollment Confirmation
- New ANC Enrollment Confirmation
- Physical Inventory Count and Stock Supply
- Stock level adjustment by CHA

**Structure Maps:**

- Children Immunization
- Sick Child Registration
- Sick Child Follow Up Visit
- Child Counter Referral
- Child Monthly Routine Visit
- Family Registration
- Add Family Member Registration
- New Pregnancy Registration
- New Pregnancy Registration
- Pregnancy Referral
- Pregnancy Outcome Registration
- Normal Weight PNC Routine Visit
- Under Weight PNC Routine Visit
- PNC Referral
- FP Registration
- FP Visit
- FP Referral
- Diseases Registration
- Diseases Followup
- Diseases Referral

**Plan Definitions:**

- Household member plan definitions
- Record sick child plan definitions
- Record to ANC  plan definitions
- Pregnancy outcome plan definitions
- Diseases Registration Form plan definitions
- Enroll to family planning plan definitions

For these resources, even if the references for `Questionnaire`, `StructureMaps` and `PlanDefinition` is removed from the `sync config`, the app will be able to sync these resources using the composition configs.  
However, I wanted to ask if this list is complete or do I need to add more resources in the list, also for Library and Measure Resources, I need a list of all the resources that should be getting downloaded from the composition configs. 
If a list can be provided for all these different resources which are going to be used by a specific application (e.g. ecbis) then I can add them in our `composition_configs`

Note: I think in the future, the individual downloading of these resources might cause problems in managing them, I was wondering if there is a way of filtering out resources for a specific application, where we can link a resource to a specific application and using that reference we download the resources in `composition_configs`? Need some input on this.    

cc: @dubdabasoduba

**Comment by dubdabasoduba** [comment]
> Note: I think in the future, the individual downloading of these resources might cause problems in managing them, I was wondering if there is a way of filtering out resources for a specific application, where we can link a resource to a specific application and using that reference we download the resources in composition_configs? Need some input on this.   

Most of our production instances will not run multiple apps like our stage and preview servers do. However, we did have an idea of adding the app id to all the resources for a certain implementation. This is now paused based on the comment about prod instances running 1 implementation only. 


> I wanted to ask if this list is complete or do I need to add more resources to the list, also for Library and Measure Resources

From a product perspective, we don't have to update the resources the projects will use. We just need to make sure that if the resource types below are added to the config then they can be downloaded correctly. 

Please make sure the following resource types can be downloaded if referenced on the composition resoruce. 
    - [ ] Binary Resource. 
    - [ ] Questionnaire Resource. 
    - [ ] PlanDefinition Resource. 
    - [ ] StructureMap Resource. 
    - [ ] Library Resource. 
    - [ ] Measure Resource.

**Comment by dubdabasoduba** [comment]
@qaziabubakar-vd this is also an issue you can fix while testing this. https://github.com/opensrp/fhircore/issues/1814
