### ISSUE TITLE
[UX] UI for Tracing registers

### ISSUE THREAD

**Issue by LZRS** [opensrp/fhircore#1793]
**Name of feature to enhance**
New register screens for both _home_ and _phone tracing_

**Description of feature**
Create new UI screens for home and phone tracing 

![unnamed](https://user-images.githubusercontent.com/12814349/199174798-46d7b6c0-6e30-43f3-978e-6e4898739a8c.png)

**Describe the enhancement**

**Comment by pld** [comment]
closed in #1774
