### ISSUE TITLE
[Quest] Background Jobs initiated via scheduled jobs with WorkManager 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1798]
**Is your feature request related to a problem? Please describe.**
Add background tasks triggered based on a defined schedule 

**Describe the solution you'd like**
The background tasks should allow us to have the following 2 main use cases / sub-tasks 
1. #1701
2. #1703 
3. #1759 
4. #1800 

**Describe alternatives you've considered**
Implement WorkManager on FHIR Core  

**Additional context**
[WorkManager](https://developer.android.com/reference/androidx/work/WorkManager) is the recommended solution for persistent work. Work is persistent when it remains scheduled through app restarts and the system reboots. Because most background processing is best accomplished through persistent work, WorkManager is the primary recommended API for background processing.

WorkManager allows you to [schedule work](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/define-work) to run [one-time](https://developer.android.com/reference/androidx/work/OneTimeWorkRequest) or [repeatedly](https://developer.android.com/reference/androidx/work/PeriodicWorkRequest) using flexible scheduling windows. Work can be tagged and named as well, allowing you to schedule unique, replaceable work and monitor or cancel groups of work together.

WorkManager handles three types of persistent work:
1. Immediate: Jobs that must begin immediately and complete soon. May be expedited.
7. Long-Running: Jobs that might run for longer, potentially longer than 10 minutes.
8. Deferrable: Scheduled jobs that start at a later time and can run periodically.

**Comment by pld** [comment]
Cool, just to clarify, is this implementation supposed to be generic for any background process we wish to run? And then bg processing related to Tasks is an example of that?

**Comment by f-odhiambo** [comment]
> Cool, just to clarify, is this implementation supposed to be generic for any background process we wish to run? And then bg processing related to Tasks is an example of that?

This is spot on

**Comment by pld** [comment]
OK cool, I changed the wording above to replace "Task(s)" with "Job(s)" so that I don't confuse it with the Task resource :D
