### ISSUE TITLE
[Quest] Add scheduled background sync for FHIR Core 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1800]
**Name of feature to enhance**
Add Scheduled background Sync for FHIR Core 

**Description of feature**

1. The background sync can be triggered after the app has moved to the Background 
2. Scheduled at a specific time of day (Before CHW Beginning of Day  or After the End of Day)

**Describe the enhancement**
Can utilize part of the background task module described in #1798

**Pre-requisite task** 
1. #1798

**Comment by pld** [comment]
Ah cool, this is an example of why #1798 needs to be generic, this sounds like it should be blocked as dependent on completion of #1798 (or the subset of that issue that is for background job management in general vs related to running the background of jobs related to Tasks)

**Comment by f-odhiambo** [comment]
> Ah cool, this is an example of why #1798 needs to be generic, this sounds like it should be blocked as dependent on completion of #1798 (or the subset of that issue that is for background job management in general vs related to running the background of jobs related to Tasks)

This is correct. 
Seeking clarification on the configurability of this ticket,  I think the background task manager should be generic to add any function. This task is just a function to trigger Sync. What part of this should be generic? I may have missed something 

CC @pld @dubdabasoduba

**Comment by pld** [comment]
Yes that agrees w/my thinking, #1798 is generic, and this is blocked by that ticket
