### ISSUE TITLE
[Documentation] Adding a docusaurus deployment GitHub action

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1823]
**Is your feature request related to a problem? Please describe.**
- We would like to have clear document implementors' documentation for the FHIR Core product.  

**Describe the solution you'd like**
- [ ] Add the docusaurus GitHub action to deploy the FHIR Core documentation. 
    - The documentation to do this can be found [here](https://docusaurus.io/docs/deployment#deploying-to-github-pages)

**Acceptance criteria**
- [ ]  The FHIR core docusaurus should be set up correctly to allow the deployment of new documentation and design of the documentation site.

**Comment by SebaMutuku** [comment]
@dubdabasoduba @f-odhiambo do we have the FHIR-CORE documentation repo?

**Comment by f-odhiambo** [comment]
> @dubdabasoduba @f-odhiambo do we have the FHIR-CORE documentation repo or any gh-pages url?

This is what we have so far https://github.com/opensrp/fhircore/wiki , but no official hosting space for docs thus this task

**Comment by SebaMutuku** [comment]
@f-odhiambo what I got from the discussion is, this will be deployed to gh-pages and then the site is published to docusaurus. My undrstanding is,for you to deploy a page to gh-pages, you need a web app. Is this part of the issue or the web team already has the web-app ready?

**Comment by f-odhiambo** [comment]
> @f-odhiambo what I got from the discussion is, this will be deployed to gh-pages and then the site is published to docusaurus. My understanding is, for you to deploy a page to gh-pages, you need a web app. Is this part of the issue or does the web team already has the web app ready?

Here is a summary of our discussion 
1. Here is the link to the current docs https://github.com/opensrp/fhircore/tree/main/docs
2. We can use the gh-pages branch or docs folder above
3. Provide a docusaurus config or command to publish new changes

**Comment by pld** [comment]
from the docs it looked like we could deploy to gh-pages without a web app of our own (link in the original issue description), only using gh-pages, can you point to docs showing otherwise?

**Comment by SebaMutuku** [comment]
@pld @dubdabasoduba @f-odhiambo , 
Below is what I have been able to do. 
1. I am able to run the docs folder with docusaurus configs locally. (Tested with 3 .md files)
2.  Set up a workflow to deploy the site to gh-pages and runs without errors.  Link to the workflow is https://github.com/opensrp/fhircore/actions/runs/3470987337
However, seems gh-pages is already active and hosts https://fhircore.smartregister.org/
Can we deploy two pages from the same repo on gh-pages?
If not, we should choose a different hosting site.

**Comment by pld** [comment]
Ah yes good point, you can only generate a single gh-page site per repo. I think we should have the docusaurus configs take over gh-pages from the kotlin gend docs, we probably want the kotlin gend docs as a subsection of the docusaurus pages later on but for now you can have them push to another branch, like `dokka` instead of `gh-pages` and we'll come back to this.

You can leave docusaurus on the fhircore.smartregister.org URL, we'll change that later, I'll ask on slack about opinions on what url to use.

**Comment by pld** [comment]
@SebaMutuku can you push the branch you're working on pls?

**Comment by SebaMutuku** [comment]
app-configuration-docusaurus

**Comment by SebaMutuku** [comment]
@f-odhiambo it seems domain is blocking the docusaurus site hosted on https://smartregister.org/fhircore/. I have tested  the same configs and docs folder from my personal gh-pages and I am able to access the docusaurus site. Martin and I have also made a request to SRE [here](https://github.com/onaio/infrastructure/issues/6369).

**Comment by SebaMutuku** [comment]
@dubdabasoduba when I click on https://opensrp.github.io/fhircore it automatically redirects to https://fhircore.smartregister.org/. I have not control for now.

**Comment by dubdabasoduba** [comment]
> @f-odhiambo  @dubdabasoduba docusaurus site is live via this link https://fhircore.smartregister.org/

Good job! What did you change?

**Comment by SebaMutuku** [comment]
When I pushed docusaurus files into` gh-pages`, a file called `CNAME` which holds domain details was overriden or deleted. This was why we couldn't access the site via domain shared up there. To avoid this in the future, I will update the workflow to everytime copy CNAME into the ./build folder that contains files to be deployed into `gh-pages` and this will solve domain issues, I believe.
