### ISSUE TITLE
Convert gender question in the registration questionnaire from an input field to a radio button for gender selection 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#183]
Implement the select gender question as a select radio button as opposed to an input text. With default selection male. See attached screenshots 

Current implementation 
<img width="307" alt="Screen Shot 2021-05-31 at 12 12 31 PM" src="https://user-images.githubusercontent.com/4540684/120170482-abef1a00-c209-11eb-9879-e8b60aac4f2d.png">

Correct mock 
<img width="307" alt="Screen Shot 2021-05-31 at 12 12 31 PM" src="https://user-images.githubusercontent.com/4540684/120170360-8cf08800-c209-11eb-9527-5a8007bb5735.png">

**Comment by shoaibmushtaq25** [comment]
Related PR #199
