### ISSUE TITLE
[Quest] Update the PIN login to  Username/Password Login redirect workflow

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1844]
When a user tries to access the admin login page from the pin login page, they are redirected back to the pin login. 

https://user-images.githubusercontent.com/58034047/202740266-212d685d-14e1-45e5-b69a-9d5f2e66145e.mp4

**Acceptance criteria**
- [ ] When the user taps on the top right-hand menu from the pin login page, the menu displays `Admin login`. 
- [ ] Tapping on the `Admin login` redirects the user to the username/ password login screen. 
- [ ] From this screen, users should be able to enter their username and password to log in.
- [ ] This should happen when connected to the internet or while offline.

**Comment by dubdabasoduba** [comment]
@DebbieArita is this complete? If yes please close it.

**Comment by f-odhiambo** [comment]
Closed via #1857
