### ISSUE TITLE
[Quest] Update the sync timestamp every time sync is completed

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1846]
- [ ] For both the auto sync (every 15 minutes) and manual sync the timestamp does not update.
<img src="https://user-images.githubusercontent.com/58034047/202711280-b92ad00c-2e8b-40da-b1cd-31b8162d2ae4.jpg" width="200" height="400" />

**Acceptance criteria**
- When a user is connected to the internet, the time stamp should show the last time a sync was completed. 
- When a manual sync is triggered, the time stamp should update when the manual sync was completed. 
- If a user has been connected to the internet for more than 15 minutes, the sync should automatically trigger every 15 minutes, and update the time stamp to the last time sync was completed.

**Comment by qaziabubakar-vd** [comment]
This is dependent on an on-going ticket: https://github.com/opensrp/fhircore/issues/1864

**Comment by pld** [comment]
replaced by https://github.com/opensrp/fhir-resources/issues/520
