### ISSUE TITLE
[Quest] Provide error-handling if StructureMap extension is provided but the StructureMap resource is not available locally/not yet synced 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1849]
**Name of feature to enhance**
Provide error handling if StructureMap extension is provided but the StructureMap resource is not available locally/not yet synced

**Description of feature**
The app should not crash upon missing StrcutureMaps for the linked Questionnaire being populated before the extraction process 

**Describe the enhancement**
On submission of a populated Questionnaire
- [x] 1. Generate a QuestionnaireReponse 
- [x] 2. If a StrucutureMap is missing log this in-app for troubleshooting and also  alert the user of the issue

**Comment by pld** [comment]
If we show the error, does that mean the QuestionnaireResponse is saved but other resources are not extracted from it?

How do we end up in this situation? It sounds like we need more checks elsewhere to prevent this from being possible, I could imagine this causing a situation where entered form data is not properly captured.
