### ISSUE TITLE
[Quest] Cursor skipping back when typing in the username and password

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#1870]
**Describe the bug**
Cursor is skipping back letters/ numbers when typing in the username and password. 

**To Reproduce**
1. Open the app and navigate to the login page. 
2. Try add username and password - observe closely while doing this.  

**Expected behavior**
The cursor does not skip back when typing in the username and password. 

**Screenshots**

https://user-images.githubusercontent.com/58034047/205026618-b8b2b46e-60fb-4a93-a559-cef4bdb35f11.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Comment by AnnieMungai** [comment]
Requires a new release

**Comment by AnnieMungai** [comment]
Test with 01.8

**Comment by NaveenZehra11** [comment]
LGTM


https://user-images.githubusercontent.com/90256461/210058833-8ba8e6ec-1f07-4ebf-b9de-6b98b1dee96c.mp4

app Deatil : https://github.com/opensrp/fhircore/releases/tag/v0.1.8-ecbis-rc1
APK environment = Preview
App ID = cha
username = ecbis
cc @AnnieMungai

**Comment by abbeyseto** [comment]
> LGTM
> 
>  simplescreenrecorder-2022-12-30_15.07.52.mp4 
> 
> app Deatil : https://github.com/opensrp/fhircore/releases/tag/v0.1.8-ecbis-rc1 APK environment = Preview App ID = cha username = ecbis cc @AnnieMungai

Please which password are we supposed to use to log in to this apk releases?
