### ISSUE TITLE
[Human Readable IDs] Generate random Human readable IDs and pass them to the forms for usage | MVP

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1882]
**Feature Context**
- OpenSRP maintains a list of unique human-readable IDs assigned to different clients for identification. 
- We want to build an MVP for this on FHIR core. This initial piece will look at generating a set of numbers that can be read by health practitioners to identify the patients. 
- We will then use the generated number on the forms by passing it as follows https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/assets/configs/app/profiles/inventory_profile_config.json#L159-L174

**Feature Implementation**
- [ ] In the [RulesFactory](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt) Class, write a method that generates a set of whole numbers (min 6).
- [ ] This method should accept a parameter that describes the length of the number.  If the parameter is not available, generate a number with a length of 6. 

**Feature acceptance criteria** 
- [ ]  The method should be able to be called from the configuration rules.  
- [ ] The method should generate numbers with the specified length or a min length of 6 when the length is not user specified.

**Comment by f-odhiambo** [comment]
More context here https://github.com/opensrp/fhircore/discussions/872

**Comment by pld** [comment]
what does min 6 mean? If I pass a parameter saying I want an ID of length 4, will it 1) throw an error 2) give me back an ID of length 6, 3) give me an ID of length 4?

**Comment by pld** [comment]
I'm not sure from a crypto perspective, or from performance perspective, whether it's better to generate (for example in the length 6 case wlog) 1 random number from 0 to 999999 or to generate 6 random numbers from 0 to 9 then concatenate them.

Maybe it doesn't matter, but if we go with the former approach we need to make sure to pad the returned value with 0s so it's of a length six.

Which leads to another question, is the return type a string? That's what I assumed since IDs are normally strings, but the issues says "a number"

**Comment by dubdabasoduba** [comment]
> what does min 6 mean? If I pass a parameter saying I want an ID of length 4, will it 1) throw an error 2) give me back an ID of length 6, and 3) give me an ID of length 4?

@pld great questions. To guarantee some sort of uniqueness. Without 0 and repeats the total of 6-digit numbers is 9^6 

I think we can allow any size when we build the full feature that accounts for more uniqueness. 

I am tempted to say we can remove the ability for the user to define the number size.

**Comment by dubdabasoduba** [comment]
> I'm not sure from a crypto perspective, or from performance perspective, whether it's better to generate (for example in the length 6 case wlog) 1 random number from 0 to 999999 or to generate 6 random numbers from 0 to 9 then concatenate them.
> 
> Maybe it doesn't matter, but if we go with the former approach we need to make sure to pad the returned value with 0s so it's of a length six.
> 
> Which leads to another question, is the return type a string? That's what I assumed since IDs are normally strings, but the issue says "a number"

@pld probably a small tweak of the second approach might it faster. We already know the least 6-digit number we can get between 0 - 9999999 is 100000. We can then just write a method to generate a random number between 100000 & 999999

The OpenSRP ID on the forms expects a number.  Based on this I think it's appropriate to return an integer.

**Comment by pld** [comment]
> > what does min 6 mean? If I pass a parameter saying I want an ID of length 4, will it 1) throw an error 2) give me back an ID of length 6, and 3) give me an ID of length 4?
> 
> @pld great questions. To guarantee some sort of uniqueness. Without 0 as the first digit and any repeats, the total of 6-digit numbers is 9*10^5
> 
> I think we can allow any size when we build the full feature that accounts for more uniqueness.
> 
> I am tempted to say we can remove the ability for the user to define the number size.

Alright cool, so for now, no selection of length, this is to generate a six digit integer randomly chosen from the interval [100,000, 999,999]

**Comment by ndegwamartin** [comment]
Perhaps we could try a _Hybrid Approach_ that involves both the Client and the Server and is hopefully _simple, efficient and guarantees uniqueness_. 

See my suggested approach in [the discussion here](https://github.com/opensrp/fhircore/discussions/872#discussioncomment-4349941)

**Comment by ndegwamartin** [comment]
Perhaps we could try a _hybrid approach_ that involves both the Client and the Server and is hopefully _simple, efficient and guarantees uniqueness_. 

See my suggested approach in [the discussion here](https://github.com/opensrp/fhircore/discussions/872#discussioncomment-4349941)

**Comment by ndegwamartin** [comment]
Perhaps we could try a **hybrid approach** that involves both the Client and the Server and is hopefully _simple, efficient and guarantees uniqueness_. 

See my suggested approach in [the discussion here](https://github.com/opensrp/fhircore/discussions/872#discussioncomment-4349941)

**Comment by pld** [comment]
Yeah we'll do that in a follow up, out of scope for this issue
