### ISSUE TITLE
[Authentication] Update Logout flow when PIN Login is configured/or not

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1883]
**Feature Context**
Update the current Logout from the app flow so that the user is able to easily enter back into the application post-logout if PIN authentication is configured or not 

**Feature Implementation**
See the current proposed flow 
![Flow chart ](https://user-images.githubusercontent.com/4540684/206255734-5a15c333-53db-4ab3-aa12-ad8a47cc9955.png)

NB. Editable [link](https://docs.google.com/drawings/d/1pgHQza5uMhlrnk0GNEqdac7_1t86Gg-gNEvZ449A9r8/edit?usp=sharing) to the above flow chart

**Feature acceptance criteria** 
- [ ] **PIN was configured**: Take the user to enter their 4 Digit PIN
- [ ] **PIN was not configured**  : Take the user to enter their username and password

**Comment by pld** [comment]
does this mean that if PIN login is enable the user is requred to set a PIN? That's what diagram implies

**Comment by ellykits** [comment]
@f-odhiambo I do not quite understand the logout flow from the diagram.

**Comment by ellykits** [comment]
Every time the user logs out, the access token is deleted and the session is also deleted from keycloak. If the user attempts to use the app after a successful logout, they will be prompted to enter their username and password regardless of whether pin is enabled or not. The user cannot get an access token just with the pin.

**Comment by ellykits** [comment]
The user should only provide their credentials in the following scenarios:
1. The very first time they login to the app
2. When both access token and refresh token have expired and the application cannot automatically refresh the token 
3. Session delete via keycloak after a succesful logout forcing a new login

**Comment by dubdabasoduba** [comment]
> Every time the user logs out, the access token is deleted and the session is also deleted from keycloak. If the user attempts to use the app after a successful logout, they will be prompted to enter their username and password regardless of whether pin is enabled or not. The user cannot get an access token just with the pin.

I don't think this support offline login then does it?

**Comment by dubdabasoduba** [comment]
> The user should only provide their credentials in the following scenarios:
> 
> 1. The very first time they login to the app
> 2. When both access token and refresh token have expired and the application cannot automatically refresh the token
> 3. Session delete via keycloak after a succesful logout forcing a new login

@ellykits I think these are the scenarios we need to account for. 
1. Initial login (username & password) this needs you to be online. 
2. If the PIN is enabled then Set Up the PIN and redirect to the main register.  
3. All subsequent Logins should be able to support offline login.  
    - This means the username & password should still allow the user to log in when offline and it should maintain the session and use the refresh token functionality to refresh it if the token is expired and the device is online.  
4. When the user clicks logout the following things should happen. 
    - If the PIN login is not enabled then we should redirect the user to the Login page but maintain the session data & authentication data to allow subsequent offline logins.  
    - If the PIN login is enabled & set then we redirect to the PIN login page but maintain the session data & authentication data to subsequent offline logins with username & password if we need to.

**Comment by dubdabasoduba** [comment]
@allan-on please test if this is fixed in your PR https://github.com/opensrp/fhircore/issues/1907

**Comment by allan-on** [comment]
> @allan-on please test if this is fixed in your PR #1907

@dubdabasoduba I tested this from the emulator and a Samsung device and I believe it's been resolved. The app doesn't crash on offline login using a set PIN

**Comment by allan-on** [comment]
From further conversations on the workflows, it was decided the changes should factor in that the app is offline first.

- Currently logging out requires the user to be online so that they’re logged out of Keycloak as well. A failure to make this request to Keycloak means the user isn’t logged out and the Login screen isn’t shown → This will be updated to logout and show the Login screen even when the request fails
- We’ll not delete the session tokens (`localLogout`). We’ll rely on renewal of tokens implementation to renew tokens if expired on subsequent logins
