### ISSUE TITLE
[FHIR web Related] Create an endpoint to fetch all root locations

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#189]
- **Root locations**  -- These are the topmost locations in any hierarchy. Currently, the assumption is any locations without the `partOf` attribute are root locations

**What's required**
- [ ] Add an endpoint to return all the root locations in the FHIR server.

**Comment by pld** [comment]
I don't think this is a fhircore issue, isn't this about the Hapi server?

**Comment by f-odhiambo** [comment]
> I don't think this is a fhircore issue, isn't this about the Hapi server?

I think let's track this here for now

**Comment by dubdabasoduba** [comment]
> I don't think this is a fhircore issue, isn't this about the Hapi server?

Yes, it is about hapi. @f-odhiambo where do we track HAPI related issues

**Comment by f-odhiambo** [comment]
Yes. Let's track this track issues #188 & #189 here

**Comment by rehammuzzamil** [comment]
Hi, As per my findings here are my thoughts:

1. To find root locations, we can also utilize the `type` field in the FHIR Location entity. By definition:
```
shortDefinition = "Type of function performed",
formalDefinition = "Indicates the type of function performed at the location."
```
 It's an array, so we could add one of the entries inside this field as `root` and can get all root locations using this end-point
`http://localhost:8080/fhir/Location?type=root`

For instance, if we get another use case in the future to store type as UC, District, Commune, etc we can add as it's an array, I have tested it by setting one of the locations as `District` and `root` both and fetched that location via this end-point:
`http://localhost:8080/fhir/Location?type=root,District`

2. The other option could be to utilize extensions but FHIR does not allow searching via extensions and it throws the following exception:
`Valid search parameters for this search are: [_id, _language, _lastUpdated, address, address-city, address-country, address-postalcode, address-state, address-use, endpoint, identifier, name, near, operational-status, organization, partof, status, type]"
`
If we want to go with this approach, additional code logic needs to be added.

3. For the `partOf` field I have explored the code and it works well when we add a correct reference like `Location/54.` It searches correctly and fetches that record only based on the request param supplied. But if we try to pass `null` it treats it as a String hence does not bring the correct result. There is a validation written inside the class `IdHelperService` that checks if id has a valid idPart, if not it throws an exception.  I believe the logic is centralized for all the resource providers as it will be called when creating a predicate. Since `partOf` is of `Reference` dataType it verifies that the id part can not be null.

4. If we go with the extension of LocationResourceProvider class i.e. creating a new end-point, we may need to change the partOf data type. But this needs to be verified.
More code level changes will be required in this approach.

@dubdabasoduba Can you please share your thoughts on this?
 cc : @f-odhiambo  @maimoonak

**Comment by pld** [comment]
Thanks Reham, using a `type` sounds like a good solution.

As you've described it, the inability to query on a null value sounds like a general limitation for any resource, is that correct? Can you ask on the FHIR Zulip about this? It would be interesting to see what other people in the FHIR community do about this.

Another option, would be to have a "root" location that all the literally root locations set as their partOf, then instead of querying for a null partOf we query for a root partOf.

I could see this potentially reduces the complexity since we could avoid type queries and only use partOf queries when looking through the hierarchy, but I'm not sure, I imagine it will depend on other factors.

**Comment by rehammuzzamil** [comment]
Yes @pld  as per my understanding, the validations on the request parameters are centralized and thus apply to all the resources. I will confirm and take the opinion from the FHIR Community as well. 

For the second option, from a high level, this also seems a valid solution.  @dubdabasoduba  can you please share your thoughts on the solutions discussed above?

**Comment by dubdabasoduba** [comment]
> Thanks Reham, using a `type` sounds like a good solution.
> 
> As you've described it, the inability to query on a null value sounds like a general limitation for any resource, is that correct? Can you ask on the FHIR Zulip about this? It would be interesting to see what other people in the FHIR community do about this.
> 
> Another option, would be to have a "root" location that all the literally root locations set as their partOf, then instead of querying for a null partOf we query for a root partOf.
> 
> I could see this potentially reduces the complexity since we could avoid type queries and only use partOf queries when looking through the hierarchy, but I'm not sure, I imagine it will depend on other factors.

@pld I agree with using the `partOf` queries. QQ to see if I get the default location idea. 
- Create a location that is maybe named `Root OpenSRP Location`, this will also be created as a migration during deployment. 
- Then all locations that have this location's location id/uuid on the part of is treated as the root location? 

If that's the case I am on board with this.

**Comment by pld** [comment]
Yea exactly that

**Comment by dubdabasoduba** [comment]
@rehammuzzamil Do you think you have enough to proceed? If not please let me know so that we can look at it together and iron out the requirements

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil Do you think you have enough to proceed? If not please let me know so that we can look at it together and iron out the requirements

@dubdabasoduba  I believe with the approach discussed above, we can go with the existing end-point. There is no need of creating a new end-point.

**Comment by dubdabasoduba** [comment]
> > @rehammuzzamil Do you think you have enough to proceed? If not please let me know so that we can look at it together and iron out the requirements
> 
> @dubdabasoduba I believe with the approach discussed above, we can go with the existing end-point. There is no need of creating a new end-point. I can share a payload for a root location which we can post to the Hapi FHIR server. Then all the literal root locations should be a `partOf` this root location.

- I guess my questions would be, do we want to let the web handle the functionality to derive the root locations. I would rather we have an endpoint that actually gives out an array response for these root locations. 

@pld @ndegwamartin @ekigamba @maimoonak any thoughts?

**Comment by rehammuzzamil** [comment]
@dubdabasoduba  We can get the array of root locations by using the end-point` http://localhost:8080/fhir/Location?partof=153`
where` partof=153` is the **id** of the root location. In this case, the server can set up a "_root_" location that all the literally root locations set as their `partOf` from the web by setting the `partOf` param in the payload to the id of the root location created by the server. 

Here is a sample response: 
```

{
    "resourceType": "Bundle",
    "id": "84df4cd4-539f-4287-9e3d-49273146b792",
    "meta": {
        "lastUpdated": "2021-07-27T12:49:29.134+05:00"
    },
    "type": "searchset",
    "total": 2,
    "link": [
        {
            "relation": "self",
            "url": "http://localhost:8080/fhir/Location?partof=153"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://localhost:8080/fhir/Location/155",
            "resource": {
                "resourceType": "Location",
                "id": "155",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2021-07-27T12:49:09.481+05:00",
                    "source": "#R5OGJqOGW1JXhjCL"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "93bc9c3d-6321-41b0-9b93-1275d7111114e22"
                    }
                ],
                "status": "active",
                "name": "Ona Office Sub Location with partof",
                "alias": [
                    "ona office 1"
                ],
                "description": "The Sub location where the ona office is located",
                "type": [
                    {
                        "coding": [
                            {
                                "system": "level",
                                "code": "root",
                                "display": "Jurisdiction"
                            },
                            {
                                "system": "type",
                                "code": "District",
                                "display": "Jurisdiction"
                            }
                        ]
                    }
                ],
                "physicalType": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
                            "code": "jdn",
                            "display": "Jurisdiction"
                        }
                    ]
                },
                "partOf": {
                    "reference": "Location/153"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "http://localhost:8080/fhir/Location/154",
            "resource": {
                "resourceType": "Location",
                "id": "154",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2021-07-27T12:49:08.368+05:00",
                    "source": "#6RKeT5SmDIwFrHMm"
                },
                "identifier": [
                    {
                        "use": "official",
                        "value": "93bc9c3d-6321-41b0-9b93-1275d7111114e22"
                    }
                ],
                "status": "active",
                "name": "Ona Office Sub Location with partof",
                "alias": [
                    "ona office 1"
                ],
                "description": "The Sub location where the ona office is located",
                "type": [
                    {
                        "coding": [
                            {
                                "system": "level",
                                "code": "root",
                                "display": "Jurisdiction"
                            },
                            {
                                "system": "type",
                                "code": "District",
                                "display": "Jurisdiction"
                            }
                        ]
                    }
                ],
                "physicalType": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
                            "code": "jdn",
                            "display": "Jurisdiction"
                        }
                    ]
                },
                "partOf": {
                    "reference": "Location/153"
                }
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}
```

cc : @pld  @maimoonak

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba We can get the array of root locations by using the end-point` http://localhost:8080/fhir/Location?partof=153`
> where` partof=153` is the **id** of the root location. In this case, the server can set up a "_root_" location that all the literally root locations set as their `partOf` from the web by setting the `partOf` param in the payload to the id of the root location created by the server.
> 
> Here is a sample response:
> 
> ```
> 
> {
>     "resourceType": "Bundle",
>     "id": "84df4cd4-539f-4287-9e3d-49273146b792",
>     "meta": {
>         "lastUpdated": "2021-07-27T12:49:29.134+05:00"
>     },
>     "type": "searchset",
>     "total": 2,
>     "link": [
>         {
>             "relation": "self",
>             "url": "http://localhost:8080/fhir/Location?partof=153"
>         }
>     ],
>     "entry": [
>         {
>             "fullUrl": "http://localhost:8080/fhir/Location/155",
>             "resource": {
>                 "resourceType": "Location",
>                 "id": "155",
>                 "meta": {
>                     "versionId": "1",
>                     "lastUpdated": "2021-07-27T12:49:09.481+05:00",
>                     "source": "#R5OGJqOGW1JXhjCL"
>                 },
>                 "identifier": [
>                     {
>                         "use": "official",
>                         "value": "93bc9c3d-6321-41b0-9b93-1275d7111114e22"
>                     }
>                 ],
>                 "status": "active",
>                 "name": "Ona Office Sub Location with partof",
>                 "alias": [
>                     "ona office 1"
>                 ],
>                 "description": "The Sub location where the ona office is located",
>                 "type": [
>                     {
>                         "coding": [
>                             {
>                                 "system": "level",
>                                 "code": "root",
>                                 "display": "Jurisdiction"
>                             },
>                             {
>                                 "system": "type",
>                                 "code": "District",
>                                 "display": "Jurisdiction"
>                             }
>                         ]
>                     }
>                 ],
>                 "physicalType": {
>                     "coding": [
>                         {
>                             "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
>                             "code": "jdn",
>                             "display": "Jurisdiction"
>                         }
>                     ]
>                 },
>                 "partOf": {
>                     "reference": "Location/153"
>                 }
>             },
>             "search": {
>                 "mode": "match"
>             }
>         },
>         {
>             "fullUrl": "http://localhost:8080/fhir/Location/154",
>             "resource": {
>                 "resourceType": "Location",
>                 "id": "154",
>                 "meta": {
>                     "versionId": "1",
>                     "lastUpdated": "2021-07-27T12:49:08.368+05:00",
>                     "source": "#6RKeT5SmDIwFrHMm"
>                 },
>                 "identifier": [
>                     {
>                         "use": "official",
>                         "value": "93bc9c3d-6321-41b0-9b93-1275d7111114e22"
>                     }
>                 ],
>                 "status": "active",
>                 "name": "Ona Office Sub Location with partof",
>                 "alias": [
>                     "ona office 1"
>                 ],
>                 "description": "The Sub location where the ona office is located",
>                 "type": [
>                     {
>                         "coding": [
>                             {
>                                 "system": "level",
>                                 "code": "root",
>                                 "display": "Jurisdiction"
>                             },
>                             {
>                                 "system": "type",
>                                 "code": "District",
>                                 "display": "Jurisdiction"
>                             }
>                         ]
>                     }
>                 ],
>                 "physicalType": {
>                     "coding": [
>                         {
>                             "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
>                             "code": "jdn",
>                             "display": "Jurisdiction"
>                         }
>                     ]
>                 },
>                 "partOf": {
>                     "reference": "Location/153"
>                 }
>             },
>             "search": {
>                 "mode": "match"
>             }
>         }
>     ]
> }
> ```
> 
> cc : @pld @maimoonak

I agree. let's mark this as done. I had completely forgotten about this.

**Comment by dubdabasoduba** [comment]
Create the default locations payload then we can document it somewhere @rehammuzzamil

**Comment by rehammuzzamil** [comment]
> Create the default locations payload then we can document it somewhere @rehammuzzamil

Sure. Thanks!

**Comment by rehammuzzamil** [comment]
**Sample payload for root location:** 

```
{
  "resourceType": "Location",
  "status": "active", 
  "name": "Root OpenSRP Location",
  "alias": [
    "root location"
  ],
  "description": "An imaginary root location to which all the literal root locations set as their partOf",
  "partOf": {
      "reference": ""
  },
  "identifier": [
		{
			"use": "official",
			"value": "93bc9c3d-6321-41b0-9b93-1275d7114e21" 
		}
	],
  "physicalType": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
        "code": "jdn",
        "display": "Jurisdiction"
      }
    ]
  }
}
```

@dubdabasoduba Please have a look. Thanks!

**Comment by dubdabasoduba** [comment]
> **Sample payload for root location:**
> 
> ```
> {
>   "resourceType": "Location",
>   "status": "active", 
>   "name": "Root OpenSRP Location",
>   "alias": [
>     "root location"
>   ],
>   "description": "An imaginary root location to which all the literal root locations set as their partOf",
>   "partOf": {
>       "reference": ""
>   },
>   "identifier": [
> 		{
> 			"use": "official",
> 			"value": "93bc9c3d-6321-41b0-9b93-1275d7114e21" 
> 		}
> 	],
>   "physicalType": {
>     "coding": [
>       {
>         "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
>         "code": "jdn",
>         "display": "Jurisdiction"
>       }
>     ]
>   }
> }
> ```
> 
> @dubdabasoduba Please have a look. Thanks!

This is now tracked here https://github.com/opensrp/fhircore/issues/443
