### ISSUE TITLE
Patient Registration

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#19]
User story : 
As a CHW, I want to register a patient so that they can be enrolled on the platform.
The patient details will be based on the FHIR resource as a  [Questionnaire](https://www.hl7.org/fhir/questionnaire-example.json.html)
Acceptance criteria : 
- [x] On the landing page, you can view a list of already enrolled patients on the platform. 
- [x] The patient list should show details of the patient (ID, Firstname, Lastname, Gener, DOB)
- [x] Click on the add patient button to be presented with a form to fill in patient details. 
- [x] On clicking a patient you can view the patient profile ([details here](https://github.com/OpenSRP/fhircore/issues/22))

This is a subtask of https://github.com/OpenSRP/fhircore/issues/51

**Comment by f-odhiambo** [comment]
User story : 
As a user, I want to register a patient and add their details to the system.

Acceptance criteria : 

- [ ] On the landing page, you can view a list of already enrolled patients on the platform. 
- [ ] The patient list should show details of the patient (ID, Firstname, Lastname, Gener, DOB)
- [ ] On clicking a patient you can view the patient profile (details here)

Click on the add patient button to be presented with a form to fill in patient details. 

- [ ] The patient details will be based on the patient FHIR resource questionnaire
- [ ] Validate details as entered by the user for data types and  also mandatory/optional fields
- [ ] Provide an option to save the response  which will be saved as an FHIR QuestionnaorResponse 
- [ ] If there is an error, prompt the user with an error notification or with a success notification upon successful submission

**Comment by vincent-karuri** [comment]
@Andati @f-odhiambo there are quite a few things to implement for this feature. Is it possible to come up with a flow to bring better visibility to what portions are being worked on at a particular time e.g. create a sub-issue(s) from the list to be tracked as part of a milestone?

**Comment by jingtang10** [comment]
This draft PR: https://github.com/google/android-fhir/pull/326 handles the extraction to create a `Patient` resource from a `QuestionnaireResponse`.

**Comment by vincent-karuri** [comment]
@f-odhiambo I think this is done?

**Comment by f-odhiambo** [comment]
Moved this issue to done. Will close after review
