### ISSUE TITLE
[Offline Login] App force closes on offline login

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1907]
App version 0.1.7- preview
Phone: Grandblue G6
When trying to log in while offline - the app is giving an error in configs and then force closing after I enter the pin. 

https://user-images.githubusercontent.com/58034047/207848949-81615310-6a50-4bbd-9c0a-cb0ec9501a53.mp4

**Acceptance criteria**

- [ ] User should be able to log in while offline. 
- [ ] While offline and for subsequent logins - the user should be redirected to the pin login page (not the username/password page).

**Comment by allan-on** [comment]
I tested this from the emulator and a Samsung device and I believe it's been resolved. 
The app doesn't crash on offline login using a set PIN

**Comment by pld** [comment]
Can you add some additional testing around this?

**Comment by f-odhiambo** [comment]
Assigning @allan-on to this. You can tag the open PR to this ticket to close it too

**Comment by dubdabasoduba** [comment]
Closing this.  Since the attached PR fixes it. https://github.com/opensrp/fhircore/pull/1898
