### ISSUE TITLE
Trigger the `FhirTaskPlanWorker` every time tasks are generated

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1909]
**Describe the bug**
- The `FhirTaskPlanWorker` is currently used to update the Tasks status.  It's however set up to run after login or after 12 hours
https://github.com/opensrp/fhircore/blob/a4d32256f35a550af303f23f7a577b783db18453/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt#L310-L325. 
- This means the users don't immediately see the ready or overdue Tasks when they are created. 

**Bug Fix implementation**
- [ ]  The `FhirTaskPlanWorker` should be called immediately after a CarePlan & Tasks are generated. This will set the correct status once the Tasks are created. 
    - [ ] This should only be triggered when the CarePlan and Tasks are generated successfully.   

**Bug fix Acceptance Criteria**
- [ ] Relevant Tasks should be marked as ready immediately they are created.

**Comment by owais-vd** [comment]
As we don't need to run this `FhirTaskPlanWorker` periodically and we need to run only when `CarePlan` is generated so could we move the body of this work in a normal method instead of creating a work task? @ellykits @f-odhiambo @dubdabasoduba

**Comment by pld** [comment]
Some tasks states will change based on the expiration date being reached, or a task may be generated based on a patient being a certain age. Without running it periodically how we will we detect when those conditions are met?

**Comment by owais-vd** [comment]
Task expiration work is running separately in [FhirTaskExpireWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireWorker.kt) periodically and now the task generation will execute every time whenever the care plan will be generated but i think we can also run a [FhirTaskPlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt) on every 12 hours just like we have previously. cc: @pld @dubdabasoduba

**Comment by pld** [comment]
Yeah agreed, please update the PR to reflect this

**Comment by owais-vd** [comment]
PR updated
