### ISSUE TITLE
[Geo-widget] Bug on adding and viewing point on a Map 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1914]
**Describe the bug**
Ability to add points on a map and be able to click on them to view more details (i.e. Family profile)
1. The Location permission doesn't seem to work well on Android API 31 and above thus one cannot initiate the map module from the navigation drawer  - screenshot shared below
2.  On reloading the map the different added points on the map are not persisted once you reload the map view

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Navigation drawer 
2. Clip on the map module  - Maps
3. Click and add a point on a maps
4. Error described above will occur depending on the device and API level it's using

**Expected behaviour**

1. Launch the Map module from the navigation drawer 
5. You will get a map view that will have either prepopulated points on a map as markers or none if it's a 1st-time launch 
6. There will be a floating action button with a plus sign (+) to be able to add a point 
7. On click, you can be able to scroll and move the cursor to a point of interest, Once settled on a point you can add a family, click DONE
8. A registration form will be launched and you will be prompted to complete it 
9. Once done you should see the new point added on a map 
10. On relaunch of the map view, all previously added points should be visible and clickable to take you to the family profile 

**Screenshots**

1. Permission Issue on Android version 13  - There seems to be no way to enable storage permissions on this API level. For some reason, the location permission is enabled but no option for storage permissions 

**Android 8.1.0**
<img src="https://user-images.githubusercontent.com/4540684/208391142-e50cc4d3-a239-4a5c-b4c7-c2566bb84746.jpg" width="200" height="400" />

**Android 13**

<img src="https://user-images.githubusercontent.com/4540684/208375461-523ebe7c-b047-47f1-8e9a-e2a2a1643ae3.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/4540684/208391159-4bbfba9d-208e-457b-9c11-3d4ff6d41e2a.png" width="200" height="400" />

**Smartphone (please complete the following information):**
 - Device: Pixel 4a Emulator 
 - Android version:  13

**Smartphone (please complete the following information):**
 - Device: Pixel 4a physical device 
 - Android version: 13
 - Build number: TQ1A.221205.011

3. Bug with adding/viewing points on a map 

https://user-images.githubusercontent.com/4540684/208388612-b66574bd-b9bd-42d7-91b9-599630ad8b0b.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A (2016) physical device 
 - Android version: 8.1.0
 - Build number: M1AJQ.P585JXS3CTL1

**Additional context**
1. Added the latest configs to the eCBIS Preview server so it may be prudent to update the local.properties configs to point to it and be able to reproduce the bug 
2. Pull from  `master` to update the geo-widget app variant with the latest changes with bug fixes and enhancements on Sync, Registers and profiles

**Comment by ekigamba** [comment]
- The generated location and family are not linked together and therefore when you open the map you cannot view the previously registered families
- The structure-map does not seem to have changed
- The questionnaire seems to be OK
- The questionnaire response is missing the location id

**Comment by ekigamba** [comment]
### Findings

- The bug was introduced in this [PR](https://github.com/OpenSRP/fhircore/pull/1636). It also disables the population functionality introduced into FHIR Core
