### ISSUE TITLE
Allow inclusion of Resources that are not related to the Patient or other baseResource

### ISSUE THREAD

**Issue by roywanyaga** [opensrp/fhircore#1924]
**Name of feature to enhance**

- [ ] Profile Configuration
- [ ] Register Configuration

**Description of feature**
On both the Profile and Register Configurations, all resources are queried based on the linkage to one primary resource. 
e.g. 
On a patient profile, the main Resource is the Patient. Condition, CarePlan, and Task resources whose subject is the reference to the Patient Resource are fetched as relatedResources.

> ```
>   "fhirResource": {
>     "baseResource": {
>       "resource": "Patient"
>     },
>     "relatedResources": [
>       {
>         "resource": "Condition",
>         "searchParameter": "subject"
>       },
>       {
>         "resource": "CarePlan",
>         "searchParameter": "subject"
>       },
>       {
>         "resource": "Task",
>         "searchParameter": "subject",
>         "sortConfigs": [
>           {
>             "paramName": "period",
>             "dataType": "DATE"
>           }
>         ]
>       }
>     ]
>   },
> ```

**Describe the enhancement**

This enhancement is to allow the inclusion of other resources that may not be related to the primary resource. 
An example would be the inclusion of commodity resources in the patient profile config.

**Proposed Approach**

include an `otherResource` attribute in the config that allows for an array of objects similar to the `fhirResource` object:

> ```
>   "otherResources": [
>     {
>         "baseResource": {
>           "resource": "Group"
>         },
>         "relatedResources": [
>           {
>             "resource": "Observation",
>             "searchParameter": "subject"
>           }
>         ]
>       }
>     ]
> ```

**Comment by pld** [comment]
Can you explain the use case where you'd want to show commodities in the patient's profile?

**Comment by roywanyaga** [comment]
> Can you explain the use case where you'd want to show commodities in the patient's profile?

@pld For the supply chain use case, the data would not be on the profile's UI; but we would need to load the commodity data(mostly the commodity balance) within the profile's context in order to avail it on the service Questionnaires that are launched from the profile.

**Comment by pld** [comment]
Can we have the baseResource be the Group to do that?
