### ISSUE TITLE
Downgrade AndroidX Test Espresso to v3.4.0

### ISSUE THREAD

**Issue by allan-on** [opensrp/fhircore#1932]
Our CI checks when PRs are raised are failing with the `CI / geowidget-tests` check being cancelled after running for some time.
With the current Espresso v3.5.0,  `connectedDebugAndroidTest` task that's executed when the GitHub CI runs the GeoWidget instrumented tests, fails to complete and the CI job is cancelled after a long while. 
This in turn prevents the code coverage from being reported. 

Reverting back to the previous **v3.4.0** allows the tests to run to completion and code coverage is reported. This can be done as a temporary fix prior to determining why instrumented tests in the GeoWidget module aren't executed with the latest version of Espresso

**Comment by pld** [comment]
Cool, I think this answers a question I had on a PR that did this downgrade, k, let's get this in through the linked PR then rebase over it on others
