### ISSUE TITLE
Deprecate FHIRCore CustomPhotoCapture widget

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#1955]
**Describe the Issue**
Safely deprecate CustomPhotoCapture in favor of the SDK Attachment widget.

The Android FHIR SDK has added support for [Attachment widget](https://github.com/google/android-fhir/pull/1680), it's features are:
- More file types supported: image, document, audio and video files
- Can limit file size
- Can upload image from camera
- Can upload file from Android File Selector
- More enhancement coming 
  - UI https://github.com/google/android-fhir/issues/1796 
  - Multi attachment https://github.com/google/android-fhir/issues/1797
  - OOM preventation for large file https://github.com/google/android-fhir/issues/1858

The FHIR Core CustomPhotoCapture widget is essentially an attachment widget but it only support uploading image from camera.
https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/CustomPhotoCaptureFactory.kt

**Comment by FikriMilano** [comment]
Also, make sure the data capture dependency are up to date and has the new Attachment widget

**Comment by FikriMilano** [comment]
cc @f-odhiambo

**Comment by FikriMilano** [comment]
Kindly also manually test all Questionnaires that uses this widget, including those from our clients. Make sure it all works.

@f-odhiambo can help collecting which Questionnaires to test

**Comment by f-odhiambo** [comment]
Closed via #2098
