### ISSUE TITLE
Add risk assessment questionnaire in Covax app

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#196]
Enable segmenting users by “at-risk” and “not at risk” for severe illness from COVID-19. The at-risk group includes:
1. Over the age of 65
2. People with medical conditions such as cancer, HIV, obesity, or diabetes.

For this, we shall need to explore the usage of RiskAssessment FHIR resource https://www.hl7.org/fhir/riskassessment.html 
This resource can be used to represent the results of formal scoring/decision support tools that evaluate risk. It can also be used to capture a practitioner's subjective assessment of the patient's risk based on existing knowledge and previous experience.

After that, we shall need to have the risk parameter ranges that will be used in the validation/measure functionality to flag risk from a range of predefined risk factors i.e patient's age, disposition/ suffering from cancer, HIV, obesity, or diabetes etc. 

Sample [Riskassessment-example.json](https://www.hl7.org/fhir/riskassessment-example.json.html)

Subtasks (To be created as separate issues)
- [x] Add comorbidity questions (multi-select - boolean values)  to registration form similar to this https://ucc.uhcitp.in/
- [x] Add ‘at risk’ designation to a client record
- [x] Show notification on the registration form if the user is at risk
- [x] Display at risk flag on the list view
- [x] Display at risk flag on client profile
- [x] Update risk status post-registration if criteria are met

Detailed user story can be referenced [here](https://docs.google.com/document/d/1jD9PS5v6RcrVQZLLa90wrYBwWUckqxa_ibbWGbz7C-k/edit#heading=h.tteilzb7txx7)

Designs attached [here](https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=880%3A1)

**Comment by f-odhiambo** [comment]
CC. @rowo Add mock to risk warning notification

**Comment by maimoonak** [comment]
RiskAssessment is an Observation itself which refers to relevant Observations leading to the risk, relevant Algorithms references (Codeable Concept) and a lot of other data relevant to the assessment logic, evaluation process etc.

Each RiskAssessment is an Observation related to Encounter/Patient. Although Encounter is not a mandatory property however, its unlikely that it would performed without any Encounter between a Patient and a CareProvider (an automated ML engine can do it though where all patient data pushed and it calculates risk based on provided data etc)

FHIR does not define how to actually do the assessment, so we need to use the $evaluate to dynamically calculate Risk.

**Comment by maimoonak** [comment]
We also need to map the questions for Comorbidity with existing CodeableConcepts. Ideally use the same name/reference in HAPI-FHIR-server to make sure that it doesnot create duplicates when importing data for any IG(s)

**Comment by maimoonak** [comment]
The UI looks like 
![Screenshot_20210706-132221_FHIR Engine Example](https://user-images.githubusercontent.com/4829880/124567559-8e8f1a80-de5d-11eb-9471-955f4e7b062d.jpg)

Each one is a separate boolean type question embedded into a group 'comorbidities'

**Comment by maimoonak** [comment]
Comorbid conditions for selection simple reference set (foundation metadata concept) = 991381000000107 = https://snomedbrowser.com/Codes/Details/991381000000107 (comorbidities group)

Diabetes Mellitus = 73211009 = https://snomedbrowser.com/Codes/Details/73211009
Essential hypertension (disorder) = 59621000 = https://snomedbrowser.com/Codes/Details/59621000
Ischaemic heart disease = 414545008 = https://snomedbrowser.com/Codes/Details/414545008
Tuberculosis = 56717001= https://snomedbrowser.com/Codes/Details/56717001
Asthma (disorder) = 195967001 = https://snomedbrowser.com/Codes/Details/195967001
Chronic Kidney Disease = 709044004= https://snomedbrowser.com/Codes/Details/709044004
Malignant neoplastic disease = 363346000 = https://snomedbrowser.com/Codes/Details/363346000 (cancer)
Other (qualifier value) = 74964007= https://snomedbrowser.com/Codes/Details/74964007

**Comment by f-odhiambo** [comment]
> The UI looks like 
> 
> <img src="https://user-images.githubusercontent.com/4829880/124567559-8e8f1a80-de5d-11eb-9471-955f4e7b062d.jpg" data-canonical-src="https://user-images.githubusercontent.com/4829880/124567559-8e8f1a80-de5d-11eb-9471-955f4e7b062d.jpg" width="200" height="400" />
> 
> Each one is a separate boolean type question embedded into a group 'comorbidities'

Can we use a multiple select drop-down for this?

**Comment by f-odhiambo** [comment]
Also, could you explore hiding other input fields (as a nested option) when others selection is false? Check a similar issue [here](https://github.com/google/android-fhir/issues/530) on the SDK demo app

**Comment by maimoonak** [comment]
- datacapture-0.1.0-alpha03 throws UcumException
- fhirengine-0.1.0-alpha02 has major changes into sync
- datacapture-0.1.0-alpha02/01 does not have ResourceMapper public and hence can not work
- adding ResourceMapper manually into project (just to test the functionality)
- Form opened after trying some hacks but now it appears that the latest available version right does not have 'repeats' in type 'choice' working. This also does not render the multiselect dropdown
- ResourceMapper calls method setGivenElement via reflection which throws no such method exception

**Comment by maimoonak** [comment]
<img src="https://user-images.githubusercontent.com/4829880/124874634-63353880-dfe1-11eb-8dd9-a0e702a876ff.jpg" data-canonical-src="https://user-images.githubusercontent.com/4829880/124874634-63353880-dfe1-11eb-8dd9-a0e702a876ff.jpg" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/4829880/124874638-64fefc00-dfe1-11eb-9a65-56425b3a529b.jpg" data-canonical-src="https://user-images.githubusercontent.com/4829880/124874638-64fefc00-dfe1-11eb-9a65-56425b3a529b.jpg" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/4829880/124874643-66302900-dfe1-11eb-8c74-a8ff88dfc49f.jpg" data-canonical-src="https://user-images.githubusercontent.com/4829880/124874643-66302900-dfe1-11eb-8c74-a8ff88dfc49f.jpg" width="200" height="400" />

Working with older versions 0.0.7-datacapture, and 0.0.2-engine. Few things not working like styling and ResourceMapper lacking advanced features
