### ISSUE TITLE
[UX] Adjust Pagination position on register  enhancement 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1965]
**Describe the enhancement**

<img width="376" alt="image" src="https://user-images.githubusercontent.com/4540684/213169069-7fd9775c-aefe-479c-9922-dc51359a5b6e.png">

1. The pagination component should still at the bottom of the list and not at the bottom if the screen.
The pagination shows when user reaches end of the list

**Comment by f-odhiambo** [comment]
To be discussed with @HenryRae on the logic

**Comment by HenryRae** [comment]
Yes @f-odhiambo, the pagination component should be at the end of the list, not fixed at the bottom of the screen.

**Comment by f-odhiambo** [comment]
I have tested the app based on the latest `main` changes see attached video 

https://user-images.githubusercontent.com/4540684/225615916-9a41addd-8de7-49dc-8334-e791871590c0.mp4


@SebaMutuku what is the link to the PR that was used to address this PR?

**Comment by ellykits** [comment]
I think this issue was addressed and should be closed.

**Comment by ellykits** [comment]
Closing this. Pagination is now displayed at the end of the list as indicated in the video link above.

**Comment by SebaMutuku** [comment]
Handled in this PR https://github.com/opensrp/fhircore/pull/1956
