### ISSUE TITLE
[UX] Household Profile menu enhancement

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1967]
**Describe the enhancement**

<img width="383" alt="image" src="https://user-images.githubusercontent.com/4540684/213169405-86e2891f-3551-4462-a156-92c6ad0aa95f.png">

1. The drop down position should be same as material design positioning, thus should be close to the icon and not below the navigation header
2. Use term Household instead of HH
3. The remove household action should have a red background as intended in the design

**Comment by f-odhiambo** [comment]
@SebaMutuku to validate if this is resolved

**Comment by SebaMutuku** [comment]
Resolved
