### ISSUE TITLE
[UX] Individual Profile Menu enhancement

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1972]
**Describe the enhancement**

<img width="389" alt="image" src="https://user-images.githubusercontent.com/4540684/213170163-9c0d97c6-e7f4-4d32-b46b-74f630c96c9c.png">

1. The drop down position should be same as material design positioning, thus should be close to the icon and not below the navigation header
2. The remove household action should have a red background as intended in the design

**Comment by f-odhiambo** [comment]
Resolved in current app

**Comment by aurangzaibumer** [comment]
![Screenshot_1674548232](https://user-images.githubusercontent.com/35099184/214242386-e50d6c00-5758-4453-a18c-2b363f77d5ca.png)
branch : main
config : app/debug
