### ISSUE TITLE
[UX] Alert Dialog enhancement

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1973]
**Describe the enhancement**

**Current Design**
<img width="200" alt="image" src="https://user-images.githubusercontent.com/4540684/213188865-65cbc56b-0f63-4670-8813-d6256d130552.png">

**Proposed changes** 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/4540684/213170914-bbdeca2c-81ab-409a-9e75-7f043430c1ef.png">

1. Spacing 

- The padding between headings, body and buttons is off according to design
- Cancel button should be grey
- button label shouldn’t be save. should “Yes, submit” or “submit” no to confuse the users

3. Spacing 

- The padding between headings, body and buttons is off according to design
- Cancel button should be grey
- button label shouldn’t be save. should “Yes, submit” or “submit” no to confuse the users

**Comment by f-odhiambo** [comment]
@SebaMutuku Thanks for the clarification the above image may be a mock and not representative of what is currently showing in the app

**Comment by SebaMutuku** [comment]
Completed
