### ISSUE TITLE
UI Changes on the PIN Set page (Add/Remove the App Logo and Name)

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1988]
@ellykits this page looks very different. We are missing the logo and App Name. The wording also seems off. Trying to find the mocks. 

<img src="https://user-images.githubusercontent.com/4817531/214323570-96fdba88-6175-4e30-8fe0-326fb541230e.png" width="200" height="400" />

- Can we update the Login page such that if the user enters the username and hits enter the cursor moves to the password, then if both the username and password are filled then we can shift the focus to the login button.
- Pin on the "Set Pin" Should be in caps

_Originally posted by @dubdabasoduba in https://github.com/opensrp/fhircore/issues/1956#issuecomment-1402062386_

**Comment by dubdabasoduba** [comment]
Comments from the PR

@ellykits 
- This design was updated as requested by the Design team. The Logo and App names were removed on purpose to fulfill the requirements @HenryRae can comment on this.
-  Here is the link to [Figma](https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-Apps-~-Design-System?node-id=19491%3A127679&t=EwUrsTaQUkQjMvCZ-0)

@dubdabasoduba 
- Interesting. This looks very weird in terms of consistency. I might be wrong but I think all the login and pre-login pages should have the same look and feel. 

@HenryRae 
- The logo was removed on the set PIN to reduce clutter on any sort of destruction, this also allows us to have more room for the design to fully show when the keyboard is open on smaller screens. FYI this screen is right after the admin signing in and this page has the logo. so it's not necessary to show it on every screen after it.

cc: @rowo any thoughts?

**Comment by rowo** [comment]
@dubdabasoduba Agree with Henry. This is a utilitarian step and the user doesn't need to see the logo since they have already seen it, like Henry is saying.

In terms of priority, this isn't a high priority step since it is used by the admin user (who we train directly) and not the end CHW user.

**Comment by ellykits** [comment]
@rowo This is noted. @dubdabasoduba We can close this issue as done.

**Comment by ellykits** [comment]
Closing this. See the comment above.
