### ISSUE TITLE
[Server Side] The Practitioner Details endpoint breaks if the Practitioner Id is a String

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1995]
**Describe the bug**
- The Practitioner Details endpoint is used to fetch all the resources tied to a practitioner. 
- We currently have a bug where the endpoint breaks if the Practitioner ID are Strings

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Practitioner with a String as the ID on the practitioner resource. 
2. Hit the Practitioner Details endpoint. 
3. The endpoint will fail. 

**Expected behaviour**
- [x] The code should expect both Strings and Integers.  

**Acceptance Criteria**
- [x] We should be able to fetch the Practitioner Details for all the practitioners

**Comment by rehammuzzamil** [comment]
Looking into it @dubdabasoduba

**Comment by dubdabasoduba** [comment]
https://ecbis-preview.smartregister.org/fhir/practitioner-details?keycloak-uuid=4798140a-613a-4ed9-9a3f-da36f77feab3 this still fails.

**Comment by dubdabasoduba** [comment]
LGTM!
