### ISSUE TITLE
[App Configuration] Update the LIST view to allow filtering of resource data sets for display using FHIR Path expressions

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2001]
**Context**
- We would like to separate into different cards based on a `code` or any other Task attribute. 
- Currently, The LIST resources can only show the whole list of the resources specified on the base resource attribute. 

**Feature Implementation**
- [ ] Update the LIST configs to add a provision to define FHIR path expressions. 
- [ ] Filter all the base resources defined on the LIST view config based on the FHIR expressions. 

**Acceptance criteria**
- [ ]  Ability to filter the base resource specified on the LIST view. 
- [ ] The ability to create multiple lists for different thing on the app

LOE
This issue should be complete by Monday EOD

**Comment by dubdabasoduba** [comment]
@ellykits What do you think of the Data Query usage?

**Comment by dubdabasoduba** [comment]
```json
{"dataQueries":[{"id":"householdQueryByType","filterType":"TOKEN","key":"type","valueType":"CODING","valueCoding":{"system":"http://hl7.org/fhir/group-type","code":"person"}},{"id":"householdQueryByCode","filterType":"TOKEN","key":"code","valueType":"CODEABLECONCEPT","valueCoding":{"system":"https://www.snomed.org","code":"35359004"}}]}
```
Here is an example of what I mean by Data Queries.

**Comment by ellykits** [comment]
So currently the LIST view is using the already loaded resources. Applying data queries would mean querying the data from the database and again re-running the rules which will impact performance a bit.

**Comment by ellykits** [comment]
Can we discuss this separately in meeting if you do not mind.

**Comment by SebaMutuku** [comment]
I will provide a solution by Monday,13th Feb EOD

**Comment by dubdabasoduba** [comment]
https://user-images.githubusercontent.com/4817531/218407086-49d0231e-1d8f-41c7-ab10-0cdd2011327f.mp4
