### ISSUE TITLE
[eCBIS] Initial sync is taking too long 

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#2002]
**Describe the bug**

**To Reproduce**
1. Install the app afresh or clear data on your app. 
2. Make sure the device is connected to the internet. 
3. Enter the app ID, username and password, and set PIN. 
4. Observer the sync speed. It takes awhile for the sync to complete.

**Expected behavior**
Sync should take only a few moments to complete and load registers.

**Smartphone (please complete the following information):**
On the Grand60 devices (2GB RAM) sync time - 15-30min. The CHA app is taking longer.- device used in the field.
On a Xiaomi (8GB RAM) - sync time is about 5 minutes. (Not the ideal device)
On a Samsung s9 (4GB RAM) sync time - is about 1 hr to sync data on the CHA app.

**Additional context**

**Comment by AnnieMungai** [comment]
Linked to [this ticket](https://github.com/opensrp/fhir-resources/issues/466)

**Comment by madrinekariuki** [comment]
`APK:quest-v0.1.9-ecbis-rc4-preview.apk`
- Samsung A10 RAM 4GB + Sync on the CHSS device taking too long after login. (sync time  40 minutes)

**Comment by AnnieMungai** [comment]
Update with 0.1.9rc4
- [ ] The sync considerably slows done when a number of people are syncing at the same time.

**Comment by madrinekariuki** [comment]
Devices: 4GB RAM android 9 and 11 devices.
Apk : [quest-v0.1.9-ecbis-rc4-preview.-p2p-revert.apk](https://github.com/opensrp/fhircore/releases/tag/v0.1.9-ecbis-rc4)

- Sync not completing on CHSS - One has to close the app and log back in for sync to show as complete.
- When you follow step one above, there is no Data showing on the CHSS app (see screenshots below.)
CHA is taking 54 minutes.
![image](https://user-images.githubusercontent.com/84722169/220315397-8d55742e-8e77-40a6-8144-3b2fc40e9050.png)

**Comment by dubdabasoduba** [comment]
@AnnieMungai I am linking these issues and adding them to the QA column. https://github.com/opensrp/fhircore/issues/2051

**Comment by madrinekariuki** [comment]
@AnnieMungai 
App:  https://github.com/opensrp/fhircore/releases/tag/v0.2.3-rc1
Blu G60  3GB RAM 64GB ROM android 9 -- CHA
Blu G60 3GB RAM 64GB ROM android 9 -- CHSS

observations:
- Internet speed 5.2 mbps
- CHA device took 5 minutes 20 seconds
- CHSS device took 5 minutes 30 seconds

**Comment by AnnieMungai** [comment]
Closing this as it is an improvement from the past. Will continue testing with each release for performance improvements.
