### ISSUE TITLE
[App Configuration] Configure the configs to use while running the app for development

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2015]
**Describe the enhancement**
- Quest support loading of application configs from the assets folder.  This makes it easier to test changes in configs immediately instead of having to push them to the server and then sync them down. 
- We however, have to keep switching the configs based on the different apps we build based on Quest. 
- We would like to make it easier for developers to target a different folder in the filesystem to load their configs from. 

**Implementation**
- [ ] Add the ability to define the configs folder on the `local.properties` file.
- [ ] Configure the Application to use the configs on the route defined on the `local.properties` file. 
    - [ ] In case the file route is missing we should then default to loading the sample configs on the assets folder.
- [ ]  When using the `app/debug` the application should use local configs on any of the local folders as defined above. 

**Acceptance Criteria**
- [ ] Developers should be able to define and use a config route used on the `local.properties` file.
- [ ] In case the above config is missing the code should use the sample configs on the assets folder

**Comment by ellykits** [comment]
@dubdabasoduba Some devs have been using symlink to link the fhir-resources directory to the `assets/configs/app`. Do we have documentation @f-odhiambo on how this is done?

**Comment by f-odhiambo** [comment]
> @dubdabasoduba Some devs have been using symlink to link the fhir-resources directory to the `assets/configs/app`. Do we have documentation @f-odhiambo on how this is done?
You need to add something like 
`ln -s `pwd`/hisp-wdf-fhir-resources/app fhircore/android/quest/src/wdf/assets/configs/app`
to link your code to app folder

**Comment by f-odhiambo** [comment]
Marking this as DONE
