### ISSUE TITLE
[Rules Evaluation] Fix the slow evaluation of rules on the configs

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2016]
**Describe the bug**
- Once we add multiple rules to the different view configs the pages seem to slow down considerably. 
- This is caused by the slow speed at which the rules are executed. 

**To Reproduce**
Steps to reproduce the behaviour:
1. log in to the latest eCBIS release found [here](https://github.com/opensrp/fhircore/releases/tag/v0.1.9-ecbis-rc3). 
2. Click on any family, then click on a family member with generated tasks. 
3. You will notice the profile takes a bit of time to load and even has a blank screen displayed. 

**Expected behaviour**
- [ ] The screen should not take long to load. It should efficiently evaluate the rules and return the results to the screen for display. 

**Screenshots**
[blank-profile-page.webm](https://user-images.githubusercontent.com/4817531/217105113-20a163c1-d2e8-4c01-9301-3f5e266a7deb.webm)

**Comment by AnnieMungai** [comment]
Update with 0.1.9rc4
Phones used: BlueGrand G60 & Samsung Galaxy tab 
Both devices- available RAM  - 1.0- 1.5GBs (3GB total). 
Android 9 and 11
- [ ] When loading the household register, the app is taking a long time - 5+ minutes. This is happening even on subsequent loads. 
- [ ] Loading family and client profiles is taking a while - again 60seconds+ for families with about 4 members and over 2 minutes for families with many members. 
- [ ] Opening of forms has considerably slowed down with some forms taking almost 5minutes load. 
- [ ] Performance degraded the longer the app was used - day 1 in the morning was relatively fast but much slower in the evening. On day 2 the registers, profiles, and form took the longest to load [Approximately 5-7minutes].

**Comment by dubdabasoduba** [comment]
@ellykits @ekigamba Here are some things we can consider while reviewing this issue. 
1. How long does the app take to read and prepare the configs for execution? 
2. How do we separate the rules execute. 
    - Have some only the rules needed in each view evaluated immediately
    - Evaluate the rules needed for questions runtime evaluation when loading the forms. 
    - Have the rules needed for extraction evaluated during extraction.  
3. How much time does fetching the data based on the config definition take?
    - Can we only load the resources needed immediately 
    - Then load the ones needed for questionnaire use when the questionnaire is loading.
4. Review this issue https://github.com/j-easy/easy-rules/issues/379 to see whether we can learn anything from the discussion.

**Comment by dubdabasoduba** [comment]
@AnnieMungai Please test this app [quest-ecbis-rc4-new-easy-rule.apk](https://github.com/opensrp/fhircore/releases/download/v0.1.9-ecbis-rc5/quest-ecbis-rc4-new-easy-rule.apk)

@ekigamba @ellykits I switch the easy rules version with the one here https://github.com/j-easy/easy-rules/issues/379

**Comment by ndegwamartin** [comment]
- [ ] We also need to test a fresh install  with the updated indexing here: [1778](https://github.com/google/android-fhir/pull/1778)

**Comment by pld** [comment]
> * [ ]  We also need to test a fresh install  with the updated indexing here: [1778](https://github.com/google/android-fhir/pull/1778)

did we see any changes testing w/a fresh install and this update?
