### ISSUE TITLE
App force closing when trying to open any forms that have a lot of data passed to them via the Intent

### ISSUE THREAD

**Issue by roywanyaga** [opensrp/fhircore#2026]
https://github.com/opensrp/fhir-resources/issues/774

**Describe the bug**
Below Forms not loading and are force closing the app:
- Enroll to FP 
- FP visit
- sick child
- pregnancy outcome

**To Reproduce**
- Login to device and sync data.
- Click on a House hold
- Click on a adult female for FP enrollment or Visit
- Click on a child for sick child form

**Expected behavior**
The forms should load to enable us to add data

**Screenshots**
See videos below

https://user-images.githubusercontent.com/84722169/217560613-7002694e-7396-4e9e-847e-09679d447b0b.mp4

**Smartphone (please complete the following information):**

https://user-images.githubusercontent.com/84722169/217560683-336ae9dd-1399-4b2a-85b5-f26bca3b6c80.mp4

Phone: `Samsung A10 android 9`
APK:` quest-v0.1.9-ecbis-rc3-preview.apk`

**Comment by dubdabasoduba** [comment]
- This is happening because we were passing more than 500KB of data from the profile to the Questionnaire through an Intent. 
- The Intent has a max restriction of 500KB on data it can carry
