### ISSUE TITLE
[Configuration] Ordering of registers by related resources last updated

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#2035]
**Name of feature to enhance**
Ordering of registers by last updated resource. 
At the moment, when a new family is registered it shows at the top of the register - this implementation is using the group resource. However, there is a need to enhance this so that the family's last update will appear at the top. This will also apply to the commodity register. 

**Describe the enhancement**
- On the registers, order the list by the last updated resource [relatedresources]. 
- On the household register, if any member of the family record is updated, this family will appear at the top of the family register. 
- On any other register, the client with the most recently updated record will appear at the top of the list, the rest will be organized in chronological order from the most recent to the furthest updated. 
- On the stock/inventory register, the commodity that was adjusted/ restocked last will appear at the top of the list, and the rest will be on order of the latest updated to the furthest.  

**Acceptance criteria**
- [ ] The household register shows the most recently updated family using [relatedresources] - the family with clients with the most recently updated will be at the top of the register list. 
- [ ] In other registers, the client with the most recently updated record is shown at the top of the register list.
- [ ] Stock/inventory register, the commodity with the most recently updated physical count [adjustment/restock] is shown at the top of the register list.

**Comment by FikriMilano** [comment]
@AnnieMungai @dubdabasoduba 
so essentially, we change the filter from latest updated family to the latest updated family member?

**Comment by AnnieMungai** [comment]
@FikriMilano it should be both. If a new family is registered, it appears at the top of the register list. However, if the last action by the user was updating a family member, then that family will be at the top of the register list.

**Comment by ellykits** [comment]
For the household ordering, I think as long as we update the household Group resource every time a member in the Group is updated, this issue will be resolved. 

@ahsanbhatti49

**Comment by ellykits** [comment]
We follow the same approach to any type of resource with relationship to other resources.

**Comment by ahsanbhatti49** [comment]
@ellykits  In case of resource update, Group information  is not passed on the questionnaire page. So we need to add group id in the config and handle the same on app side. I have started looking at it.

**Comment by aurangzaibumer** [comment]
> @ellykits In case of resource update, Group information is not passed on the questionnaire page. So we need to add group id in the config and handle the same on app side. I have started looking at it.

Discussed the challenges with @roywanyaga and @dubdabasoduba, we will have a call tomorrow on this with @SebaMutuku included to discuss the implementation plan. Because we need to come up with a generic solution, as suggested by both @dubdabasoduba & @ellykits

**Comment by ahsanbhatti49** [comment]
Progress updates:
We are able to update the group resource(lastupdated) everytime when there is any update in the child resource.
But registers sorting on the main page is not working as expected. for example :
here are two registers,
1- lastupdated is 2023-02-28T07:57:33.866+00:00 for the first register( so this should be displayed on the top)
2-lastupdated is 2023-02-23T16:12:03.832+00:00  this is currently displaying on the top

This is blocker issue, I need to discuss with @ellykits  @roywanyaga  

cc: @f-odhiambo  @dubdabasoduba

**Comment by dubdabasoduba** [comment]
> Progress updates: We are able to update the group resource(lastupdated) everytime when there is any update in the child resource. But registers sorting on the main page is not working as expected. for example : here are two registers, 1- lastupdated is 2023-02-28T07:57:33.866+00:00 for the first register( so this should be displayed on the top) 2-lastupdated is 2023-02-23T16:12:03.832+00:00 this is currently displaying on the top
> 
> This is blocker issue, I need to discuss with @ellykits @roywanyaga
> 
> cc: @f-odhiambo @dubdabasoduba

I couldn't replicate this but I tested the implementation and left some [comments](https://github.com/opensrp/fhircore/pull/2086#issuecomment-1449246223) on the PR.

**Comment by AnnieMungai** [comment]
@SebaMutuku cc @dubdabasoduba re-opening as it failed QA.

**Comment by madrinekariuki** [comment]
@AnnieMungai 
This Fails QA.

App:  https://github.com/opensrp/fhircore/releases/tag/v0.2.3-rc1
G60 3GB RAM 64GB ROM android 9 
App ID -- `cha`

See below observations:
- A House hold where the family members careplan was last edited is not going to the top of the register
- In the other registers, client with most recent record updates is Not being shown at the top of the list e.g in sick child, ANC
-  Stock/inventory register, the commodity with the most recently updated physical count [adjustment/restock] is not being shown at the top of the register list.

**Comment by AnnieMungai** [comment]
@madrinekariuki Retest with v0.2.3rc3
