### ISSUE TITLE
[Configuration] Update all the configurable views to add a visibility configuration

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2041]
**Description of feature**
- We will often have the need to show or hide views based on the patient data. Adding a visibility attribute on the configs will allow the configuration author to easily hide or show the views based on some rules that evaluate to `true` or `false` 

**Implementation**
- [x] Add a `visible` attribute to all the views we have for the configurable UI. Below is a list of the views
     - [ ] CARD, COLUMN, COMPOUND_TEXT, SPACER, PERSONAL_DATA, BUTTON
- [x] This attribute show should the view if its value is `true` and hide the view if its value is `false`
     - [ ]`true` should set the visibility to `visible` 
     - [ ] `false` should set the visibility to `gone` 

**Acceptance criteria**
- [x] It should be possible to toggle visibility for all configurable views.

**Comment by FikriMilano** [comment]
do we need to differentiate between visible, invisible, gone?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba do we need to differentiate between visible, invisible, gone?

We will use `visible` for items that are shown on the UI and `gone` for items not shown on the UI
