### ISSUE TITLE
[P2P Sync] P2P data transfer breaks during transfer of data. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2049]
**Describe the bug**
- We use the P2P module to transfer data between 2 devices while offline. Currently, the app breaks when we try to transfer data from one device to another.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the eCBIS CHA application then create a family
2. Click on the transfer data option and tried to transfer data to the CHSS application
3. Both the CHSS and CHA app force close. 

**Expected behaviour**
- [ ] Data transfer should be completed successfully without force closing.

**Comment by dubdabasoduba** [comment]
**Update on the bug review**
- The apps force close when trying to transfer the **List resource**. 
- The Resources to be transferred are defined here https://github.com/opensrp/fhir-resources/blob/6392ac13ad681bfac4480a106c371785010edf1d/ecbis_liberia/app_configurations/ecbis_cha_preview/application_config.json#L22-L37

- We have a workaround which is to remove the **List Resource** from the list of resources to be transferred.

**Comment by dubdabasoduba** [comment]
**New Implementation requirements**
- [ ] Make sure all the FHIR resources can be transferable via P2P

**Comment by AnnieMungai** [comment]
Linked to [this ticket](https://github.com/opensrp/fhir-resources/issues/810).

**Comment by AnnieMungai** [comment]
LGTM!
