### ISSUE TITLE
Practitioner Details endpoint not working (High Priority)

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#2060]
**Describe the bug**
The Practitioner Details endpoint does not return the Keycloak user details. 

**To Reproduce**
1. Go to postman 
2. Perform this GET request with a valid token : [https://fhir-stage.smartregister.org/fhir/practitioner-details?keycloak-uuid=some-uuid-on-keycloak](https://fhir-stage.smartregister.org/fhir/practitioner-details?keycloak-uuid=some-uuid-on-keycloak)
3. See the error(Screenshot below)

**Expected behavior**
User details should be returned from the endpoint as described here #499 

**Screenshots**
The request below gives the following response:
 `https://fhir-stage.smartregister.org/fhir/practitioner-details?keycloak-uuid=<some-uuid-on-keycloak>`

```json 
 {
    "resourceType": "Bundle",
    "id": "c98de53b-bcf9-4a31-a340-d3063343c0b3",
    "meta": {
        "lastUpdated": "2023-02-18T17:42:11.664+00:00"
    },
    "type": "searchset",
    "total": 1,
    "link": [
        {
            "relation": "self",
            "url": "http://fhir-stage.smartregister.org/fhir/practitioner-details?keycloak-uuid=some-uuid-on-keycloak"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://fhir-stage.smartregister.org/fhir/practitioner-details/Keycloak User Not Found",
            "resource": {
                "resourceType": "practitioner-details",
                "id": "Keycloak User Not Found",
                "meta": {
                    "profile": [
                        "http://hl7.org/fhir/profiles/custom-resource"
                    ]
                }
            }
        }
    ]
}
```

**Device**
 - Tested on Postman
 
**Additional context**
Might be because :
- Keycloak was updated to a newer version 
- Something to do with the KC user configuration.

**Comment by rehammuzzamil** [comment]
Hi @ndegwamartin ,
I see the following request[]( https://fhir.labs.smartregister.org/fhir/practitioner-details?keycloak-uuid=9ed39e30-3350-4625-8943-47e611fb1dcf) returns a valid response along with the Keycloak User Details.

Can you please brief me the use-case of when Practitioner Details endpoint is failing with the Proxy instance?
cc: @dubdabasoduba

**Comment by dubdabasoduba** [comment]
@rehammuzzamil did you hit the endpoint via the proxy or did you hit the server directly?

**Comment by rehammuzzamil** [comment]
@dubdabasoduba  I have tested out by hitting the Patient Resource via the Proxy Server.

I have shared screenshots on slack earlier.

**Comment by dubdabasoduba** [comment]
@rehammuzzamil we need to test the Practitioner Details endpoint to make sure it works well. It's one of the endpoints the app will be hitting

**Comment by rehammuzzamil** [comment]
@dubdabasoduba  I have tested out the end-point separately as well, it returns valid response on my local server.

Would you mind sharing me the API endpoint along with the params and logs from the app?

**Comment by dubdabasoduba** [comment]
@rehammuzzamil Please try hit this endpoint with the FHIR stage server oauth credentials https://fhir-stage.smartregister.org/fhir/practitioner-details?keycloak-uuid=9ed39e30-3350-4625-8943-47e611fb1dcf

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil Please try hit this endpoint with the FHIR stage server oauth credentials https://fhir-stage.smartregister.org/fhir/practitioner-details?keycloak-uuid=9ed39e30-3350-4625-8943-47e611fb1dcf

 Sure.

**Comment by ndegwamartin** [comment]
@rehammuzzamil any feedback on your results after you tried hitting the endpoint above?

**Comment by rehammuzzamil** [comment]
Yes @ndegwamartin , There seem to be two issues:
1. `SecurityContextHolder.getContext().getAuthentication() ` is always returning false, need to debug it that why it is failing now. Earlier, it was working perfectly.
2. There seems to be a bug in introducing an additional searchParam `isAuthProvided` logic. 

Apart from this, there is an area under RnD, where we can get the `KeycloakUserDetails` data directly from the userInfo API of the Keycloak, if that is the case, we will be removing it from the PractitionerDetails Response Payload. 

cc: @dubdabasoduba
