### ISSUE TITLE
[App Performance] Profile the time it takes for the app to save a response from the server

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2065]
**Describe the enhancement**
- The FHIR core performs a comprehensive initial sync. This sync gets the following items. 
    - Application Composition resource (Based on the Application ID)
    - Application Congis referenced on the Composition
    - Patient data based on the sync configs

**Implementation**
- [ ] Review the time and device resources it takes for the application to save the response from the server. 
    - [ ] The time and device resources to save the Composition resource after the response from the server
    - [ ] The time and device resources to save the Application configs  defined in the Composition
    - [ ] The time and device resources to save the Patient data. Here we can look at 3 different resources
        - [ ] Patient resource.
        - [ ] Group resource.
        - [ ] Task resource. 
        - [ ] Observation resource.
        - [ ] CarePlan resource.
        - [ ] MeasureReports resource

 **Device configuration**
- RAM 3GB
- ROM 64GB 

**Expected results.** 
- Profiling documentation can be done by recording the following
    - [ ] Time and device resources it takes to save each response type as defined in the implementation section
    - [ ] Amount of resources used by the device for each request.  i.e RAM & CPU

**Comment by pld** [comment]
@ekigamba let's add a perf test to close this out

**Comment by pld** [comment]
sorry, nevermind, let's save profiling that requires a remote server for later
