### ISSUE TITLE
[Immunization] Calculate DUE dates for dependent Tasks

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2146]
## Context
- For FHIR core to implement correct Tasks dependencies we need to update the tasks' DUE dates in case the dependent tasks have a time constraint depending on the pre-requisite tasks. 

## Implementation
- [ ] Write a function that does the following. 
    - [ ] Accepts a task/tasks as input. 
    - [ ] Determine its dependent tasks. This [scoping piece](https://github.com/opensrp/fhircore/discussions/2141) defines how to identify the dependencies. 
    - [ ] Updates the dependent tasks `Task. executionPeriod.start` to account for the constraint interval defined [here](https://github.com/opensrp/fhircore/discussions/2141). 
        - [ ] This [discussion](https://github.com/opensrp/fhircore/discussions/2140) explains how to update the dependent DUE dates 

## Acceptance criteria
- [ ] The dependent tasks' DUE dates should be updated based on the pre-requisite date of administration. 

## Scoping details
- https://github.com/opensrp/fhircore/discussions/2111

**Comment by dubdabasoduba** [comment]
This was blocked due to some comments on the codes. It's now updated. @SebaMutuku feel free to add an LOE and implementation plan.

**Comment by SebaMutuku** [comment]
@dubdabasoduba @f-odhiambo this is the implemetation plan
1. refractor `transitionTaskTo` in class `FhirCarePlanGenerator` to a generic name (This is to centralize tasks logic in one place)
2. Create an extension function to handle this issue.

**Comment by SebaMutuku** [comment]
@dubdabasoduba  that's found it in this discussion https://github.com/opensrp/fhircore/discussions/2142

**Comment by SebaMutuku** [comment]
@dubdabasoduba do you mind sharing a sample generated `task` json file that I can use to test with?
Be sure to include `task.input.value` in days because the type  is `listOf(Task.ParameterComponet)`

**Comment by dubdabasoduba** [comment]
@SebaMutuku The `Task.input.value` can hold different values https://www.hl7.org/fhir/task.html.

**Comment by SebaMutuku** [comment]
Thanks @dubdabasoduba

**Comment by dubdabasoduba** [comment]
> @SebaMutuku You are right. It's on the Observation created after extraction. Please feel free to leave comments on the discussion if something isn't clear.

@SebaMutuku After some discussion, this implementation will change. The date of Administration will now be stored on the Immunization resource. It will be stored on the `Immunization.occurrenceDatetime` attribute.  

Please review this discussion item https://github.com/opensrp/fhircore/discussions/2142

**Comment by dubdabasoduba** [comment]
@pld I will re-open this ticket since it's failing the engineering QA

**Comment by dubdabasoduba** [comment]
**How to replicate the bug.** 
1. Run the code on `main` pointing to the eCBIS preview server or the stage server using the configs [here](https://github.com/opensrp/fhir-resources/tree/main/ecbis_liberia/app_configurations/ecbis_cha_preview)
2. Create a child of age 2 yrs. 
3. The immunization schedule should be generated and immunization task statuses updated correctly.  
4. The OPV 0 will have a due date in the year 2021. 
5. Complete the tasks then wait for the OPV 1 task to become due.  
6. OPV 1 dues date should be updated to 28 days after the Immunization date entered while completing the OPV 0 task.
    - e.g if OPV 0 was completed on 21/06/2022 then the OPV 1 due date should be updated to 19/07/2022

**Comment by ellykits** [comment]
From our investigation with @SebaMutuku and @dubdabasoduba 

**The problem**
The code for updating the due dates of the dependent Tasks is never called. Reason: the condition for `hasPartOf` is evaluating to false on this function [ResourceExtension#updateDependentTaskDueDate](https://github.com/opensrp/fhircore/blob/6dfa937ee22cb10c64850c716206efe7d96e4a22/android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt#L342). The code was implemented with the interpretation that the `part-of` property should be extracted from the parent resource. The property should be retrieved from the dependent `Task` instead.

**The solution**
1. Do a reverse search for Tasks that are part of the current task loaded on QuestionnaireSubmission. The filter would look like below:

```kotlin
 fhirEngine.search<Task> {
      filter(
          referenceParameter = ReferenceClientParam("part-of"),
          { value = id.asReference(ResourceType.Task).reference })
    }
```
2. Update the logic for modifying the dependent `Tasks` due date against the result of the query above

**Comment by dubdabasoduba** [comment]
Still, work in progress
