### ISSUE TITLE
[Immunization] Update the `ProfileViewModel.kt` to allow launching of a profile from another profile. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2147]
### Context
- FHIR core is adding an extra screen to display more data away from the main profile. This can be used for different purposes e.g Upcoming and Past Encounters,  Medical History. 
- The Immunization workflow will have an upcoming encounters and medical history page. 

### Implementation
- [ ] Update the `ProfileViewModel.kt` to allow launching profiles from other profiles. This [discussion](https://github.com/opensrp/fhircore/discussions/2144) gives more context to the need.  
- [ ] Allow passing of the information needed by the extra screens to allow data fetch. 

### Acceptance criteria
- [ ] It should be possible to launch a profile by the `action` configurations from another profile.
- [ ] The ability to fetch data for a specific subject on the new screen.   

### Scoping details
- https://github.com/opensrp/fhircore/discussions/2111

**Comment by SebaMutuku** [comment]
Closing the issue with comment on  [PR](https://github.com/opensrp/fhircore/pull/2154)

**Comment by f-odhiambo** [comment]
Reopening this issue for further discussion
