### ISSUE TITLE
Render profile view in stages

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#2165]
**Describe the Issue**
Render the profile view in stages so that the page is not left blank for a period of time. The page will be rendered as soon as it receives data.

- Split loading and rendering of data so that the demographic data is shown immediately it's rendered. 
- Split the rendering of list items in the profile page so that each list item is fetched, run through the rules engine to calculate the values to be shown and then rendered immediately before moving to the item. This assumes that each list items has related resources that take time to load thus the difference in UX when rendered individually given that the primary list of resources is loaded from a single database query

**Comment by f-odhiambo** [comment]
This ticket is blocked by rev_include implementation on ticket #2276. Will give an updated LOE once unblocked 
CC @pld

**Comment by ekigamba** [comment]
Yea, that's correct @pld . The remaining work on the PR was working on the tests. From @ellykits quick review, we'll need to refactor some of the code so that it follows the previous patterns and therefore the initial work on tests will be overwritten after the refactor. Elly is to review this PR but at the same time we need to evaluate the impact of `revInclude`. Elly is in the best position to refactor for revInclude and has prioritised this for the moment in readiness for the Thursday call with Google. We also think this gives us a better idea on how to integrate both given that one requires multiple queries while the other uses less queries. 

I hope this makes it clear why the remaining test fixes on this is blocked

**Comment by pld** [comment]
Yes, very clear, thank you
