### ISSUE TITLE
Fix Flakey Test

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#2184]
**Describe the Issue**

The test case on [the LOC here](https://github.com/opensrp/fhircore/blob/031ac9a6df1cf79c3d2c7f34aafb87aabc45590e/android/engine/src/test/java/org/smartregister/fhircore/engine/util/extension/PatientExtensionTest.kt#L58) is failing depending on the time of year.

The above flakey test can be fixed by refactoring the code to pass the` LocalDate.now()` date as a param for the method `calculateAge` . That way, it can be mocked during testing making the test case stable.

**Comment by Rkareko** [comment]
This issue has been duplicated [here](https://github.com/opensrp/fhircore/issues/2260)
