### ISSUE TITLE
[ServerSide] Sync the OpenSRP FHIR Gateway repo with the upstream Google FHIR Gateway repo

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2188]
**Implementation**
- [ ]Sync the current [OpenSRP FHIR Gateway](https://github.com/opensrp/fhir-access-proxy) with the upstream [Google FHIR Gateway](https://github.com/google/fhir-gateway). 
    

**Acceptance Criteria**
- [ ] The OpenSRP FHIR Gateway should only be ahead of the Google FHIR Gateway because of the changes we have added to the plugins and deployments. 
- [ ] All the current permission checking and sync filtering functionality should work as expected.

**Comment by pld** [comment]
closed by https://github.com/opensrp/fhir-gateway/pull/24
