### ISSUE TITLE
Update Icon & Formatting for Cancelled/Revoked Tasks

### ISSUE THREAD

**Issue by qiarie** [opensrp/fhircore#2208]
When CarePlans are closed/revoked together with it's associated Tasks, they are displayed as completed on profiles.

Update how cancelled tasks' font colour and icon to match the designs (pending).

Refer to the conversations in issue [#2168](https://github.com/opensrp/fhircore/issues/2168) & PR [#2192](https://github.com/opensrp/fhircore/pull/2192) for more details and context.

**Comment by f-odhiambo** [comment]
Based on @HenryRae comment [here](https://github.com/opensrp/fhircore/issues/2168#issuecomment-1489900795) , I think we should close this ticket 
CC @qiarie @HenryRae
