### ISSUE TITLE
[In-App Reporting] Have values with decimal fractions represented to one decimal place

### ISSUE THREAD

**Issue by roywanyaga** [opensrp/fhircore#2237]
**Describe the feature request.**
Currently, on the in-app reports, data values are represented as integers. This means that values with decimal fractions are truncated to their integer values, leaving out the fraction. 
To improve accuracy of the indicators, we will include values with decimal fractions representing them as floating-point numbers with one decimal place.

**Acceptance criteria**

- [ ] Reporting indicator values with fractions are represented as floating point numbers with one decimal place

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _*Reports_
4. Click on _specific indicator with possibility of fraction values_
5. Click on _measure period (month)_
6. Indicator values with fractions should be represented as floating point numbers with one decimal place

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
This looks good, I expect in the feature we'd want this (the precision of digits) to be configurable, so we can take that into consideration in the implementation but not implement it as configurable yet.

**Comment by AnnieMungai** [comment]
@roywanyaga eCBIS will require to round off to the nearest whole number.

**Comment by madrinekariuki** [comment]
`opensrp-ecbis-0.2.5-rc4-preview-gateway-mock.apk`
Device: G60 `android 9`
user: `awori`

This passes QA.
 - any decimal number is rounded of the next whole number e.g 19.34 becomes 20 and 19.56 becomes 20
