### ISSUE TITLE
Styling of vaccine status in patient list and profile view

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#224]
Add styling to the patient list for the vaccine status based on the provided mock attached here. 

Acceptance criteria 
- [x] When fully vaccinate show _A green vaccinated text with a check-tick on top_
- [x] On a partially vaccinated i.e show _Greyed out label Vaiine 1 with the date received at the bottom of it_ 
- [x] When overdue show _Red Label with Overdue text_ 
- [x] When not vaccinated show _a Blue text - Record vaccine_ 

![image](https://user-images.githubusercontent.com/4540684/120622518-8e1ef080-c467-11eb-9742-ce92de44b929.png)
![image](https://user-images.githubusercontent.com/4540684/121144654-df075e00-c846-11eb-8633-cb83cab577cb.png)

**Comment by f-odhiambo** [comment]
Cannot be merged until the Covax app branch is merged to main

**Comment by pld** [comment]
> **Update** : Cannot be merged until the Covax app branch is merged to main

aren't we not merging that branch? is there a specific part of that branch we need to cherry-pick and open a pr for?

**Comment by maimoonak** [comment]
<img src="https://user-images.githubusercontent.com/4829880/125775137-ac70fe54-e8ba-4481-90e9-3aa54992ea9a.jpg" data-canonical-src="https://user-images.githubusercontent.com/4829880/125775137-ac70fe54-e8ba-4481-90e9-3aa54992ea9a.jpg" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/4829880/125775148-e59538fd-df8e-4612-8bee-af69c9883f16.jpg" data-canonical-src="https://user-images.githubusercontent.com/4829880/125775148-e59538fd-df8e-4612-8bee-af69c9883f16.jpg" width="200" height="400" />
