### ISSUE TITLE
End to end P2P test results

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#2268]
v.0.2.1
Device: G60

- [x] (this is acceptable) p2p is still quite slow it took 17 minutes to complete the first p2p sync
- [ ] if you cancel the search for a recipient, then click on send and receive again, it is not showing any devices see video below

https://user-images.githubusercontent.com/84722169/233114360-12a8939a-0902-4bb8-81f8-1e6d37dc6810.mp4

- [ ] for the data sent via P2P, it is showing 0 tasks on the HH after the transfer is complete on chss (right icon) see screenshot below

  (first 2 Households)
  
![image](https://user-images.githubusercontent.com/84722169/233115627-2a6418e7-4aab-4000-806c-846a15183f77.png)

- [ ] for the data sent using p2p on CHSS, when you open a profile e.g PNC, FP, Disease, it is not showing any tasks. keeps showing (no visit tasks available for this client) 

  steps:
      - on CHA , add a client and enroll them to a careplan e.g FP and wait for tasks to generate.
      - Send data to CHSS, then from the chas list click on your cha and open the HH and open the client you added and observe there are no tasks.
  
- [ ] chss app crashing after p2p transfer and you click back from top left on the app but when you click from the bottom device back button it is working well. see video below.

https://user-images.githubusercontent.com/84722169/233111686-3d44c2c8-e59e-4152-ae5e-2cb3f74f5e5e.mp4

- [ ] no option to decine a pair request on CHSS. according to [this](https://user-images.githubusercontent.com/4817531/195072130-40085646-2384-4620-b21c-dc2a957a50e8.png) workflow a receiver can decline a pair request

- [ ] There is no prompt showing that the receiver is waiting to receive data. also this is according above workflow.
- [ ] Subsequest p2p data transfers are showing data sent successfully but no data is being transferred e.g  when you open the HH you cannot see the data that you added on cha after the first p2p was done.   
  steps:
      - send data via p2p. 
      -  go back to cha and add some data e.g a sick child
     - send data via p2p again
     - from chss open the HH and confirm if the sick child has been added 
     - observe the sick child is missing
    
- find attached test cases used.
[P2P Transfer Test Run 4_19_2023 - TestRail.pdf](https://github.com/opensrp/fhir-resources/files/11274531/P2P.Transfer.Test.Run.4_19_2023.-.TestRail.pdf)

_Originally posted by @madrinekariuki in https://github.com/opensrp/fhir-resources/issues/1203#issuecomment-1514898563_

**Comment by AnnieMungai** [comment]
@madrinekariuki kindly check how long subsequent P2P is taking on the G60 phones. i.e the second or 3rd time you try p2p.

**Comment by madrinekariuki** [comment]
@AnnieMungai 

- A subsequent p2p with no data added after the first p2p its taking 2 secs.
- A subsequent p2p with added data i.e add a woman and enroll her to a careplan its taking 5 secs

**Comment by pld** [comment]
K thank you, closing this issue, please open specific issues for any problems that need to be resolved.

**Comment by madrinekariuki** [comment]
@AnnieMungai 

v.0.2.3rc1
As requested see below:
A subsequent P2P with 10 users all in different careplans it takes 8 seconds
