### ISSUE TITLE
[Quest] Add title for Profile pages

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2278]
**Describe the feature request.**

1. Add a title to the TopBar to describe the name of the profile page on which the user is currently navigating 
2. Currently there is a bug , bit working as it should 

**Additional context**
Sample config to add TopBar title

```
"topAppBar": {
    "title": {
      "viewType": "COMPOUND_TEXT",
      "primaryText": "@{familyName} Family",
      "primaryTextColor": "#FFFFFF",
      "fontSize": 20.0,
      "maxLines": 1,
      "primaryTextFontWeight": "BOLD"
    },
    "content": [
      {
        "viewType": "COMPOUND_TEXT",
        "primaryText": "@{familyName} Family",
        "primaryTextColor": "#FFFFFF",
        "fontSize": 16.0,
        "maxLines": 1,
        "primaryTextFontWeight": "BOLD"
      },
      {
        "viewType": "COLUMN",
        "backgroundColor": "primaryColor",
        "children": [
          {
            "viewType": "COMPOUND_TEXT",
            "primaryText": "@{familyVillage} - HH No: @{familyId}",
            "primaryTextColor": "#FFFFFF",
            "colorOpacity": 0.76,
            "fontSize": 16.0
          }
        ]
      }
    ]
  },
```

**Acceptance criteria**
Each profile should have a title to describe the name of the profile page on which the user is currently navigating 

**Area path**
 **TBD**

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _checklist_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_
**TBD**

**Screenshots**
<img src="https://user-images.githubusercontent.com/4540684/234823604-1a6564e9-36e4-433e-ae74-c1ac1d779c14.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
Based on the discussions we can add a function on the ActionConfg.kt to be able to add the page title to the action bar based on the provided title in the configs file  and also make it translatable based on the String file provided 

Sample Config

````
{
  "appId": "app",
  "configType": "profile",
  "id": "defaultProfile",
  "title": "{{user.profile}}",
  "fhirResource": {},
  "secondaryResources":[],
  "rules":[],
  "views":[],
  "overFlowMenuItems":[]
}
````

**Sample Strings file  = `strings_config.properties`**
you can add

`user.profile=User Profile`

**Comment by ellykits** [comment]
Can we use the [ProfileConfiguration.topBar](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/profile/ProfileConfiguration.kt)  instead. I do not think we need a new property for this.

**Comment by f-odhiambo** [comment]
Here is the topbar condif 

````
"topAppBar": {
    "title": {
      "viewType": "COMPOUND_TEXT",
      "primaryText": "@{familyName} Family",
      "primaryTextColor": "#FFFFFF",
      "fontSize": 20.0,
      "maxLines": 1,
      "primaryTextFontWeight": "BOLD"
    },
    "content": [
      {
        "viewType": "COMPOUND_TEXT",
        "primaryText": "@{familyName} Family",
        "primaryTextColor": "#FFFFFF",
        "fontSize": 16.0,
        "maxLines": 1,
        "primaryTextFontWeight": "BOLD"
      },
      {
        "viewType": "COLUMN",
        "backgroundColor": "primaryColor",
        "children": [
          {
            "viewType": "COMPOUND_TEXT",
            "primaryText": "@{familyVillage} - HH No: @{familyId}",
            "primaryTextColor": "#FFFFFF",
            "colorOpacity": 0.76,
            "fontSize": 16.0
          }
        ]
      }
    ]
  },
````
