### ISSUE TITLE
[Roadmap] Notice E0 - Shelf Readiness: Work package 1 : Adding an automated testing framework and improving modular test coverage to 80%

### ISSUE THREAD

**Issue by mwkhan1983** [opensrp/fhircore#228]

**Comment by mwkhan1983** [comment]
- [ ] Activity 1.1: Adding the automated test framework to the Android client, data warehouse, and server 
libraries #229 
- [ ] Activity 1.2: Updating test coverage across the OpenSRP Fast Healthcare interoperability Resources( 
FHIR) app to reach 80%

**Comment by pld** [comment]
https://github.com/opensrp/fhircore/pull/355
