### ISSUE TITLE
[Quest] App crashes if user switches to Dark mode 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2282]
**Describe the bug**
App crashes if the user switches to Dark mode

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  the Quest app
2. If the application has the ability to switch to dark mode switch to it 
3. App will crash or the Text appears to be whitewashed in Dark mode 

**Expected behaviour**
1. If the Dark mode theme is configured user should be able to switch to the dark mode 
2. Test should be legible 
3. App should not crash on the switch from Dark/Light mode 

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 13

**Additional context**
See the screen recording here 

https://user-images.githubusercontent.com/4540684/235115013-e612e034-7149-4cd4-a813-e9473efa8071.mp4

https://user-images.githubusercontent.com/4540684/235115087-8d5415dd-404b-4ae2-b1c4-84725e9792bc.mp4

**Comment by ndegwamartin** [comment]
@f-odhiambo @dubdabasoduba for us to fully support Dark Mode we'd actually need input from the design team with night mode theming for FHIR Core app designs cc @HenryRae 

For now we can try focus on the crash and and legibility(even if it looks the same in both modes) if someone changes the mode.

**Comment by dubdabasoduba** [comment]
@Maryann-Mweru-Wambui-Programmer @ndegwamartin agreed!
