### ISSUE TITLE
[ServerSide] Sync the OpenSRP FHIR Gateway repo with the upstream Google FHIR Gateway repo

### ISSUE THREAD

**Issue by rehammuzzamil** [opensrp/fhircore#2340]
**Reason**
-  Latest updates on the upstream added the support for gzip 
- https://github.com/google/fhir-gateway/pull/147
- Need for Gzip for the security audit that has been requested for the codebase that we’ll be deploying.

**Implementation**
- [ ] Sync the current [OpenSRP FHIR Gateway](https://github.com/opensrp/fhir-access-proxy) with the upstream [Google FHIR Gateway](https://github.com/google/fhir-gateway).

**Acceptance Criteria**
- [ ] The OpenSRP FHIR Gateway should only be ahead of the Google FHIR Gateway because of the changes we have added to the plugins and deployments.
- [ ] All the current permission checking and sync filtering functionality should work as expected.

FYI @dubdabasoduba  @ndegwamartin  @f-odhiambo

**Comment by dubdabasoduba** [comment]
Closing this since all the PRs are merged
