### ISSUE TITLE
[Quest] Add DOB Filter to Patient Register 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2357]
**Describe the feature request.**
Update the rules Engine to be able to execute a DOB filter on Patient data dynamically and not a hardcoded age limit as described in the code snippets below for the Register configs

**Data Query**
**Child**
````json
{
"fhirResource": {
    "baseResource": {
      "resource": "Patient",
      "dataQueries": [
        {
          "paramName": "birthdate",
          "filterCriteria": [
            {
              "dataType": "DATE",
              "computedRule": "underFive",
              "prefix": "GREATERTHAN_OR_EQUALS"
            }
          ]
        }
      ],
}
````

**Adults** 

**Data Query** 
````json
"fhirResource": {
    "baseResource": {
      "resource": "Patient",
       "dataQueries": [
        {
          "paramName": "birthdate",
          "filterCriteria": [
            {
              "dataType": "DATE",
               "computedRule": "overEighteen",
              "prefix": "GREATERTHAN_OR_EQUALS"
            }
          ]
        }
      ],
}
}
````

**Additional context**
Currently, the DOB filter is hardcoded for most patient registers that require it and will need the config maintainer to update it every year to keep the filter up to date based on the desired Age i.e Children under 5 or Adults 

**Acceptance criteria**
1. Add to the register config the required age filter and be able to use the rule defined for the min/max age

**Child**
**Rule**
````json
{
   "appId": "app",
  "configType": "register",
  "id": "childRegister",
  "configRules": [
    {
      "name": "underFive",
      "condition": "true",
      "actions": [
        "data.put('underFive', dateService.addOrSubtractYearFromCurrentDate(5,'-'))"
      ]
    }
  ]
````

**Adults**
**Rule**
````json
 { "appId": "app",
  "configType": "register",
  "id": "adultRegister",
   "configRules": [
    {
      "name": "overEighteen",
      "condition": "true",
      "actions": [
        "data.put('overEighteen', dateService.addOrSubtractYearFromCurrentDate(5,'-'))"
      ]
    }
  ]
````

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Children register_ or Adult register_
4. All Patient should be filter based on the configured age limit

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem

**Comment by f-odhiambo** [comment]
CC @ellykits @samkanga @qaziabubakar

**Comment by SebaMutuku** [comment]
**Proposed implmentation plan**

- Refactor RulesFactory class to move RuleInterface methods outside for easier and future implementation
- Create a rules-service method to calculate expected date when we pass years from current date. I.e calculate minimum date from today's date and period from today e.g under 5 years
- Add configuration to ResourceConfig to accomodate dataQuery rules.These rules should be evaluated during loading of register or profile data.
- Implement a logic on register repository to accommodate the dataQueryRules

**Comment by f-odhiambo** [comment]
@samkanga Kindly take note CC @Naima-Bashir

**Comment by ellykits** [comment]
@f-odhiambo I think we need to update the acceptance criteria on this issue. The current will not apply.

**Comment by ellykits** [comment]
> @f-odhiambo I think we need to update the acceptance criteria on this issue. The current will not apply.

Reason: At the time the data is queried, no Patient data is available for filtering. So the date needs to be know before running the query.

**Comment by SebaMutuku** [comment]
@f-odhiambo @samkanga kindly note the updates

**Comment by f-odhiambo** [comment]
Re-opoening for a hotfix
