### ISSUE TITLE
[P2P] Subsequent syncs have records to send

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#2390]
**Describe the bug**
The p2p sync does not seem to finish sending data since subsequent syncs have records to send

**To Reproduce**
1. Open the side menu
2. Click on "Settings"
3. Click on "Transfer Data"
5. Click on "Receive Data" in the new page that opens
6. Initiate data sending on the other device. Repeat from steps 1 to 5. Click on "Send Data"
7. Select the correct receiving device on the sending device
8. When the sending finishes, click on the "Okay" button on the  receiving device
9. Click on the device's back button, and start the process again from step 1 to 7. 

**Expected behavior**

There are still available records to be sent after any p2p sync

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Comment by pld** [comment]
is this correct?
> There are still available records to be sent after any p2p sync
should that be "There are no records to be sent after p2p sync"?

**Comment by pld** [comment]
That sounds like it means that it will be re-sending (some of) the same records, is that correct?

Could we mark records that have been confirmed received to avoid the above, and avoid showing that there are still records to sync after sync has completed successfully?

**Comment by pld** [comment]
Can't the receiving device continue to track the checkpoint, w/the change here that there would be a set of monotonic IDs that the receiver can use for that tracking
