### ISSUE TITLE
[Sync] - Last sync date doesn't update

### ISSUE THREAD

**Issue by ageryck** [opensrp/fhircore#2394]
**Describe the bug**
The app doesn't immediately update the sync date upon a successful sync, this happens event when the sync has been successful and the local resources pushed to HAPI

**To Reproduce**
1. Log into FHIRCore app
2. Add a new resource record, and query local SQLite to pick resource `id`
3. Sync the app to push resources to the server
4. Query the above `id` in HAPI to check the `lastUpdated`
5. Compare the datetime with the last sync date in the app

**Expected behavior**
Updated last sync date immediately after the sync is completed and successfully 

**Screenshots**

**Smartphone (please complete the following information):**
 - tested on emulator

**Additional context**
See the screenshot below the app vs the resource sync time

**Comment by ageryck** [comment]
![image](https://github.com/opensrp/fhircore/assets/23252704/c0d3ac3c-80f4-41c8-8f6b-b76e056bc34a)

**Comment by ageryck** [comment]
```
{
	"resourceType": "Patient",
	"id": "5a41a9cd-657b-4b77-a8fc-c2b756deeb53",
	"meta": {
		"lastUpdated": "2023-05-26T23:23:07.291+03:00",
		"tag": [
			{
				"system": "https://smartregister.org/",
				"code": "0.2.3-echis",
				"display": "Application Version"
			},
			{
				"system": "https://smartregister.org/",
				"code": "0.2.3-echis",
				"display": "Application Version"
			},
			{
				"system": "https://smartregister.org/",
				"code": "698acddb-36d6-44aa-a266-603756cb7545",
				"display": "Practitioner CareTeam"
			},
			{
				"system": "https://smartregister.org/",
				"code": "1599cdb2-2239-43e0-8403-60d6fbe85794",
				"display": "Practitioner Location"
			},
			{
				"system": "https://smartregister.org/",
				"code": "75a1be9b-93fb-4b97-956f-27f56ba92a3c",
				"display": "Practitioner Organization"
			},
			{
				"system": "https://smartregister.org/",
				"code": "6edaafb0-0212-4069-a0e2-c6a90a080c83",
				"display": "Practitioner"
			}
		]
	},
	"identifier": [
		{
			"use": "official",
			"type": {
				"coding": [
					{
						"system": "http://ona.io/codes",
						"code": "id_category",
						"display": "Nationality Type"
					}
				],
				"text": "Ugandan National"
			}
		},
		{
			"use": "secondary",
			"value": "e6347340-b83c-4a67-b28a-8aeb638c948d",
			"period": {
				"start": "2023-05-26T23:23:06+03:00"
			}
		}
	],
	"active": true,
	"name": [
		{
			"use": "official",
			"text": "Kwacha",
			"family": "Cess"
		}
	],
	"telecom": [
		{
			"system": "phone"
		}
	],
	"gender": "male",
	"birthDate": "2021-05-26",
	"deceasedBoolean": false,
	"generalPractitioner": [
		{
			"reference": "Practitioner/6edaafb0-0212-4069-a0e2-c6a90a080c83"
		}
	],
	"managingOrganization": {
		"reference": "Organization/75a1be9b-93fb-4b97-956f-27f56ba92a3c"
	}
}
```

**Comment by ageryck** [comment]
From the user perspective, the timestamp indicates when the last data was successfully synced to the server side, if this is true then this is currently the only indicator for the user to determine when last they had a successful sync. 
The current challenge is that FHIRCore sync each resource independently, so should this time be the time of the last successfully synced resource or define it based on some algorithm for sets of resources synced successfully. 
A further sync stats page will be more useful to user and can eliminate data loss for just relying on the toast message and the timestamp

**Comment by ndegwamartin** [comment]
@ellykits I think this is inline with the conversation we had on what should constitutes the **Last Timestamp** shown on the app

**Comment by f-odhiambo** [comment]
@qiarie take note of this

**Comment by ageryck** [comment]
@qiarie are you working on this issue
cc @ellykits

**Comment by ageryck** [comment]
currently the sync timestamp updates correctly, this need understanding for better training on the meaning of the date for end users
