### ISSUE TITLE
Vaccine Certificate Support

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#24]
Add functionality to 
- [ ] Collect all the requisite information required to generate a vaccine certificate as defined by the FHIR International Patient Summary (IPS) being defined by the WHO Covid-19 Digital certificate working group. (The required resources will be made available via a FHIR API to be consumed by a program like DIVOC that is able to generate vaccine certificates.)

**Comment by ekigamba** [comment]
Notes based on previous discussions within the team and a meeting with IPRD Group

- There are 3 major vaccine certificates across the world

1. DVOC standard used in India - https://divoc.egov.org.in/
2. VCI used in US and other Western countries - http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/
3. WHO Smart Vaccine Certificate which has not been completely defined - https://www.who.int/groups/smart-vaccination-certificate-working-group/about

To make the vaccine certificate accessible useful:
- It needs to be transferrable to the patient
- It needs to be verifiable

One of the ideas was to generate a smart health card as a *signed* JSON document that can be encoded into a QR code and easily transferrable. The idea is a bit rough and would need to be based on a FHIR dependent standard
