### ISSUE TITLE
[Quest] - Support Menu Icons

### ISSUE THREAD

**Issue by ageryck** [opensrp/fhircore#2430]
**Describe the feature request.**
Ability to add configurable overflow menu icons and button icons as shown on the designs below.

**Additional context**
Currently, configurable icons are supported on the navigation menu via this config, a similar implementation is to be added/supported by creating an icon placeholder in the overflow menu items and in the service task button 
```
"menuIconConfig": {
              "type": "local",
              "reference": "ic_children"
          },
```

**Acceptance criteria**
Configurable icons as shown below

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by ageryck** [comment]
![image](https://github.com/opensrp/fhircore/assets/23252704/b8f52486-5ee4-47a5-9f33-cdecb523f149)
![image](https://github.com/opensrp/fhircore/assets/23252704/c330deae-a8bc-4916-9f04-980dcc22527f)

**Comment by ageryck** [comment]
For the service button, since it's one button rendering all tasks the configs should specify icons against the desired task i.e. the ANC task can have a pregnant woman however the sick child will show child icon but both are rendered with the service task button

**Comment by ellykits** [comment]
For `BUTTON` use the following config

```json
   {
                    "viewType": "BUTTON",
                    "smallSized": "true",
                    "startIcon": {
                      "type": "local",
                      "reference": "ic_walk"
                    },
                    "text": "@{taskDescriptionWithStartDate}",
                    "status": "@{taskStatusColorCode}",
                    "visible": "true",
                    "enabled": "@{patientActive}",
                    "actions": [
                      {
                        "trigger": "ON_CLICK",
                        "workflow": "LAUNCH_QUESTIONNAIRE",
                        "questionnaire": {
                          "id": "@{taskQuestionnaireId}",
                          "title": "@{taskDescription}",
                          "saveButtonText": "Save",
                          "taskId": "@{taskId}",
                          "resourceIdentifier": "@{taskFor}"
                        },
                        "params": [
                          {
                            "paramType": "PREPOPULATE",
                            "linkId": "0ea6b537-08b3-48b8-aa83-c70e10fe836b",
                            "dataType": "INTEGER",
                            "key": "albendazole400mgPreviousBalance",
                            "value": "@{albendazole400mgPreviousBalance}"
                          },
                          {
                            "paramType": "PREPOPULATE",
                            "linkId": "236022f2-e608-4e51-a56d-c9e21c4271cd",
                            "dataType": "STRING",
                            "key": "albendazole400mgObservationId",
                            "value": "@{albendazole400mgObservationId}"
                          },
                          {
                            "paramType": "PREPOPULATE",
                            "linkId": "7b02d76c-4752-41d4-98d2-96a1fc91652f",
                            "dataType": "STRING",
                            "key": "albendazole400mgStockOutFlagId",
                            "value": "@{albendazole400mgStockOutFlagId}"
                          }
                        ]
                      }
                    ]
                  }
```

>NOTE: It is named `startIcon` because we may have the icon position to the left (start), right (end) or even center in future. For now we only position the icon on the left side.

**Comment by ellykits** [comment]
![Screenshot_1686575773](https://github.com/opensrp/fhircore/assets/26865532/f355a398-5393-4465-9742-25e987ef0be4)
![Screenshot_1686566453](https://github.com/opensrp/fhircore/assets/26865532/3695583c-c5b5-413d-9b87-e4e3e5e10d04)

**Comment by dubdabasoduba** [comment]
> To be used as the following:
> 
> ```json
>       "title": "Registration info",
>       "titleColor": "@{patientTextColor}",
>       "visible": "true",
>       "enabled": "@{patientActive}",
>       "icon": {
>         "type": "local",
>         "reference": "ic_user"
>       },
>       "actions": [
>         {
>           "trigger": "ON_CLICK",
>           "workflow": "LAUNCH_QUESTIONNAIRE",
>           "questionnaire": {
>             "id": "197312",
>             "title": "Patient registration info",
>             "saveButtonText": "Update registration",
>             "setPractitionerDetails": true,
>             "setOrganizationDetails": true,
>             "type": "EDIT",
>             "resourceIdentifier": "@{patientId}",
>             "planDefinitions": [
>               "201153"
>             ]
>           }
>         }
>       ]
> ```

@ellykits do we get the default (+) task icon if the `icon` is not defined?

**Comment by ellykits** [comment]
Default icons remain the same @dubdabasoduba
