### ISSUE TITLE
Add documentation and enforce reduced usage of FhirEngine.update and FhirEngine.create

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#2455]
**Describe the Issue**

Calling of FhirEngine.update and FhirEngine.create instead of DefaultRepository for similar operations skips some operations performed such as tagging of resources, updating the lastUpdated and proper merging of resourcing before saving resource updates. 

This can lead to:
- Records not syncing to other devices due to the wrong tags
- Records not being syncing during p2p transfer
- Previous resource values being lost when a resource update does not have all the previous resources properties

### Tasks for the issue

- [x] Add clear documentation for `DefaultRepository.create`, `DefaultRepository.update` and `DefaultRepository.addOrUpdate`
- [ ] Integrate Detekt to fail the build when `FhirEngine.update` and `FhirEngine.create` is used in classes other than ConfigurationRegistry and DefaultRepository

**Comment by pld** [comment]
This Detekt? https://github.com/detekt/detekt

**Comment by ekigamba** [comment]
Yea, but I'll first try `ktlint` since we already use it together with `spotless`
