### ISSUE TITLE
[Quest] Broken Edit patient Details functionality 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2456]
**Describe the bug**
There are missing details when trying to populate the edit patient details Questionnaire 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Patient Register
2. Click on a patient 
3. Go to the overflow menu to access the Registration Info that allows you to edit the patient details 
4. See the error

**Expected behaviour**
A user should be able to view previously populated data to be able to make amendments to the patient data

**Comment by karina4050** [comment]
@AnnieMungai 
APK: 0.2.4-rc1
This passes QA.
