### ISSUE TITLE
Update "Other Patients" name on the app drawer.

### ISSUE THREAD

**Issue by Lentumunai-Mark** [opensrp/fhircore#2458]
**Describe the feature request.**
Currently, Other patients items on app drawer, one cannot change the name "Other Patients". However, I would like to suggest some flexibility such that one can define a custom name.

**Additional context**
![image](https://github.com/opensrp/fhircore/assets/90028422/b8a3d7af-5df8-41c3-acc5-3f5e36ae8d4f)

**Acceptance criteria**
One should be able to define a custom display name on the config and reflect on the app.

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open app drawer
3. One should be able to see the name defined.

**Comment by dubdabasoduba** [comment]
Nice job, implementing this in a configurable way.
