### ISSUE TITLE
[OpenSRP 2] Refactor QuestionnaireViewModel.kt 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2470]
**Describe the Issue**
Refactor QuestionnaireViewModel.kt

**File** https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt

This code has some failing Conditions as described in the following line of code  

https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt#L204

**Context** 
1. We need to underhand why we need to declare the resource type before performing the extraction. is it necessary? We may need to have better handling of how we parse data before extraction  (Patient, Group, Encounter, ...)
2. There are other code smells that may need to be looked into also in this class 
3. Resolve some of the open TODOs in the code too

**Comment by pld** [comment]
@f-odhiambo can you please make this issue more specific than "refactor"? Fine if we need multiple issues, eg maybe this is about resourceType and you can add detail on that, then each TODO can be it's own separate issue

**Comment by dubdabasoduba** [comment]
@f-odhiambo could we have a conversation on this change so it can be clearly documented? This class has been changed a lot I would like us to iron out its functionality before implementation.

**Comment by ekigamba** [comment]
The three TODOs are related to closed issues most of which have been implemented. We might only need to review this https://github.com/opensrp/fhircore/issues/900. @maimoonak seems to have more context on the issue
