### ISSUE TITLE
App configuration resources persisted as local changes that need sync up

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#2511]
**Describe the bug**
Currently when we sync our Composition resource and referenced resources they are persisted/interpreted as new resources that need to be Synced up back to the cloud.

We need to refactor the implementation to use a Download Manager so that they are persisted as remote resources. There is no (exposed) API currently to directly persist any resources as _remote resources_

**Comment by dubdabasoduba** [comment]
@ndegwamartin closing this since both PRs are merged
