### ISSUE TITLE
[Gateway] Update the sync filter to exempt all the resources referenced on a List referenced on the Composition 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2527]
**Describe the bug**
- The resources referenced on the Composition are exempted from sync filtering since all those resources are universal and should be synced for every user.  
- A List resource is used to hold a reference of some dynamic resources that are also dynamic. The sync filter exempts the said list from filtering but does not exempt the referenced resources. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Update the Composition resource to add a List e.g [here](https://github.com/opensrp/fhir-resources/blob/804c419e9bfc9b0e1223daf93053a3b848aaecd9/ecbis_liberia/app_configurations/ecbis_cha_preview/gateway_composition_config.json#L1292-L1307) 
2. Log in to the app using the new composition resource. 
3. Check the app for the resource's reference on the List
4. See the error

**Expected behaviour**
- [ ] All the resources referenced on a List referenced on the Composition should be synced down without filtering.

**Comment by ndegwamartin** [comment]
**Implementation Plan**
- We can achieve the implementation by enhancing the _OpenSRPSyncAccessDecision_ class in the FHIR Gateway.
- We'll use the _Post Process_ feature supported by the Gateway to enhance the proxy's responses via _Plugins_. 
- We'll then trigger the feature/mode using a HTTP Header sent by the client 
- Header **FHIR-Gateway-Mode** with a value of **list-entries**
- **Note**: The Header above can be utilized for all future use cases for composite endpoints e.g. to fetch Practitioner Details add a value **practitioner-details**
