### ISSUE TITLE
[Quest]  Sync getting beyond 100%

### ISSUE THREAD

**Issue by ageryck** [opensrp/fhircore#2541]
**Describe the bug**
App syncs beyond 100%

**To Reproduce**

Install fhircore sync data either for the first time or upon clearing data, te sync start and moves beyond 100 % and keeps counting.

**Expected behavior**
Sync should stop at 100% and redirect the user to the default register.

**Screenshots**

<img src="https://github.com/opensrp/fhircore/assets/23252704/b08b82c4-8bf6-489f-ae05-a38a43279974" height="600" width="300"/>

**Additional context**

**Comment by pld** [comment]
potentially related project issues:
- https://github.com/opensrp/fhir-resources/issues/1965
- https://github.com/opensrp/fhir-resources/issues/1986

**Comment by ageryck** [comment]
Noted this only happens to me on `main` branch, I have tried these two branches and they seem okay for syncing down;
`fix-profile-data-refresh`
`opensrp-0.2.4`

**Comment by ageryck** [comment]
Recommended sync stats [page](https://github.com/opensrp/fhircore/issues/2394#issuecomment-1567097232) is now available however the toast message indicates sync successful while the stats page indicates unsynced resources, this is misinforming the users

**Comment by ageryck** [comment]
New info noted is if the sync encounters an HTTP error, it restarts resetting the sync percentage to zero
cc @dubdabasoduba

**Comment by madrinekariuki** [comment]
@AnnieMungai 
https://github.com/opensrp/fhircore/releases/tag/v0.2.4-rc3

 This passes QA

- sync stops at 100%. 

https://github.com/opensrp/fhircore/assets/84722169/b7318b4a-a80f-450f-bbb3-005a9144066c

**Comment by pld** [comment]
great! closing
