### ISSUE TITLE
Refactor _revinclude and _forward include Search API implementation on RegisterRepository

### ISSUE THREAD

**Issue by ellykits** [opensrp/fhircore#2563]
Update the code to use the[ new APIs ](https://github.com/google/android-fhir/pull/1978)provided via the Search DSL.

**Comment by f-odhiambo** [comment]
Pending refactoring on Adytiya PR https://github.com/google/android-fhir/pull/1978

**Comment by pld** [comment]
marking as blocked while we wait for Aditya's PR
