### ISSUE TITLE
Notice E0 - Shelf Readiness: Project Blog post published on the website and/or on Digital Square website

### ISSUE THREAD

**Issue by mwkhan1983** [opensrp/fhircore#257]

**Comment by f-odhiambo** [comment]
Draft Available here  - https://docs.google.com/document/d/1LovqXic6GaVhX00R9WBc-9bNND9b3Ep40I4FgR8yROM/edit# 

CC @mwkhan1983

**Comment by f-odhiambo** [comment]
Updated https://ona.io/home/improving-automated-testing-interoperability-and-privacy-of-opensrp/
