### ISSUE TITLE
Enable Logging of user Activity on the App

### ISSUE THREAD

**Issue by samkanga** [opensrp/fhircore#2574]
**Describe the issue to be researched**
From a discussion with PATH, they are seeking a non functional requirement where the user activity on the app would be logged and uploaded into a space where it can be reviewed based on need. This is meant to support any audit on a users action while interacting with the app. Some of the logs bing sought include:

1. Log all activities performed by the user
2. Log access to views of individual client records
3. Log access to data summaries, reports, analysis, and visualization features (e.g. in app reports or charts)

Request **1** summarises the request from **2** and **3**.

**Describe the goal of the research**
The outcome is that a manager will be able to access a report that provides all the actions conducted by a user on the device. 

**Describe the methodology**
Considerations to be made include:
1. How the logging can be achieved on the app
2. How the logged details can me submitted to a central place for reporting
3. What is the best option for visualising the logs

**Comment by dubdabasoduba** [comment]
https://github.com/opensrp/fhircore/discussions/2528
