### ISSUE TITLE
Sync Progress UX Update

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#2606]
**Describe the feature request.**
Currently the implementation of initial sync is such that once it fails to complete it gives the user the feedback on the failure amongst retries but allows the user to interact with the application by dismissing the Sync progress dialog.

Previously the app would block the user with the sync progress dialog until after all the default retries are complete but then allow the user to interact with the application.

From the conversation [here](https://github.com/opensrp/fhircore/issues/2575) sounds like the consensus is to block the user from using the app until all data in the initial sync has successfully been synced down.

**Additional context**
Related conversation here https://github.com/opensrp/fhircore/issues/2575

**Acceptance criteria**
- [x] When any of the endpoints sync fails the sync progress dialog should NOT dismiss

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.

1. Simulate a condition where initial sync down fails for some endpoints e.g. corrupt data, missing permissions, network failure
2. Fresh install app and login to the app
3. Initiate initial sync

**Implementation plan (For Engineers)**
- Disable dismissal of initial sync Progress dialog in case of a Sync Glitch or Failure. Only dismiss on successful sync for all endpoints.

**Comment by pld** [comment]
This can be the longer terms fix issue that we want to get into the next release. For a patch on the current release, let's revert to this:

> Previously the app would block the user with the sync progress dialog until after all the default retries are complete but then allow the user to interact with the application.

**Comment by AnnieMungai** [comment]
0.2.5rc2
Sync complete only shows when the sync is complete and successful. No failures were noted on the initial sync.

**Comment by joyce-x-chen** [comment]
@ndegwamartin there have been instances where initial sync did not complete successfully, yet I'm still able to interact with the app. This happened when I was testing the SID FHIR apps and encountered the issue where sync would get stuck (https://github.com/onaio/fhir-resources/issues/2900). Is there a new issue for that? Or should this issue be re-opened?

**Comment by pld** [comment]
looking at the merged branch, is this is main? the branch is a merge into 0.2.4, not sure if we merged 0.2.4 into main later on.

If it is in main, let's open a new issue for the problem with interaction allowed without initial sync completing, if it is not in main, let's get it into main and wait to open that issue until we see a re-occurrence on a release with this fix
