### ISSUE TITLE
Progress dialog not displayed when in app reports are being generated

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2634]
**Describe the bug**
A progress dialog should be displayed when generation of reports starts and hidden when complete as shown in the logic at the start and end of this [code block](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt#L285-L337)

At the moment when report generation takes quite a bit of time there is no visual cue presented to the user to indicate that processing is happening in the background.

**To Reproduce**
1. Go to navigation drawer
2. Click on Service Delivery Reports
3. Click one row on the CHA selection screen
4. On the Select Date Range screen select a month
5. On the Reports screen click on a type of report
6. Notice there is a moment where no visual cue is presented to the user that somehting is happening before the app navigates to the report results screen

**Expected behavior**
A progress dialog should be displayed to indicate that report generation is happening in the background.

**Comment by madrinekariuki** [comment]
This passes QA.
https://github.com/opensrp/fhircore/releases/tag/v0.2.5-opensrp-rc3

https://github.com/opensrp/fhircore/assets/84722169/0f8dd4db-213d-4193-ba8e-2332f2afcfaf
