### ISSUE TITLE
Rename measure reports main screen title.

### ISSUE THREAD

**Issue by Lentumunai-Mark** [opensrp/fhircore#2652]
**Describe the feature request.**
This entails renaming the measure reports screen title to "Select Month" instead of "Selecting Date Range," as the user's action involves choosing months rather than specific dates. This change will be implemented in the "strings.xml" file.

**Additional context**
![Screenshot from 2023-08-08 10-32-53](https://github.com/opensrp/fhircore/assets/90028422/2a1a29fb-e281-4da5-9dbb-9d2958e8d7d8)

**Acceptance criteria**
- The screen title should display as "Select Month" throughout the app.
- The change should only affect the measure reports screen.

**Area path**
1. Login to the app.
2. Click on the drawer icon so as to see the side menu.
3. Click on "Service Delivery Reports."
4. Checkout the screen title.

**Implementation plan (For Engineers)**
- Locate the "strings.xml" file in the app's resources.
- Search for the string resource associated with the measure reports screen title.
- Update the string value to "Select Month."
- Verify the change in the app's UI and test for any layout issues or inconsistencies.

**Comment by madrinekariuki** [comment]
https://github.com/opensrp/fhircore/releases/tag/v0.2.5-opensrp-rc3 
This passes QA
