### ISSUE TITLE
Build the Community Health Worker (CHW) application for SID

### ISSUE THREAD

**Issue by MargaretNjenga** [opensrp/fhircore#2661]
This is a request to build the community health worker application.
Linked here is the[ data dictionary](https://docs.google.com/spreadsheets/d/1Y8KcFRVn_pvZ7Pq3mQRzbHUTACwLILGW/edit#gid=125600017)
The questionnaires are ready.
The CHW app is being prepared in readiness ahead of the ThinkMD integration.

**Comment by f-odhiambo** [comment]
@MargaretNjenga Kindly move this issue to the correct repo
