### ISSUE TITLE
OpenSRP FHIR Gateway repository diff to upstream main

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#2674]
**Describe the Issue**
We need to create the accurate diff of chances between the OpenSRP repo and the FHIR Gateway upstream repo. This will help determing which changes can be contributed back upstream, which could be refactored in to plugins or which changes can be made onto upstream to enhance the Gateway.

Currently the PR introduces extra changes that are not required leading to a bloated PR. Cherry picking of the correct changes is required to get the correct diff.

https://github.com/google/fhir-gateway/pull/179

**Comment by f-odhiambo** [comment]
This is DONE
