### ISSUE TITLE
Add a flavor for the WHO EIR reference app

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2690]
**Describe the feature request.**
- We need to add a flavor to the WHO EIR reference application

**Additional context**
- Here are the items to use
    - App Label: WHO EIR 
    - App ID suffix: `.who_eir`
    - App Name suffix: `-who_eir`
    - App Logo: @AngelaKabari  Please provide this

**Acceptance criteria**
- [ ] We should be able to build an app with the above name and id. 

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by AngelaKabari** [comment]
@owais-vd Please use the WHO logos [available here](https://drive.google.com/drive/folders/19iw90fkc1yiwgN-B3bMSW_QavEOkxzL2?usp=drive_link) as a place holder while I get better resolution logos from the WHO team.
