### ISSUE TITLE
[FHIR Core] -  The +Add household button overlays the pagination arrows

### ISSUE THREAD

**Issue by Mstjamush** [opensrp/fhircore#2706]
**Describe the bug**
The +Add household button overlays the pagination arrows

**To Reproduce**
1. Launch app and log in with a user with more than 10 HHs
2. Navigate to the HH register and observe the NEXT> navigation butto

<img width="326" alt="Screenshot 2023-08-22 at 15 38 37" src="https://github.com/opensrp/fhircore/assets/29072646/a56991ba-68eb-4480-98b5-d4a4cf3ba36c">

**Comment by ellykits** [comment]
I think this is an issue because we are displaying the extended fab by default. Plus I think the behavior is consistent with Fabs as documented in [Material 3 Fab button specs](https://m3.material.io/components/floating-action-button/overview)

cc @HenryRae

**Comment by HenryRae** [comment]
@ellykits there should be a margin/padding bottom so the pagination is 16px above the FAB when user scrolls to the last item. see example
![image](https://github.com/opensrp/fhircore/assets/31955469/f3177cf9-5fcc-40b1-bcf6-93a5ded72368)

**Comment by HenryRae** [comment]
@ellykits, @Mstjamush and on scroll, the search should collapse into just an icon, see example above and also other behaviours [here](https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-Apps-~-Design-System?type=design&node-id=10543%3A113075&mode=design&t=W7difyHFt5SnyOhq-1).  Let me know if this is something we can do

**Comment by ellykits** [comment]
This was fixed. I'm closing this issue.
