### ISSUE TITLE
Migrate FHIR Core to the latest FHIR SDK artifacts

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#2708]
**Describe the feature request.**
 FHIR SDK artifacts with the latest changes from the 'master' branch _(including a few extra un-merged PRs)_ have been published. 
 
We need to upgrade and refactor FHIR Core to utilize them on main.
 

**Additional context**
The artifacts have been published under the following signatures

- Common - `org.smartregister:common:0.1.0-alpha04-preview1-SNAPSHOT`
- Engine - `org.smartregister:engine:0.1.0-beta03-preview10-SNAPSHOT`
- SDC - `org.smartregister:data-capture:1.0.0-preview15-SNAPSHOT`
- Workflow - `org.smartregister:workflow:0.1.0-alpha03-preview1-SNAPSHOT`
- Knowledge/IG - `org.smartregister:knowledge:0.1.0-alpha01-preview2-SNAPSHOT`

The un-merged PRs included are:

-  https://github.com/google/android-fhir/pull/2032
-  https://github.com/opensrp/android-fhir/pull/1
-  https://github.com/google/android-fhir/pull/1669
-  https://github.com/google/android-fhir/pull/2132
-  https://github.com/opensrp/android-fhir/pull/9

**Acceptance criteria**
- [ ] Migrate common library
- [ ] Migrate engine library
- [ ] Migrate SDC library

**Workflow** and **Knowledge/IG** will probably break the app entirely so can be upgraded at a different point or tracked on a different ticket cc @maimoonak @allan-on @f-odhiambo

**Comment by ndegwamartin** [comment]
We now have newer SDC and Engine artifacts from the latest changes on the SDK:

- Engine - `org.smartregister:engine:0.1.0-beta04-preview-SNAPSHOT`
- SDC - `org.smartregister:data-capture:1.0.0-preview16-SNAPSHOT`

**Comment by ndegwamartin** [comment]
We now have newer SDC and Engine artifacts from the latest changes on the SDK:

- Engine - `org.smartregister:engine:0.1.0-beta04-preview2-SNAPSHOT`
- SDC - `org.smartregister:data-capture:1.0.0-preview17-SNAPSHOT`

**Comment by ndegwamartin** [comment]
We now have newer SDC and Engine artifacts from the latest changes on the SDK:

- Engine - `org.smartregister:engine:0.1.0-beta04-preview2-SNAPSHOT`
- SDC - `org.smartregister:data-capture:1.0.0-preview17-SNAPSHOT`

**Comment by ellykits** [comment]
I have referenced your comment above to a new issue so we can close this issue with the PR tagged.
