### ISSUE TITLE
CHW/ANC - Login and authenticate the user to the app

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#272]
- [x] User can log into the application. 
- [x] Users will stay logged into the application unless they actively log out. 
- [x] Token expiration can be set to accommodate an offline first environment.  

**FHIR Reosuecwe to be used/synced**
1. Practitioner 
2. Organization 
3. Location

**Comment by pld** [comment]
how is this different from https://github.com/opensrp/fhircore/issues/65 ?
