### ISSUE TITLE
[P2P] Validate the need for using a custom query for P2P

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2729]
A d[atetime index](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt#L151-L153) and c[ustom search query](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/p2p/dao/BaseP2PTransferDao.kt#L88-L118) were added as part of the performance improvements of P2P on the FHIRCore codebase.

Since then various updates on the Android FHIR SDK have been implemented in order to improve app performance.

We need to validate whether the custom index and query are still needed on FHIR Core codebase.

**Comment by Rkareko** [comment]
Initial tests using staging data show that after removing the custom index and query in FHIR Core P2P transfer speeds slightly improved.

It took `40` minutes to transfer `45253` records with the custom index and query in place.

After removing the custom query and index it took 32 minutes to transfer `45353` records.

QA team may need to run their own tests to validate this as well as verify that data is being transferred correctly.

**Comment by pld** [comment]
Cool that's a 25% reduction in speed, that's definitely an improvement!
