### ISSUE TITLE
[Refactoring] Make Addition of Basic Resources for Z-Score Calculation Generic

### ISSUE THREAD

**Issue by qaziabubakar-vd** [opensrp/fhircore#2747]
Currently, the code for adding Basic Resources for Z-Score calculation is specific to four resource IDs. This can be refactored to make it more generic and flexible. The goal is to allow the addition of Basic Resources based on a dynamic list of resource IDs, making the code more maintainable and extensible.

**Proposal**:

- Create a new function, addBasicResourcesToBundle, that accepts a libraryId and dynamically determines the resource IDs needed for Z-Score calculation based on that libraryId. This function should load the necessary Basic Resources and add them to the input bundle.
- In the existing code block (line 577), replace the hard-coded resource IDs with a call to the addBasicResourcesToBundle function, passing the current libraryId as an argument.

Linked PR: https://github.com/opensrp/fhircore/pull/2745

**Comment by pld** [comment]
This looks great, how can we determine the other resource IDs needed given a libraryID?

**Comment by qaziabubakar-vd** [comment]
> This looks great, how can we determine the other resource IDs needed given a libraryID?

One idea for that is to use a new extension in the `Questionnaire` and add the needed resources for the CQL in that extension, later in the QuestionnaireViewModel, we can get all those resources using something like this:

```
fun Questionnaire.resourcesNeededForCQL() =
  this.extension
    .filter { it.url.contains("cql-dependency", ignoreCase = true) }
    .mapNotNull { it.value?.asStringValue()?.replace("Library/", "") }
```
    
and add it to the bundle, that way it can be slightly more dynamic.

**Comment by qaziabubakar-vd** [comment]
I had a chat with @maimoonak regarding the ticket and she suggested that we can use [QuestionnaireConfig](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfig.kt) as well for achieving this. 

Currently QuestionnaireConfig class doesn't have any input/parameter resource field, which can be added and be used to fetch the dependency resources for the CQL library. 
cc: @pld , @f-odhiambo

**Comment by pld** [comment]
OK that's a good idea, that seems very reasonable
