### ISSUE TITLE
Upgrade SDC and Engine libraries

### ISSUE THREAD

**Issue by ellykits** [opensrp/fhircore#2749]
We now have newer SDC and Engine artifacts from the latest changes on the SDK:

- Engine - `org.smartregister:engine:0.1.0-beta04-preview2-SNAPSHOT`
- SDC - `org.smartregister:data-capture:1.0.0-preview17-SNAPSHOT`

_Originally posted by @ndegwamartin in https://github.com/opensrp/fhircore/issues/2708#issuecomment-1717226524_

**Comment by ndegwamartin** [comment]
We now have newer SDC and Engine artifacts from the latest changes on the SDK:

- Engine - `org.smartregister:engine:0.1.0-beta04-preview3-SNAPSHOT`
- SDC - `org.smartregister:data-capture:1.0.0-preview18-SNAPSHOT`
