### ISSUE TITLE
Implement Gzip compression for all requests

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#2753]
**Describe the feature request.**
We need to enforce GZIP for all requests from the android client. This leads to 7x improvements during sync in terms of bandwidth.

**Additional context**
We have confirmed that currently some endpoints do not use `gzip` compression when making requests to the backend e.g custom endpoints during initial sync.

**Acceptance criteria**
The app should login and sync down data successfully for all the endpoints/resources.

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Sync data

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
- On the Android client add the header `Accept-Encoding: gzip` on all outgoing requests to the server
- On the Gateway investigate why custom endpoint `/practitioner-details` breaks with Gzip configuration

**Comment by ellykits** [comment]
**Findings**

This header is not present in the download requests `Accept-Encoding: gzip`. The `OkHttp` client responsible for performing the requests is in the Android FHIR SDK code. FHIRCore HTTP clients will also need to be updated to include this header  esp. for the endpoint that returns practitioner-details.

**Comment by pld** [comment]
nice, this is kinda a great finding, since we should get a speedup from having gzip on, is there an issue on the SDK yet for this?

**Comment by ellykits** [comment]
No issue yet

**Comment by Rkareko** [comment]
When a breakpoint is added in the OkHttpCall.java class in the parseResponse function that is part of the Retrofit package, and then run rawResponse.networkResponse(), you will see that in the request headers, gzip is set as the encoding method when running fhir core agaimst the stage server `https://fhir.labs.smartregister.org/fhir/Patient?organization=144238&_count=100&_sort=_lastUpdated&_summary=count`

![fhir_core_request_header](https://github.com/opensrp/fhircore/assets/47570855/38220334-4fc6-4cbc-aea5-aa6dc6839f40)

**Comment by Rkareko** [comment]
Apps pointing to the gateway also have the gzip encoding header as seen below

![fhir_core_gateway](https://github.com/opensrp/fhircore/assets/47570855/21232e86-d3bd-42cf-97ac-550f5b126847)

**Comment by ellykits** [comment]
This issue can be closed. As verified by the screenshots logs shared above by @Rkareko.
