### ISSUE TITLE
Set Color opacity on Compound Text & Button properties

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2812]
Use case : Fade the buttons that the user should not be able to action 

Applies on
1. Compound Text
2. Actionable Button 
- Name of property   = `colorOpacity`
- To be applied to text color and background color

**Comment by f-odhiambo** [comment]
@HenryRae kindly provide some screenshots to this ticket based on the discussions with @ellykits

**Comment by HenryRae** [comment]
[Link to designs](https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-Apps-~-Design-System?type=design&node-id=23314%3A15781&mode=design&t=chSPb42ZpL9HPWbG-1)

![image](https://github.com/opensrp/fhircore/assets/31955469/64f3c6cf-98bd-48a0-b049-0d71ad8f083d)

**Comment by sharon2719** [comment]
@f-odhiambo can you assign @brandy-kay ?

**Comment by ellykits** [comment]
**Implementation Plan** 

Implement a new configuration property for CompoundText and ActionableButton that will be used to change the opacity of the content and background colors used in those widgets. I think we can create a new issue for this PR labeled Fix opacity color for disabled button. I will add this comment to the issue tagged here.

@brandy-kay

**Comment by brandy-kay** [comment]
okay @ellykits
