### ISSUE TITLE
Logout user from the application  

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#282]
- [x] User can log out of the application. 

**Question**: Do we need to clear the data locally stored on the device?

**Comment by ndegwamartin** [comment]
@f-odhiambo I think we should only clear session data. also not sure if this is already implemented by @maimoonak ?

**Comment by ndegwamartin** [comment]
Something else to factor in is that we support _offline login_. 

So the log out mechanism should log one out of the app but still leave the ability for one to log back in while offline

**Comment by pld** [comment]
some questions

- how long does the ability to log back in offline last for? is that configurable
- how is offline log in implemented?
 
we may want to do sec review on this
