### ISSUE TITLE
Launch dialer to initiate phone call when a phone number is clicked on the client/patient profile

### ISSUE THREAD

**Issue by allan-on** [opensrp/fhircore#2822]
**Describe the feature request.**

When the phone number is clicked on the default profile, a dialer should be launched to initiate a phone call (to the patient) 

**Additional context**

![profile_phone_number](https://github.com/opensrp/fhircore/assets/16164649/81bde9c8-4a7e-4590-9812-4938db1670f4)

**Acceptance criteria**
- Clicking on the phone number launches the phone dialer with the patient/client's phone number

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _checklist_ for the various ordered tasks that must be completed.

**Config**
1. With the assumption we are using COMPOUND_TEXT widget to display the text. We need to set the following properties:

```json
"clickable": "true",
"primaryTextActions": [
    {
      "trigger": "ON_CLICK",
      "workflow": "LAUNCH_DIALER",
      "params": [
         {
             "paramType": "PARAMDATA",
             "key": "phoneNumber",
             "value": "@{phoneNumber}"
         }
      ]
    }
]
```

The `@phoneNumber` is the name of the rule executed to provide the user's phone number by extracting it from the relevant resource previously loaded for the Profile e.g. from the Patient's contact. If the number is not extracted via a RULE please write one.

> NOTE:  The extracted phone number should contain the country code for best practices. E.g. If the patient is from Kenya +254712347891 (+254 as the country code). No need to use application configuration for the country code. 

**Code changes**
1. Introduce a new [ApplicationWorkflow](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/workflow/ApplicationWorkflow.kt) called `LAUNCH_DIALER`
2. This workflow will be triggered via `ON_CLICK`  [ActionTrigger](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/workflow/ActionTrigger.kt) as indicated in the configuration sample above.
3. Implement functionality to launch a dialer in the [ConfigExtensions#handleClickEvent](https://github.com/opensrp/fhircore/blob/eb90db59c6e17972ed68c54d166b892f7c45d7f3/android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensions.kt#L41C31-L41C31)
4. Launch dialer function should launch an intent from any context. In the above `handleClickEvent` function you can obtain the context from the `navController` parameter. See the [LoginActivity#launchDialPad](https://github.com/opensrp/fhircore/blob/eb90db59c6e17972ed68c54d166b892f7c45d7f3/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginActivity.kt#L129) implementation for reference on how to launch a dialer.
5. Call the extension function `Context.getActivity()` if the activity is needed instead of just the instance of the`Context`.

**Comment by kelvin-ngure** [comment]
@allan-on @pld @ellykits @dubdabasoduba @ndegwamartin 
https://docs.google.com/document/d/1F5ru2RALVjDekaC8icK9gPw5c85tOhkxzj9NHUJbGHU/edit

I have drafted a design doc for this issue. @ellykits, I had trouble deciding where the configuration information e.g whether or not to call directly or just open the dialer should be stored since the [documentation](https://docs.opensrp.io/engineering/android-app/configurations/user-interface/profile-config) on the Profile Configuration hasn't fully fleshed out its properties. I would appreciate all your feedback to gain more clarity on the project as a whole

**Comment by ellykits** [comment]
> How would you manage this through configs?
> 
> It seems reasonable that in the config you can specify for any field that it should launch a dialer. Some issues
> 
> 1. one issue is we wouldn't be able to enforce the type of data that launches into the dialer, if you launch text into a dialer is that fine?
> 2. when you launch a dialer, does it place a phone call or just load the number up into the phone ready to be placed?
> 3. we usually (sometimes, often, never?) store country codes w/phone numbers, will placing the call be an issue if those aren't included?
> 4. do we need any sort of visual indication that this is clickable vs the other fields?

To answer your questions @pld:
1. Passing a text into the dialer is fine. The required format is actually `tel:0123456789`
2. When you launch the dialer it DOES NOT place a phone call. It will just load the number.
3. We'd need to provide the country code (via config)
4. We can use a different color code for the text (default to primaryColor - some shade of blue) to differentiate the text from the rest without click action cc @HenryRae.

**Comment by ellykits** [comment]
> @allan-on @pld @ellykits @dubdabasoduba @ndegwamartin @DebbieArita https://docs.google.com/document/d/1F5ru2RALVjDekaC8icK9gPw5c85tOhkxzj9NHUJbGHU/edit
> 
> I have drafted a design doc for this issue. @ellykits, I had trouble deciding where the configuration information e.g whether or not to call directly or just open the dialer should be stored since the [documentation](https://docs.opensrp.io/engineering/android-app/configurations/user-interface/profile-config) on the Profile Configuration hasn't fully fleshed out its properties. I would appreciate all your feedback to gain more clarity on the project as a whole

Requested access to the document.

**Comment by kelvin-ngure** [comment]
> 1. assing a text into the dialer is fine. The required format is actually `tel:0123456789`

just provided access. sorry for the inconvenience

**Comment by ellykits** [comment]
@allan-on We'll need an implementation plan written for this. I will take @kelvin-ngure through how the configurations work/interact with FHIR resources before writing the plan. cc @dubdabasoduba

**Comment by ellykits** [comment]
@allan-on @dubdabasoduba @Rkareko @kelvin-ngure I have updated the implementation plan for the issue. For inquires @kelvin-ngure contact @Rkareko .

**Comment by kelvin-ngure** [comment]
> @allan-on @dubdabasoduba @Rkareko @kelvin-ngure I have updated the implementation plan for the issue. For inquires @kelvin-ngure contact @Rkareko .

thanks for the implementations plan @ellykits
