### ISSUE TITLE
Allow option to hard-code App ID in properties and skip App ID entry screen

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#2849]
**Describe the feature request.**
Currently, the app workflow always requires the user to enter an App ID. Once this is entered it triggers a sync to the backend for all the apps configs & content.

Some of the apps will only ever expect an App ID, e.g. their icon and name might imply only a single App ID. This mean that we can hardcode the App ID in the APK and skip the App ID entry screen.

**Additional context**
- This should not modify any of the existing functionality when an App ID is not hard coded.
- Use the existing properties files where the FHIR API base URL is defined to define the App ID

**Acceptance criteria**
- [ ] when an App ID is defined in the built APK properties file
    - the App ID entry screen does not show
    - the App ID in the properties file is set anywhere an App ID entered in the screen would have been set
- [ ] if no App ID is defined, everything work as it currently does

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Open an APK with the App ID in the properties file
    1. Verify the App ID entry screen does not show
1. Open an APK without the App ID in the properties file
    1. Verify the App ID entry screen does show

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
I'm gonna update the text a bit to clarify what workflow means in this context so it does not conflict with how we use it as healthcare workflow...

**Comment by kelvin-ngure** [comment]
@ndegwamartin @pld what would you want done in the case where the user defines a debug app id but doesn't have the folder in their assets?

**Comment by pld** [comment]
this looks great! I think that's exactly what I would have suggested
