### ISSUE TITLE
CHW/ANC SubTask - User can assign a head of household	

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#285]
The Head of Household is the mom but can be updated. Core caregiver is defined as the mom

1.5 days FTE + 20% buffer

![image](https://user-images.githubusercontent.com/4540684/125638166-676e8c96-7fd4-403d-b468-1029a4abea3c.png)

**Comment by maimoonak** [comment]
The flow can not map exactly as mentioned on mockups. Since Family is a person so the registration of family and members would be separate as in #276 . ANC Registration is gettign updated with this https://github.com/opensrp/fhircore/issues/416 .

**Comment by maimoonak** [comment]
https://github.com/opensrp/fhircore/pull/547 - Family , head and member registration was done with this PR https://github.com/opensrp/fhircore/pull/547. We can not change HHH for now. At what point we should change it and what should be the flow. i.e. we need to make deallocate first and allocation next in same flow

@f-odhiambo

**Comment by pld** [comment]
Let's start a new issue or changing HHH
