### ISSUE TITLE
Info Gateway Onboarding guidelines

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2851]
**What we want to achieve**
- We would like to build an Engineering Info Gateway onboarding documentation. 
- The idea is to document what it takes to understand the following. 
    - How to deploy and test the Info Gateway locally and on production.  
    - How to add plugins to the Info Gateway. 
    - How the different plugins work 

**Expected Outcomes**
- [ ] Updates to the Gateway [Documentation](https://docs.google.com/document/d/1DuTYm8hUSG9kYzGEUEbkMQKu8A50GPs_LoTcihPLVUs/edit?usp=sharing) where necessary.

**Comment by pld** [comment]
Can we move this to the `docs` folder?

**Comment by ndegwamartin** [comment]
> Can we move this to the `docs` folder?

Yeah we can. @sharon2719 was looking to help with moving them to the `docs` folder. Perhaps she can do it as part of this ticket or we can create separate ticket for that.

**Comment by pld** [comment]
Let's have a PR w/changes to the docs close this ticket

**Comment by sharon2719** [comment]
> Let's have a PR w/changes to the docs close this ticket

Doing that
