### ISSUE TITLE
CHW/ANC SubTask - User can view a patient's details

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#286]
Patient Details 
- [ ] Name , ID
- [ ] Upcoming  service 
- [ ] Last seen  - Encounters 

1.5 days FTE + 20% buffer

![image](https://user-images.githubusercontent.com/4540684/125637527-6ee0fdeb-c988-439a-9a09-59e857f39db9.png)

**Comment by pld** [comment]
might depend on https://github.com/opensrp/fhircore/issues/159

**Comment by RaaziaTarique** [comment]
@kimigxfoxy shared ANC details xml with you check slack.
