### ISSUE TITLE
Enhance the DOB unknown behavior

### ISSUE THREAD

**Issue by HenryRae** [opensrp/fhircore#2866]
**Describe the bug**
When "Date of Birth Unknown" checkbox is selected, the DOB input field above is hidden and the age input field is displayed below the checkbox.
<img width="357" alt="Screenshot 2023-11-17 at 14 06 18" src="https://github.com/opensrp/fhircore/assets/31955469/961e62be-b894-437a-b2ce-9fd06ec5d8d3">
<img width="354" alt="Screenshot 2023-11-17 at 14 06 40" src="https://github.com/opensrp/fhircore/assets/31955469/eebf1e50-8e4b-4f5b-b749-e0ce3d25700d">

**How it should behave**
The age input field should also be displayed above the "Date of Birth Unknown" checkbox.

Expected result:
<img width="869" alt="Screenshot 2023-11-17 at 15 03 52" src="https://github.com/opensrp/fhircore/assets/31955469/14ea1627-d760-4a7d-ba3b-46da09e95def">

**Comment by allan-on** [comment]
Transferred to https://github.com/ona-health/hisp-wdf-fhir-resources/issues/151
