### ISSUE TITLE
Enable UI tests on debugNonProxy build variants

### ISSUE THREAD

**Issue by kelvin-ngure** [opensrp/fhircore#2885]
Currenty, if you are on a `debugNonProxy` build variant you can't run UI tests. The `androidTest` folder pictured below disappears and running UI tests is disabled.
![image](https://github.com/opensrp/fhircore/assets/129178453/f6665789-42fa-4d2e-8d65-f5d7af31b6b8)

A quick fix to enable testing is to add this into the `build.gradle: quest`

`
android {
   testBuildType = "debugNonProxy"
}
`

However, this disables UI testing for the debug variants. Therefore we likely need an if else statement to enforce testing on both build variants.

**Comment by kelvin-ngure** [comment]
Yes, the ServiceCard tests for instance. Even more interestingly is that @LZRS discovered that they seem to fail on the CI as well but are eventually marked as passed

> I think there are some tests already written targeting the debug variant that would fail for non-proxy variants.

**Comment by kelvin-ngure** [comment]
> Is the debug variant working okay? Can you use that as a workaround? We may in future remove the nonProxy variants once all servers have been migrated to use the gateway.

If working for a team that can't provide a proxy url, then one can't run UI tests

**Comment by ellykits** [comment]
@dubdabasoduba Most projects will be required to use the gateway server is that correct?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba Most projects will be required to use the gateway server is that correct?

@ellykits Yes, most projects will use gateway

**Comment by ndegwamartin** [comment]
Closing this since the corresponding [PR is closed](https://github.com/opensrp/fhircore/pull/2888)

Moving forward we'll want to focus our efforts on Gateway since OpenSRP backend functionality is introduced by the proxy layer cc @kelvin-ngure @dubdabasoduba
