### ISSUE TITLE
Styling update to forms

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2910]
**Describe the feature request.**
Related to [Styling update to lists](https://github.com/opensrp/fhircore/issues/2887) . The padding changes to the forms (Questionnaires) needs changes both on the SDK and on Fhir Core. This ticket will details the changes required on FhirCore

**Additional context**
[Filter options ](https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-(OpenSRP)-Apps-~-Design-System?type=design&node-id=22397%3A69425&mode=dev&t=mx5dRhoa3AHVNcTX-1)- (bottom padding/margin 24px)
[All Forms](https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-(OpenSRP)-Apps-~-Design-System?type=design&node-id=20600%3A241314&mode=dev&t=mx5dRhoa3AHVNcTX-1) - (bottom n top padding/margin 24px)

![questionnaire_content_padding](https://github.com/opensrp/fhircore/assets/47570855/809ab75b-5d02-4729-a034-fcffaebafafb)

**Acceptance criteria**
A check list of all things to verify once the implementation by the engineer is complete

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Children register_
4. Click on _Child profile_
5. Click on _Edit profile_ from menu

**Implementation plan (For Engineers)**

This depends on  [Questionnaire content style customization](https://github.com/google/android-fhir/issues/2353)

**Comment by Rkareko** [comment]
@HenryRae to confirm whether these changes are required.

**Comment by HenryRae** [comment]
> @HenryRae to confirm whether these changes are required.

yes changes are required @Rkareko
