### ISSUE TITLE
Add Indonesia translation files

### ISSUE THREAD

**Issue by SebaMutuku** [opensrp/fhircore#2935]
**Describe the feature request.**
A clear and concise description of the feature or what problem is being solved 

**Additional context**
If available add any other context or screenshots about the feature here.

**Acceptance criteria**
When the app language is changed to indonesia or bahasa, the app string texts should change to Bahasa/Indonesia

**Implementation plan (For Engineers)**
Create a folder called `id ` under `res` folder both in quest and engine.
Paste the translated strings there.

**Comment by dubdabasoduba** [comment]
@dubdabasoduba As we reviewed earlier I think this is caused by the fact that we are overriding the ResourceBundle when processing the `.properties`. This means everything on the `strings.xml` resources is missing.

**Comment by SebaMutuku** [comment]
@dubdabasoduba after thorough investigation, I found out the local read when the language tag is `id` was `in` instead of `id`. So I renamed the folder names to `strings_in` and works both for property files and `strings.xml`.
