### ISSUE TITLE
All Apps: sync progress and sync complete Toasters not showing on Manual sync trigger

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2943]
**Describe the bug**
- In the apps, During sync, the apps are not showing sync progress (usually indicated `syncing` ), when you initiate manual sync .  **nb** the syncing toaster showing only once( first time after trigger) and does not show again.

- After sync is complete, the toaster message `sync complete` is supposed to show but this is not happening on some app (Cadre)

**To Reproduce**
- install an app e.g cadre
- perform an action
-  manually initiate sync
-  observe that : 
    -  syncing only shows the first time consecutively it does not show.
     - sync complete is not showing in some app e.g cadre.

**Expected behavior**
- on manual sync, `syncing` should show whenever the sync button has been clicked and sync is progressing
-  after sync is complete, `sync complete` toaster message should show.

**Comment by ellykits** [comment]
Observer for sync state in user settings screen to fix

**Comment by ellykits** [comment]
Implement this interface `OnSyncListener` in the `UserSettingScreen` to handle the sync events.

**Comment by kelvin-ngure** [comment]
@ellykits your comment just made it click for me that it was the manual sync in the settings, not the drawer. I had failed to replicate this

**Comment by kelvin-ngure** [comment]
@f-odhiambo @ellykits I've been trying out different approaches for this to make the appropriate implementation plan

1. Immediate challenge was that UserSettingScreen is a compose function. I had no direct way of implementing the interface within a function except maybe trying something like this 

```
 val onSyncHandler: OnSyncListener = object : OnSyncListener {
        override fun onSync() {
            // TODO: implement
        }
    }
```
2. There is similar functionality in the RegisterFragment that powers the Manual Sync provided by the drawer

  ----> If we want the Manual Sync in the UserSetting screen to be exactly the same as the drawer one. We end up with a challenge of code duplication. I tried to create a [use case](https://developer.android.com/topic/architecture/domain-layer) to allow both screens to share logic but I ended up with some concerns 

        1. Delegating UI specific work to the view model. My use case intends to have the two screens only make one function call to the view model and then the view model calls the use case. Some functions are currently launched in lifecyclescope, there may be issues with moving all the functionality away from the fragment. Also, I can't access the resource strings outside the UI (at least it is not advisable to do so) so I would need an organized way of passing those strings and deciding when to display which.     I was cutting and pasting a lot of code from the register fragment 
        2. I am cutting and pasting a lot of code away from the UI and into the use case. This includes a lot of the Flows in the RegisterFragment and view model
   ----> If we don't want the Manual sync in the User setting screen to be exactly the same as the drawer one, what functionality should we omit?

**Comment by ellykits** [comment]
Every composable screen in FHIRCore is rendered via a fragment. Implement
the interface on the `UserSettingFragment` and update the
`UserSettingScreen` composable to react to snackbar events.

**Comment by kelvin-ngure** [comment]
@ellykits Thanks for the info! What about the code duplication concern? The implemenation would be similar to that implemented in the RegisterFragment and RegisterViewModel. Does that need to be unified or is it ok if the code is the same?

**Comment by ellykits** [comment]
Code duplication should not be a concern. It's just the way to use Snackbars with compose code. Furthermore, data refresh happens on Registers when sync is completed which is not required in the user settings screen. For the settings UI, you need to log the statuses and display snackbar.
