### ISSUE TITLE
Unable to translate some FHIR resources text

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#2970]
**Describe the bug**
For example, this "display" field in the plan definition for child immunization in Indonesia has the text for "Influenza", https://github.com/ona-health/sid-dto-fhir-resources/blob/38580c12093feb5276a463aa6851f8652d9ffa17/plan_definition/immunization/child_immunization_pd.json#L743, this should display as "Influenza" when set to English and "Influensa" when set to Bahasa, but the text can only be written in a single language, because PlanDefinitions do not support the translation extension.

**To Reproduce**
1. Write a PlanDefinition with an ActivityDefinition that includes a display field
2. Load the PlanDefinition and sync to device and run to generate the ActivityDefinition
3. View the ActivityDefinition in the task list and note that it can not be translated

**Expected behavior**
There is a way to translate text content for display in the PlanDefinition.

**Comment by dubdabasoduba** [comment]
**Other affected resources**
- [ ] MeasureReports

**Comment by pld** [comment]
cc @roywanyaga this is the issue related to translation we discussed

**Comment by pld** [comment]
replaced by https://github.com/opensrp/fhircore/issues/3301
