### ISSUE TITLE
Fix attempt to login with a different user error on first time app login

### ISSUE THREAD

**Issue by ellykits** [opensrp/fhircore#3044]
**Describe the bug**
The application prevents the user from trying to log in with a different username if the initial login fails. This should not happen, the app should only prevent the user from logging in with a different user on subsequent logins only if the previous login attempt was successful.

**To Reproduce**
1. Start a new app, set the application ID
2. Go to the login page, and enter the correct username with the WRONG PASSWORD (deliberately)
3. Notice the login error
4. Clear the username and the incorrect password
5. Now attempt to log in with VALID credentials for a DIFFERENT user

**Expected behavior**
As long as it is the very first time the user tries to log in to the app, they should be allowed to log in with any valid credentials then subsequently, logging in with a different user should be denied. 

**Additional context**
Multi-user login will be allowed in the future but not with the current implementation. The multi-user login was scoped to only work with users belonging to the same Organization/Location etc. For now, only single-user login is allowed.

This fix should also be applied to version `opensrp-0.2.5`

**Comment by brandy-kay** [comment]
@ellykits I would like to work on this issue

**Comment by brandy-kay** [comment]
Hello, @ellykits i have looked through this issue and tried several times with different app variants I have access to the bug is not reappearing the only problem I get is it returns an error saying it **cannot fetch user details and it takes much time loading**  then I click the button and it logged in.

**Comment by brandy-kay** [comment]
@ellykits have a look at this
[auth.webm](https://github.com/opensrp/fhircore/assets/60472476/51c848c1-03f3-4d1e-b3e3-ce705f77ab4e)

**Comment by pld** [comment]
I'm assuming this is fixed?
