### ISSUE TITLE
Refactor Sync status handling  to migrate to CurrentSyncJobStatus

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3059]
**Describe the feature request.**
We need to migrate from using `SyncJobStatus` to using `CurrentSyncJobStatus` which has both work state and SyncJobStatus state representations.

**Additional context**
This follows the upgrade SDK libraries PR https://github.com/opensrp/fhircore/pull/2825 changes

**Acceptance criteria**
A check list of all things to verify once the implementation by the engineer is complete

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Children register_
4. Click on _Child profile_
5. Click on _Edit profile_ from menu

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
Is this cleanup only or do we get a functional benefit from this change?

**Comment by ndegwamartin** [comment]
> Is this cleanup only or do we get a functional benefit from this change?

This is related to the findings here https://github.com/opensrp/fhircore/issues/2942

**Comment by ellykits** [comment]
This should be code cleanup plus it will improve the sync notification UX.
