### ISSUE TITLE
Set up on Transifex

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#306]
Set up Transifex and link it to the FHIR Core repository to allow for language translations.
Once that's done the string.xml files are usually uploaded there and once translations are done we download them (or Transifex creates a PR with the translation changes)
_NB. The PMs also organise for the team that handles the actual translations for a project. i.e. the actual persons who'll do the translations (3rd party partners)_

**Comment by ndegwamartin** [comment]
@f-odhiambo fhircore is now configured on Transifex https://www.transifex.com/opensrp/fhircore/
