### ISSUE TITLE
How to Bundle the Configuration and Target a Specific App Version

### ISSUE THREAD

**Issue by qiarie** [opensrp/fhircore#3061]
**Describe the feature request.**
Limit the content that can be loaded into an APK based on an explicit version defined in the content.

**Additional context**

**Acceptance criteria**
A check list of all things to verify once the implementation by the engineer is complete

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Children register_
4. Click on _Child profile_
5. Click on _Edit profile_ from menu

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by ndegwamartin** [comment]
@qiarie could you share the draft write up on this with the team?

**Comment by qiarie** [comment]
@ndegwamartin Write-up for [Bundling Configurations to Target Specific App Versions](https://docs.google.com/document/d/1y3uMvoSmGdL0KurTkWwP-XiAvkFlSEtRcGgQzLTBrN0/edit?usp=sharing)

**Comment by qiarie** [comment]
Specific tasks are defined in issues [#3150](https://github.com/opensrp/fhircore/issues/3150) and [#3151](https://github.com/opensrp/fhircore/issues/3151)
