### ISSUE TITLE
Add a free text box to a questionnaire if a check box has been selected

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/fhircore#3091]
**Describe the feature request.**
We have a questionnaire that has a question with several check box options. If an answer choice is checked, then we would like a free response text box to appear below the checkbox option so that the provider can capture further information about the choice that has been selected. 

**Additional context**
<img width="207" alt="SPI Checkbox" src="https://github.com/opensrp/fhircore/assets/8417097/9f5aa334-0a38-420e-8f4e-285e5e04d485">
In the screenshot above, if an answer choice is checked, a free response text box titled "Take detailed history" should show up under that choice (e.g., if “Taking pills” is checked, then a free text box emerges right under the choice) to allow the provider to capture details on the nature and quantity of the pills, how frequently, etc

**Acceptance criteria**
- When an answer choice is checked, a text box should appear below that specific checkbox option. 
- If a choice is **not** checked, then no text box should appear below that specific checkbox option. 

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the Columbia Engage App
2. Open a patient profile
3. For the IPC Module 
   - Click on the IPC Session 1
   - When you get to  [Identifying activities to feel better] step (https://docs.google.com/spreadsheets/d/1wiT7ya2HVYbdw7aKN_w73aoCgz7J6GK5USYwxHPrlak/edit#gid=1366189401&range=G56), then the free text boxes for "What relationships make you feel better", "What community activities help you feel better?", "What spiritual activities help you feel better?" , "What other activities help you feel better?" text boxes should appear directly below the respective checkboxes and not at the bottom of the screen.
4. For the SPI Module
   - Click on the SPI: Safety Planning Intervention module
   - Click on sub-form 4 **SPI: Psychoeducation and Safety Planning Intervention**
   - When you get to [(Step 6A: Making the environment safe)](https://docs.google.com/spreadsheets/d/1wiT7ya2HVYbdw7aKN_w73aoCgz7J6GK5USYwxHPrlak/edit#gid=1289765342&range=C23), when an answer choice is checked, a text box should appear below that specific checkbox option. 

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
Let's look into options without a product change before we work on this.

**Comment by pld** [comment]
Ah right I see, what we split these up into a different question for each option? Then we could have a different hidden text box show per question directly below it

**Comment by AngelaKabari** [comment]
I agree @FikriMilano  - as long as the UI doesn't look very different then I don't think we would need to convince the client.
