### ISSUE TITLE
Add the ability to switch between a map and register view

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3139]
**Describe the feature request.**
- The Map and Register view ideally displays the same data in different formats. We would like to add the ability to switch between the map and register views.  
- The current UI MockUps show this switching happening via an icon on the application top bar.  
- We would however want to define the switching as a generic workflow that can be triggered from any other location.  

**Acceptance criteria**
- [x] Be able to switch from the Register to Map view using an icon on the top bar
- [x] Ability to define this switching from any other widget on the app. 

**UI Mock UP**
![Screenshot 2024-03-13 at 13 44 33](https://github.com/opensrp/fhircore/assets/4817531/d74cda8a-b0ad-47b7-a978-fff189cf3ed6)

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by aurangzaibumer** [comment]
@AnnieMungai I need this icon - Can you please provide it.
![image](https://github.com/opensrp/fhircore/assets/35099184/380221f4-4669-4aea-ac3c-a579dc20df20)

**Comment by pld** [comment]
@HenryRae can you share that asset ^?

**Comment by HenryRae** [comment]
![map](https://github.com/opensrp/fhircore/assets/31955469/1f62ae6c-da15-492f-a2ae-32905a538e81)

**Comment by AnnieMungai** [comment]
@aurangzaibumer see above ^^

**Comment by aurangzaibumer** [comment]
Thanks - Updating.

**Comment by aurangzaibumer** [comment]
![image](https://github.com/opensrp/fhircore/assets/35099184/2e898e34-0baa-46ad-b966-c49a28570fa7)

**Comment by AnnieMungai** [comment]
@Mstjamush this is ready for QA.

**Comment by ellykits** [comment]
@Mstjamush Did you get a chance to QA this?

**Comment by AnnieMungai** [comment]
v.2.0.0rc4- LGTM!
