### ISSUE TITLE
Allows configuration of icons for the location points on the map view

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3141]
**Describe the feature request.**
- The OpenSRP 2.0 geo-widget module allows the display of points on a map. These points can have different icons. 
- This ticket is to add a configuration to allow the definition of the different icons to be used on the points. 

**Acceptance criteria**
- [x] Content authors should be able to define the different icons to use for the location points. 
- [x] The Geo-Widget should display the configured icons for each location point

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by AnnieMungai** [comment]
@Mstjamush this is ready for QA.
