### ISSUE TITLE
Remove patient overflow menu and editing registration info item duplicates patient in household profile

### ISSUE THREAD

**Issue by SebaMutuku** [opensrp/fhircore#3142]
**Describe the bug**

**To Reproduce**
**Scenario 1**
Steps to reproduce the behavior: Remove patient
1. Log in to any app  whose workflow begins with household register
2. Open any household with patients
3. Click on any patient and open overflow menu items
4. Click remove patient and fill in the questionnaire and save it
5. Go to household profile . You will notice that the patient you remove has duplicated on the household profile

**Scenario 2**
Steps to reproduce the behavior: Edit registration info
1. Log in to any app  whose workflow begins with household register
2. Open any household with patients
3. Click on any patient and open overflow menu items
4. Click registration info and edit any field in the questionnaire and save it
5. Go to household profile . You will notice that the patient you edit has duplicated on the household profile

**Expected behavior**
Removing a patient from household should grey out the patient or remove him/her from the household profile based on different app but not duplicate the patient
Editing patient details should save the changes but not duplicate the patient

**Screenshots**.

![image](https://github.com/opensrp/fhircore/assets/36365043/7e9916bd-c583-40bd-b65f-2a32050a48ca)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A21 S]
 - Android version: 11
 - Version 30

**Additional context**

**Comment by f-odhiambo** [comment]
@allan-on Add more context here

**Comment by SebaMutuku** [comment]
Findings.
When an extraction was performed, a patient below payload is created
``` json 
{
        "resourceType": "Patient",
        "id": "7d0121aa-6682-423f-8c3b-2daab283c3b5",
        "active": false
      }
```
An entry is the localChangeEntity is created with the below details
``` json 
[{"op":"replace","path":"\/active","value":false}]
``` 
with patient id above. 
A single patient with id above only exists on the DB and the status is updated to `false`.Below is the sample resource
``` json 
{
  "resourceType": "Patient",
  "id": "7d0121aa-6682-423f-8c3b-2daab283c3b5",
  "meta": {
    "lastUpdated": "2024-03-19T11:06:47.612+03:00",
    "tag": [
      {
        "system": "https://smartregister.org/app-version",
        "code": "Not defined",
        "display": "Application Version"
      },
      {
        "system": "https://smartregister.org/location-tag-id",
        "code": "Not defined",
        "display": "Practitioner Location"
      },
      {
        "system": "https://smartregister.org/care-team-tag-id",
        "code": "13235df1-6229-49a2-933a-cf1dc00ee66d",
        "display": "Practitioner CareTeam"
      },
      {
        "system": "https://smartregister.org/organisation-tag-id",
        "code": "a43bf680-8518-499e-abcc-364dbf8a7008",
        "display": "Practitioner Organization"
      },
      {
        "system": "https://smartregister.org/practitioner-tag-id",
        "code": "1fb68b79-d038-44f2-baed-d41c79c40afa",
        "display": "Practitioner"
      }
    ]
  },
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><div class=\"hapiHeaderText\"><b>MATT </b></div><table class=\"hapiPropertyTable\"><tbody><tr><td>Identifier</td><td/></tr><tr><td>Address</td><td/></tr><tr><td>Date of birth</td><td><span>13 December 1977</span></td></tr></tbody></table></div>"
  },
  "identifier": [
    {
      "use": "secondary",
      "period": {
        "start": "2024-03-14T13:59:03-04:00"
      }
    },
    {
      "use": "usual",
      "value": "d19efa47-eaa6-4e78-bbd3-334bf8d2c5b5",
      "period": {
        "start": "2024-03-14T13:59:03-04:00"
      }
    },
    {
      "use": "official",
      "value": "4444422242224442",
      "period": {
        "start": "2024-03-14T13:59:03-04:00"
      }
    },
    {
      "use": "secondary",
      "period": {
        "start": "2024-03-14T13:59:03-04:00"
      }
    },
    {
      "use": "secondary",
      "period": {
        "start": "2024-03-14T13:59:03-04:00"
      }
    }
  ],
  "active": false,
  "name": [
    {
      "use": "official",
      "text": "Berg",
      "family": "Matt"
    }
  ],
  "telecom": [
    {
      "value": "33333344422",
      "use": "mobile"
    }
  ],
  "gender": "male",
  "birthDate": "1977-12-13",
  "address": [
    {
      "use": "home",
      "type": "physical",
      "district": "46 Brewer Parkway"
    }
  ],
  "generalPractitioner": [
    {
      "reference": "Practitioner/1fb68b79-d038-44f2-baed-d41c79c40afa"
    }
  ],
  "managingOrganization": {
    "reference": "Organization/a43bf680-8518-499e-abcc-364dbf8a7008"
  }
}
```
This might be a catching issue @ellykits, do you have sometime to give some pointers on how to invalidate cache on the app when running any workflow?

**Comment by ellykits** [comment]
Thanks @SebaMutuku for this report. I will verify and revert.

**Comment by SebaMutuku** [comment]
After further investigation, this narrows down to
 ```kotlin 
  private suspend fun searchRelatedResources(
    search: Search,
    relatedResourcesConfigsMap: Map<ResourceType, List<ResourceConfig>>,
    relatedResourceWrapper: RelatedResourceWrapper,
    configComputedRuleValues: Map<String, Any>,
  ) {
    kotlin
      .runCatching { fhirEngine.search<Resource>(search) }
```
which loads data saved in LocalChangeEntity and ResourcesEntity databases but instead of combining the two patients, it returns both as different resources
