### ISSUE TITLE
Add the ability to display statuses on the Locations points on the map view

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3143]
**Describe the feature request.**
- Since we can add different icons for the location points on the map view.  We would want the ability to display statues. e.g. display a green band around the locations icon if all tasks are completed. 
- This status would be defined by executing some rules then, based on the rules' value we choose what status to display. This is almost similar to what we do with tasks. We have a set of colors representing the different statuses we can show then we let the content authors define how the statuses are evaluated

**Acceptance criteria**
- [x] Content authors should be able to define and config the location point status. 
- [x] The geo-widget module should be able to display the status once the correct config are given. 

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by dubdabasoduba** [comment]
@HenryRae  we need a mock-up that shows how the statues and location point icons work together

**Comment by AnnieMungai** [comment]
@Mstjamush this is ready for QA.
