### ISSUE TITLE
Data search optimization for Location Widget

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3179]
**Overview**
We have the **Searchable Multi-select Widget** implemented as defined here https://github.com/opensrp/fhircore/issues/3068. However, loading data has noticeable latency. We need to investigate various approaches to improve this.

The outcomes of this investigation/implementation will probably be re-used to improve other aspects of the application.

**Comment by ellykits** [comment]
The issue on performance occurs only when loading data from the database (similar to other data loading issues reported). Do you know if we need to sync all Location resources? More data result to slower queries. The rendering and search performance is insignificant.

**Comment by ndegwamartin** [comment]
cc @f-odhiambo @dubdabasoduba

**Comment by ellykits** [comment]
The performance here can be mitigated by reducing the amount of Location data needed other than that any optimizations that will be made on SDK-generated queries will benefit us. I'm closing this issue for now. It can be re-opened if there is any particular performance issues raised by QA team.
