### ISSUE TITLE
Enhance Insights screen UX

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3194]
**Describe the feature request.**
Following the feature impelmentation here: [#2873](https://github.com/opensrp/fhircore/pull/2873) , the right now when there are no **Unsynced Resources** the section just disappears. We can improve the UX by still showing the section but then showing a message like - **All resources synced** :heavy_check_mark:

**Additional context**
Screenshot of current state

When all the data is synced
<img src="https://github.com/opensrp/fhircore/assets/110402503/eb6ca86e-cbc3-4665-880b-239e2bf52718" alt="All_resources_synced.jpg" width="300"/>

When we have unsynced data
<img src="https://github.com/opensrp/fhircore/assets/110402503/5e88c7d9-aa78-4469-8bc6-4af7b8b15b31" alt="Some_resources_unsynced.jpg" width="300"/>

**Acceptance criteria**

- [ ] When there are no Unsynced resources there should be a message that shows **_No resources to sync_** or **_All resources synced_**

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Settings_
4. Click on _Insights_

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by ageryck** [comment]
@Raynafs on the same workstream the above screenshot has titles for `App info` vs `Assignemnt Info` mixed up. Please rectify that under the same changes on this ticket.

**Comment by Raynafs** [comment]
Yes sure. Will do so @ageryck
