### ISSUE TITLE
Limit editing of Questionnaire fields not working

### ISSUE THREAD

**Issue by LZRS** [opensrp/fhircore#3213]
**Describe the bug**
Limiting fields that are editable as described [here](http://docs.opensrp.io/engineering/android-app/configuring/editing#limiting-what-is-editable) no longer seems to hide fields after recent sdk updates

**To Reproduce**
http://docs.opensrp.io/engineering/android-app/configuring/editing#limiting-what-is-editable

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Comment by ageryck** [comment]
@LZRS we noted this too on the `0.2.5` branch, we have made some refactor on this [PR](https://github.com/opensrp/fhircore/pull/3218), and the same can be done on the `main` to allow editing through the `readonlylinkids`
