### ISSUE TITLE
Upgrade Kujaku dependencies to the latest

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3215]
Closes https://github.com/onaio/kujaku/pull/369

**Describe the feature request.**
- The mapping feature on FHIR Core uses the [Kujaku Library](https://github.com/onaio/kujaku). This library hasn't been uploaded for a while. 
- This update should focus on the Google Location Services dependencies but we can update all the other dependencies too. 

**Additional context**
If available add any other context or screenshots about the feature here.

**Acceptance criteria**
- [x] Kujaku should use version 21+ of the Google Location Services. 
- [x] All the mapping functionality provided by Kujaku should work as expected with the latest main branch.

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by ndegwamartin** [comment]
Depends on Kujaku PR https://github.com/onaio/kujaku/pull/369

**Comment by f-odhiambo** [comment]
**Update July 1st 2024**

1. CI is still broken and needs maybe to be addressed on CHT

**Comment by f-odhiambo** [comment]
Kujaku libs still have issues with CI  - Aug 5th 

CC @ndegwamartin @dubdabasoduba

**Comment by ndegwamartin** [comment]
Closing this since the corresponding PR on Kujaku is merged to main - https://github.com/onaio/kujaku/pull/369
