### ISSUE TITLE
PDF Generation from HTML

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#3232]
**Describe the feature request.**
Create a feature to process HTML to a PDF

**Additional context**
- Configurations will be addressed in ticket https://github.com/opensrp/fhircore/issues/3235

**Acceptance criteria**
- [x] Must be able to generate PDF based on these [samples](https://github.com/ona-health/columbia-engage-fhir-resources/issues/21#issuecomment-2006905233)

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Use the HTML of the samples
2. Pass it to the class that will generate a PDF
3. Compare it w the PDF samples

**Implementation plan (For Engineers)**
1. Create a class called PdfGenerator in org/smartregister/fhircore/engine/pdf
2. On creation of PdfGenerator, define instance of WebView or PdfRendererBuilder(OpenPDF). By the time we want to generate a PDF, these instance are ready to use, and it should only be defined once
3. Create a public function to launch the generator, that has htmlText as it's parameter. We will call this function on places like user interaction/on click/on submit questionnaire

**Comment by pld** [comment]
Can you please add details on how you will add the PDF generation, like

1) where in the package hierarchy
2) what will the facade look like for the external library (i.e. architect so if we start with webview and switch to openpdf we make minimal changes to the code

plus any other relevant details about the code implementation, thank you!

**Comment by pld** [comment]
cc @ellykits @ndegwamartin

**Comment by ellykits** [comment]
@FikriMilano 
On the implementation plan:

>Create a public function to launch the generator, that has htmlText as it's parameter. We will call this function on places like user interaction/on click/on submit questionnaire

Can this be implemented as new [ApplicationWorkflow](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/workflow/ApplicationWorkflow.kt) that can be triggered via any view actions.
