### ISSUE TITLE
Nested Filter not filtering the resource based on last resource

### ISSUE THREAD

**Issue by syedowaisali** [opensrp/fhircore#3233]
**Describe the bug**
On the main register screen resources are filtered with the nested search but do not correctly pick the nested resource for example if we have multiple related resources then we can't have the option to provide the config to sort and pick up the right related to filter out the parent resource. Moreover, we also need an option to provide a static filter config

**To Reproduce**
1. Go to the Main screen
2. Click on the filter icon button
3. Apply some filter
4. see the wrong filtered result

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

**Comment by ellykits** [comment]
I am closing this. The issue was resolved. New bugs can be reported separately.
