### ISSUE TITLE
Update to OpenSRP 2 Branding

### ISSUE THREAD

**Issue by roywanyaga** [opensrp/fhircore#3238]
**Describe the feature request.**
Update the default application's branding to the new OpenSRP 2 Branding to provide consistency in branding especially for demo applications 

This will include the following:

- Updating the **FHIRCORE APP** launch screen text with the horizontal OpenSRP2 Logo ![opensrp2-horiz-176x28](https://github.com/opensrp/fhircore/assets/84201465/d0be80b8-3829-40cd-b06b-7b3371691be4)
![image](https://github.com/opensrp/fhircore/assets/84201465/3ac5d5b3-e139-46ed-9874-87d3dc960eb4)

- Updating the launcher icon with the OpenSRP2 logo

- On the Login Screen
![image](https://github.com/opensrp/fhircore/assets/84201465/dc56c4cb-e840-427b-95f8-63e14fea58d0)

   - Update the login logo with an OpenSRP 2 logo
   - Update the powered by OpenSPR logo with the new OpenSRP2 horizontal logo.

**Comment by ndegwamartin** [comment]
Looks like we already had the assets provided on this ticket here - https://github.com/opensrp/fhircore/issues/2410

**Comment by roywanyaga** [comment]
> Looks like we already had the assets provided on this ticket here - #2410

There are supposed to be new ones with the OpenSRP 2 branding

**Comment by pld** [comment]
we did or replaced this

**Comment by rowo** [comment]
![Image](https://github.com/user-attachments/assets/665d64f2-9579-4abb-a965-af04ac27bc15)

@roywanyaga here is a new OpenSRP 2 logo file. Do you need anything else for now? What sizes do you need?
