### ISSUE TITLE
Disabled features on the SID Apps Settings page

### ISSUE THREAD

**Issue by MargaretNjenga** [opensrp/fhircore#3256]
**Describe the bug**
Project: SID
- Apps Affected: Bidan, Immunizer, Cadre
- APK:  https://github.com/opensrp/fhircore/releases/tag/v1.1.0.2 
   - Username for all apps: qadata
   - Password: A******3

The following features are disabled on the Settings page of the apps:
- Offline Maps
- Contact Help

**To Reproduce**
1. Log in to any of the SID apps: Bidan, Immunizer, Cadre
2. Click on the Slider Menu and navigate to "Settings"
3. Click on Offline Maps and Contact Help options.
4. The 2 options do not perform any action when clicked.

**Expected behavior**
The 2 options "Offline Maps" and "Contact Help" should have corresponding action when clicked, otherwise, they should be omitted for now.

**Additional context**
Issue reported on SID repo: https://github.com/ona-health/sid-dto-fhir-resources/issues/838

**Comment by pld** [comment]
is this a config issue or a product issue?

**Comment by f-odhiambo** [comment]
@pld  Both. The product component will be resolved via PR https://github.com/opensrp/fhircore/pull/3300
