### ISSUE TITLE
Improve code coverage on FHIR Core

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#326]
We need to increase code coverage on the FHIR core repo. Currently we have 86% code coverage

- [ ] Add unit tests for broader/maximum code coverage

**Comment by pld** [comment]
at >=80% will close

- https://github.com/opensrp/fhircore/issues/241

**Comment by ndegwamartin** [comment]
@syedowaisali90 please note for the unit tests to be effective we need to cover as many edge cases as we can for any feature we are testing. 

Also check out some more recommendations on the OpenSRP wiki [here](https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1345257557/Writing+effective+unit+tests)

**Comment by pld** [comment]
@ndegwamartin what coverage is needed to close this issue?

**Comment by ndegwamartin** [comment]
:@pld _85% to 90+_ would be great especially since the codebase is still young. **99.99%** would be awesome :)

**Comment by pld** [comment]
Cool, let's say 85 to close this issue, updated title

**Comment by pld** [comment]
closing for now, we're over 80, we can follow up on tt but don't think we need an issue to track

**Comment by pld** [comment]
open to track this until we get to 95, updated title to match
