### ISSUE TITLE
G6PD  - FHIR approach 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#33]
We shall be mainly working on the following FHIR  resources

- Patient
- Related Person (Optional ?)
- Questionnaire
- QuestionnaireResponse
- Encounter
- Observation
- ServiceRequest
- DiagnotsticReport
- CarePlan
- Location (Optional)

Later on, we can circle back and  then link the ML kit portion

At the FHIR SDK the application will rely on the following :

- Data Access API - Set of APIs for performing CRUD operations on FHIR resources in the SQLite DB
- Search API - On-device fluent search API allows the application to compose complex search queries to filter FHIR resources and build lists
- Data Capture API - SDC specification implementation
- Sync API - Provides sync capabilities between a FHIR server and the local DB

NB. support for displaying forms and submitting (via Questionnaire/QuestionnaireResponse) and support for clinical decision support may also be core features

Common Features to the Core Android SDK app

- Patient registration 
- Patient search 
- Patient profile view
- Sync support
- Multilingual support (Optional ?)

G6PD specific features

- Image processing engine (IPE)
- Results interpretation module (RIM)

**Comment by pld** [comment]
A request, can you link this out to the existing issues that relate to it? Also some comments

1. I don’t think RIM is G6PD specific, this will definitely overlap w/work we plan to do for mADX on FHIR using Measure and MeasureReports. We can step back even further and recognize the general use-case of displaying metrics in app, this is common to almost all apps, and RIM is the tool that we can use to serve that general purpose.
2. ServiceRequest vs CarePlan resources is something we need to figure out, from previous discussion it sounded like we can get away with only using ServieRequests, @f-odhiambo how would we use CarePlans here? If we do use CarePlans, I think we’ll want PlanDefinitions to generate CarePlans from

**Comment by pld** [comment]
https://github.com/OpenSRP/fhircore/issues/32, is a prereq for the IPE

**Comment by vincent-karuri** [comment]
I think what RIM rides on is not G6PD specific. Again, RIM may just end up being a collection of CQL Libraries that run on top of the more generalized FHIRCore feature that would support evaluating CQL Libraries

**Comment by vincent-karuri** [comment]
Not exactly FHIR-related but general G6PD requirements. Looking at the fine print, I think there are requirements around authx, data encryption (that are guaranteed by current OpenSRP) which we may also want to consider supporting. We need to understand how critical those are as part of the project deliverables.

**Comment by pld** [comment]
Let's create issues for those, we'll need them for fhircore in general

**Comment by vincent-karuri** [comment]
Tentative architecture

![g6pd_architecture_diagram(2)](https://user-images.githubusercontent.com/33488286/116560294-e7947c80-a909-11eb-8325-885a03e2e057.png)

**Comment by pld** [comment]
This is out of date, Host Application is FHIR core and the RIM module is a set of FHIR resources that get loaded into FHIR Core

**Comment by vincent-karuri** [comment]
yea, but I guess one of the features of the IPE module is to be callable from any host application (fhircore can be one such application). 

The RIM module box has a comment about it not strictly being a module per se (but I guess we can emphasize that by removing the box altogether).

**Comment by pld** [comment]
Yep agree, IPE stays as a separate module, we'll have to determine the exact boundary as we get further into its details

**Comment by f-odhiambo** [comment]
Linked to #108
