### ISSUE TITLE
Add Transifex to Current Documentation

### ISSUE THREAD

**Issue by sharon2719** [opensrp/fhircore#3312]
**Describe the Issue**

Current OpenSRP 2 does not have documentation on how Transifex is used. This should be updated based on FHIRCore Context.

- [ ] How to Add Transifex to GitHub Repositories
- [ ] How to SetUp Transifex and push and pull string resources
- [ ] Files Translation using Transifex

**Comment by sharon2719** [comment]
Seems  like the `Page cannot be found` for this.

**Comment by pld** [comment]
we renamed the android-app to app, https://docs.opensrp.io/engineering/app/configuring/internationalization

**Comment by sharon2719** [comment]
I think the current docs has everything that we need. We can close this issue as completed.
