### ISSUE TITLE
Initial Sync stalls when app is running in the background

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3341]
***Apk Vesrion*** - `opensrp-dc-clinic-v0.0.5.apk`
**Device**: `SM-T380`
***Android Version*** - `9`

**Issue Description**
Initial Sync is stalling when the app is pushed to the background. On reopening the app, sync does not progress to completion. It remains stuck at the percentage it was at when the user switched to another app. There are no errors recorded in the logs

**Steps to reproduce**
1. Clear the app's data
2. Initialize a new login session by entering the app ID
3. Log into the app and Set Pin
4. After initial sync starts, switch to a different app

**Expected Results**

- [ ] Initial sync should continue running when the app is pushed to the background until completion

**Comment by f-odhiambo** [comment]
@qiarie Any updates here ?

**Comment by faith-mutua** [comment]
**Apk version** - `opensrp-dc-v0.1.2.apk`
**Device** - `BLUG60`
**Android version** - `9`

Initial sync still stalls when the app is pushed to the background. On reopening the app, sync does not progress to completion. It remains stuck at the percentage it was at when the user switched to another app. There are no errors recorded in the logs

**Comment by ellykits** [comment]
Are they using the latest main? @allan-on Maybe not. This issue was resolved.

**Comment by allan-on** [comment]
> Are they using the latest main? @allan-on Maybe not. This issue was resolved.

Yeah @ellykits you're right. We'll test this with a new release that has the latest changes that are in the `main` branch

**Comment by ellykits** [comment]
Thanks @allan-on

**Comment by ellykits** [comment]
You can close this or leave it open after the test.

**Comment by ndegwamartin** [comment]
> > Are they using the latest main? @allan-on Maybe not. This issue was resolved.
> 
> Yeah @ellykits you're right. We'll test this with a new release that has the latest changes that are in the `main` branch

cc @faith-mutua

**Comment by faith-mutua** [comment]
**Apk versio**n - `opensrp-dc-v0.1.3.apk`
**Device** - `BLUG60`
**Android version** - `9`

@Gental-Giant @ndegwamartin @ellykits @allan-on, I confirm that this is now resolved on both the diabetes Compass and diabetes Compass Clinic apps.

**Comment by pld** [comment]
closing this
