### ISSUE TITLE
Transition experimental performance optimizations to FHIR Core

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3358]
**Describe the Issue**

- [x] https://github.com/google/android-fhir/issues/2561
- [x] https://github.com/google/android-fhir/issues/2559
- [x] Caching the Questionnaires and the corresponding StructureMaps - PR https://github.com/opensrp/fhircore/pull/3461
    - Write back, can sync the first time they are used
    - Write through, can we do the caching in the background? Could cache on Q/SM change, e.g. after initial sync, then first load will be faster
- [x] #3439
- [x] https://github.com/google/android-fhir/issues/2668
    - [x] Parallelize any independent processing that happens after a search query e.g. when the SDK fetches the FHIR Resources from the DB they are returned as JSON documents. These need to be mapped to HAPI FHIR Structures which is a separate operation
- [x] #3440
- [x] https://github.com/google/android-fhir/issues/2531 
       When saving a questionnaire, run as single transaction, and not having to wait for other parts of related operations when queued in other transactions

**Comment by pld** [comment]
@ndegwamartin for the last one in this list, parallelization, do we have existing code that's implementing this? Can you share a link to this? Related, should we open an SDK issue for this or is this something that should live in the client (ie fhircore)

**Comment by ndegwamartin** [comment]
> @ndegwamartin for the last one in this list, parallelization, do we have existing code that's implementing this? Can you share a link to this? Related, should we open an SDK issue for this or is this something that should live in the client (ie fhircore)

The code should reside on the SDK - The custom changes are bundled on this branch, they can be cherry. picked for PRs or discussions so that the SDK team can review first https://github.com/opensrp/android-fhir/tree/test-removed-select-transaction

**Comment by pld** [comment]
Cool, do we have an issue on Android FHIR SDK for that? On the Android FHIR SDK release we default to are we included the changes in that branch / should we be?

**Comment by ndegwamartin** [comment]
> Cool, do we have an issue on Android FHIR SDK for that? On the Android FHIR SDK release we default to are we included the changes in that branch / should we be?

The latter is part of the focus of this ticket

**Comment by pld** [comment]
@ndegwamartin can you split infinite scroll into a new issue?

**Comment by f-odhiambo** [comment]
@LZRS @ndegwamartin Share an update here - Aug 5th

**Comment by qiarie** [comment]
@ndegwamartin @LZRS Should we consider adding a debounce interval to the register search if not already there?

**Comment by ndegwamartin** [comment]
> @ndegwamartin @LZRS Should we consider adding a debounce interval to the register search if not already there?

Yeah we can explore this and evaluate its impact. Depending on the user patterns it may reduce the race conditions for the db connections as well as provide faster responses for users who enter more search characters. The latter may not be noticeable now though because of the scrolled pagination enhancement.

**Comment by ndegwamartin** [comment]
Final item on Questionnaire/SM caching completed/merged to main - https://github.com/opensrp/fhircore/pull/3461
