### ISSUE TITLE
MLS - app strings (not forms) not picking accents

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#3366]
**Describe the bug**
1. When you change the app language to French - some of the app strings are not picking accents. 
2. There are some untranslated strings on the app still. 
![image](https://github.com/onaio/fhir-resources/assets/58034047/1eb59373-577a-4dcc-8158-7e59fa23c63b)

**To Reproduce**
1. Log into the app and complete sync. 
2. On the settings page, change the app language to French.
3. Observe the different parts of the app.

**Expected behavior**
- [ ] All strings on the app can be read in French. 
- [ ] The strings can pick up special characters i.e accent.

**Comment by pld** [comment]
interesting, this looks like an encoding issue

**Comment by pld** [comment]
Replaced by https://github.com/opensrp/fhircore/issues/3370
