### ISSUE TITLE
i18N Bug: MLS for strings not picking special characters e.g. French Accents

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3370]
**Describe the bug**
1. When you change the app language to French - some of the app strings are not picking accents. 
2. There are some untranslated strings on the app still. 
![image](https://github.com/onaio/fhir-resources/assets/58034047/1eb59373-577a-4dcc-8158-7e59fa23c63b)

**To Reproduce**
1. Log into the app and complete sync. 
2. On the settings page, change the app language to French.
3. Observe the different parts of the app.

**Expected behavior**
- [ ] All strings on the app can be read in French. 
- [ ] The strings can pick up special characters i.e accent. 

**Additional context**

**Implementation plan**
- Bulleted pointed list of notes on the plan to address this issue
- Can be added, expanded, and modified by the assignee

**Comment by ndegwamartin** [comment]
Further investigations on the Eusm project where this was originally reported revealed that the French translations contained the malformed content on the server. Doing a fetch on POSTman gives us the response below(screenshot).

<img width="503" alt="Screenshot" src="https://github.com/opensrp/fhircore/assets/10017086/5d9d3cf2-e010-485b-98c8-98ec7bd0f2c2">




This property file needs to be re-uploaded again correctly. Note, the original properties file from Transifex has the correct content - https://github.com/onaio/fhir-resources/blob/1d0d8a0a7720e0c06acc77bfd39080e19c6c9ae4/eusm/configs/translations/strings_fr_config.properties#L37C34-L37C45

**Comment by ndegwamartin** [comment]
For the untranslated strings e.g. those reading `ITEMS` and `CHECKED`, the tooling needs to be updated to handle translations for `primaryText` and `secondaryTexts` in configs for automation. 

```json
    {
      "viewType": "CARD",
      "visible": "true",
      "contentPadding": 0,
      "header": {
        "viewType": "COMPOUND_TEXT",
        "primaryText": "Checked",
        "primaryTextColor": "#000000",
        "fontSize": 18.0,
        "padding": 16
      }
....

    {
      "viewType": "CARD",
      "visible": "true",
      "contentPadding": 0,
      "header": {
        "viewType": "COMPOUND_TEXT",
        "primaryText": "ITEMS",
        "primaryTextColor": "#000000",
        "fontSize": 18.0,
        "padding": 16
      }

```


These can also be manually translated (if they are urgent and are not many).

**Comment by dubdabasoduba** [comment]
@ndegwamartin https://github.com/onaio/fhir-tooling/issues/207

**Comment by dubdabasoduba** [comment]
@AnnieMungai Martin and I have looked into this. We think the app is still breaking for some reason. @ndegwamartin will review and provide a fix

**Comment by ndegwamartin** [comment]
@AnnieMungai after troubleshooting found an issue with FHIR Core translations that needed a patch for languages that contain diacritical marks . The issue should now fixed - PR https://github.com/opensrp/fhircore/pull/3376

**Comment by ndegwamartin** [comment]
@dubdabasoduba  after troubleshooting found an issue with FHIR Core translations that needed a patch for languages that contain diacritical marks . The issue should now fixed - PR https://github.com/opensrp/fhircore/pull/3376 cc @AnnieMungai

**Comment by AnnieMungai** [comment]
LGTM!
