### ISSUE TITLE
Update the target version on FHIR Core

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3374]
![Screenshot 2024-07-08 at 17 11 13](https://github.com/opensrp/fhircore/assets/4817531/bf6132b4-cd8c-474f-a135-4d0f6764adce)

**Comment by ndegwamartin** [comment]
https://developer.android.com/google/play/requirements/target-sdk

**Comment by ndegwamartin** [comment]
![Steps](https://github.com/user-attachments/assets/5030d1d6-949e-47fe-b22a-9e96170f7258)

**Comment by f-odhiambo** [comment]
@ageryck To follow up on this issue. Updated 5th Aug 2024
