### ISSUE TITLE
FHIR CarePlan generator not appending 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#3383]
**Issue** 
The current code generates reference as `123456` instead of `PlanDefinition/123456`

**Resolved**
The PlanDefiniton reference is not correctly appended to CarePlan using StructureMap extraction against a patient. Sample code snippet from the FhirCarePlanGenerator Ln 133

```kotlin
        ?: CarePlan().apply {
          // TODO delete this section once all PlanDefinitions are using new recommended approach
          this.title = planDefinition.title
          this.description = planDefinition.description
          this.instantiatesCanonical = listOf(CanonicalType(planDefinition.asReference().reference))
          // Add the subject's Related Entity Location tag to the CarePlan
          relatedEntityLocationTags.forEach(this.meta::addTag)
        }
```

**Comment by pld** [comment]
Note that the current hunch is that there was a regression when we upgraded to the latest version of the SDK libraries, do have any more info on whether that is correct and what the potential fix is?

**Comment by f-odhiambo** [comment]
Here is a fix to the above issue https://github.com/opensrp/fhircore/pull/3385

**Comment by f-odhiambo** [comment]
> Note that the current hunch is that there was a regression when we upgraded to the latest version of the SDK libraries, do have any more info on whether that is correct and what the potential fix is?

@pld I think this is a new change introduced by the SDK in the latest artifact update. I have shared a hot fix PR but a refactor should follow once product agrees on how stuff should work moving forward
