### ISSUE TITLE
Change the contact number under Forgot PIN

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#3391]
**Describe the bug**
On the login page, the forgot PIN option shows the following generic number to call if a user forgot their PIN: 012-3456-789

**To Reproduce**
1. Click forgot password

**Expected behavior**
Be able to replace the phone number

**Screenshots**

![300042641-9186a230-5f65-43cb-ba3b-448be9bb95ef](https://github.com/user-attachments/assets/73acf3a7-7d04-420a-ac75-68f4f32557a1)

![299561437-cf92113c-cb68-4233-874d-afda595f717a](https://github.com/user-attachments/assets/5ee264ff-0791-4db2-8301-1bf5dc84703d)

**Smartphone (please complete the following information):**
 - All devices

**Additional context**
I think the simplest fix is to create a translation "for the number."

**Comment by Subhraaa** [comment]
Hi! I would like to work on this issue.

**Comment by pld** [comment]
Sounds good! For implementation you can replace hard-coded phone number with a translated string, you can follow the pattern for the other string on this line.

**Comment by Subhraaa** [comment]
can you please share the above uploaded screenshots again as I am not able to view those?

**Comment by pld** [comment]
re-uploaded, you should be able to see them now!

**Comment by Subhraaa** [comment]
Hey sorry you can assign this issue to someone else because I  have never worked in android development

**Comment by sharon2719** [comment]
This might require some scoping and discussion to determine which method would be most suitable to achieve maximum reconfigurability  @pld

**Comment by pld** [comment]
> Hey sorry you can assign this issue to someone else because I have never worked in android development

no worries, done!

**Comment by f-odhiambo** [comment]
@sharon2719 Any update on the failing test here ? Aug 5th Sprint Review 
CC @ndegwamartin

**Comment by sharon2719** [comment]
Reworking them based on @ellykits  comment

**Comment by ageryck** [comment]
@sharon2719 and @ellykits any updates on this PR
