### ISSUE TITLE
Add targetSdk to modules

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#3407]
**Describe the Issue**
We have defined API 34 as our latest targetSdk, but it has not been applied to our modules. Add the targetSdk to prevent this [prompt](https://developers.google.com/android/play-protect/warning-dev-guidance#android_app_compatibility_too_low_warning) to appear when installing the app.

<img width="222" alt="Screen Shot 2024-07-26 at 10 26 31" src="https://github.com/user-attachments/assets/d2a7e1b8-920d-4d12-ab7c-2693dc18101b">

Original issue: https://github.com/ona-health/sid-dto-fhir-resources/issues/909

**Comment by ndegwamartin** [comment]
@FikriMilano which version of the code base are you building from?

**Comment by ndegwamartin** [comment]
Following the merge of this PR this has since been fixed - https://github.com/opensrp/fhircore/pull/3369
