### ISSUE TITLE
Add app version ID to the Login screen 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#342]
Display the app version  based on the release of the code-base 
- [ ] pull (and also store somewhere accessible to the code if doesn't exist) the app version
- [ ] display on log in screen
- [ ] display on info/about screen

See mock attached. This should be updateable based on the app release 
<img width="391" alt="Screen Shot 2021-06-29 at 5 40 27 PM" src="https://user-images.githubusercontent.com/4540684/123817874-3017e880-d901-11eb-902b-3e7e9e8c28ff.png">

**Comment by pld** [comment]
1. is there an info/about screen that you also see this when logged in already? if not we need that
2. that mock has a very prominent version, I'd think smaller type at the bottom might be more appropriate? CC @rowo

**Comment by rowo** [comment]
@f-odhiambo Does this app have a name? 

1. Yes, there is a place we can put the version number — in the menu something like this: https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=247%3A4907. 
2. Yes the logo does look a bit larger than on the other apps. I think this is due to an unfinished login screen from our new Figma files. The change would be to get the "powered by" text the same size as the "show" and lighten it, and make the logo slightly smaller. Here's a link: https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=1765%3A7686

**Comment by MuhammadSalman-7214** [comment]
Currently there can be two ways to achieve this
1. If we say we want to set app version here, then we can write code that can get the latest app version which we set in build.gradle file from Android Studio
2.  If we don't want to use android app version here, then we can set it by calling an api that provides us the latest app version

**Comment by f-odhiambo** [comment]
> 2\. https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=1765%3A7686

@rowo For now, we are referring to it as the Covid 19 Vaccination tracking app or simply Covax Demo app

**Comment by ndegwamartin** [comment]
@MuhammadSalman-7214 I'd go for No. 1

> Currently there can be two ways to achieve this
> 
> 1. If we say we want to set app version here, then we can write code that can get the latest app version which we set in build.gradle file from Android Studio
> 2. If we don't want to use android app version here, then we can set it by calling an api that provides us the latest app version

**Comment by f-odhiambo** [comment]
> Currently there can be two ways to achieve this
> 
> 1. If we say we want to set app version here, then we can write code that can get the latest app version which we set in build.gradle file from Android Studio
> 2. If we don't want to use android app version here, then we can set it by calling an api that provides us the latest app version

@MuhammadSalman-7214 
Addtional comments here 

1. We could fetch it programmatically from here [build.gradle#L39](https://github.com/opensrp/fhircore/blob/f02d4bcdded6a2fba3ac8a867e407ec24e2ea0f0/android/app/build.gradle#L39)
2. The constant would then be BuildConfig.VERSION_NAME
3. We can also use BuildConfig.VERSION_CODE if we need the actual code as well

**Comment by f-odhiambo** [comment]
@Muhammad Salman @ndegwamartin 
1. This is currently showing version 1.0 ? is this valid?
2. Based on the releases we are currently  https://github.com/opensrp/fhircore/releases 0.0.5 to be precise
