### ISSUE TITLE
Update permissions checker is use on Geo-widget module 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#3431]
**Describe the bug**
There  is a permission issue blocking the user from using the maps feature on newer Android API

**To Reproduce**
1. Login to the app
2. Click on caregiver
3. Select the map feature
4. Observe if the user can select the location permissions. The app closes itself when one tries to select the permissions. 

The video can be found here: 

https://github.com/user-attachments/assets/2c9fc0fe-c9b9-42c5-b3d2-beb42debbc48

**Expected behavior**
The user should be prompted to accept the required permissions to use the module 

**Screenshots**
N/A
**Additional context**
N/A

**Comment by AnnieMungai** [comment]
Other comments from the same ticket:
> This issue is coming from the externally managed `kujaku` library I think this issue needs to be fixed there
> https://github.com/onaio/kujaku/blob/3465b99bcbe983ae1a87283101fde443aafcc342/library/src/main/java/io/ona/kujaku/utils/KujakuMultiplePermissionListener.java#L37-L39

Based on this comment, the app closes if the location/storage permission is not given. I think this is correct but we can improve it to redirect the user to the login screen and give the necessary message. 

Kujaku needs the location permissions to work well so it doesn't make sense to not give them. 

An alternative would be to disable all the location-based functionality if permission is not given. This way users can use the other parts of the app that do not need locations

**Comment by AnnieMungai** [comment]
On EUSM - when user installs and runs app on Android 13 - the app does not ask for files and folders permission, and it force closes. 
Steps
1. Download the app on an Android 13 and above phone. 
2. Try the initial login process. Observe.
3. After loggin, App does not request for all the required permissions. 

**Acceptance Criteria**
- [ ] App should ask for all the required permissions including files and folders, photos, and location. 
- [ ] Once all permissions are given, user should successfully log into the app and view items on the map.
