### ISSUE TITLE
Add the ability to define date formats on FHIR core

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3472]
**Describe the feature request.**
- Currently, the date format in FHIR Core is inconsistent. For example, most dates (e.g., Last Sync Date) use the MM/DD format, while others (e.g., Build Date on the Insights page) use YYYY-MM-DD.
- Can we implement a configuration option that allows users to define a consistent date format to be applied across the entire app?

**Additional context**
- https://github.com/onaio/fhir-resources/issues/3354

**Acceptance criteria**
- [ ] Define a standard date format for all dates on FHIR Core
- [ ] Introduce a configuration option that allows implementations to define the date formats to be used throughout the app. 

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Children register_
4. Click on _Child profile_
5. Click on _Edit profile_ from menu

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by joyce-x-chen** [comment]
Thanks for creating this issue @dubdabasoduba! I have definitely heard feedback about date formats across our projects. Here are my two cents:

- Recommend default as DD/MM/YYYY as it is in most of the world, [except the US](https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_States). There's a case to be made to use the [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601) of YYYY-MM-DD, but I think in most of our contexts, date and month coming before year work well and it seems to be [the most popular across countries](https://en.wikipedia.org/wiki/List_of_date_formats_by_country).) 
- Love the idea of it being configurable
- For simplicity, I would suggest offering 2 options of each: (a) all-numeric and (b) spelled out month, even though there are dozens of possible formats (e.g. https://developers.google.com/sheets/api/guides/formats)
  - Default (international):  
    - (a) DD/MM/YYYY (with 0 in front of single digits) 
    - (b) D Month YYYY (with no 0 in front of single digits, Abbreviated month–if design team agrees–to avoid clutter)
  - US:
    - (a) MM/DD/YYYY (with 0 in front of single digits)
    - (b) Month D, YYYY (with no 0 in front of single digits, Abbreviated month–if design team agrees–to avoid clutter)
- It would be ideal if this configuration could also apply to date pickers, so the date picker and how it's displayed in the UI match (e.g. date or month first)
