### ISSUE TITLE
Insights view not rendering correct unsynced records status on initial load

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3476]
**Describe the bug**
The first time one opens the Insights screen,  the view renders All resources synced  ✔ and then after a few milliseconds renders the actual unsynced records.

**To Reproduce**
1. Log into the app
2. Register a client or add some records
3. Navigate to the Settings Page
4. Navigate to Insights

**Expected behavior**
On initial load/render of the Insights page, it should show **Loading ..** e.g with an infinite progress spinner until the actual status is queried and returned.

**Screenshots**
**What it initially shows**
![Screenshot_20240901_011515](https://github.com/user-attachments/assets/f015e42a-0e30-443c-b1d4-b9359f324c3b)

**What is shows after a few seconds**
![Screenshot_20240901_011455](https://github.com/user-attachments/assets/ec8f3b96-475a-45e4-9df1-d25bea87fe3c)

**Smartphone (please complete the following information):**
Reproducible on any device

**Additional context**
Original implementation - PR https://github.com/opensrp/fhircore/pull/2873

**Comment by aurangzaibumer** [comment]
![image](https://github.com/user-attachments/assets/0100c90b-9a31-4ff9-9052-d576332a167e)


https://github.com/user-attachments/assets/8c956920-1079-40ca-aebf-98e6a35e7a2f

@ndegwamartin 
it doesn't show me any spinner or infinite loading.

**Comment by ndegwamartin** [comment]
> ![image](https://private-user-images.githubusercontent.com/35099184/364724133-0100c90b-9a31-4ff9-9052-d576332a167e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzcxMDQsIm5iZiI6MTcyNTUzNjgwNCwicGF0aCI6Ii8zNTA5OTE4NC8zNjQ3MjQxMzMtMDEwMGM5MGItOWEzMS00ZmY5LTkwNTItZDU3NjMzMmExNjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDExNDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWVjMmNkOTNlN2FlNmNkZDI2OTA5NTE1OGE1MGE0ZjJmZWYxNGE2ZDYxNzMxY2YzMTBjZDFkYzkzYWI5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BOPLYVyt9OVOvQxd0FiYkCTwDnswTUwuwv178ki_LS8)
> 
>  3476_investigation.mp4 
> @ndegwamartin it doesn't show me any spinner or infinite loading.

That is correct, you need to add one
