### ISSUE TITLE
Override onBackPressed() and prompt user before exiting from App

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#3479]
**Desired Feature**
Override onBackPressed() and prompt the user before exiting from the App

1. onBackPressed() prompts the user if they want to Quit the application if on the Homescreen 
2. If in a given workflow, navigate through the back stack to the home screen then prompt the user to exit the app 
3. This should also be reproduced whether you use the physical back button or on the top bar navigation back button icon

**Acceptance Criteria** 

- [ ] For previously navigated screens traverse back the back stack list else if no home then exit the app after the prompt
- [ ] Make the on-back press text prompt translatable in the build variant string.xml file

**Comment by f-odhiambo** [comment]
Related ticket https://github.com/ona-health/sid-dto-fhir-resources/issues/968

**Comment by hamza-vd** [comment]
@f-odhiambo ,

After discussing with @qaziabubakar , we've identified some potential implementations, but we need clarification first. Is the **HomeScreen** mentioned above referring to the **All Households** screen, or could it be any register screen? For example, in the current implementation, the user can exit the app from any register, such as by pressing the back button on the **Under Five Years** register and exiting the app.

If the user is allowed to exit the app from any register, we can simply override the `onBackPress` callback in `AppMainActivity`. In that case, we can define whether to show the exit dialog based on a setting in `ApplicationConfiguration`. Depending on this value, we can either show a dialog or allow the app to exit directly. However, if we want to always navigate back to the **All Households** screen before exiting, we would need to implement additional logic to check the current fragment.

**Comment by f-odhiambo** [comment]
If you are in any workflow, navigate back till you are back to the register then exit i.e. If I was filling in a form I get a prompt do you want to discard fo back to the register and then prompt, then exit

**Comment by ellykits** [comment]
@hamza-vd To simplify it further, if there is no entry in the navigation back stack, prompt the user with the dialog to choose whether to exit the app. Currently, the user exits the application as long as there is no previous screen to navigate.

**Comment by hamza-vd** [comment]
@f-odhiambo @ellykits 
Referencing the acceptance criteria 
> Make the on-back press text prompt translatable in the build variant string.xml file

Can we do this via configs? like 
```
"onBackPressPrompt" : {
    "title" : "Exit App",
    "message": "Are you sure you want to exit from the app?"
  }
```
or should I just introduce a config like
```
"showAppExitDialog" : true
```
and declare strings in `strings.xml`?

**Comment by ellykits** [comment]
I wouldn't mind having this as a configuration. The first is  reasonable.

**Comment by ellykits** [comment]
We would need defaults. The config should be optional.

**Comment by hamza-vd** [comment]
@ellykits `appExitDialog` will be  optional, if it isn't declared, app will exit without any prompt. Is that fine?

**Comment by ellykits** [comment]
That's fine

**Comment by ellykits** [comment]
@hamza-vd Can the dialog still be shown even if the config is not provided? When the config is `null`, use default strings for the title and message of the dialog. Read the defaults from the string.xml file. Implementers can then override the messages with the new config. @f-odhiambo Can you provide the defaults?

**Comment by hamza-vd** [comment]
Makes sense. Yes, this can be implemented

**Comment by pld** [comment]
is clicking the back button leading to app exit a normal UI flow? I haven't encountered that much, app's try to never quit, I don't think have the default be back button leads to app exit makes sense. A default of no further action makes sense to me.

@rowo what do you think?

**Comment by rowo** [comment]
@pld It's the normal behavior in Android using the system back button (bottom one). iPhones don't have this (they have like a swipe up from bottom to exit). We don't have an app back button on the main register view, so it wouldn't be that one. 

So it's okay to proceed as planned.
