### ISSUE TITLE
Perfomance Enhancements 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#3486]
**What to test**

**FHIRCore** 
- [x] 1. App Launch - Time is taken from Press App Icon move  auth page
- [x] 2. Login  - First-time login and Subsequent Login when resuming from the background 
- [x] 3. UI (Registers and Profiles): Splitting Queries that may be large into smaller ones to allow for other transitions to get processing time 
- [x] 4. Initial sync. Sample metrics from WDF found on [this ticket](https://github.com/opensrp/fhircore/issues/3543)

**Content review**
- [x] 1. Rules engine - review configs to optimize and remove unused rules and extensions
- [ ] 2. Review how inter-form and inter-visit logic is currently being implemented for possible areas of refactoring to optimize data queries (Potentially use Forward include, Reverse include, etc while getting Related Resources)
- [ ] 3. Triage Questionnaire population (Related Expressions (FHIRPath) being executed or prepopulated) - improve load and save times
- [ ] 4. Triage FHIRPath expressions evaluation and extensions - benchmarking

**Android FHIR SDK**
- [ ] 1. Triage query performance for searches and data queries
- [ ] 2. Triage Extraction of nested rules on StructureMaps - benchmarking

**Where to start** 
- [ ] 1. Add all release flavors based on the latest artifacts FHIR Core and SDK to a branch 
- [ ] 2. Publish a release artifact - This can be done locally or using GitHub actions 
- [ ] 3. Cut release APKs flavor based on the above branch  
- [ ] 4. Benchmark the APKs
- [ ] 5. Maintain the branch for subsequent updates 
- [ ] 6. Repeat 3,4,5

**Comment by f-odhiambo** [comment]
As shared from email 

![image](https://github.com/user-attachments/assets/4360a60a-6ea5-4e0e-a5d0-e1587594bdd0)

**Comment by f-odhiambo** [comment]
There is a branch that was built by @LZRS here https://github.com/opensrp/fhircore/tree/experiment-perf-branch that @qiarie you can build upon

**Comment by qiarie** [comment]
@f-odhiambo This branch has the latest updates and dependencies [performance-improvements](https://github.com/opensrp/fhircore/tree/performance-improvements)

**Comment by pld** [comment]
https://github.com/opensrp/fhircore/pull/3636
