### ISSUE TITLE
Slow filtering/search on the Map views

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3495]
**Describe the feature request.**
- Map views are taking long to search.  This seems to be because of the rules re-executing every time the search is changed. 
- Could we cache the rules facts for the map view? 
    - The map loads all the locations and creates the facts maps for all the locations.  
    - Could we cache the facts and always search through them?  
    - We will need to make sure we refresh the cache in some way to always present the correct statuses. 

**Acceptance criteria**
- [ ] Update the search on the map to reduce the amount of time it take to the search locations on the map. 

**Area path**
A list of ordered steps in the app on the usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Children register_
4. Click on _Child profile_
5. Click on _Edit profile_ from menu

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _checklist_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by dubdabasoduba** [comment]
- Right the search hangs when searching through 300 locations on an 8gb XIaomi 10 device

We can start by making sure it does not freeze in this scenario.  The we can decide on numbers metrics.

**Comment by ndegwamartin** [comment]
We have a new version of the upgraded Kujaku library, could we test this for any performance enhancements? 

Basically [in the FHIR Core toml file](https://github.com/opensrp/fhircore/blob/migrate-deps/android/gradle/libs.versions.toml#L54-L58) update to the following two versions:
```yml
kujaku-library = "library-v0.10.6-ALPHA-SNAPSHOT"
mapbox-sdk-turf = "7.2.0"
```

**Comment by ellykits** [comment]
Thanks @ndegwamartin. I will update the version.

**Comment by pld** [comment]
This is the open Android FHIR SDK issue to create a geo index for Location resources, https://github.com/google/android-fhir/issues/475

**Comment by ellykits** [comment]
Closed by this https://github.com/opensrp/fhircore/pull/3634
