### ISSUE TITLE
Support securely transmitting and storing data

### ISSUE THREAD

**Issue by vincent-karuri** [OpenSRP/fhircore#35]
This is a broad issue but includes encrypting data on the device, server and when transmitting it over the wire. This is supported in the current OpenSRP core and is part of the G6PD requirements.

**Comment by pld** [comment]
Is this all missing from `android-fhir`? Are the sub-items here:

- [ ] sync using TLS
- [ ] SQLite encrypted at rest

is there anything else?

**Comment by vincent-karuri** [comment]
I think it supports sync with TLS it uses [Retrofit](https://github.com/google/android-fhir/blob/e42e9e93fbedfa05008eb91d650875dcb874b151/reference/src/main/java/com/google/android/fhir/reference/api/HapiFhirService.kt#L46) whose OkHttpClient [attempts TLS connections](https://square.github.io/okhttp/https/#https).

**Comment by vincent-karuri** [comment]
For SQLite, I don't think there's any encryption happening atm. It uses Room + SQLite which requires extra steps to configure encryption. 

SQLCipher can now work with Room (needs more research). We'll also need to worry about key-management.

Useful resources:

https://medium.com/@sonique6784/protect-your-room-database-with-sqlcipher-on-android-78e0681be687
https://medium.com/vmware-end-user-computing/securing-a-room-database-with-passcode-based-encryption-82ec670961e
https://github.com/sqlcipher/android-database-sqlcipher#using-sqlcipher-for-android-with-room

**Comment by vincent-karuri** [comment]
Not sure about Hapi FHIR server support for encryption of data at rest - it may be another point of research.

**Comment by pld** [comment]
HAPI uses JPA so you can back it with the encrypted DB of your choice, https://hapifhir.io/hapi-fhir/docs/server_jpa/introduction.html

Only open question is SDK sqlite store.

**Comment by pld** [comment]
Android FHIR SDK team reported SDK uses standard data encryption at rest, looks like this is all covered

**Comment by vincent-karuri** [comment]
@pld It's not clear that encryption at rest is currently supported on the SDK. Google suggested we open an issue on the SDK repo, I think we should re-open this?

**Comment by pld** [comment]
They specifically said in conversation on Monday it is

**Comment by vincent-karuri** [comment]
Jing mentioned they are not doing anything special/explicit around encryption. Worth following up imo.

**Comment by pld** [comment]
OK, please follow-up with Jing, if there’s something specific missing, let’s open that in a new issue detailing what specifically is missing
