### ISSUE TITLE
Distorted Sync warning text on the navigation drawer

### ISSUE THREAD

**Issue by faith-mutua** [opensrp/fhircore#3522]
**Describe the bug**

The text in the `Sync` warning on the navigation drawer is misaligned with the date being distorted and appearing vertically instead of horizontally. Refer to attached screenshot for more details

**To Reproduce**
1. Go to 'All patients' register and register a patient
2. Click on 'the hamburger icon' to open the navigation drawer
3. Observe how the Sync warning is displayed

**Expected behavior**

Text within the Sync warning should be well-aligned

**Screenshots**

![Screenshot from 2024-09-27 11-39-56](https://github.com/user-attachments/assets/28cc2a8f-c243-4340-9757-865d8237f11e)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator] - `BLUG60`
 - Android version: [e.g. Settings -> About phone -> Android version] - `9`
 - Build number: [e.g. Settings -> About phone -> Build number] - `PPR1.180610.011`
 - Version [e.g. 24] - `BLU-G0270WW_V9.0.04.20_GENERIC 18-07-2022 09:44`

**Additional context**

This has been observed in the WDF project on the` opensrp-dc-v0.1.3.apk`

**Comment by hilpitome** [comment]
I was not able to recreate the above issue on Eusm using the latest version of fhircore. Check the screenshot below.
![eusm](https://github.com/user-attachments/assets/5baf5800-e27a-4b5e-816c-8072b966c0d0)

**Comment by hilpitome** [comment]
The text is assigned on this [line](https://github.com/opensrp/fhircore/blob/fb238c2c061f4dea86db477aec4dc73985ba9b8f/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt#L348) in AppDrawer

**Comment by hilpitome** [comment]
However, in the above was done on an a tablet in an emulator. On the phone the time appears to be compressed and spread over a few lines like below.
![Screenshot_20241003-173233](https://github.com/user-attachments/assets/dcc74297-6c60-4815-a156-906a0c0daaaf)
