### ISSUE TITLE
[EUSM]Android and Web app Performance testing 

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/fhircore#3551]
EUSM locations and products are being uploaded-  in that regard, we need to test performance of the app and web. 

**Required**
- Performance tests for the app.
- Performance testign for web.
- Conduct these with the preview versions. 

**Acceptance Criteria**
- [ ] Login is fast and take sonly a few seconds (QA to advise what is acceptable). 
- [ ] Forms load relatively fast and save fast too (seconds). 
- [ ] Sync should take a few seconds (QA to advise what is acceptable). 
- [ ] If user selects many locations and data is downloaded on their app - app performance is not affected. 
- [ ] Web forms open and save fast. 
- [ ] No buffing occurs when loading pages. 
- [ ] User can easily navigate from one page to another without a lag.

**Comment by Mstjamush** [comment]
```
Phone - Galaxy A25
RAM - 6GB
ROM - 128GB
Android Version - 14
WiFi - 20Mbps
```
Login(follow up) - 0:00:08.11
Loading Service Points Register(479 Sps) - 0:00:06.39
Load a Service Point profile - 0:00:01.20
Loading a SP check form - 0:00:01.33
Submit a SP check form(save) - 0:00:02.18
Loading a Consult beneficiaries form - 0:00:01.27
Submit a Consult beneficiaries form(save) - 0:00:02.52
Loading a Update GPS form - 0:00:01.46
Loading Past Visit page - 0:00:01.00

**Comment by AnnieMungai** [comment]
@Mstjamush do we have results for the sync down on initial login?

**Comment by madrinekariuki** [comment]
Device: Samsung A12, android 11, RAM 4 GB, ROM 64GB
release: https://github.com/onaio/fhir-resources/releases/tag/v2.0.0-opensrp-eusm (rc16 madagascar)
Wifi: 10 mbps

Login(follow up) - 00:24:70
Loading Service Points Register(479 Sps) - 00:14:46
Loading Service Points MAps(479 Sps) - 01:20.69
Load a Service Point profile - 00:6:21
Loading a SP check form - 00:10:46
Submit a SP check form(save) - 00:15:20
Loading a Consult beneficiaries form - 00:08:56 
Submit a Consult beneficiaries form(save) - 00:18:23 
Loading a Update GPS form - 00:09:43
Loading Past Visit page -00:02:20

nb// The app keeps becoming unresponsive and one has to close and open again to proceed:

screenshot:
![Screenshot 2025-01-15 at 11 54 53](https://github.com/user-attachments/assets/d94e3340-0b65-469f-9c2c-d4d4d0e0d6d8)

logs:
```
2025-01-15 11:44:56.229  1278-13550 ActivityManager         system_server                        E  ANR in org.smartregister.opensrp.eusmMg (org.smartregister.opensrp.eusmMg/org.smartregister.fhircore.quest.ui.main.AppMainActivity)
                                                                                                    PID: 24593
                                                                                                    Reason: Input dispatching timed out (e4472f org.smartregister.opensrp.eusmMg/org.smartregister.fhircore.quest.ui.main.AppMainActivity (server) is not responding. Waited 10006ms for MotionEvent)
                                                                                                    Parent: org.smartregister.opensrp.eusmMg/org.smartregister.fhircore.quest.ui.main.AppMainActivity
                                                                                                    Load: 27.64 / 27.63 / 25.49
                                                                                                    ------ Current CPU Core Info ------
                                                                                                    - offline : 
                                                                                                    - online : 0-7
                                                                                                    - AP Temp = 430
                                                                                                                                 0           1           2           3           4           5           6           7
                                                                                                    ------------------------------------------------------------------------------------------------------------------

```
