### ISSUE TITLE
Decouple sync and register/map filtering control from the multiselect widget

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3567]
**Describe the feature request.**
- The current multi-select widget helps in downloading and filtering data.  We would like to decouple these two functions but leave the same functionality on the multi-select widget
- We can add configuration to decide what function the multi-select widget should take.  

**Acceptance criteria**
- [ ] Decouple the sync and filtering functionality on the multi-select widget.  
- [ ] Selection of the functionality should be determined by configurations.  

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _checklist_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by AnnieMungai** [comment]
EUSM v2.0.0RC12
LGTM!
