### ISSUE TITLE
Basic Map View Support

### ISSUE THREAD

**Issue by samkanga** [opensrp/fhircore#359]
This is scoped to the work required to stand up a map view in the FHIR app without any workflow. This would include the ability to see a map layer and structures on it. The scope and work @ekigamba did for the Goldsmith CHW app is a good reference (without any custom coloring or labels for the structures). 

What we want to understand is what the LOE would be to port the map over to the FHIR app. If this LOE also includes some of the extras like the "locate me" button, pls note that as well. 

v2 of this will be addressed by other issues. Those will include things like the compass widget, showing operational boundaries, or the ability to add a structure.  

For v1

- [ ] Syncing locations (jurisdictions/buildings) - dependent on FHIR [location mapping](https://github.com/opensrp/fhircore/issues/154) (3 hours)
- [ ]  Integrate [Kujaku library](https://github.com/onaio/kujaku) (Might require updating) (1 day)
- [ ] Create/copy mapbox style (Is this changing?) (3 hours)
- [ ] Port over the Map Activity refer to [tasking library implementation](https://github.com/opensrp/opensrp-client-tasking/blob/goldsmith-merge-map-stuff/opensrp-tasking/src/main/java/org/smartregister/tasking/activity/TaskingHomeActivity.java) (1 day)
- [ ] Implement conversion of FHIR location model to Geojson feature collection (3 hours)
- [ ] Implement handling of click actions on map / structures (scope unknown)
- [ ] Support [searching](https://www.hl7.org/fhir/location.html#search) for structures from the app db. Dependent on this [issue](https://github.com/google/android-fhir/issues/475) (3 hours when search is complete)

3.5 days FTE + 20% buffer

**Comment by pld** [comment]
do we want every fhir app to include a map?

if not, we'll want to move adding the map lib to the configs, including the binary
