### ISSUE TITLE
Dynamic tasking

### ISSUE THREAD

**Issue by samkanga** [opensrp/fhircore#362]
@f-odhiambo is there any reason this would be a different work stream than the current one to generate and assign plans on the client/offline?

This entails generation of tasks based on actions defined in the plan definition both on the opensrp server and the the android client. Task generation can be triggered by plan activation or event submission.

Documentation found on [Reveal Jira](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1491959809/Dynamic+Task+Generation+and+Entity+Persistence) and [Ona Guides / Dynamic Tasking and Entity Persistence Techincal Description and User Guide](https://docs.google.com/document/d/15tJNDmAkKceIggCqospSbR2TJXxS1GwgalBllS3Bk8Y/edit#)

**Comment by f-odhiambo** [comment]
> @f-odhiambo is there any reason this would be a different work stream than the current one to generate and assign plans on the client/offline?
> 
> This entails generation of tasks based on actions defined in the plan definition both on the opensrp server and the the android client. Task generation can be triggered by plan activation or event submission.
> 
> Documentation found on [Reveal Jira](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1491959809/Dynamic+Task+Generation+and+Entity+Persistence) and [Ona Guides / Dynamic Tasking and Entity Persistence Techincal Description and User Guide](https://docs.google.com/document/d/15tJNDmAkKceIggCqospSbR2TJXxS1GwgalBllS3Bk8Y/edit#)

@samkanga I have no access to this document linked [here](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1491959809/Dynamic+Task+Generation+and+Entity+Persistence)
