### ISSUE TITLE
Issues observed on the  minified Bidan APK.

### ISSUE THREAD

**Issue by karina4050** [opensrp/fhircore#3624]
### Issues Observed:
- [x] Family head tag does not show under the name of the assigned member on the family register; this is either during registration or by using the change family head option on the overflow menu on the family register
- [x] App crashes when a user clicks on the change family head option on the overflow menu on the family register. This only happens if a user has been assigned the family head role during member registration. Here is the zip folder that contains the logs. (This is no longer happening but you can review the logs just to confirm what was the issue)
[Xiaomi-2404ARN45A-Android-14_2024-11-19_112029.zip](https://github.com/user-attachments/files/17812554/Xiaomi-2404ARN45A-Android-14_2024-11-19_112029.zip)
- [x] The remove persons feature does not work. Removed persons are still active; users can enroll them in a CarePlan.  i.e ANC/PNC
- [x] User is not able to select any choice in the question **Urine test type** after answering **Yes** to the question **Urine test conducted?**

**Comment by qiarie** [comment]
@karina4050 

> Family head tag does not show under the name of the assigned member on the family register; this is either during registration or by using the change family head option on the overflow menu on the family register

I am able to see the `Family Head` tag on the household profile in the WDF app. We may need to check whether this works as expected with a release build from `main`.

>  App crashes when a user clicks on the change family head option on the overflow menu on the family register. This only happens if a user has been assigned the family head role during member registration. Here is the zip folder that contains the logs. (This is no longer happening but you can review the logs just to confirm what was the issue)
Xiaomi-2404ARN45A-Android-14_2024-11-19_112029.zip

No crash on WDF app. Test on release build from main.

> The remove persons feature does not work. Removed persons are still active; users can enroll them in a CarePlan. i.e ANC/PNC

Also not removed from the household profile after removal. Confirm with release from main

> User is not able to select any choice in the question Urine test type after answering Yes to the question Urine test conducted?

Confirm result with release from main

**Comment by karina4050** [comment]
@qiarie 
https://onaio.slack.com/archives/C01JEDB8WTU/p1732104514854829?thread_ts=1731918948.243569&cid=C01JEDB8WTU

> @karina4050
> 
> > Family head tag does not show under the name of the assigned member on the family register; this is either during registration or by using the change family head option on the overflow menu on the family register
> 
> I am able to see the `Family Head` tag on the household profile in the WDF app. We may need to check whether this works as expected with a release build from `main`.
> 
> > App crashes when a user clicks on the change family head option on the overflow menu on the family register. This only happens if a user has been assigned the family head role during member registration. Here is the zip folder that contains the logs. (This is no longer happening but you can review the logs just to confirm what was the issue)
> > Xiaomi-2404ARN45A-Android-14_2024-11-19_112029.zip
> 
> No crash on WDF app. Test on release build from main.
> 
> > The remove persons feature does not work. Removed persons are still active; users can enroll them in a CarePlan. i.e ANC/PNC
> 
> Also not removed from the household profile after removal. Confirm with release from main
> 
> > User is not able to select any choice in the question Urine test type after answering Yes to the question Urine test conducted?
> 
> Confirm result with release from main

**Comment by qiarie** [comment]
The issues were confirmed to be configs-related and will be handled separately for each project
