### ISSUE TITLE
Entity persistence

### ISSUE THREAD

**Issue by samkanga** [opensrp/fhircore#363]
We inherently create a conflict in the Android client across plans if a task has been generated server side and the Android client hasn’t synced. This is the case when we have multiple plans working in the same operational area and a new plan is created in that same operational area. Additionally,  The current process requires a duplicate registration of that family in the second plan.

Below is a list of entities that must persist across plans:
    Jurisdiction Location (We may need to edit jurisdiction locations at some time in the future in the Android client)
    Non-Jurisdiction Location
    Family
    Family Member

Documentation found on [Reveal Jira](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1491959809/Dynamic+Task+Generation+and+Entity+Persistence#Entity-Persistence)

How to create a CarePlan for a location without a patient [discussion](https://github.com/opensrp/fhircore/discussions/320). No timelines, ending discussion - RESOLVED.

**Comment by pld** [comment]
@ekigamba what do you mean by "workflow" in this context? a workflow is defined by one or more plan and activity definitions

**Comment by rkodev** [comment]
@pld This refers to the workflow api being implemented on the SDK

**Comment by pld** [comment]
K cool, thanks, so that's not really a FHIR thing but the Android FHIR SDK Workflow API.

Reading through the issue, the way we're structuring the FHIR resource graph might also address these issues
