### ISSUE TITLE
[Bug] The "Submit Anyways" button doesn't work.

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#3648]
**Describe the bug**
In the latest updates to UNICEF Mexico, if you fill in the Child Follow up, Pregnancy Follow up, or Lactating Mother Follow up visit, don't fill in all the questions, and try to submit anyway, the submit anyway is not available. Can we please add it back?

<img width="305" alt="Screenshot 2024-12-06 at 8 25 13 AM" src="https://github.com/user-attachments/assets/bc840707-73df-40b5-9f07-f4b82a0c6973">

**To Reproduce**
1. Go to Contigo app and pick a already registered caregiver or child
2. Select Follow up visit
3. Fill some of the questions and then hit "Submit", no "Submit any way" is available, but it use to be.

**Expected behavior**
If I don't fill all the questions in the follow up visit forms and hit submit, the submit anyway will appear.

**Additional context**

**Implementation plan**
- Bulleted pointed list of notes on the plan to address this issue
- Can be added, expanded, and modified by the assignee

**Comment by f-odhiambo** [comment]
This is broken but we need to figure out where it was configured. This is a product issue 

<img src="https://github.com/user-attachments/assets/2f442efa-39e7-41ba-bcec-56ac8daef190" width="200" height="400" />

**Comment by joyce-x-chen** [comment]
Hi @f-odhiambo cc: @msschroeder 

I believe we have default hidden the "submit anyway" button from the product if there are mandatory fields unfilled. There was an issue I created here [#3503](https://github.com/onaio/fhir-resources/issues/3503) that was worked on by Aleem for the WB demo app (based on GIZ EIR). 

Fikri worked on this https://github.com/opensrp/fhircore/issues/3549 and it seems to still be configurable by form, so you could still show the dialogue & "submit anyway" option if non-mandatory fields are left blank. 

We should not enable the "submit anyway" button for UNICEF Mexico if there are any mandatory fields. Hope that clarifies things.
