### ISSUE TITLE
Sort and Filters on task register

### ISSUE THREAD

**Issue by samkanga** [opensrp/fhircore#366]
@f-odhiambo my assumption here is that we will cover some of this functionality with the CHW scope. The primary case there being filter by task status. 

The Reveal implementations will likely have more factors by which to sort (ie by distance) or filter the structures/families. 

**Map View Features**
### Thailand:
**Sort Options:**
- [ ] Distance from the user
- [ ] Task Status 
- [ ] Task Type 

**Filter Options:**
1. Status:
- [ ] Not Visited
- [ ] Family Registered `(Family has been registered for this structure)`
- [ ] Bed Net Distributed `(Family Regustration done + Bed net distributed)`
- [ ] Complete ` (Family Registration done + Bed net distributed + At least on Blood Screening done)`
- [ ] Not Eligible

2. Task Type - The task detailed can be accessed on the respective form links.
- [ ] [Mosquito Collection](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/mosquito_collection_form.json)
- [ ] [Larvae Dipping](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/larval_dipping_form.json)
- [ ] [BCC](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/behaviour_change_communication.json)
- [ ] [Bed Net Distribution](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/bednet_distribution.json)
- [ ] [Blood Screening](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/bednet_distribution.json)
- [ ] [Case Confirmation](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/case_confirmation.json)
- [ ] [Register Family](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/family_register.json)
- [ ] [PAOT](https://github.com/opensrp/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/paot.json)

3. Intervention Unit
- [ ] Operational Area
- [ ] Structure
- [ ] Family
- [ ] Person

### Namibia:
**Sort by:**
- [ ] Distance
- [ ] Status

**Filter By:**
- [ ] Not visited
- [ ] Not sprayed
- [ ] Partially sprayed
- [ ] Sprayed

**Comment by pld** [comment]
this all has to be done generically as search queries against a resource that show up in a list view of that resource

the resource here being Task
