### ISSUE TITLE
Mockups for covid-19 app needed

### ISSUE THREAD

**Issue by Andati** [opensrp/fhircore#39]
We need mockups for covid-19 app
- [x] Login page
- [x] Navigation drawer
- [x] Register page (search button included)
- [x] Search page
- [x] View patient profile
- [x] Add vaccine/care plan
- [x] View vaccination status
- [x] View vaccination certificate

**Comment by pld** [comment]
@rowo probably to be delegated

**Comment by vincent-karuri** [comment]
We may need these to be more generic and not focused on the covid-19 app

**Comment by rowo** [comment]
@Andati probably need more than this to go on

**Comment by Andati** [comment]
@rowo @f-odhiambo will create a meeting to go through the SRS document.

**Comment by f-odhiambo** [comment]
@rowo Kindly update the mockups to include the Login page and navigation drawer. Details added to the mockup brief [doc](https://docs.google.com/document/d/1M_2Iwj3X9w8skQNinXkB_0SEnhqwBlorszw_crILEoc/edit?ts=6061405e#)

**Comment by vincent-karuri** [comment]
I think this is complete
