### ISSUE TITLE
Date Standardization

### ISSUE THREAD

**Issue by rkodev** [opensrp/fhircore#397]
**Is your feature request related to a problem? Please describe.**
When resources are created in the SDK, the device stores at least some dates without a time or timestamp i.e the [Patients BirthDate](https://www.hl7.org/fhir/patient-definitions.html#Patient.birthDate) e.g YYYY-MM-DD.

The current implementation stores the date as is, in local time and timezone information. These dates are also synced as is, we need to investigate that the dates uploaded to the server do not lose timezone information. e.g a device in GMT+3 syncing to a server in GMT-4 should auto adjust the date information

**Describe the solution you'd like**
The server/app implementation should be able to standardize all the date information. 

1. We can either have all data uploaded by the apps adjusted to GMT+0 before upload and have the server parse all dates as GMT+0 or
2. Dates sent to the server should be in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format and should include the timezone information

**Comment by syedowaisali90** [comment]
I think solution 2 is good we can go with [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) @maimoonak what do you think

**Comment by maimoonak** [comment]
Checking the tables (SyncedResourceEntity, Patient.resource)  in sqlite database I see that sdk already stores timezone info, and the indexes are created on millis timestamp. So for datetime fields there would be no issue, however, the birthdate is a date (date-only) field and can not have timezone https://www.hl7.org/fhir/patient.html. So what we would do for such fields?

{"resourceType":"Patient","id":"3","meta":....."lastUpdated":"2021-03-10T13:18:22.074+00:00",...."birthDate":"1988-08-04",.....}]}

**Comment by syedowaisali90** [comment]
Thanks @maimoonak for your input. I think we are already complying with the ISO 8601 date format for resources synchronization. 
cc: @rkodev

**Comment by pld** [comment]
If birth dates are dates only, that shouldn't be a problem, we can assume it's the same date in all timezones, I think that's ok since we don't have more information. I don't think we usually record time of birth (@isabelcshaw is that common enough to plan for it now or can we wait until we see this requested?)

**Comment by isabelcshaw** [comment]
@pld I've never seen a need to record time of birth. For the CHW workflows, we only record a self reported DOB - and, in some cases, age (and estimate a DOB) if they don't know the actual date. Unless I'm misunderstanding this question, I don't see any use case for time of birth unless a future facility/ANC/PNC app requires it, which I think would be rare.

**Comment by rkodev** [comment]
@ekigamba can you check @maimoonak comment here

**Comment by ekigamba** [comment]
@rkodev I think what you proposed should work. Standardizing all dates without timezone to GMT before sharing them i.e. 
- On the API
- Client to server upload

I see @pld also suggests that we can assume the dates being OK and disregard any timezone differences where we only have a date

**Comment by pld** [comment]
@ekigamba I think given @maimoonak and @syedowaisali90's comments, and the fact we're already storing tz info, we're leaning towards option (2) in @rkodev's description: store all dates w/tz info in ISO 8601

**Comment by ekigamba** [comment]
@pld the [Patient.birthDate](https://www.hl7.org/fhir/patient-definitions.html#Patient.birthDate) of type date https://www.hl7.org/fhir/datatypes.html#date does not have timezone per the specification. The Google Android FHIR SDK also saves the date without any timezone information.

I think this will apply for any other Resource property of type `date`. Any inconsistencies will affect any age/date calculations across the system. I cannot accurately say if the impact will be significant but it would be good to have this resolved/decided before we start recording any such data

**Comment by pld** [comment]
OK I might be missing something then, if it's a date it wouldn't have a tz to begin with so we wouldn't have to worry about standardization.

If it's a datetime it will include tz info and we can store it.

**Comment by ekigamba** [comment]
@pld Yea, I think this should be OK

**Comment by syedowaisali90** [comment]
I think as we already saving the consistent date and tz info then we don't need to remain this issue open anymore. @rkodev
