### ISSUE TITLE
Update FHIR Core to latest release of Data Capture

### ISSUE THREAD

**Issue by rkodev** [opensrp/fhircore#398]
**Name of feature to enhance**
Update the Data Capture library to the latest [version](https://github.com/google/android-fhir/releases/tag/sdc-0.1.0-alpha03)

**NB**
The last release was done from this [PR](https://github.com/google/android-fhir/pull/489) 

Might need to follow up on this PR to support the barcode issue. either resolve the issue on that SDK or port the code to FHIR core

**Comment by f-odhiambo** [comment]
Blocked - Current release from SDK not yet published

**Comment by pld** [comment]
We can push our own release of the SDK for this if we need it

**Comment by ndegwamartin** [comment]
This is now published https://oss.sonatype.org/content/repositories/snapshots/org/smartregister/data-capture/

**Comment by ndegwamartin** [comment]
Tag https://github.com/onaio/android-fhir/releases/tag/v0.1.0-alpha03-preview-SNAPSHOT
