### ISSUE TITLE
Barcode scanning crashes on search 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#399]
**Describe the bug**
The current bar code reader crashes when you try an scan for a patient at the patient list or register a new patient view. The current ID being used is the UUID and not the patient identifier being used for the Barcode ID, thus crashing, no error handling added for this at the moment 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the patient list or register a new patient 
2. Scan ID 
4. See an error from logcat
` Resource not found with type Patient and id 18!`

**Expected behaviour**
Scan an ID from barcode if found, show patient in registration view with details else add a new patient 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
Needs actual device 

**Additional context**
N/A

**Comment by f-odhiambo** [comment]
The earlier reported bug is still persistent - Needs more test

**Comment by maimoonak** [comment]
The app seems to be working fine without any crash. Could you plz provide steps/data where it crashes. https://drive.google.com/file/d/1BfT6E4aDIpXZ23K2VPCWSdQO0Ix9JFIg/view?usp=sharing

**Comment by f-odhiambo** [comment]
Steps used to reproduce the bug 
1. Scan for non-registered id - https://user-images.githubusercontent.com/4540684/126748257-4846493f-328c-493d-a3eb-83c0a80eb09c.jpg picks the wrong ID
2. Scan for Cook - Does not return profile page but an empty registration page 

See video link https://onaio.slack.com/files/U01J0J33337/F028QPA8YMV/20210726_130706.mp4

**Comment by maimoonak** [comment]
# 1 - the ID seems to be different from https://barcode.tec-it.com/en/Code128?data=123456 . May be image has wrong ID.
# 2 - the ID is case sensitive and using uppercase C would scan the ID
 
I found another issue with ID where it was not setting right ID when saving. Fixed this in PR https://github.com/opensrp/fhircore/pull/439
