### ISSUE TITLE
CHW/ANC SubTask  - Search for a Family

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#408]
Search for a given family by its Family name else if not found, register the new family 

3.5 days FTE + 20% buffer
![image](https://user-images.githubusercontent.com/4540684/125637864-f60e5878-5dc1-412e-81a1-154f9c1ab28a.png)

**Comment by f-odhiambo** [comment]
We need to decide how we represent a family based on the discussions [here](https://github.com/opensrp/fhircore/issues/276)

**Comment by maimoonak** [comment]
https://github.com/opensrp/fhircore/pull/493 The was supposed to resolve the issue but now it needs to be on new code structure.

**Comment by maimoonak** [comment]
https://github.com/opensrp/fhircore/pull/547 Resolved in this PR
![Screenshot from 2021-09-20 13-47-37](https://user-images.githubusercontent.com/4829880/133976916-1f08da95-0204-4912-a0ae-166f662114e8.png)

@f-odhiambo

**Comment by f-odhiambo** [comment]
Done
