### ISSUE TITLE
Codebase re-structure and refactor

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#414]
**Change the structure of the current codebase**
In an effort to move towards a single apk approach we need to make the following changes:
- Single code base for all our apps
- Refactor/Reuse any generic code

**Current structure of the FHIRCore/Covaxx demo module**
`/app`

**New structure**
`/anc` _- anything ANC specific will build CHW app for LMH and mADX_
`/eir` _- anything EIR specific will build Covax app_
`/engine`
` |--- /register`
` |--- /report`
` |--- /task`
` |--- /search`

**NB:** This will result into 3 modules, the _anc_, eir_, and _libraries_ modules. _anc_ and _eir_ library modules that we can build into APKs.

**Notes:**
- [ ] Refactor to above structure/modules
- [ ] Refactor existing EIR to new structure
- [ ] Add a README in each of the modules with a simple description _e.g. Community Health Worker module for the CHW_

**Comment by pld** [comment]
Can the Covax/EIR activities be performed in a non-facility setting? I've heard plans of door-to-door vax, but haven't heard of it actually being run.

Can we also add more details to these categories, saying what is CHW specific?

**Comment by f-odhiambo** [comment]
@pld FYI: In Kenya, there is the door to door polio campaigns. For Covid-19 vaccination, you have to go to a facility

**Comment by pld** [comment]
Cool, I imagine that's quite common, b/c of this I think we want to separate EIR functionality from facility functionality (if there's any of either that we don't push to configs)

@ndegwamartin what do you think about `/eir` for anything covax/eir specific?

**Comment by pld** [comment]
updated based on conversation in https://docs.google.com/document/d/1-8MjzCeo1NJdrVGnhHq1YLInzrs5lHL5QKfrwb0JwMc/edit?ts=60f037f2#heading=h.qyfxrlaqj1lv

**Comment by pld** [comment]
Sounds like we need to build a flavor for CHW and EIR

**Comment by f-odhiambo** [comment]
And mADX too even though delayed

**Comment by pld** [comment]
> And mADX too even though delayed - #177

I disagree, my understanding is anything we need for mADX we'll need for CHW, so to demo mADX, we'll build the CHW flavor and show the functionality it includes that we have as mADX deliverables

**Comment by pld** [comment]
w/ANC replacing CHW, mADX will be a flavor of the ANC app
