### ISSUE TITLE
Show progress dialog showing in the foreground during the auth

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#417]
**Describe the bug**
Currently, In auth screen when we try to login there is a progress dialog showing in the foreground so we need to show the progress dialog during the auth.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Launch app 
2. Add correct credentials
3. Login 

**Expected behaviour**
Show progress dialog as once waits to be authenticated 

**Screenshots**

**Smartphone (please complete the following information):**
 - Emulator
**Additional context**
N/A

**Comment by f-odhiambo** [comment]
What's the status of this issue @syedowaisali90?

**Comment by syedowaisali90** [comment]
@f-odhiambo WIP will be done by today-end
