### ISSUE TITLE
Post patient questionnaire to HAPI

### ISSUE THREAD

**Issue by Andati** [opensrp/fhircore#42]
The patient questionnaire will be downloaded from HAPI and use for patient registration.

Currently, it's a file on the apk.

**Comment by pld** [comment]
This leads to the broader question of how to manage FHIR files that define projects.

If we're iterating on these we might want them in a VCS and then synced to the FHIR server

**Comment by MuhammadSalman-7214** [comment]
Here are some of the findings regarding this:
1. Currently ResourceEntity table only contains Patient lists and not have Questionnaire that have already been uploaded to server.
2. To set Questionnaire from server requires the list of uploaded Questionnaire to be present in ResourceEntity table(that is only have patients list currently) through which we can write code to pick questions from the table

**Comment by f-odhiambo** [comment]
As per the above ticket, the question has been uploaded to the HAPI server, and in the application, I am downloading questions from the HAPI server and using the SDC library the questions are rendering on the application. Previously the questionnaire was present within the application, but with my work, it is not dependent on the Android Studio.

Concerns:
1. There should be a mechanism to recognize which question should be rendered for which application

**Comment by f-odhiambo** [comment]
This issue is done. The related issues on Sycning of resources, location sync and location mapping will be addressed in separate issue/tickets
