### ISSUE TITLE
Create a Developer's Guide for FHIRCore

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#431]
We can use this as reference https://github.com/google/android-fhir/wiki/Developer's-Guide

**Comment by ndegwamartin** [comment]
@f-odhiambo closing this as is implemented [here](https://github.com/opensrp/fhircore/blob/main/docs/contributing.md)

**Comment by ndegwamartin** [comment]
This as is implemented [here](https://github.com/opensrp/fhircore/blob/main/docs/contributing.md)
