### ISSUE TITLE
Integrate with SDK functionality to edit a resource using a questionnaire

### ISSUE THREAD

**Issue by vincent-karuri** [opensrp/fhircore#45]
This includes patient demographic info or any information collected against the patient.

**Comment by pld** [comment]
Updating via client or server?

For via client, approach is when saving a questionnaire have logic there that generates/edits the patient resource.

For via server, on sync

**Comment by vincent-karuri** [comment]
Cool, this is via client.

**Comment by shoaibmushtaq25** [comment]
Can I get some more details about this issue to start over it @vincent-karuri ? It would be helpful for me to understand it before actually starting it.

**Comment by vincent-karuri** [comment]
The flow is not settled upon but it would be something like:

1. Load existing patient information into questionnaire and launch it
2. Allow the user to edit the information
3. On submission, update the information (possibly including any other resources generated previously from the questionnaire
4. The updated information should then sync to a FHIR server

There are still open questions on what the approach should be for updating multiple resources generated from a single questionnaire which would need to be worked out.

There's a related issue on the [SDK](https://github.com/google/android-fhir/issues/273).

**Comment by pld** [comment]
I just posed a question in the issue, but I think this is blocked by the that SDK issue, https://github.com/google/android-fhir/issues/273, so that might be the pre-req to work on

More generally, we should be able to do this without reference to a specific type of resource, maybe the more general title is "integrate with SDK functionality to edit a resource using a questionnaire"

**Comment by vincent-karuri** [comment]
yep, modified the title

**Comment by f-odhiambo** [comment]
This issue will be resolved on ticket number #79
