### ISSUE TITLE
Integrate the Barcode reader function to the latest merged version of SDC

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#452]
**Is your feature request related to a problem? Please describe.**
The Barcode reader is required to scan the paper card, the patient identifier that is used to track the paper card that is issued to the patient. 

**Describe the solution you'd like**
The current SDC release has an issue with the barcode functionality. We need to resolve the bug(s) associated with it in the codebase to ensure that the barcode feature  works appropriately as its a critical feature for the WHO Covax SVC demo app 

**Describe alternatives you've considered**
N/A

**Comment by f-odhiambo** [comment]
Required to unblock #448

**Comment by ndegwamartin** [comment]
This issue is blocked by the Android FHIR SDK issue [#489 ](https://github.com/google/android-fhir/pull/489#issuecomment-875626249)

**Comment by pld** [comment]
is anyone working on that? from the PR comments it looks like it needs to be reimplemented

**Comment by f-odhiambo** [comment]
> is anyone working on that? from the PR comments it looks like it needs to be reimplemented

@pld I have assigned Owais to assist in unblocking this issue as Martin continues working on #414

**Comment by mwkhan1983** [comment]
blocked by https://github.com/google/android-fhir/pull/704
