### ISSUE TITLE
Support data type validation on Questionnaires

### ISSUE THREAD

**Issue by vincent-karuri** [opensrp/fhircore#46]
This is broad but includes validating that data rules for fields are not broken e.g. a number-only field should not allow text, some fields cannot be left blank etc.

**Comment by pld** [comment]
I think that's handled by the SDC, https://hl7.org/fhir/us/sdc/index.html

Could we close this issue with an example of coding a questionnaire that has data validation logic?

**Comment by vincent-karuri** [comment]
Yes, this should be in SDC, not sure it's implemented already.

**Comment by pld** [comment]
This looks like it would cover it, and needs work, https://github.com/google/android-fhir/issues/383

**Comment by vincent-karuri** [comment]
related to https://github.com/google/android-fhir/issues/374#issuecomment-806549142

**Comment by vincent-karuri** [comment]
related pr https://github.com/google/android-fhir/pull/224

**Comment by vincent-karuri** [comment]
The pr above will add `minValue` and `maxValue` validation extension support to the Android FHIR SDK. Our work will be to extend this and add more validators in the future. Atm, this work is blocked until the pr merges.

**Comment by vincent-karuri** [comment]
list of all validators http://build.fhir.org/ig/HL7/sdc/behavior.html.
