### ISSUE TITLE
Scan for Patient Identifier and not Patient ID for the barcode reader functionality 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#472]
Upon scanning a bar code, search for the Patient Identifier ID as shown in the below code snippet and not scan for patient ID as is the case currently 

````
"identifier": [
    {
      "use": "official",
      "system": "WHO-HCID",
      "value": "111000111"
    }
  ],
`````

**Acceptance criteria** 

If a patient with the identifier is found 
`load patient profile `
else
`Register a patient and append a new Identifier from the Barcode ID that has been scanned`. ie.

Open a new register page with the scanned barcode prepopulated and then on post append the identifier to the patient resource as shown below 
````
"identifier": [
    {
      "use": "official",
      "system": "WHO-HCID",
      "value": "SCANNED BARCODE ID"
    }
  ],
````

Test Patient https://fhir.labs.smartregister.org/fhir/Patient/969/ or https://fhir.labs.smartregister.org/fhir/Patient/1010

Test Bar code 
<img  src="https://user-images.githubusercontent.com/4540684/128434995-2c64d652-7891-47d2-a93f-31a24ecf9284.png" width="300" height="200" />

**Comment by owais-vd** [comment]
@f-odhiambo the implementation of this ticket has been covered in ticket #452

**Comment by owais-vd** [comment]
I think we can safely close this
