### ISSUE TITLE
Update the correct fields for retrieving relevant dates for either registration or immunization

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#474]
Update the date so patient list view and patient profile 

**Acceptance criteria:** 
- [ ] On the patient profile, get the registered date  from  the last updated filed in meta in history 1 of a patient record  e.g. https://fhir.labs.smartregister.org/fhir/Patient/969/_history/1 to get the date when the patient was 1st enrolled to the system as shown in the below code snippet 

`````
  "meta": {
    "versionId": "1",
    "lastUpdated": "2021-08-03T12:38:53.067+00:00",
    "source": "#65b176eb81769cba"
  },
`````
_This can also be used to track edits to the resource in the system_

**To get the last seen date in the patient list view use** 
- [ ] Patient never received shot 1 - use registration date as described above 
- [ ] Patient received shot 1 & shot n  - use the Immunization. occurrence filed from the Immunization resource

NB. The profile page was updated and no longer shows the registration date . We could add it in under the age section

**Comment by f-odhiambo** [comment]
@ellykits, I noticed the new profile page, we do not have a registered date, kindly add a field under the  age i.e. Registered: XX-XX-XXXX

**Comment by ellykits** [comment]
Noted.

**Comment by f-odhiambo** [comment]
moved the detail on patient profile to show registration date in the issue details above
