### ISSUE TITLE
August 18th Demo Release

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#495]
**Demo release**

- [x] Create demo release branch `who-demo-release`
- [x] Publish preview artifacts from the Android FHIR SDK e.g. for barcode feature
- [x] Merge in any PRs with features required for the demo
- [x] Create the demo release APK

**Comment by ndegwamartin** [comment]
@f-odhiambo could you confirm [which Features/PRs here](https://github.com/opensrp/fhircore/pulls) are required for the Demo tomorrow?

**Comment by f-odhiambo** [comment]
> @f-odhiambo could you confirm [which Features/PRs here](https://github.com/opensrp/fhircore/pulls) are required for the Demo tomorrow?

@ndegwamartin Here is a checklist of the relevant PRs and features required 

- [ ] https://github.com/opensrp/fhircore/pull/492 
- [ ] https://github.com/opensrp/fhircore/pull/483  - Has the latest Quesionnaire for bar code 


CC @MuhammadSalman-7214 @syedowaisali90

**Comment by f-odhiambo** [comment]
**Some key things** 
WHO also wanted for us to 
- [ ]  hide any comorbidities questions 
- [ ] change the filter from Nairobi to Rome 

```
 fun addBasePatientFilter(search: Search) {
    search.filter(Patient.ADDRESS_CITY) {
      modifier = StringFilterModifier.CONTAINS
      value = "NAIROBI"
    }
  }
```

CC @MuhammadSalman-7214 @syedowaisali90

**Comment by MuhammadSalman-7214** [comment]
> **Some key things**
> WHO also wanted for us to
> 
> * [ ]   hide any comorbidities questions
> * [ ]  change the filter from Nairobi to Rome
> 
> ```
>  fun addBasePatientFilter(search: Search) {
>     search.filter(Patient.ADDRESS_CITY) {
>       modifier = StringFilterModifier.CONTAINS
>       value = "NAIROBI"
>     }
>   }
> ```
> 
> CC @MuhammadSalman-7214 @syedowaisali90

@f-odhiambo we are rendering questionnaire from server. If we don't want to include comorbidities question, then we have to update questionnaire from server and remove comorbidities question from server

**Comment by f-odhiambo** [comment]
Thanks for all the effort @MuhammadSalman-7214 @syedowaisali90 @ndegwamartin. Closing this ticket for now
