### ISSUE TITLE
CHW/ANC - Add location widget 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#520]
Tracking issues for [#800](https://github.com/google/android-fhir/issues/800)

**Comment by pld** [comment]
would this be useful in the Android FHIR SDK?

CC @jingtang10

**Comment by jingtang10** [comment]
> would this be useful in the Android FHIR SDK?
> 
> CC @jingtang10

Yeah absolutely. There are two parts to this

 - create a new widget that captures the location
 - have a sample questionnaire that has extraction set up that uses that widget

**Comment by pld** [comment]
Is there an issue in Android FHIR SDK that this links with?

**Comment by f-odhiambo** [comment]
> Is there an issue in Android FHIR SDK that this links with?

Yes there is now [#800](https://github.com/google/android-fhir/issues/800)

**Comment by f-odhiambo** [comment]
Done via https://github.com/opensrp/fhircore/issues/1536
