### ISSUE TITLE
Standardized theme when app is in use in either Light mode or Dark mode 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#527]
**Describe the bug**
Need to standardize the app theme to be default in either dark or light theme. Applied in mostly data entry fields and questionnaires 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  app setting and switch between light and dark mode
2. Check on Login page or select a questionnaire entry form 

**Expected behaviour**
The proposal is to The theme should be standardised across the entire app. To be advised by the design team 

**Screenshots**

**Light mode** 
<img src="https://user-images.githubusercontent.com/4540684/132827073-37f15dc8-423b-4485-b35c-3427eb0c9cde.png" width="200" height="400" />

**Dark mode** 
<img src="https://user-images.githubusercontent.com/4540684/132827086-62fb1e54-6ded-44b9-abaf-38682ae37825.png" width="200" height="400" />

**Smartphone (please complete the following information):**
The device with Dark theme enable functionality 

**Additional context**
N/A

**Comment by f-odhiambo** [comment]
@ellykits @syedowaisali90 Take note.

@rowo Kindly advise

**Comment by ellykits** [comment]
I have disabled dark theme mode for now.

**Comment by pld** [comment]
I think disabling is sufficient, this feels very low priority

**Comment by f-odhiambo** [comment]
**Update Jan 20th 2022**
Dark mode disabled in Quest 

CC @ndegwamartin
