### ISSUE TITLE
CHW/ANC - View Past Encounters for an individual household member profile 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#544]
Query and view all the past encounters for a patient and add pagination or continous scroll view 

**Access from menu item**

<img src="https://user-images.githubusercontent.com/4540684/133265687-8d0dbf9c-906b-469a-b9c3-cb400a84dcb2.png" width="200" height="400" />

**View past encounters**

- [ ] View status of the task  - check status field 
- [ ] View detail of the encounter type  - check class.display field

sample encounter resource 

```
{
  "resourceType": "Encounter",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Encounter with patient @example</div>"
  },
  "status": "in-progress",  
  "class": {
    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "code": "IMP",
    "display": "inpatient encounter".
  },
  "subject": {
    "reference": "Patient/example"
  }
}
```
<img width="200" height="400" alt="Screen Shot 2021-09-21 at 3 15 24 PM" src="https://user-images.githubusercontent.com/4540684/134169824-8fa2dfc0-fd04-4b60-ba5c-1ecb5b04c548.png">

**Comment by f-odhiambo** [comment]
@ellykits I think this is a good candidate to showcase continuous scroll view/loading new details. Let me know what you think. Thanks

**Comment by HenryRae** [comment]
@f-odhiambo were are we showing [these](https://github.com/opensrp/fhircore/issues/544#issuecomment-919156949) encounters?
If it's in that "past encounters" section then I think we don't need to show some statuses since it's **PAST** encounters.
I think maybe there's need for us to discuss if we need all these statuses.

cc: @rowo

**Comment by f-odhiambo** [comment]
> @f-odhiambo were are we showing [these](https://github.com/opensrp/fhircore/issues/544#issuecomment-919156949) encounters?
> If it's in that "past encounters" section then I think we don't need to show some statuses since it's **PAST** encounters.
> I think maybe there's need for us to discuss if we need all these statuses.
> 
> cc: @rowo

Hi, @HenryRae This is accurate. You can progress based on the discussion we had on the call, to add icons for encounters that have been done in the past or cancelled. Future tasks may not apply here

**Comment by f-odhiambo** [comment]
@HenryRae For upcoming services/encounters will update the icons for this tickets #543

**Comment by f-odhiambo** [comment]
@syedowaisali90 Here are updated [images](https://drive.google.com/drive/folders/1l4MHDUqo78uS9ZPo-lgJISnaZBGrMtnM?usp=sharing) and icons for update and also updated mock

<img width="465" alt="Screen Shot 2021-09-21 at 3 15 24 PM" src="https://user-images.githubusercontent.com/4540684/134169824-8fa2dfc0-fd04-4b60-ba5c-1ecb5b04c548.png">
