### ISSUE TITLE
Known issues with Family registration

### ISSUE THREAD

**Issue by maimoonak** [opensrp/fhircore#548]
**Describe the bug**
Some known issues exist on Family Registration and ANC Flow which needs to be resolved

**Issues**

- [x] 1- Thousands of records may need a proper filter when syncing (Discussion Point)
- [x] 2- Questionnaire must have ONA as publisher OR may be any category as well for different apps (Discussion Point)
- [x] 3- Use Practitioner and CareTeam reference when added by the server
- [ ] _4- Observation not binding to date only (SDK issue)_
- [x] _5- Sync failing due to some entity/record (Maimoona)_
- [x] _7- Implement SDK changes into data load for tags (Maimoona)_
- [x] _8- Add CarePlan based on activity detail of CarePlan (Maimoona)_
- [x] 9- Use vector instead of png https://github.com/opensrp/fhircore/pull/547#pullrequestreview-754886342 (Need images from Roger)
- [x] 10- Remove run blocking from side menu count when functionality is implemented @ellykits

**Comment by maimoonak** [comment]
@ellykits I noticed the issue on sync is due to this line in engine -> FhirResourceConverter

```
return parser.parseResource(Bundle::class.java, value.string())
```

Basically the data after insert is the resource itself and not the bundle resource. Any reason it is casting to Bundle?

![Screenshot from 2021-09-20 17-34-15](https://user-images.githubusercontent.com/4829880/134005673-93f1440c-3cb5-472a-91bf-45d859f2aa17.png)
![Screenshot from 2021-09-20 17-33-42](https://user-images.githubusercontent.com/4829880/134005686-ca24fbbe-fde3-41ef-99dd-af739c47c105.png)

**Comment by ndegwamartin** [comment]
@maimoonak would casting to `Resource` type instead solve it without breaking the app?

**Comment by maimoonak** [comment]
I guess no! But SDK class src/main/java/com/google/android/fhir/reference/api/FhirConverter.kt does implementation of this.

**Comment by maimoonak** [comment]
7- Implement SDK changes into data load for tags (Maimoona)
8- Add careplan based on activity detail of Careplan (Maimoona)

Above would be resolved by #556

**Comment by ellykits** [comment]
1. and 2. Are related to app configuration work tracked separately.

**Comment by maimoonak** [comment]
#-3 is partially done by adding [organization](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModel.kt#L154) to Patient when extracting resources. The rest would be done and accommodated into work done for #594 
 #-4 only occurs when mapping observation via fhir-path which is unlikely and we use structure-map for extraction, so it can be ignored

**Comment by pld** [comment]
@maimoonak it appear these are all handled, if that's true please go ahead and close this issue
