### ISSUE TITLE
CHW/ANC - Create a FHIR Questionnaire to record pregnancy outcome and create new Patient(s)

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#553]
This questionnaire will  be used to : 
- [ ] Record a pregnancy outcome details
- [ ] Create new patient(s) record for newborn(s)

Form dictionary available [here](https://docs.google.com/spreadsheets/d/1vMCTQTfh4NN0IgtUWPGeU1uxreUgXPCGbiy59exNV7E/edit#gid=1097941285) 

NB. Multiple resource extreaction will be required here

**Comment by f-odhiambo** [comment]
Based on the below mock 
<img width="618" alt="Screen Shot 2021-09-07 at 11 10 21 AM" src="https://user-images.githubusercontent.com/4540684/132325530-083d77fa-1a74-4a5e-8cd2-2a5b35276e89.png">

1. If multiple births do we need to create a nested form that will be used to record the new children born ?
2. Do we create a new patient record and mark deceased if child dies or stillbirth?

CC @isabelcshaw @rowo @HenryRae

**Comment by rowo** [comment]
Pregnancy outcome form: https://docs.google.com/spreadsheets/d/1vMCTQTfh4NN0IgtUWPGeU1uxreUgXPCGbiy59exNV7E/edit#gid=1097941285

Figma mockups: https://www.figma.com/file/QZ4cdpgBNy86XTOUnrnLap/COVID19-FHIR-Future-Design-System?node-id=3426%3A34064

![CHW - due](https://user-images.githubusercontent.com/1584163/134367152-5a39823f-22ce-4052-89da-9899e9972467.png)

![CHW-WRA - preg outcome-2](https://user-images.githubusercontent.com/1584163/134367185-6a9c4d3c-831b-4ab4-8a9a-aa088a37eecb.png)

![CHW-WRA - preg outcome](https://user-images.githubusercontent.com/1584163/134367202-788dc3e8-1d67-487f-a9ed-381f24ad330f.png)

Multiple children at birth has repeat groups. @HenryRae think about this a bit if there's a better UX we can do here.
![CHW-WRA - preg outcome-1](https://user-images.githubusercontent.com/1584163/134367220-97d6b60f-a357-498a-b0cb-a7b31bcf97f5.png)

For new patient record for stillbirth — what goes into making this decision? Is it about reporting or whether the stillbirth appears as a family member?

**Comment by f-odhiambo** [comment]
Quick thoughts : This approach for adding births via an incremental count may not be supported by FHIR questionnaire, may need a custom approach

@rowo @HenryRae
