### ISSUE TITLE
Add / update missing or conflicting properties into Patient, Observation resources for ANC Patients

### ISSUE THREAD

**Issue by maimoonak** [opensrp/fhircore#555]
**Make Patient resources compliant with data being by ANC CQF work**

**Current Patient profiles are not 100% compliant with requirements for CQF ANC**

Some of the conflicting attributes are:

- [ ] 1 - Profile not set to "http://fhir.org/guides/who/anc-cds/StructureDefinition/ancpatient" (Bryn in one of the discussions mentioned that Profiling is not the best and recommended approach)
- [x] 2 - No identifier being set yet in app (would add to questionnaires)
- [ ] 3 - We donot have CQF into our forms
- [x] 4 - We are using snomed mapping and not loinc into our Questionnaires. Need to make sure that all questionnaires are properly assessed and gone through Product Manager for mappings
- [x] 5 - Pregnancy status Obs not created in current app (would add into our ANC flow)
- [ ] 6 - HB Obs not collected yet (I guess Abdul Wahab is working on it)
- [ ] 7 - Encounter for HB not created yet (I guess it depends on above point)

Any other requirements? @f-odhiambo

**Comment by f-odhiambo** [comment]
@maimoonak this looks ok I will seek Brynn's advise and also pose it on the WHO Tuesday call about codable concepts and the usage of SNOMED/LOINC codes.

Also to note here that there is a thin boundary of what EMRs are supposed to do in comparison to an ANC app so will seek clarification on the same in subsequent calls

**Comment by pld** [comment]
> @maimoonak this looks ok I will seek Brynn's advise and also pose it on the WHO Tuesday call about codable concepts and the usage of SNOMED/LOINC codes.
> 
> Also to note here that there is a thin boundary of what EMRs are supposed to do in comparison to an ANC app so will seek clarification on the same in subsequent calls

Is there an update here from the CPG call?

**Comment by AbdulWahabMemon** [comment]
@maimoonak , I worked on BMI computation, and @RaaziaTarique did on vital-signs, though none of our tasks include capturing HB Obs in questionnaire.
cc: @f-odhiambo

**Comment by AbdulWahabMemon** [comment]
@pld , the questionnaire I worked for BMI is also in assets as sample-bmi-compute-questionnaire, one can access that on local server with id=1999.

as per last discussion with @maimoonak on this issue, it was mentioned that there is no HB-Obs property being add/update within bmi questionnaire or vital-sign questionnaire from @RaaziaTarique's work.

cc: @f-odhiambo

**Comment by pld** [comment]
closed by #852
