### ISSUE TITLE
Update Vaccine codes and Manufacturer for the Covax demo app 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#558]
Add Vaccine codes to the various Vaccine options questionnaire that will be submitted in the Immunization resource payload once a patient received a vaccine shot. This is for the 4 options in the current demo 

**1. Pfizer**

**Code** 
```
"vaccineCode": {
    "coding": [
      {
        "system": "https://icd.who.int/dev11/l-m/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f667112200",
        "code": "XM8NQ0",
        "display": "XM0GQ8 COVID-19 vaccine, RNA based"
      }
    ],
    "text": "Pfizer"
  },
```

**Manufacturer** - Changes per country. For demo use 

```
  "manufacturer": {
    "identifier": {
      "system": " https://icd.who.int/dev11/l-m/en "
    },
    "display": "BioNTech"
  },
```

**2. Moderna**

**Code** 
```
"vaccineCode": {
    "coding": [
      {
        "system": "https://icd.who.int/dev11/l-m/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f1211296175 ",
        "code": "XM3DT5",
        "display": "XM0GQ8 COVID-19 vaccine, RNA based"
      }
    ],
    "text": "Moderna"
  },
```

**Manufacturer** - Changes per country. For demo use 

```
  "manufacturer": {
    "identifier": {
      "system": " https://icd.who.int/dev11/l-m/en "
    },
    "display": "Moderna"
  },
```
**3. AstraZeneca**

**Code** 
```
"vaccineCode": {
    "coding": [
      {
        "system": "https://icd.who.int/dev11/l-m/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f473439328 ",
        "code": "XM4YL8",
        "display": "XM9QW8 COVID-19 vaccine, non-replicating viral vector"
      }
    ],
    "text": "AstraZeneca"
  },
```

**Manufacturer** - Changes per country. For demo use 

```
  "manufacturer": {
    "identifier": {
      "system": " https://icd.who.int/dev11/l-m/en "
    },
    "display": "Oxford"
  },
```
**4. Janssen**

**Code** 
```
"vaccineCode": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "1119349007",
        "display": "SARSCoV2  mRNA vaccine"
      }
    ],
    "text": "Janssen"
  },
```

**Manufacturer** - Changes per country. For demo use 

```
  "manufacturer": {
    "identifier": {
      "system": " https://icd.who.int/dev11/l-m/en "
    },
    "display": "Johnson & Johnson"
  },
```

**Comment by ekigamba** [comment]
- Suggested COVID-19 vaccine codes link https://icd.who.int/dev11/l-m/en#/http://id.who.int/icd/entity/1802851204
- Current WHO value set https://worldhealthorganization.github.io/ddcc/ValueSet-who-ddcc-vaccines-covid-19.html

**Comment by f-odhiambo** [comment]
1. Type of vaccines listed in the spec (will be updated with new ICD-11 codes) https://worldhealthorganization.github.io/ddcc/ValueSet-who-ddcc-vaccines-covid-19.html
2. Vaccine codes have also been created in ICD -11: https://icd.who.int/dev11/l-m/en#/http://id.who.int/icd/entity/1802851204
3. Presentation Carl shared: https://docs.google.com/presentation/d/1WRjcGzeX5TQdj2mkVI8o-XJlyVR70L0BVrzn9HGETJk/edit
4. Github Issues link Richard shared: https://github.com/synthetichealth/synthea/issues/869
5. Data elements using element names: https://github.com/intrahealth/synthea-elements/blob/main/prepare-elements-names.ipynb
6. List of covid vaccines that have been adopted and have an Market Authoritization in at least one country (shared by Derek): https://en.wikipedia.org/wiki/List_of_COVID-19_vaccine_authorizations
