### ISSUE TITLE
CHW/ANC - Extract vital signs observations and encounter using StructureMap

### ISSUE THREAD

**Issue by RaaziaTarique** [opensrp/fhircore#561]
Origin Issue #528 

Sample Observation:
https://www.hl7.org/fhir/observation.html
https://www.hl7.org/fhir/observation-example.json.html
http://hl7.org/fhir/us/core/2021Jan/Observation-blood-pressure.json.html
https://www.hl7.org/fhir/observation-example-f001-glucose.json.html
https://www.hl7.org/fhir/observation-example-satO2.json.html
 
CC: @f-odhiambo

**Comment by ekigamba** [comment]
Extract Encounter with either of the following:

- [ ] Weight observation
- [ ] Height observation
- [ ] Blood Oxygen Level observation
- [ ] Blood pressure observation
- [ ] Pulse rate observation
- [ ] Blood glucose observation
