### ISSUE TITLE
Update codebase documentation

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#565]
**Documentation**

- [ ] ~Restructure change log based on existing multiple modules~ [See the comment here](https://github.com/opensrp/fhircore/issues/565#issuecomment-931106536l)
- [x] Update coding standards documentation

**Comment by pld** [comment]
I don't think it's worth the time to retroactively update the changelog, let's just do it going forward

**Comment by ndegwamartin** [comment]
For updates to the multiple modules, since we envision a single APK in future, all the updates should preferable go to the same [CHANGELOG.md](https://github.com/opensrp/fhircore/blob/main/CHANGELOG.md) file. 

We can approach it by adding the module name before the update separated by a pipe character 
e.g. `ANC | Add Family Member Profile`
