### ISSUE TITLE
Quest v0.1 / G6PD: Authentication 

### ISSUE THREAD

**Issue by isabelcshaw** [opensrp/fhircore#569]
This issue includes all work required to allow a user to log in and out of the Quest / G6PD application. 

**Login / Logout UX:** 
Pull in the ability for an end user to log into the app via a username and password. 
Pull in the ability for an end user to log out of the app via an option in the settings menu in the bottom right navigation. 

Reuse the current login UI
<img width="259" alt="Screen Shot 2021-09-22 at 1 20 11 PM" src="https://user-images.githubusercontent.com/12836913/134416050-8f13fa60-32cc-4967-bae8-309c18ef6b63.png">

**Comment by isabelcshaw** [comment]
@rowo the [Quest mocks here](https://docs.google.com/presentation/d/166OtwGqN_ZnaT6qT4TcF6t75qO4pVVnsTYCmT5WbsLQ/edit#slide=id.gf01d0db526_0_120) represent a shift to the bottom navigation only. Was this a design system decision for how we wanted to handle our simpler apps? (just want to confirm navigation as it relate to the settings functionality for this case) 

If so, then my understanding is that if you hit "settings" in the bottom nav, we would be directed to a simplified version of this view: https://www.figma.com/file/QZ4cdpgBNy86XTOUnrnLap/COVID19-FHIR-Future-Design-System?node-id=2518%3A26055

**Comment by pld** [comment]
No keycloak setup needed, we can use the existing keycloak and create a `g6pd-demo` user (or named whatever) that has a `g6pd` publisher field somewhere in it so it aligns with #571
