### ISSUE TITLE
Quest v0.2 / G6PD: test results questionnaire 

### ISSUE THREAD

**Issue by isabelcshaw** [opensrp/fhircore#570]
This issue covers all work required to open, present, and submit the G6PD questionnaire. 

**_As an end user, when I select the G6PD form, I want to be able to fill in the required fields and submit the questionnaire._**  

Most updated mocks of the questionnaire live in [this Figma project](https://www.figma.com/file/PDv9RjEun7Y7Xhqzt48EOB/COVID19-FHIR-Future-(All-Sandbox)?node-id=2202%3A11979).
 
<img width="504" alt="Screen Shot 2021-10-11 at 1 16 48 PM" src="https://user-images.githubusercontent.com/12836913/136850586-13fd3a8f-60b7-4a47-95ab-9dc6ec5e0c8b.png">

_Please note that for this scope, the button will say "Save" not "Next"_

**There are three key fields:** 
1. G6PD result type - [select one: "Number," Error," "N/A"] 
2. G6PD - [decimal]
3. Hemoglobin (Hb) - [decimal]
_Do not worry about field constraints for this release unless @f-odhiambo these were provided already?_

**Expected form logic:** 
If the user selects "Number" as the G6PD result type, present both G6PD and Hemoglobin (Hb) fields. If the user selects "Error" or "N/A" don't show the G6PD and Hemoglobin (Hb) fields. @maimoonak if we are running into any challenges with the form logic that could delay delivery, we can have a questionnaire with three static fields. TBC 

Other work this issue touches, but does **not** include: 
- [ ] Establishing a method of tagging the specific questionnaire so that the end user can open it when they hit the "record test result" button --> work being delivered by Trevor / Maimoona 
- [ ] Establishing how to integrate images into the questionnaire (for training step) -->  https://github.com/opensrp/fhircore/issues/572
- [ ] Visualizing the results of the questionnaire responses --> this is part of WP2 and not in scope

**Comment by maimoonak** [comment]
There are two extensions to change text style into a questionnaire but none is working

1. "http://hl7.org/fhir/StructureDefinition/rendering-style",
2. "http://hl7.org/fhir/StructureDefinition/rendering-xhtml",

Which means that we can not make the questionnaire dynamic and independent of G6PD flow or do all into one questionnaire unless we have these functional in SDK.

**Comment by f-odhiambo** [comment]
**Update**
This is WIP as of Oct 12th 2021
