### ISSUE TITLE
 Quest v0.2 / G6PD: Create FHIR Service Request

### ISSUE THREAD

**Issue by mwkhan1983** [opensrp/fhircore#597]
ServiceRequest is a record of a request for a procedure or diagnostic or other service to be planned, proposed, or performed, as distinguished by the `ServiceRequest.intent` field value, with or on a patient. The procedure will lead to either a [Procedure](https://www.hl7.org/fhir/procedure.html) or [DiagnosticReport](https://www.hl7.org/fhir/diagnosticreport.html), which in turn may reference one or more [Observations](https://www.hl7.org/fhir/observation.html), which summarize the performance of the procedures and associated documentation such as observations, images, findings that are relevant to the treatment/management of the subject.

**Comment by mwkhan1983** [comment]
**Peter**: How is this created? Simplest might be to create with a StructureMap from the QuestionnaireResponse when a client is registered

**Comment by mwkhan1983** [comment]
**Francis**: Yes. That's one approach . We can decide on the best approach once we assign a ticket for this incase we need to change the implementation for another alternative

**Comment by pld** [comment]
I'm still not convinced this is required and that we should do it, marking as blocked.

**Comment by pld** [comment]
service request generation is handled in #599, that looks like it covers this issue, closing
