### ISSUE TITLE
Configure questionnaires 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#6]
Configure questionnaires to collect data for 

1. Registration
2. Observation
3. Immunization
4. COVID-19 Screening

**Comment by rkodev** [comment]
Immunization issue is related to this issue https://github.com/OpenSRP/fhircore/issues/21

**Comment by pld** [comment]
I don't think Observation is specific enough, perhaps same with Registration b/c it depends on the use-case
