### ISSUE TITLE
Add UserConfiguration

### ISSUE THREAD

**Issue by ellykits** [opensrp/fhircore#603]
**Name of feature to enhance**
User configuration

**Description of feature**
Introduce a new configuration for providing user settings like realm access role

**Describe the enhancement**
There are some configurations that specific to a logged in user that needs to be provided separately

**Comment by pld** [comment]
Where/how is this added?

What exactly will it control?

**Comment by ellykits** [comment]
Closing this. @trevorgowing Has created a new issue to provide more context here #607
