### ISSUE TITLE
Quest v0.2: Add a configurable login page for the app

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#605]
**Name of feature to enhance**
Add a configurable login page for the app

**Describe the enhancement**
- [ ] Change icon
- [ ] Background color to white 
- [ ] Change auth details  i.e. create new user and organization for user-specific for G6PD
- [ ] Only sync G6PD specific data  with G6PD publisher attribute 

Attached is a screenshot
<img width="375" alt="Screen Shot 2021-10-05 at 9 53 31 AM" src="https://user-images.githubusercontent.com/4540684/135976875-0bbafa7e-f7e5-45f9-a301-a7df1b8dd77c.png">

Here is a link to the SVG icon https://drive.google.com/file/d/1UM0f0viRCOc7pS2M1iQ2coLFTIZ2v-mh/view?usp=sharing

**Comment by pld** [comment]
This is blocked by research on how we encode and sync configurations for the app, touched on this discussion, https://github.com/opensrp/fhircore/discussions/594
