### ISSUE TITLE
Questionnaire Publisher Filtering

### ISSUE THREAD

**Issue by trevorgowing** [opensrp/fhircore#607]
**Name of feature to enhance**
Questionnaire Publisher Filtering

**Description of feature**
In order to support different applications ANC, EIR & Quest from potentially a single FHIR Server there is a need to filter resources based on certain fields.

In the context of the Quest Application there is a requirement to filter [Questionnaires](http://hl7.org/fhir/questionnaire.html) by the [publisher](http://hl7.org/fhir/questionnaire-definitions.html#Questionnaire.publisher) field.

In order to support this requirement a solution was discussed between @f-odhiambo @maimoonak @trevorgowing @ndegwamartin and @dubdabasoduba.

The agree solution was to add an additional role to the user in keycloak and expose that via the `GET /userInfo` endpoint.
```json
{
    "sub": "dbde5c0c-2aa0-4278-a505-f6ef9d262a1b",
    "email_verified": false,
    "realm_access": {
        "roles": [
            "g6pd-questionnaire",
            "offline_access",
            "default-roles-fhir_android",
            "uma_authorization",
            "g6pd"
        ]
    },
    "name": "G6PD Test",
    "groups": [
        "g6pd-questionnaire",
        "offline_access",
        "default-roles-fhir_android",
        "uma_authorization",
        "g6pd"
    ],
    "preferred_username": "g6pd",
    "given_name": "G6PD",
    "family_name": "Test",
    "email": "g6pddemo@ona.io"
}
```

This solution was implemented in #571 and #590.

**Describe the enhancement**

Identify a key/value storage mechanism in keycloak that can be use to expose an additional property in the `GET /userInfo` response of the form:
```json
{
  "questionnaire_publisher": "g6pd" 
}
```

So that a more generic solution can be implemented that doesn't require previous knowledge of the publisher value but rather only the key.

**Comment by ellykits** [comment]
Can we leverage custom user attributes on keycloak for this?

**Comment by trevorgowing** [comment]
@ellykits I don't know. Can we?

**Comment by ellykits** [comment]
I think so. Trying to find the relevant docs to share.

**Comment by ellykits** [comment]
Hope these will be helpful:

https://www.keycloak.org/docs/latest/server_admin/index.html#_user-attributes
https://www.baeldung.com/keycloak-custom-user-attributes

**Comment by trevorgowing** [comment]
Thanks @ellykits. I will check those out.

**Comment by trevorgowing** [comment]
Steps to expose custom user attribute:

1. Add a custom attribute to the user. [Keycloak Docs](https://www.keycloak.org/docs/latest/server_admin/index.html#_user-attributes). [Keycloak Admin Interface](https://keycloak-stage.smartregister.org/auth/admin/master/console/#/realms/FHIR_Android/users/dbde5c0c-2aa0-4278-a505-f6ef9d262a1b/user-attributes).
2. Expose the custom user attribute by adding a mapping to the client. [Keycloak Docs](https://www.keycloak.org/docs/latest/server_admin/index.html#_protocol-mappers). [Keycloak Admin Interface](https://keycloak-stage.smartregister.org/auth/admin/master/console/#/realms/FHIR_Android/clients/d614163b-97ed-43c8-b48d-1c6cca852588/mappers).
