### ISSUE TITLE
Quest v0.2 / G6PD: Sub-Task - Add validation before posting a registration questionnaire 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#616]
**Acceptance criteria** 
- [ ] Check on mandatory and optional fields before submission 
> 1. Family name*
> 2. Given name*
> 3. Gender*
> 3. Contact *
<img src="https://user-images.githubusercontent.com/4540684/135977549-db9f5aa2-cf81-44f0-9cb9-fe58b520e51f.png" width="200" height="400" />

**NB. This is a good candidate to also test validation of required fields based on the SDC library.** 
This ticket will be used to track the FHIRCore implementation

**Comment by pld** [comment]
Cool, it's possible this'll be baked into the SDC and all we need to do to close this issue is verify that's functioning as expected

**Comment by pld** [comment]
Sounds like we need to implement our own validation in FHIR Core in the mean time, doesn't look like anyone's working on that broader issue

**Comment by maimoonak** [comment]
<img height="400" width="200" src="https://user-images.githubusercontent.com/4829880/138291487-a05d90f1-d3b5-475e-b06b-f7352a414b78.jpg">

**Comment by pld** [comment]
Instead of showing a popup, can we disable the "Save" button until validation passes?
