### ISSUE TITLE
Quest v0.2 / G6PD: Subtask - Allow configuration of G6PD classification thresholds

### ISSUE THREAD

**Issue by mwkhan1983** [opensrp/fhircore#627]
As a user I want to configure G6PDS thresholds which will be provided as an input to RIM to calculate patient status.

There can be separate threshold values based on gender.  The solution should allow the configuration of G6PD thresholds per implementation basis. It should not be uniform for all implementations.

![image](https://user-images.githubusercontent.com/69383347/137087885-957ccce1-409b-487a-bfca-0f1e69ff44c3.png)

**Options to load thresholds:**
- [x] 1. Use custom method
- [ ] 2. Use FHIRPath
- [x] 3. Use CQL - Load G6PD thresholds via a Library Resource - Proposal to load Clinical recommendation and Medication request from CQL statements contained in a  Library Resource

**Comment by f-odhiambo** [comment]
This is done via CQL
