### ISSUE TITLE
Quest v0.2 / G6PD: Develop Results Interpretation Module (RIM)

### ISSUE THREAD

**Issue by mwkhan1983** [opensrp/fhircore#630]
As a healthcare worker, I should be able to assign patient classification based on predetermined thresholds of G6PD activity. 

 Based on the configured thresholds, the following classification can be assigned to male and female patients:

**Male**
- G6PD deficient  
- G6PD normal  

**Female**
- G6PD deficient
- G6PD intermediate  
- G6PD normal

Please refer to image below for G6PD status & PQ regimen:
![image (9)](https://user-images.githubusercontent.com/69383347/137092561-c596e10a-983b-41d7-af92-24bd8d06231f.png)

**Calculator should be available with or without the link to patient record**

Calculation/decision support flow should be available as a stand-alone functionality of the app as well as part of a reference application. The decision support flow will be provided through Results Interpretation Module (RIM).  RIM will be available both as a separate module (and can be integrated by third-party applications) and as part of the reference application.

![image](https://user-images.githubusercontent.com/4540684/137742257-9025a958-548f-418b-869f-3d889baefb15.png)

**SubTask**

- [x] #627

**Comment by pld** [comment]
Technical approach is discussed in https://github.com/opensrp/fhircore/discussions/659, specifically https://github.com/opensrp/fhircore/discussions/659#discussioncomment-1548255

**Comment by pld** [comment]
think this is complete
