### ISSUE TITLE
Minimum SDK support for FHIR Core

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#639]
**Describe the Issue**
We need to test the FHIRCore modules on the lower API versions and log any bugs found for implementation
FHIR SDK supports from API 21, we can use this as the minimum and test all the way up till API 30

Checklist:
- [ ] Quest
- [ ] EIR
- [ ] ANC

**Comment by f-odhiambo** [comment]
@ndegwamartin @dubdabasoduba should we close this and move this info to the docs ?

**Comment by ndegwamartin** [comment]
@f-odhiambo yeah I think if we are confident the app works okay from API 21 to 30 we can indeed close it
