### ISSUE TITLE
Quest v0.2/ G6PD: Get a patient's DOB by entering their age as an integer 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#652]
**Name of feature to enhance**
Add a client's DOB by entering their age as an integer 

**Description of feature**
Add on the registration questionnaire for Quest the ability to add age either an integer or actual date, add a selection before the DOB as seen in the screenshot below 

**Describe the enhancement**
1. Add a skip logic question that asks a user to either enter date as a number or date 
2. If Date show a date picker else if number enter a numerical filed
3. On submit, if used date picker submit date, if integer, get the value and compute the DOB i.e if today is **2021**, and entered 21, compute DOB as 2021-21 = **01-01-2020**

**Screenshot**
<img src="https://user-images.githubusercontent.com/4540684/138410974-d5c1e472-2cc2-4435-818a-718310b3065d.png" width="200" height="400" />

**Comment by AbdulWahabMemon** [comment]
> True, could be a use-case for CQL then.
> 
> But yes, I think writing the structure map to get as close as we can is worthwhile, we'll need it regardless at some point. I think @ekigamba is working on moving the Structure Map Language to Structure Map code out of the app and to a separate tool, worth liasing with him so you can write in SML and generate the Structure Map JSON.
> 
> To store and process the structure map we need to complete the engine work for #594 (connecting a StructureMap to a Questionnaire) and #659 (post-Questionnaire submission processing of extraction and computation)

**Comment by AbdulWahabMemon** [comment]
reopenning this as it was close by mistake

**Comment by f-odhiambo** [comment]
This is marked as done for now, any enhancements will be done later in a new ticket
