### ISSUE TITLE
Build patient register page UI

### ISSUE THREAD

**Issue by vincent-karuri** [opensrp/fhircore#66]
This issue is based off these [mockups](https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=247%3A4829). The different deliverables are:

-  Build patient list: 
    - [x] Create ViewHolder
    - [x] Create RecyclerView
    - [x] Create ViewModel
    - [x] Create LiveData populator
    - [ ] Support pagination
    - [x] Add patient registration button
 
- Build app bar:
    - [x] Create search field
    - [x] Create NavigationDrawer
    - [x]  Add `Show overdue` toggle button

- Support configurability of the views (TBD)

**Comment by vincent-karuri** [comment]
@pld @rowo @f-odhiambo is this agreed to be the general UI for FHIR apps going forward? If so, should we be thinking about the approach to make it configurable?

**Comment by vincent-karuri** [comment]
@rowo A few questions:

1. Do we need the `mic` icon [here](https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=247%3A4829)?
2. What happens when we click the back arrow in the search field [here](https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=247%3A4863)?
3. What happens when we click the `X` in the search field [here](https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=247%3A4863)?

**Comment by vincent-karuri** [comment]
Support paging: https://developer.android.com/topic/libraries/architecture/paging

**Comment by vincent-karuri** [comment]
https://developer.android.com/topic/libraries/architecture/paging/ui
https://developer.android.com/topic/libraries/architecture/paging/data

**Comment by rowo** [comment]
@vincent-karuri 
1. No mic. Sorry, that was from another thing. 
2 and 3. Sorry also. So this search box should just work the same as it does currently. We're working on a larger system that I pulled this from. The only thing that really changes for this app is the "due" column statuses/buttons and possibly the identification information. As far as identification information — if "last seen" is feasible right now, the view works as is. However, if not, we should just move the sex and age to the second line.

**Comment by vincent-karuri** [comment]
@rowo cool, yea I was just going to mock `last seen` for now since we can't pull that info atm - it may be supported down the line.

**Comment by vincent-karuri** [comment]
Looks like paging may require a bit more work. We can track this in the SDK https://github.com/google/android-fhir/issues/441.

**Comment by vincent-karuri** [comment]
> https://developer.android.com/topic/libraries/architecture/paging/ui
> https://developer.android.com/topic/libraries/architecture/paging/data

This may not be what we're looking for, consider [viewpager2](https://developer.android.com/training/animation/screen-slide-2).

**Comment by vincent-karuri** [comment]
@rowo is there a specific design for the `next` and `prev` navigation buttons for the register? Or do they just look as they are in OpenSRP? `<< PREVIOUS` and `NEXT >>`?

**Comment by rowo** [comment]
@vincent-karuri I don't have anything specifics. I think the bias should be on either reusing what we have or using any existing defaults as defined by Google.

**Comment by vincent-karuri** [comment]
@rowo with the registration button at the bottom I'm not sure of the right place to put these controls (which are usually at the bottom).

In Android, the implementation would be supported by a version of this [feature](https://developer.android.com/training/animation/screen-slide-2).
