### ISSUE TITLE
Quest v0.2/ G6PD: View DOB as Year and Month as opposed to zero (0)

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#661]
**Name of feature to enhance**
Show the exact age of a person as Year and Month 

**Description of feature**
The current app shows age as 0 when a person is less than 1 yr old. Hard to know how old a patient is from the Patient list or profile. See Screenshot

**Describe the enhancement**
Compute age as Year and Months and display accordingly 

**Screenshot**
<img src="https://user-images.githubusercontent.com/4540684/138687114-94dde9bd-f239-4614-b7fa-7309951b3db9.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
This should probably go somewhere (engine) where it's extensible across all Patient lists

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo I was writing unit test to cover different output from different ages 

here are some examples of expected age of patient :
val expectedAge1 = "31y 1m"
val expectedAge2 = "21y 1w"
val expectedAge3 = "1m 5d"
val expectedAge4 = "4d"
val expectedAge5 = "1w"
val expectedAge6 = "1w 2d"
val expectedAge7 = "1m 2w 3d"
val expectedAge8 = "1y 2m 3w 4d"

would such sample ages looks fine appending PatientName is the listing,
or we need to limit the display format like suggested 2 formats below
- #y #m 
- #m #d

cc: @HenryRae

**Comment by f-odhiambo** [comment]
I would prefer 
#y #m
#m #d

But ill defer to the design team to comment on this CC @rowo @HenryRae

**Comment by HenryRae** [comment]
My question would be when do we want to show months, weeks or days? @f-odhiambo and @AbdulWahabMemon 
Otherwise without that in question I would suggest we show

ages 10+ yrs = "#y" = 31y
ages <10 yrs = "#y #m" = 1y 2m
ages <1 yr = "#m #w" = 4m 2w
ages <1month = "#w #d" = 1w 2d
ages <1week = "#d" = 4d

@FrankApiyo @AbdulWahabMemon 
cc: @rowo

**Comment by f-odhiambo** [comment]
> My question would be when do we want to show months, weeks or days? @f-odhiambo and @AbdulWahabMemon 
> Otherwise without that in question I would suggest we show
> 
> ages 10+ yrs = "#y" = 31y
> ages <10 yrs = "#y #m" = 1y 2m
> ages <1 yr = "#m #w" = 4m 2w
> ages <1month = "#w #d" = 1w 2d
> ages <1week = "#d" = 4d
> 
> @FrankApiyo @AbdulWahabMemon 
> cc: @rowo 

Agreed let's use that approach

**Comment by AbdulWahabMemon** [comment]
![image](https://user-images.githubusercontent.com/66945489/139834067-5d356c66-de1f-49fe-a514-646ead98d898.png)
@f-odhiambo here is updated snap, and linked PR is ready to merge.

**Comment by f-odhiambo** [comment]
@AbdulWahabMemon is this reusable across all apps ? Quest and ANC specifically?

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo yes it is, actually it replaces all previous occurrences of age (# in years) from # to #y or #y #m #d (if matching the conditions in the ticket).
I did checked these in client listing and patient detail in Quest and ANC app also.

**Comment by f-odhiambo** [comment]
> @f-odhiambo yes it is, actually it replaces all previous occurrences of age (# in years) from # to #y or #y #m #d (if matching the conditions in the ticket).
> I did checked these in client listing and patient detail in Quest and ANC app also.

Fantastic 🙌

**Comment by f-odhiambo** [comment]
This issue has been implemented
