### ISSUE TITLE
Quest v0.2 / G6PD : Edit Patient Details 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#662]
**Is your feature request related to a problem? Please describe.**
NO
**Describe the solution you'd like**
- Add the ability to edit the user details from the profile page
- Add a menu item when you click on a patient on the patient list view  - accessed via the top bar menu item. See screenshot 

**Describe alternatives you've considered**
N/A

**Additional context**
Add the relevant structure map, retrieve the patient details, validate and save details. Patient Resource version number to be incremented upon save. i.e. meta.versionId
```
"meta": {
    "versionId": "1",
    "lastUpdated": "2021-10-19T18:12:19.994+00:00"
  },
```

**Acceptance criteria**
- [ ] 1. Edit user details 
- [ ] 2. Refresh patient details page 

**Screenshot**
**Screenshot of the mock** 
<img width="296" alt="Screen Shot 2021-11-22 at 8 55 04 AM" src="https://user-images.githubusercontent.com/4540684/142808115-b4b23189-243c-4cb1-9556-8c07abb758a6.png">

**Comment by f-odhiambo** [comment]
@pld The task here is to add the editing functionality of the patient resource and not the previously filled in survey via a QuestionnaireResponse. The patient is also saved before responding to a survey

**Comment by pld** [comment]
I understand that, the process is the same for patients as for surveys, you complete a Questionnaire and could implement this through edit in a Questionnaire based on a QuestionnaireResponse, so that both of these issues are using the same piece of code
