### ISSUE TITLE
Quest v0.2: Edit a survey once completed & submitted 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#667]
**Is your feature request related to a problem? Please describe.**

As a user of Quest, I would like to edit a previously submitted survey (QuestionnaireReponse) and submit  it back with updated responses 

**Describe the solution you'd like**

1. Access a previously filled in survey from the Patient profile 
2. On click, allow the user to get back a prepopulated form that can be updated and submitted back - see screenshot 

**Describe alternatives you've considered**
N/A

Provide validation for the mandatory and input fields types as deinfed by the questionnaire 

**Screenshot**
<img src="https://user-images.githubusercontent.com/4540684/138703271-5fb7c2e1-4cc7-4375-b5cf-0bfc24197259.png" width="200" height="400" />

NB. The version ID will be incremented on updates and can be used to track changes to the resource i.e. QuestionnaireReponse

```
"meta": {
    "versionId": "1",
    "lastUpdated": "2021-10-19T18:12:19.994+00:00"
  },
```

**Comment by ekigamba** [comment]
- @pld We will need to add support for saving previous versions of the same Resource instance so that we can have all versions of a Questionnaire and easily edit old QuestionnaireResponses. We can retrieve the historical versions of a single Resource from the Hapi FHIR server but we can only store 1 version per Resource instance. How is this  currently handled on Ona and ODK?
- @pld We can maintain older versions of QR and extracted resources on the device. However, they will have different **Resource.id**'s and we can filter `Resource.meta.lastUpdated` to get a history. We would still be able to match to the parent Questionnaire

Adding support for editing old QRs is currently under discussion within the team and Google. We'll split this issue into two:
- Editing QRs corresponding to current Questionnaires (current issue)
- Editing old versions of QRs https://github.com/opensrp/fhircore/issues/740

**Comment by ukanga** [comment]
Assuming a Questionnaire represents a single XLSForm/XForm/Form in ODK, every form has `id` and `version` attributes. When you have multiple versions of the same form, i.e. the form will have the same `id` attribute value, only the most recent is presented to the user. When the form is edited, the `id` attribute value never changes, but the form version will be updated. On the server side we will store all versions of the same form, but only expose to the user or primary API the latest version.
```XML
<!-- first version of the tutorial form -->
<data id="tutorial" version="202102161351">
...
</data>

<!-- Another version of the same tutorial form - same "id" different "versions" -->
<data id="tutorial" version="202111192035">
...
</data>
```
Assuming a QuestionnaireResponse represents  a single ODK XML submission, every submission has `id` and `version` attributes. The collection device/ODK Collect will generate a submission response with the `version` attribute using the form's id and version attributes e.g.`version="202111192035"` on the root node of the submission. The ODK aggregate server will accept ALL submissions of all form versions will be accepted by the server and be linked to that single form using the `id` attribute to identify the form the submission belongs to. Every submission contains a metadata element `<instanceID/>` which is an id that is meant to be a globally unique identifier.
```XML
<!--  a submission using the first version of the tutorial form -->
<data id="tutorial" version="202102161351">
...
    <meta><instanceID>uuid:22534d4d-07c3-4487-b48b-07725852e882</instanceID>
</data>

<!--  another submission using a newer version of the same tutorial form - same "id" different "versions" -->
<data id="tutorial" version="202111192035">
...
    <meta><instanceID>uuid:d1559e9e-5bab-480d-9804-e32111e8b2b8</instanceID>
</data>
```
When a submission is edited, the element `<instanceID/>`  will contain the new submission unique identifier as well as a new element `<deprecatedID/>` that contains the identifier for the record being edited. Take for example if we were to edit the submission above that has the identifier `uuid:d1559e9e-5bab-480d-9804-e32111e8b2b8`, the edit XML will now be:

```<!--  an edit submission XML -->
<data id="tutorial" version="202111192035">
...
    <meta>
        <instanceID>uuid:ae874dd4-8cb5-439b-87f0-545ae38d1689</instanceID>
        <deprecatedID>uuid:d1559e9e-5bab-480d-9804-e32111e8b2b8</deprecatedID>
</data>
```
On the server side, for a single submission with multiple edits, we store all the edits for that single submission and are able to trace the order through the elements `<instanceID/>`  and `<deprecatedID/>` .

If the client device has received a newer version of the form and is attempting to edit a submission that was captured by an older form then when the record is edited, it will use the format of the new version  of the form. Structurally the data changes and some fields in the record might disappear on edit, this is generally acceptable but if the hold history is necessary then it can be recovered server side.

I would hope FHIR has a way to handle a similar or equivalent scenario.

**Comment by pld** [comment]
Cool, thanks Dickson, this is what I expected and lines up w/my suggestion for how we handle it

> If the client device has received a newer version of the form and is attempting to edit a submission that was captured by an older form then when the record is edited, it will use the format of the new version of the form.
