### ISSUE TITLE
Dynamically select Period  (periodStart & periodEnd) for generation of measure reports 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#675]
**Name of feature to enhance**
As a Community health supervisor, I would like to see how a given facility is doing based on the recommended measures tracking various health Indicators in a given jurisdiction.

**Description of feature**
Add the ability to load measure reports that can be used to generate reports for either Individual ANC patients or a subset of a defined population with given characteristics e.g Age, Education levels etc. 
 
**Describe the enhancement**
For the mADX work, look into adding a dynamic selection of dates (periodStart & periodEnd) for the generation of the measureReport, for the 1st Indicator. 
1. Add a UI for doing the Report filters 
2. Add a UI for Reporting Template to be used once a measure is run and computed to generate a MeasureRerport 

**Screenshots**
**Landing page - listing of measures**
![image](https://user-images.githubusercontent.com/69383347/140267169-edf6a0c9-1a46-4dcf-810f-dd8b88222530.png)

**Filter screen**
![image](https://user-images.githubusercontent.com/69383347/140267331-f9fea035-e845-4aa8-9c74-1b119a6d36cf.png)
Date range default selected for a period — either last 30 days or last 90 days to current day. All patient is default selected.

Once individual option is selected, we show the select patient screen with search. 
**Search for a patient**
1. Add ability to search by Family name, Given name , Patient ID or Identifier
![image](https://user-images.githubusercontent.com/69383347/140267426-7668579e-3ddb-461c-9b3a-488f4f46188d.png)
![image](https://user-images.githubusercontent.com/69383347/140267553-aea144c6-b84c-4991-86a8-e8ee36259491.png)
![image](https://user-images.githubusercontent.com/69383347/140267597-0dca407a-8adc-4631-ad6d-42524885a66a.png)

when a user is selected, we show the selected check icon on the far right, and automatically take user back to the filter screen with selected patient.
![image](https://user-images.githubusercontent.com/69383347/140267709-ebe3947b-4183-4e44-9c83-0171bc476ee5.png)

**Filtered Patient**
![image](https://user-images.githubusercontent.com/69383347/140267755-08366178-7198-4c41-b832-2431c4bd5af8.png)

**Generate Report for Individual** 
![image](https://user-images.githubusercontent.com/69383347/140268066-870d7ac9-0875-449a-93a5-1b9e85cf9cd6.png)

**Generate Report for Population** 
![image](https://user-images.githubusercontent.com/69383347/140268432-22890f2b-85cc-4713-a6a5-97e35125311d.png)

**Acceptance Criteria**
- [ ] Move the functionality from patient profile to Reports module 
- [ ] Convert the JSON output to feed into the reporting UI

**NB.** The CQL Evaluation will also need to find a new UX to allow the user to also do CQL expressions, perhaps have the same but change in Filters 

_NB. Later we want to also dynamically sync and select measures that will be used to generate the rest of the 12 Indicators for the mADX project_

**Comment by mwkhan1983** [comment]
@f-odhiambo does this needs updation based on our last call? We discussed:
1. Indicator reporting whether for single patient or population should be accessible from Reports section only.
2. Get practitioner from synced details at app login - background task
3. On the selection screen 
        a. Date-picker for periodStart & periodEnd
        b. report type - patient or population
        c. select patient - if report type is patient
        d. Select Measure
        e. Compute button 
4. Get a measure report screen

**Comment by f-odhiambo** [comment]
@mwkhan1983 @kimigxfoxy will share updated mocks for this . Design team did a version 1 for the same . Will share on slack

**Comment by f-odhiambo** [comment]
> @f-odhiambo does this needs to be updated based on our last call? We discussed:
> 
> 1. Indicator reporting whether for single patient or population should be accessible from Reports section only.
> 2. Get practitioner from synced details at app login - background task
> 3. On the selection screen
>    a. Date-picker for periodStart & periodEnd
>    b. report type - patient or population
>    c. select patient - if report type is patient
>    d. Select Measure
>    e. Compute button
> 4. Get a measure report screen

@mwkhan1983 Updated the ticket

**Comment by mwkhan1983** [comment]
Thanks @f-odhiambo. One suggestion is to have radio buttons instead of checkboxes for `All` and `Individual` since only one can be selected at a time.

Secondly, is Education Level something mandatory to provide? If not, we may not have data to bifurcate based on Education level.

**Comment by f-odhiambo** [comment]
@mwkhan1983, 
1. Rasio button noted
2. On the  details for reporting ,  disaggregation is secondary and will come later once we also get feedback from client

**Comment by mwkhan1983** [comment]
`On the details for reporting , disaggregation is secondary and will come later once we also get feedback from client` In that case, do we really need separate results screen? In case of individual patient, its just a boolean (true/false) and for a population simple ratio is to be displayed. Hence, result may be displayed on the same screen after tapping Generate Report. A loader may need to be displayed while results are calculating.

**Comment by mwkhan1983** [comment]
Updated main issue with latest mocks agreed in yesterday call

**Comment by AbdulWahabMemon** [comment]
reopening, as its get close with PR for UI updates
