### ISSUE TITLE
Automate APK Release process CD

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#680]
**Is your feature request related to a problem? Please describe.**
- It is currently a manual/tedious process to generate a signed APK. 
- Only select engineers have access to the signing keys.

**Describe the solution you'd like**
- Ideally, we should have a process where we selectively trigger a workflow that generates the release APK on demand

**Describe alternatives you've considered**
- Idea is to use Github Actions /workflows to implement this. 
- The solution should implement building, signing, eventual upload of release artifacts to a Github tag

**Check list**
- [x] Gradle task to build the signed APK
- [x] Update Github workflow configuration + keystore setup
- [x] Add support for building + signing AAB files
- [x] Add support for building + signing APK files
- [x] Add support for uploading artifacts to tag

**Comment by ndegwamartin** [comment]
@f-odhiambo we are currently working with Allan on this broken down in two parts: Bundling the signed APK and Using CI to trigger the process, create a Github tag and upload it as an asset cc @pld

**Comment by f-odhiambo** [comment]
**Update Feb 25th, 2022**
Still in progress,  had been paused





[12:20](https://onaio.slack.com/archives/D01JUBVU1AN/p1645780811458889)
Rather in the back burner

**Comment by f-odhiambo** [comment]
What's the ETA for this @ndegwamartin? 
CC @pld

**Comment by ndegwamartin** [comment]
@f-odhiambo will depend on how we prioritise it(and dedicate). For now it is being worked on as an OpenSRP road map item so we can target next Monthly road map review as ETA
