### ISSUE TITLE
SubTask - Integrate cucumber for instrumentation test

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#682]
Check on the latest version v4.9.0 if we can be able to resolve the issues around compose and cucumber and allow us to write tests on the app using the Gherkin Syntax via Cucumber-Android  BDD testing

**Comment by f-odhiambo** [comment]
**Update  - NOv 15th 2021**
Kindly note this item is still on RnD. There's not much breakthrough as yet. Unless we are to implement this without Gherkin
Adding items is blocked and requires research 
CC @pld

**Comment by f-odhiambo** [comment]
Marking this as unblocked  - Support for Cucumber Jetpack compose plugging available in latest release https://github.com/cucumber/cucumber-android/releases/tag/v4.9.0

**Comment by f-odhiambo** [comment]
**Update Feb 25th, 2022**
Concluded to use Espresso without Cucumber due to faces issues

**Comment by Mstjamush** [comment]
Work on Espresso started. Had projected the initial timeline to 22nd March which was depended on QA requests. This has been recalibrated to 31st March.

However, we are facing the following blockers :

1. The build time. Application is taking too long to build making tests timeout
2. Sync is taking too long. Most actions are dependent on completion of sync process. This is taking too long making them time out
3. ApplicationID. Currently we are having the tests ignore the ApplicationID page. This is leading the app to crash on login. Engaging the team for a possible work around

Cc @FrankApiyo & @pld

**Comment by f-odhiambo** [comment]
> Work on Espresso started. Had projected the initial timeline to 22nd March which was depended on QA requests. This has been recalibrated to 31st March.
> 
> However, we are facing the following blockers :
> 
> 1. The build time. Application is taking too long to build making tests timeout
> 2. Sync is taking too long. Most actions are dependent on the completion of the sync process. This is taking too long making them time out
> 3. ApplicationID. Currently, we are having the tests ignore the ApplicationID page. This is leading the app to crash on login. Engaging the team for a possible workaround
> 
> Cc @f-odhiambo & @pld

Updated target end date on the Product Roadmap 

CC @pld

**Comment by pld** [comment]
> Work on Espresso started. Had projected the initial timeline to 22nd March which was dependent on QA requests. This has been recalibrated to 31st March.
> 
> However, we are facing the following blockers :
> 
>     1. The build time. Application is taking too long to build making tests timeout

I wonder what we are doing different here versus other place we are running tests, @ndegwamartin is this something you can take a look at?

> 
>     2. Sync is taking too long. Most actions are dependent on the completion of the sync process. This is taking too long making them time out

Are we restricting the sync to only whats needed for the app ID we give? Is this pulling data from a specific testing server or the general server? We might want a separate testing server, but we definitely want a specific testing app ID, that should make what's pulled predictable and let use control its size

> 
>     3. ApplicationID. Currently, we are having the tests ignore the ApplicationID page. This is leading the app to crash on login. Engaging the team for a possible workaround

Don't we want to submit an app ID on the app ID page?

> 
> 
> Cc @f-odhiambo & @pld

Cool, thanks, adding some questions inline above

**Comment by NaveenZehra11** [comment]
if i manually one time give the application id and initailize the login page still this error showing
![Screenshot from 2022-03-29 14-19-19](https://user-images.githubusercontent.com/90256461/160768855-ea39b15f-d023-4988-a779-f435898de373.png)
cc @Mstjamush @f-odhiambo

**Comment by pld** [comment]
Cool, yep both of those makes sense to me @ndegwamartin can you please follow-up to unblock this?

**Comment by Mstjamush** [comment]
Update for AppSettingActivity page
We managed to get a work around. This is incorporating what @ellykits and @ndegwamartin explained plus introducing a runner class.
The runner class will enable one to run test classes in an order specified in the class, thus having the first test class in the list run from the App Setting page, and the proceeding test classes initialise the Login page

Yet to be handled is the sync issue

Cc @f-odhiambo & @pld

**Comment by pld** [comment]
was this closed by? https://github.com/opensrp/fhircore/pull/1306

**Comment by f-odhiambo** [comment]
Closed via https://github.com/opensrp/fhircore/pull/1306

**Comment by f-odhiambo** [comment]
I don't think this is related @pld, let me reach out to @Mstjamush , this was brought up when we were doing Notice E0 for Gherking test intergration

**Comment by f-odhiambo** [comment]
**Update** 
We will only do Espresso instrumented tests, And this will run on CI

**Comment by pld** [comment]
Sounds great! Can you merge something into main that test pre-sync parts of the app?
