### ISSUE TITLE
Create a build config to generate either a JnJ Covax demo app workflow or WHO Covax demo app workflow 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#686]
Add Config to choose between JnJ Covax app and WHO Demo app
**If the JnJ Covax app**
- [ ]  Remove Barcode/HCID scanning in Homescreen
- [ ]  Registration Questionnaire should only capture Patient Family name, Given name, DOB, Gender. City, Country, is Active, Risk flagging questions and related person fields
- [ ]  Show Risk flag in the patient list and patient profile
- [ ]  Maintain Report adverse event in the patient profile
- [ ]  Remove Show QR Code button in the patient profile

**If the WHO Covax app**
- [ ]  Registration Questionnaire should only capture Barcode/HCID, Patient Family name, Given name, DOB, Gender. City, Country, is Active
- [ ]  Remove Risk flag in the patient list and patient profile
- [ ]  Remove Report adverse event in the patient profile
- [ ]  Maintain Show QR Code button in the patient profile

**Comment by pld** [comment]
Cool, agree this is directly related IF we achieve this configurability dynamically without a build config.

Otherwise, it's conceptually related, because we're here talking about multi-APK config
