### ISSUE TITLE
[Roadmap] FHIR Core  - CHW/ANC Features

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#704]
**Legend** 

:heavy_check_mark: -- Completed
:construction: -- Work in Progress
:x: -- Not Done
:books: -- Research & development
:no_entry: -- Blocked

---
**Features to implement**
1. User management
    - Authenticate users - :heavy_check_mark:
        - Forgot password - :x: -- Not Done
        - Log in via PIN - :x: -- Not Done

2. Sync 
    - Sync Data from HAPI - :heavy_check_mark:
        - Sync Registration Questionnaire for Family - :heavy_check_mark:
        - Sync Family - :heavy_check_mark:
        - Sync Family memebers  - :heavy_check_mark:
        - Sync ANC Clients  - :heavy_check_mark:

3.  Patient Registration 
    - Add Head of Household - :heavy_check_mark:
    - Add Family Member - :heavy_check_mark:
    - Add ANC Client - :heavy_check_mark:
4. Patient List 
    - View Family Register - :heavy_check_mark:
    - View ANC Register - :heavy_check_mark:
5. Patient Profile 
    -  View Family Member Profile :construction: -- Work in Progress
    - View ANC Member Profile :construction: -- Work in Progress
6. Multi-language support
    - Multilanguage support for Questionnaire  :x: -- Not Done
   - Multilanguage support for Questionnaire items  - :x: -- Not Done  Language switching does not update on option/radio buttons :books: -- Research & development :no_entry: -- Blocked 
7. Task Management
    - Careplan Generation - :books: -- Research & development :construction: -- Work in Progress on Android FHIR SDK side
        - Tasks for individuals - ::books: -- Research & development
        - Tasks for Household - :books: -- Research & development

**Current priorities**
- Make the app configurable and Quest Based  - :books: -- Research & development & :construction: -- Work in Progress

ANC Mocks  - [Link](https://www.figma.com/file/QZ4cdpgBNy86XTOUnrnLap/COVID19-FHIR-Future-Design-System?node-id=1063%3A14329)

**Comment by dubdabasoduba** [comment]
@f-odhiambo Can we port over the MLS pieces on QUEST into this?

**Comment by f-odhiambo** [comment]
> @f-odhiambo Can we port over the MLS pieces on QUEST into this?

Yes but will need to be priorozed and perhaps have an engineer do the integration/implemention
