### ISSUE TITLE
Bug - Username and Password Validation and removal of spacing option or new line while entering the credentials to app 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#712]
**Describe the bug**
As a user as I enter the username and password field, we do not trim the spaces before we try to evaluate the creds. i.e if you write a `user` as a valid username,  then add a space the auth will block it

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  Login in screen 
2. Type in a valid username and/or password 
3. Add a space in either username of password files, enter a new line in either field  
4. See an error

**Expected behaviour**
- [ ] Validate username name and password 
- [ ] Trim spaces in username input filed 
- [ ] Disable entering of space in username fields to move to next line 

**Screenshots**
<img src="https://user-images.githubusercontent.com/4540684/140077381-c3f055bd-4ceb-4ee9-8ac3-29de885dfc0d.png" width="200" height="400" />

**Smartphone (please complete the following information):**
 - Emulator or Physical device

**Additional context**
N/A

**Comment by pld** [comment]
I think this is expected behavior, spaces are valid characters in passwords, sometimes in usernames too

**Comment by pld** [comment]
I think a "show password" option might be reasonable, that's common on login forms where you can toggle changing from the text you typed being hidden to shown

**Comment by ndegwamartin** [comment]
One can toggle _Show password_ by tapping the icon to the far right of the password text widget

**Comment by ndegwamartin** [comment]
> I think a "show password" option might be reasonable, that's common on login forms where you can toggle changing from the text you typed being hidden to shown

@pld my patch trims the spaces (on both ends only but not within). We could update that to allow the spaces though I think its uncommon e.g. These passwords are different `"password1"` and `"password1 "`

Let me know and we can revert this

**Comment by ndegwamartin** [comment]
We should probably allow all types but it is also a trade off with the ease of use (and troubleshooting) for our target audience

**Comment by ndegwamartin** [comment]
We should probably allow all types of characters but it is also a trade off with the ease of use (and troubleshooting) for our target audience

**Comment by pld** [comment]
What do most apps do? Space trimming isn't something I've noticed other apps doing for login fields

**Comment by ndegwamartin** [comment]
I think it depends on the backend's password policy, for instance in the old platform we didn't allow any whitespaces and required that the usernames were in lowercase. We therefore had this enforced.

**Comment by pld** [comment]
OK cool, I feel like I’m just bike shedding at this point, let’s close this issue, keep it as what you implemented, we can revise if/when it ever comes up :)
