### ISSUE TITLE
Quest  - Implement simple responses sorting

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#738]
**Name of feature to enhance**
Sorting of questionnaire responses

**Description of feature**

**Describe the enhancement**
The current responses list looks jumbled 

![Screenshot from 2021-11-10 15-27-02](https://user-images.githubusercontent.com/31766075/141113332-e9a1650a-d9d3-45d8-9a2c-8c84191c2721.png)
![Screenshot from 2021-11-10 15-33-06](https://user-images.githubusercontent.com/31766075/141113856-fb6e7311-6f89-4e9b-9aa5-61877ce6a791.png)

**Comment by pld** [comment]
Sort by submission date w/newest first makes sense for now
