### ISSUE TITLE
Document findings on MLKits Libs on Android that  support reading seven-segment displays

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#74]
- [x] What works 
- [x] What does not work
- [ ] Final conlusion

**Comment by pld** [comment]
Can you clarify what type of support this is referring to?

**Comment by f-odhiambo** [comment]
Link to the updated [documentation](https://docs.google.com/document/d/1JwAfdeFDncYXbymO-hHktWZSOnMqYSHwmDktxFVV5Dc/edit)

**Comment by vincent-karuri** [comment]
More specific issues have superseded this. Findings specific to MLKit are documented [here](https://docs.google.com/document/d/1JwAfdeFDncYXbymO-hHktWZSOnMqYSHwmDktxFVV5Dc/edit).
