### ISSUE TITLE
Confirm/Test Quest/G6PD previous resources deletion

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#748]
Related to #667

- [ ] Check if `QuestionnaireResponse.contained` resources have the IDs after saving is done. 

### Assumptions 

1. Android SDK FHIR Engine updates the Resource.id after saving. Resources generated by definition-based extraction do not have `Resource.id` assigned. This can also happen for some resources generated through StructureMap-based extraction
1. The Bundle and Resources value are passed by reference hence FHIR Engine should update the `Resource.id` before the QuestionnaireResponse is saved

This needs to be tested once we have multiple extractable-questionnaires available  on Quest using the various extraction methods

**Comment by pld** [comment]
Very interesting, to make sure I understand (and yea I'm basically just rewriting what you wrote :)), does this mean when we use resource extraction, the newly created resources may not have an ID assigned?

Then in that case, they would be assigned IDs on sync to server? This could cause problems if we're doing offline stuff, or what to link other things to those extraction created resources.

I think we need a way to enforce (verify?) that extraction created (or even simply all saved) resources had IDs assigned

**Comment by ekigamba** [comment]
Yes, the newly created resources may not have an ID assigned. I can now confirm that Android FHIR SDK does not assign IDs but due to the **(ResourceType, ResourceId)** primary key, resource saving will fail fast due to overwriting of resources after the first resource with an empty ID.

Yes, we need to enforce that all resources have IDs assigned. I will update the `DefaultRepository.save` https://github.com/opensrp/fhircore/blob/a6eb4fd8bd717338ab351ebc9ee0a26d7914ff4c/android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt#L55 on **FHIR Core** to enforce this. We will still have to confirm that some other uses of `fhirEngine.save` are changed to use the `DefaultRepository.save` method instead

**Comment by pld** [comment]
Cool thanks sounds good, @jingtang10 not sure if you saw this, probably good to know if you didn't already
