### ISSUE TITLE
Identify the ML Kit libraries that support seven segment display and also work offline

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#75]
- [x] Google ML Kit https://developers.google.com/ml-kit/vision/text-recognition/android
- [x] Quick start app https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart
- [x] Anyline App app https://anyline.com/

**Comment by vincent-karuri** [comment]
@f-odhiambo can we close this?
