### ISSUE TITLE
[eCBIS] Add a side navigation to the ANC FHIR variant

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#750]
**Name of feature to enhance**
- Currently, the chw ANC app on FHIR has a bottom navigation
- We would like to add the side navigation to match the eCBIS project requirements

**Description of feature**
- [x] Remove/hide the bottom navigation
- [x] Add a side navigation drawer that looks like the image described below. 
- [x] Hook up all the navigation functionalities to the side navigation drawer

![menu](https://user-images.githubusercontent.com/4817531/141794362-27c83e2b-72fb-4ccb-b16a-600dce504525.png)

NB:- Do not delete the bottom navigation implementation.

**Comment by dubdabasoduba** [comment]
> Can we do this in a configuration based way so whether the drawer shows, and what's in it, is defined through a resource linked from the app's Composition resource? Then we can put this in engine and pull it into Quest later on

@pld Yes, that's the idea.

**Comment by RaaziaTarique** [comment]
@dubdabasoduba I need icons for this UI.

**Comment by dubdabasoduba** [comment]
![image](https://user-images.githubusercontent.com/4817531/143466820-556cb5f8-06ee-4a7d-a257-a7417902b409.png)
![image](https://user-images.githubusercontent.com/4817531/143466895-531132ab-c32f-4dfd-b735-dad4e88098a8.png)
![image](https://user-images.githubusercontent.com/4817531/143466942-48a5bd09-294d-4630-b650-409992df6ea3.png)
![image](https://user-images.githubusercontent.com/4817531/143466979-592b32fd-e448-427f-9ae1-351d3de8fa98.png)
