### ISSUE TITLE
Increase code coverage to >=80% on Quest 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#752]
**Describe the Issue**
- [x] We need to add code coverage reporting for the quest module codebase. The current ranking is at ~52.93% and Quest module 65.51% https://app.codecov.io/gh/opensrp/fhircore 
- [x] Fix failing test to be able to add/improve coverage percentage 
- [ ] Fix ignored tests 
- [x] Go through the individual tests and in some cases refactor the code.
- [x] Write more tests on the Quest module to increase its code coverage

**Comment by maimoonak** [comment]
Quest has 65% coverage at the moment
![Screenshot from 2021-11-16 14-18-27](https://user-images.githubusercontent.com/4829880/141957521-1aae7c63-d7de-4caf-9b9f-30773d336fa3.png)

**Comment by maimoonak** [comment]
As per discussion with Raazia I would be working on ui.details for this ticket

**Comment by f-odhiambo** [comment]
> As per discussion with Raazia I would be working on ui.details for this ticket

Peter closed @RaaziaTarique ticket and requested to use single ticket
