### ISSUE TITLE
Increase code coverage to >=80% on Quest 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#753]
**Describe the Issue**
- [ ] We need to add code coverage reporting for the quest module codebase. The current ranking is at ~52.93% and Quest module 65.51% https://app.codecov.io/gh/opensrp/fhircore 
- [ ] Fix failing test to be able to add/improve coverage percentage 
- [ ] Fix ignored tests 
- [ ] Go through the individual tests and in some cases refactor the code.
- [ ] Write more tests on the Quest module to increase its code coverage

**Comment by pld** [comment]
this is a duplicate, https://github.com/opensrp/fhircore/issues/752
