### ISSUE TITLE
[eCBIS] Update the login page

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#757]
**Name of feature to enhance**
- Currently, we have the login page as the default login page with FHIR core logos. 
- We need to update this page to have the eCBIS branding

**Description of feature**
- [x] Update the login logo to use the eCBIS logos
- [x] Update the app naming to `eCBIS`

<img width="360" alt="returning user" src="https://user-images.githubusercontent.com/4817531/142266249-a973361f-677c-47a9-ab8d-a77a93086fab.png">

**Comment by pld** [comment]
are we going to use the app config to have this loaded from a fhir-based remote config? or is there another strategy?

**Comment by ellykits** [comment]
> are we going to use the app config to have this loaded from a fhir-based remote config? or is there another strategy?

We'll use the application configurations.

**Comment by AnnieMungai** [comment]
@dubdabasoduba The logo on the app can be found [here](https://upload.wikimedia.org/wikipedia/commons/6/64/Coat_of_arms_of_Liberia.svg) - linked to [this issue](https://github.com/opensrp/opensrp-client-chw/issues/1092) with details of the app login page that currently exists. The idea is to keep this the same - maybe with a change of name? @rowo
