### ISSUE TITLE
Hold a briefing session with UW ML dept on ways to go about reading seven-segment-display

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#76]
Possible solution
1. Launch the IPE and do some pre-processing 
2. Take the G6PD image Create some segments where the reading will be collected 
3. Join the spaces on seven-segment digits Get the whole number so no space within a digit
4. Run the new image through ML Kit Do post-processing to get the different values 
5. Send to the RIM module for interpretation i.e (Result Interpretation Module)

**Comment by vincent-karuri** [comment]
Findings on this are documented [here](https://docs.google.com/document/d/1JwAfdeFDncYXbymO-hHktWZSOnMqYSHwmDktxFVV5Dc/edit).
