### ISSUE TITLE
[eCBIS] Remove the family

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#766]
**Name of feature to enhance**
- We would like to have the ability to delete a family. 
- A family is currently represented by the patient resources of the head of household. 

**Description of feature**
- [x] Add a `Remove family` button on the family profile.
- [x] On clicking the button, launch a confirmation dialog to confirm the delete actions. 
- [x] If yes is clicked, then update the head of household patient resource `active` attribute with a `false`

**Comment by pld** [comment]
would you also need to remove the links btwn the HH and family members?

**Comment by dubdabasoduba** [comment]
> would you also need to remove the links between the HH and family members?

@pld We might want to keep the links unless we see a scenario of moving the family members to a new family. If this is the case then I would suggest just using the remove family member functionality. 

@pld @ndegwamartin I think we can remove the family tag and leave the HHH as active.  This means we can see the patient in other registers if need be. This then might introduce the necessity to delink the other family members as @pld was suggesting.

**Comment by ndegwamartin** [comment]
@dubdabasoduba ok, i will refactor to use this approach
