### ISSUE TITLE
Add the Composition & Parameters resource to be exempted from authentication 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#770]
**Description of feature**
- [ ] Update the authentication interceptor to exempt the composition resource from authentication. 

**Acceptance Criteria**
- [ ] The composition resource API should be able to accept requests without authentication.

**Comment by pld** [comment]
Is it always expemted, or sometimes?

I could imagine a use-case where the app definition files themselves are confidential

**Comment by dubdabasoduba** [comment]
@rehammuzzamil can we update this functionality to only exclude GET requests?

**Comment by dubdabasoduba** [comment]
> Is it always exempted, or sometimes?
> 
> I could imagine a use-case where the app definition files themselves are confidential

This means in such cases the login screen would have to come before the configuration screen on the app.  I don't think we have thought about this use case from a UX and configuration perspective. 

Questions
- How do we tell the APK which use case to configure for? i.e show the configuration page first or the login page first.

**Comment by maimoonak** [comment]
> Is it always expemted, or sometimes?
> 
> I could imagine a use-case where the app definition files themselves are confidential

@dubdabasoduba thats true. Composition resource contains client information as well. For e.g. [IPS](http://hl7.org/fhir/uv/ips/StructureDefinition-Composition-uv-ips.html) (International Patient Summary) is a Composition of highly sensitive Patient data. The least should be that we do not expose Compositions which have 'subject'. The rest we can assess and discuss. An alternate could be that we expose Composition with specific pattern only

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil can we update this functionality to only exclude GET requests?

Yes @dubdabasoduba, we can restrict to only exclude GET endpoint.

**Comment by pld** [comment]
> > Is it always exempted, or sometimes?
> > I could imagine a use-case where the app definition files themselves are confidential
> 
> This means in such cases the login screen would have to come before the configuration screen on the app. I don't think we have thought about this use case from a UX and configuration perspective.
> 
> Questions
> 
>     * How do we tell the APK which use case to configure for? i.e show the configuration page first or the login page first.



> > Is it always expemted, or sometimes?
> > I could imagine a use-case where the app definition files themselves are confidential
> 
> @dubdabasoduba thats true. Composition resource contains client information as well. For e.g. [IPS](http://hl7.org/fhir/uv/ips/StructureDefinition-Composition-uv-ips.html) (International Patient Summary) is a Composition of highly sensitive Patient data. The least should be that we do not expose Compositions which have 'subject'. The rest we can assess and discuss. An alternate could be that we expose Composition with specific pattern only

Agreed, this approach makes sense to me @dubdabasoduba

**Comment by dubdabasoduba** [comment]
> > @rehammuzzamil can we update this functionality to only exclude GET requests?
> 
> Yes @dubdabasoduba, we can restrict to only exclude GET endpoint.

Awesome! let's implement this too.

**Comment by dubdabasoduba** [comment]
> > Is it always expemted, or sometimes?
> > I could imagine a use-case where the app definition files themselves are confidential
> 
> @dubdabasoduba thats true. Composition resource contains client information as well. For e.g. [IPS](http://hl7.org/fhir/uv/ips/StructureDefinition-Composition-uv-ips.html) (International Patient Summary) is a Composition of highly sensitive Patient data. The least should be that we do not expose Compositions which have 'subject'. The rest we can assess and discuss. An alternate could be that we expose Composition with specific pattern only

@rehammuzzamil please do some R&D on how much work this filtering would take.

**Comment by rehammuzzamil** [comment]
> > > Is it always expemted, or sometimes?
> > > I could imagine a use-case where the app definition files themselves are confidential
> > 
> > 
> > @dubdabasoduba thats true. Composition resource contains client information as well. For e.g. [IPS](http://hl7.org/fhir/uv/ips/StructureDefinition-Composition-uv-ips.html) (International Patient Summary) is a Composition of highly sensitive Patient data. The least should be that we do not expose Compositions which have 'subject'. The rest we can assess and discuss. An alternate could be that we expose Composition with specific pattern only
> 
> @rehammuzzamil please do some R&D on how much work this filtering would take.

@dubdabasoduba  @maimoonak I believe we need to add a filter to get only the specific Composition resource. Maybe we can add a particular subject value to the Composition Resource of configurability to access it without logging in. 

Based on high-level findings, we can do filtering at the resource level to allow only GET URL along with that request param value.

**Comment by dubdabasoduba** [comment]
> > > > Is it always expemted, or sometimes?
> > > > I could imagine a use-case where the app definition files themselves are confidential
> > > 
> > > 
> > > @dubdabasoduba thats true. Composition resource contains client information as well. For e.g. [IPS](http://hl7.org/fhir/uv/ips/StructureDefinition-Composition-uv-ips.html) (International Patient Summary) is a Composition of highly sensitive Patient data. The least should be that we do not expose Compositions which have 'subject'. The rest we can assess and discuss. An alternate could be that we expose Composition with specific pattern only
> > 
> > 
> > @rehammuzzamil please do some R&D on how much work this filtering would take.
> 
> @dubdabasoduba @maimoonak I believe we need to add a filter to get only the specific Composition resource. Maybe we can add a particular subject value to the Composition Resource of configurability to access it without logging in.
> 
> Based on high-level findings, we can do filtering at the resource level to allow only GET URL along with that request param value.

@rehammuzzamil Does this mean if I had something like `"subject":"configurability"` then we filter and get only the compositions with this as the subject?

**Comment by rehammuzzamil** [comment]
> > > > > Is it always expemted, or sometimes?
> > > > > I could imagine a use-case where the app definition files themselves are confidential
> > > > 
> > > > 
> > > > @dubdabasoduba thats true. Composition resource contains client information as well. For e.g. [IPS](http://hl7.org/fhir/uv/ips/StructureDefinition-Composition-uv-ips.html) (International Patient Summary) is a Composition of highly sensitive Patient data. The least should be that we do not expose Compositions which have 'subject'. The rest we can assess and discuss. An alternate could be that we expose Composition with specific pattern only
> > > 
> > > 
> > > @rehammuzzamil please do some R&D on how much work this filtering would take.
> > 
> > 
> > @dubdabasoduba @maimoonak I believe we need to add a filter to get only the specific Composition resource. Maybe we can add a particular subject value to the Composition Resource of configurability to access it without logging in.
> > Based on high-level findings, we can do filtering at the resource level to allow only GET URL along with that request param value.
> 
> @rehammuzzamil Does this mean if I had something like `"subject":"configurability"` then we filter and get only the compositions with this as the subject?

Yes, this is my understanding.

**Comment by dubdabasoduba** [comment]
@rehammuzzamil I think we can start with implementing the GET-only approach then we can discuss the filtering. Please feel free to work on this.

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil I think we can start with implementing the GET-only approach then we can discuss the filtering. Please feel free to work on this.

Okay, noted @dubdabasoduba  . Thanks!

**Comment by dubdabasoduba** [comment]
@rehammuzzamil Based on our discussion earlier we need to also exempt the Parameters. This will hold some configs required before login too.

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil Based on our discussion earlier we need to also exempt the Parameters. This will hold some configs required before login too.

Sure, will start work on this piece.

**Comment by pld** [comment]
this looks closed based on the merged prs
