### ISSUE TITLE
Quest v0.2 / G6PD : View G6PD Status on the Patient List view 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#777]
**Is your feature request related to a problem? Please describe.**
As a G6PD app user, I would like to view the currently enrolled patients on the G6PD Test app 

**Describe the solution you'd like**
Post sync, I should be able to see at a glance from the Patient list view
1. Family name 
2. Given name 
3. Age  - in Year, Month or Weeks, Day format 
4. Gender - abbreviated
5. Status

**Describe alternatives you've considered**
This should be done in a configurable way using compose 

**Additional context**

1. Screenshot of the mock 
<img width="291" alt="Screen Shot 2021-11-22 at 8 54 22 AM" src="https://user-images.githubusercontent.com/4540684/142807971-1bc81650-bbd2-460c-a907-321080c8dc27.png">

**Acceptance Criteria** 
- [ ] Paginated List view 
- [ ] Paginated list view on filters search results 
- [ ] Patient Search 
- [ ] Add client for registration button 
- [ ] Menu Item to go to the menu items 
- [ ] Setting page to view sync, language switcher and log out page  

**Minor enhancement UX**
1. We can use Red, Amber and Green for the status Deficient, Intermediate and Normal

**Comment by pld** [comment]
how would this be controlled through configuration?

clearly, this wouldn't be applicable in all Quest applications.

do we have an existing configuration for the patient list view? can we add a key where the value describes additional data to show in the list view?

**Comment by f-odhiambo** [comment]
@pld 
1. This can be done by adding a configuration to set the list level item for the status label/ indicator 
2. This will be done in a new config away from the register config and can be done for also the rest of the applications

**Comment by owais-vd** [comment]
> @pld
> 
> 1. This can be done by adding a configuration to set the list level item for the status label/ indicator
> 2. The setting will be added to a new config away from the register config and can be done for also the rest of the applications
> 
> CC @ellykits

@ellykits any thoughts about the above points?

**Comment by ellykits** [comment]
@owais-vd Here are my thoughts on the implementation:

The colored status should only be displayed for g6pd apps just like risk flag for EIR apps. This composable view is available in the register list rows which is separate from the LazyColumn compose view hence the need for new configuration that will be supplied to the composable function used to render register list item rows. Since this is specific to quest, the implementation will reside in Quest app.

**Implementation**
1. Implement a data class in quest app that implements [Configuration](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/Configuration.kt) you can name it `PatientRegisterRowViewConfiguration` 
2. The class should have a property `showG6pdStatus` default false
3. Create a new file`patient_register_row_view_configuration` in `asset/configurations/view`
4. Add new `enum` constant `PATIENT_REGISTER_ROW` to  [QuestConfigClassification](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/util/QuestConfigClassification.kt)
5. Retrieve the above config from `ConfigurationRegistry` using `PATIENT_REGISTER_ROW` constant
6. Provide to and use the config in [PatientListItem](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/register/components/PatientListItem.kt)

>**NB**: EIR risk flag can use of this refactor too. Currently relying on data to hide/show the flag i.e. the flag will only show when captured.

**Comment by ellykits** [comment]
We can discuss how to provide the config to `PatientListItem`

**Comment by ellykits** [comment]
Here is how you can provide the configuration to PatientListItem via the `PatientRegisterList` composable:

1. Inject the `ConfigurationRegistry` in the [PatientRegisterFragment](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/register/PatientRegisterFragment.kt)
2. Retrieve the config to a class property in the fragment then refactor `PatientRegisterList` composable function's signature by adding a new parameter for the config. Do the same for the composable function used for rendering the view (`PatientRow`).

**Comment by owais-vd** [comment]
Thanks, @ellykits for the detailed comments. I'll follow this. Awesome.

**Comment by pld** [comment]
The main goal here is to do this in a manner that does not add anything g6pd specific to the code but instead pushed that all into FHIR configuration files that are loaded into the app, so this approach, specifically step (2) will not work.

How is the g6pd status being stored? What we'd like to do is, is load a `PatientRegisterConfiguration` file, and have that include a has something like an `additionalRows` map list key and the values are a list of maps, in this case the values would have one entry with two keys `name: "G6PD status"` and a `value` of something describing how to load from the patient record what to show there

**Comment by owais-vd** [comment]
@pld based on your comment i have removed the `g6pd` specific status and tried to make it more generic by using the configuration filters now, getting the G6PD Status from the `Condition` resource by adding the `patient id`, and `g6pd code` constraints. Here is the current patient row configuration json.

```
[
  {
    "appId": "quest",
    "classification": "patient_register_row",
    "filters": []
  },
  {
    "appId": "g6pd",
    "classification": "patient_register_row",
    "filters": [
      {
        "resourceType": "CONDITION",
        "key": "code",
        "valueType": "CODEABLECONCEPT",
        "color": "#000000",
        "valuePrefix": " G6PD Status - ",
        "valueCoding": {
          "system": "http://snomed.info/sct",
          "code": "260372006"
        },
        "dynamicColors": [
          {
            "valueEqual": "Deficient",
            "useColor": "#FF0000"
          },
          {
            "valueEqual": "Intermediate",
            "useColor": "#FFA500"
          },
          {
            "valueEqual": "Normal",
            "useColor": "#00a000"
          }
        ]
      }
    ]
  }
]
```

**Comment by pld** [comment]
that looks great!

**Comment by owais-vd** [comment]
here is the updated configuration that is currently being used to display G6PD statuses.
```
{
    "appId": "g6pd",
    "classification": "patient_register_row",
    "filters": [
      {
        "resourceType": "CONDITION",
        "key": "category",
        "label": "Optional Label",
        "valueType": "CODEABLECONCEPT",
        "valuePrefix": " G6PD Status - ",
        "valueCoding": {
          "system": "http://snomed.info/sct",
          "code": "9024005"
        },
        "properties": {
          "label": {
            "color": "#000000",
            "textSize": 20
          },
          "value": {
            "color": "#000000",
            "textSize": 20
          }
        },
        "dynamicColors": [
          {
            "valueEqual": "Deficient",
            "useColor": "#FF0000"
          },
          {
            "valueEqual": "Intermediate",
            "useColor": "#FFA500"
          },
          {
            "valueEqual": "Normal",
            "useColor": "#00a000"
          }
        ]
      }
    ]
  }
```
