### ISSUE TITLE
Quest v0.2 / G6PD : G6PD Administer Test page 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#778]
**Is your feature request related to a problem? Please describe.**
As a G6PD app user, I would like to initiate a G6PD test questionnaire to be able to check if a person is having Normal, Deficient or Intermediate levels of the G6PD enzyme 

**Describe the solution you'd like**
Implementation of the mock design to be able to allow the user to view information on test results or initiate a new test 

**Describe alternatives you've considered**
This should be done in a configurable way based on the Quest approach 

**Additional context**

1. We should use the publisher field  to filter only G6PD test results 

**Screenshot of the mock** 
<img width="296" alt="Screen Shot 2021-11-22 at 8 55 04 AM" src="https://user-images.githubusercontent.com/4540684/142808115-b4b23189-243c-4cb1-9556-8c07abb758a6.png">

**Acceptance Criteria** 
- [ ] Ability to initiate G6PD test 
- [ ] View previous test i.e. Status, Date, G6PD reading, Hemoglobin reading

**Comment by pld** [comment]
Aren't the acceptance criteria complete?

What is the new work for this issue, is this about configuring what additional information is shown in these views and configuring it?

If so, can you please suggest a configuration format that aligns with how configurations are currently managed

**Comment by f-odhiambo** [comment]
@pld This view can be made configurable. For this, we may need a profile config  - 'Quest Profile view' config and then use it to swap out the items in the list view as defined in the mock. Add a config property to swap the UI components

CC @ellykits

**Comment by shoaibmushtaq25** [comment]
We have following 3 categories of forms for Quest,
1. G6PD Test Result form
2. MSF Questionnaire form
3. G6PD **Photo** Test Result form

so  @mwkhan1983 do we have all three category of forms included in the scope of G6PD as well or do we have only one category (G6PD Test Result form) out of three mentioned above?

**Comment by mwkhan1983** [comment]
I guess only difference between G6PD Test Result form and G6PD photo Test result form is the ability to upload a photo. For G6PD we require a questionnaire where photo can be captured and uploaded along with other questions.  MSF Questionnaire form has nothing to do with G6PD.

**Comment by maimoonak** [comment]
@shoaibmushtaq25 @owais-vd plz see generated data details in issue https://github.com/opensrp/fhircore/issues/781

**Comment by maimoonak** [comment]
@owais-vd plz confirm that the hardcoded TODO for G6PD is handled in PR for this issue.. https://github.com/opensrp/fhircore/pull/936#discussion_r782419120

**Comment by shoaibmushtaq25** [comment]
Here are new configurations of `patient_details_view_configurations.json` that I am going to use to handle the G6PD/Quest use case in more generic way, @maimoonak @owais-vd @pld 

`[
  {
    "appId": "quest",
    "classification": "patient_details_view",
    "contentTitle": "Responses",
    "rows": []
  },
  {
    "appId": "g6pd",
    "classification": "patient_details_view",
    "valuePrefix": "G6PD ",
    "contentTitle": "TEST RESULTS",
    "rows": [
      {
        "filters": [
          {
            "resourceType": "CONDITION",
            "key": "category",
            "valueType": "CODEABLECONCEPT",
            "valueCoding": {
              "system": "http://snomed.info/sct",
              "code": "9024005"
            }
          }
        ]
      },
      {
        "filters": [
          {
            "resourceType": "OBSERVATION",
            "key": "code",
            "valueType": "CODEABLECONCEPT",
            "label": "G6PD: ",
            "valueCoding": {
              "system": "http://snomed.info/sct",
              "code": "86859003"
            },
            "properties": {
              "label": {
                "color": "#74787A",
                "textSize": 16
              },
              "value": {
                "color": "#74787A",
                "textSize": 16
              }
            }
          },
          {
            "resourceType": "OBSERVATION",
            "key": "code",
            "valueType": "CODEABLECONCEPT",
            "label": " - Hb: ",
            "valueCoding": {
              "system": "http://snomed.info/sct",
              "code": "259695003"
            },
            "properties": {
              "label": {
                "color": "#74787A",
                "textSize": 16
              },
              "value": {
                "color": "#74787A",
                "textSize": 16
              }
            }
          }
        ]
      }
    ]
  }
]`

**Comment by f-odhiambo** [comment]
I think let's have a basic start of this implemention be merged and tested and then any additions can come as enhancements. Final decision to be communicated before end of week
