### ISSUE TITLE
Quest v0.2 / G6PD : View Test Results Page

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#779]
**Is your feature request related to a problem? Please describe.**
As a G6PD app user, I would like to view the test results page of a patient post-evaluation based on a CQL expression 

**Describe the solution you'd like**
Implementation of the mock design to be able to allow the user to view  the Test results 

**Describe alternatives you've considered**
This should be done in a configurable way based on the Quest approach 

**Additional context**

<img width="299" alt="Screen Shot 2021-11-22 at 8 57 46 AM" src="https://user-images.githubusercontent.com/4540684/142808369-fa9172c3-c3c3-4e4b-8650-86b6867622e2.png">

**Acceptance Criteria** 
- [x] View G6PD and Hemoglobin level 
- [x] View G6PD status
- [ ] View recommended regimen 
- [x] On press done , go to [View Test Results Page ](https://github.com/opensrp/fhircore/issues/779)

**Minor enhancement UX** 
1. We can use Red, Amber and Green for the status Deficient, Intermediate and Normal 

Prerequisite ticket
- [ ] #778

**Comment by pld** [comment]
Please describe how the configuration will be written for this so we can implement it with Quest

**Comment by f-odhiambo** [comment]
Good question. On thinking through this, I think we should not even have a new screen just to show the results. We could do the CQL computation and then move to the user profile view with test results. See mock below. Will consult design team 

NB. mock not approved 

<img width="799" alt="Screen Shot 2021-11-24 at 3 34 17 PM" src="https://user-images.githubusercontent.com/4540684/143240612-bb6a1248-a080-4b7f-9c77-5dfcf2cc588b.png">





CC @rowo @HenryRae

**Comment by maimoonak** [comment]
see generated data details in issue https://github.com/opensrp/fhircore/issues/781

**Comment by HenryRae** [comment]
We made some updates to access test results from the profile page i.e replaced header copy with the "status and date" e.g Deficient (5-Oct-2021) see image below
<img width="304" alt="Screenshot 2022-01-05 at 13 01 59" src="https://user-images.githubusercontent.com/31955469/148198974-4899bc14-e152-43b7-8b0c-92fe8c655c81.png">


Access results after testing has not changed, thus we will keep the header copy as it is currently.
cc: @f-odhiambo @rowo

**Comment by f-odhiambo** [comment]
I think we can raise a new PR to address this to have two flows 
1. If you Administer a new test, upon completion you view the results page with  the header label  configured as   'Test Results'
<img src="https://user-images.githubusercontent.com/4540684/148200193-491948b3-9790-4e67-841a-3914b23260b8.pn" width="200" height="400" />


2. If you are viewing previous test results from the patient profile,  then the header label is configured to show Status & Date 
<img src="https://user-images.githubusercontent.com/4540684/148200243-fbd11664-820f-4422-95e7-1950298655e9.png" width="200" height="400" />




CC @maimoonak

**Comment by maimoonak** [comment]
- Medication request not added (Need clarification on cql part, once we add it on cql just need to add configs to details page)
- The dynamic header needs discussion and other issue to track as it may compromise configurability. 
- Current implementation is completely dynamic

<img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/148537718-64b72f4c-6e7f-4381-9468-ff779da29b73.jpg"/> <img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/148537725-770b207e-f197-417b-8846-40040ad65781.jpg"/>
