### ISSUE TITLE
Quest v0.2 / G6PD : Add Codable concept fields  to the G6PD registration  questionnaire 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#789]
**Describe the issue to be researched**
We need to figure out how to add the following fields during registration to save to the [patient](http://www.hl7.org/fhir/patient.html) FHIR resource 

- [x] 1. Marital status
- [x] 2. Ethnicity
- [x] 3. Occupation

**Describe the goal of the research**
Figure out how we can capture and save these to the patient resource are extensions by reviewing the list of supported Resource Patient - [Extensions & Profiles](http://www.hl7.org/fhir/patient-profiles.html)

NB. Not sure how they will be editable but will figure out. Also not sure of SDK support

**Comment by f-odhiambo** [comment]
Update Nov 24th 2021 - Marital staus is available in the R4 FHIR spec for patient  - http://www.hl7.org/fhir/patient-definitions.html#Patient.maritalStatus

**Comment by maimoonak** [comment]
Ethinicity in other IG:
https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-ethnicity.html
https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-race.html
_https://fhir.hl7.org.uk/STU3/CodeSystem/CareConnect-EthnicCategory-1 for STU3_

**Comment by maimoonak** [comment]
Occupation in other IG:
https://build.fhir.org/ig/who-int/anc-cds/StructureDefinition-occupation.html
https://build.fhir.org/ig/HL7NZ/northernRegion/StructureDefinition-current-occupation.html
http://www.hl7.it/fhir/base/2020-06/StructureDefinition-patient-occupation-it.html
_Observaion -> http://hl7.org/fhir/us/odh/StructureDefinition-odh-PastOrPresentJob.html_

Currently looking into ways to create own extension for these

**Comment by maimoonak** [comment]
SDK has an issue with the way it works for fhir-path

```
private fun Class<*>.getFieldOrNull(name: String): Field? {
  return try {
    getDeclaredField(name)
  } catch (ex: NoSuchFieldException) {
    return null
  }
}
```

This is a bug in SDK and can be fixed very easily... Instead of picking declared-field we should also pick fields inherited. Patient or any other resource extends DomainResource and the Resource. It means that we can not set inherited fields like meta.tag/extension etc using fhir-path. We can also do a quick-fix into our own code and then wait for SDK fix as well. Fix to this would help in adding extension without any custom code and remove some code from ANC as well

**Comment by pld** [comment]
> SDK has an issue with the way it works for fhir-path
> 
> ```
> private fun Class<*>.getFieldOrNull(name: String): Field? {
>   return try {
>     getDeclaredField(name)
>   } catch (ex: NoSuchFieldException) {
>     return null
>   }
> }
> ```
> 
> This is a bug in SDK and can be fixed very easily... Instead of picking declared-field we should also pick fields inherited. Patient or any other resource extends DomainResource and the Resource. It means that we can not set inherited fields like meta.tag/extension etc using fhir-path. We can also do a quick-fix into our own code and then wait for SDK fix as well. Fix to this would help in adding extension without any custom code and remove some code from ANC as well

K, let's open an issue on Android FHIR SDK, whichever approach we take, will be good to have that issue tracked

**Comment by maimoonak** [comment]
https://github.com/google/android-fhir/issues/943 - SDK issue to track

https://fhir.labs.smartregister.org/fhir/Questionnaire/3435 - Kindly review and specify what should be options for ethnicity and occupation

**Comment by maimoonak** [comment]
@pld @f-odhiambo Kindly provide options list for ethnicity and occupations for the region current app is targeted. Whole end to end flow is implemented and tested. The options can be easily updated via form

**Comment by f-odhiambo** [comment]
> @pld @f-odhiambo Kindly provide options list for ethnicity and occupations for the region current app is targeted. Whole end to end flow is implemented and tested. The options can be easily updated via form

@maimoonak for now I would have to check I with the client but I would propose we can add the following samples 
**Occupation** 
1. Employed 
2. Self-Employed
3. Unemployed 

**Ethinicity** 
1. White
2. Black 
3. Asian
4. Other

**Comment by maimoonak** [comment]
Done. you can the questionnaire here https://fhir.labs.smartregister.org/fhir/Questionnaire/3435

**Comment by f-odhiambo** [comment]
@maimoonak Can you verify that [Registration Questionnaure](https://fhir.labs.smartregister.org/fhir/Questionnaire/3435) has  
1. Marital status
2. Ethnicity
3. Occupation
Captured?

**Comment by f-odhiambo** [comment]
**Update Dec 6th 2021**
1. Updated Questionnaire 
2. Dependancy on SDK  - google/android-fhir#943 - SDK issue to track

**Comment by f-odhiambo** [comment]
This is complete on Questionnaire and marked as DONE
