### ISSUE TITLE
Implement Edit functionality for patient information

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#79]
This is part of #22 

- [x] Add menu item for editing patient information
- [x] Search for the patient resource from the DB using id/identifier
- [x] Open page containing the patient information (This would ideally be the patient registration questionnaire with populated values)
- [x] Allow editing and saving the new information

**Comment by Rkareko** [comment]
Documentation for population questionnaires with existing data can be found in the [SDC form population spec](http://build.fhir.org/ig/HL7/sdc/populate.html#form-population)

The data would be loaded in the initial value as specified here: https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial

Support for initial values was added to the android fhir SDK in [this PR](https://github.com/google/android-fhir/pull/417)

**Comment by Rkareko** [comment]
For editing patient data we need to populate the patient questionnaire with existing data.
Related issue in the android FHIR SDK is here [Questionnaire population with another resource](https://github.com/google/android-fhir/issues/273)

**Comment by Rkareko** [comment]
Issue created for [Search for the resource from the db using id](https://github.com/google/android-fhir/issues/452)

**Comment by f-odhiambo** [comment]
Not implemented as per SDK standard @MuhammadSalman-7214 to pick this up

**Comment by f-odhiambo** [comment]
**Update** 
1. Updated on SDK side moving to FHIR Core side, PR reviews left 
2. Will implement changes on FHIR core

**Comment by MuhammadSalman-7214** [comment]
This is being done on the sdk side as well as the core side. Only waiting for that sdc release from google team to update the version in fhir core and create a PR

**Comment by pld** [comment]
K is the code we need for this in the main branch of the Android FHIR SDK?

**Comment by MuhammadSalman-7214** [comment]
yes @pld it is in the main(master) branch of Android Fhir SDK

**Comment by pld** [comment]
Can we cut our own releases from main and import that until they're releases catch up?

**Comment by f-odhiambo** [comment]
@pld Reopening this as not ready in FHIRCore

**Comment by pld** [comment]
This was closed via a PR, was something wrong with that PR?
