### ISSUE TITLE
Notice E0: Deployment of cucumber/gherkin tests on server

### ISSUE THREAD

**Issue by mwkhan1983** [opensrp/fhircore#807]
**Describe the Issue**

Move the cucumber/gherkin integration tests to production server and implement CI/CD. 

@f-odhiambo can you please add further details if applicable.

**Comment by pld** [comment]
this is CI to run against PRs opened against this repo and main merges

is that correct?

**Comment by f-odhiambo** [comment]
> this is CI to run against PRs opened against this repo and main merges
> 
> is that correct?

This is correct. From our last discussions, this was supposed to run on an Orchestration server via a  CI loop, ideally, that starts/runs/stops and managed automatically to do perform the tests
****
