### ISSUE TITLE
Quest  - Sync configs via Composition resources

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#812]
**Is your feature request related to a problem? Please describe.**

1. Create Binary resource for sync-config same as assets file
2. Add the Binary to Composition as section as per template shared by Ben
3. Move the sync-filter loading to Composition in Quest
4. Associate Composition to the organization so that it can be linked with the user organization

Handle edge cases
**Test**
- [ ] (optional- check if we can use SearchParameterResource reference directly into Composition instead of using Binary)

**Additional context**
The composition would be the same as what was shared on the ticket https://github.com/opensrp/fhircore/discussions/594#discussioncomment-1635591 with an additional 'section' for sync-config.json. This would have a Binary resource reference which with content the same as  sync-config.json in assets. (We would see if we can use existing FHIR Resource (SearchParameter) instead of Binary but that would be assessed after testing Composition)

**Comment by f-odhiambo** [comment]
@ellykits Can you share the list of configs we would like to migrate to the composition resource to be DONE via this task ?

**Comment by pld** [comment]
I'd like to block this until we've discussed https://github.com/opensrp/fhircore/discussions/594#discussioncomment-1724738

**Comment by f-odhiambo** [comment]
Implementation for this has been paused 
CC @shoaibmushtaq25 @pld

**Comment by pld** [comment]
@dubdabasoduba assigning to you to pull relevant content from #594 and close this discussion, then reassign to an engineer for imlpementation

**Comment by pld** [comment]
@dubdabasoduba can you get this completed by end of next week?

**Comment by dubdabasoduba** [comment]
@f-odhiambo the Parameters version of the resources are added [here](https://github.com/opensrp/fhircore/issues/821#issuecomment-999422483). 

The composition resources tagging this is added [here](https://github.com/opensrp/fhircore/issues/821#issuecomment-999422483).

**Comment by f-odhiambo** [comment]
@maimoonak @ellykits Let's use issue #809 to complete this tasks here . 

Closing this for now
