### ISSUE TITLE
Quest v0.2/ G6PD: Get a patient's DOB by entering their age as an integer

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#816]
**Name of feature to enhance**
Add a client's DOB by entering their age as an integer 

**Description of feature**
Add on the registration questionnaire for Quest the ability to add age either an integer or actual date, add a selection before the DOB as seen in the screenshot below 

**Describe the enhancement**
1. Add a skip logic question that asks a user to either enter date as a number or date 
2. If Date show a date picker else if number enter a numerical filed
3. On submit, if used date picker submit date, if integer, get the value and compute the DOB i.e if today is **2021**, and entered 21, compute DOB as 2021-21 = **01-01-2020**

NB. This ticket is related to #652 and will be done via a structure map , and adding calculation of attributes in the questionnaire

**Comment by pld** [comment]
how does this differ from #652?

**Comment by f-odhiambo** [comment]
> how does this differ from #652?

https://github.com/opensrp/fhircore/issues/652#issuecomment-973797214
