### ISSUE TITLE
Implement the usage of the different JSON app configuration from the SQLite DB

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#822]
**Description of feature**
- Currently, we have a couple of JSON configs we use to configure different things in the app. 
- We would like to update the functionality to read these JSON files from the SQLite DB. 

**Description of implementation**
- [ ] Load the correct JSON configs based on the `type` & `reference` in the `section.focus` attribute of the composition. 
      - `reference` -- Will help identify the binary resource id to query from. 
      - `type` -- will identify where the JSON config is to be used. 
- [ ]  Apply these JSON configs to the correct workflow points to alter things like the look & feel, sync parameters e.t.c

**Depends on**
- [Add Composition & All linked Resources fetch functionality](https://github.com/opensrp/fhircore/issues/809)
- [Design & create the SettingsEntity table & BinaryEntity table in the SQlite DB](https://github.com/opensrp/fhircore/issues/821)

**Comment by pld** [comment]
Cool, does this also depend on https://github.com/opensrp/fhircore/issues/821 and how we end up implement config storage?

**Comment by dubdabasoduba** [comment]
> Cool, does this also depend on #821 and how we end up implementing config storage?

Yes, it does. I think if #821 is complete we can work on this since we know the data structure expected.  So, dummy data can be used until #809 is completed and the live data can be hooked up

**Comment by pld** [comment]
I want to double-check that the implementation plan for this is to use the existing FHIR file store and not make any database schema changes?

CC @f-odhiambo

**Comment by f-odhiambo** [comment]
> Title

HI @pld Kindly refer to this discussion item , we are going to use the Parameter resource and not have any database schema changes

**Comment by pld** [comment]
yay sounds great! this will give us more flexibility going forward

**Comment by dubdabasoduba** [comment]
Already implemented through the composition workflow
