### ISSUE TITLE
[eCBIS] Family name - use cases to think about

### ISSUE THREAD

**Issue by HenryRae** [opensrp/fhircore#823]
**Some use cases I think we need to have more thoughts on**
After thinking more about [[eCBIS] Remove the family member #767](https://github.com/opensrp/fhircore/issues/767#issue-1057769582) issue, I came up with some use cases for us to think about and the changes these might happen. If it's happens rarely, we can ignore the 1% cases.

What happens to the family details like family name when:
1. the family head is removed, dies?
- when the family head is divorced and moves to create another family, do we create a new family for them with same family name(remember we using surname as family name)?
- when the family isn't assigned a new family head?
2. the another member is assigned the family head role?
3. when the family head dies or is divorced and a new head(maybe new husband) moves into the family?
4. how would we handle cases when the father/husband has more than one family/compound?
- do we register then twice?
- do we assign them the family head role in all families he owns?
- do we give the all the families the same name?
5. how would the CHA differentiate families or family names where the family heads have the same surname?
6. what if a family relocates/moves from one Community to another, and family head happens to have same surname as another family

**Comment by f-odhiambo** [comment]
@HenryRae @pld converting this to a Discussion Item for the short term
