### ISSUE TITLE
[eCBIS/Quest] Do not show the settings/configurations page after initial set up

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#825]
**Description of feature**
- Currently, the FHIR Core app has a settings/configurations page that allows us to save the app type to enable configurations for the app.  
- We however keep showing this page even after the initial app setup and login.  We should not show this page after the first app setup. 

**Description of implementation**
- [ ] Save the app type setting to the SettingsEntitty table.
- [ ] Always check after app launch.  If the app type setting exists and is not blank or null then skip the configuration page and show the login page with the correct configurations loaded.  

**Acceptance criteria**
- Load the FHIR core app, set the app type. The app should redirect you to the login with the correct login page configs
- Close the app and re-launch it. The setting pages should not be shown to the user. The login page shown should also have the correct configuration

**Depends on**
[Design & create the SettingsEntity table & BinaryEntity table in the SQlite DB](https://github.com/opensrp/fhircore/issues/821)

**Comment by dubdabasoduba** [comment]
![settings](https://user-images.githubusercontent.com/4817531/144501216-69a7d211-18df-4479-9f6b-277e8678919b.png)

**Comment by owais-vd** [comment]
@dubdabasoduba In the FhirCore app, we are using `SharedPreferences`  for persisting the configs. Therefore, i think we can store appConfigId in the `SharedPreferences` as well.

**Comment by pld** [comment]
Can you still get to the settings page through menus if you need to and change your app?

**Comment by owais-vd** [comment]
> Can you still get to the settings page through menus if you need to and change your app?

No, we have to logout the app first if we need to change the app id

**Comment by pld** [comment]
> > Can you still get to the settings page through menus if you need to and change your app?
> 
> No, we have to logout the app first if we need to change the app id

Got it, that makes sense, so the process is

1) log out
2) change app ID
3) log back in
