### ISSUE TITLE
CHW/ANC - Refresh and show patient Weight and Height post computing the BMI via Widget 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#835]
**Describe the bug**
As a user, I would like to add details about the Patients Weight and Height and then be able to compute the BMI for that patient 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Family member profile or ANC client profile 
2. Click on Menu Item  - BMI Widget
3. Add details on weight and height and compute 
4. Check on the vitals tab in the menu to access the latest Height and Weight 

**Expected behaviour**
1. Extract and Save the Observation resources for both weight, height  and BMI 
2. The last updated weight, height and BMI should be visible post Computing and Saving the BMI 

**Screenshots**

<img src="https://user-images.githubusercontent.com/4540684/144843165-80fe81b7-1ff4-456c-a712-d50a1d2f41a5.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/4540684/144842872-c1bbf592-93e2-4731-a4cb-0a0ba679381d.png" width="200" height="400" />

**Additional context**
1. This ticket may be dependent on ticket https://github.com/opensrp/fhircore/issues/561 
2. Write test and test the functional behaviour before closing this ticket

**Comment by AbdulWahabMemon** [comment]
https://github.com/opensrp/fhircore/issues/897 
cc: @ekigamba , @f-odhiambo , @kwasim
