### ISSUE TITLE
Patient bio data info not loading on profile view

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/fhircore#84]
After updates made to the [match fhir sdk update + uploading fhir resources PR](https://github.com/OpenSRP/fhircore/pull/83) , patient bio data is not being displayed on the profile view.

**Comment by Rkareko** [comment]
@rkodev assist in creating a ticket for the search by identifier implementation

**Comment by rkodev** [comment]
@Rkareko We have an issue that is listed in search by token types in [Android FHIR SDK](https://github.com/google/android-fhir/issues/431)

We can also add search/find by Resource ID

**Comment by rkodev** [comment]
Issue created for [Find Resource by Id](https://github.com/google/android-fhir/issues/452)

**Comment by Rkareko** [comment]
Able to load the patient bio data by getting the info from the patient list as done on this [PR](https://github.com/OpenSRP/fhircore/pull/93)

An ideal way is by fetching the patient record using the id. When that functionality is implemented in the SDK, the implementation on FHIR CORE will be updated.
