### ISSUE TITLE
CHW/ANC - Replace the current home icon in the ANC 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#843]
**Name of feature to enhance**
Replace the current icon for the Register in home screen for bottom navigation 

**Describe the enhancement**
**Screenshot**

**Mock** 

<img width="264" alt="Screen Shot 2021-12-07 at 12 40 27 PM" src="https://user-images.githubusercontent.com/4540684/145005730-9a435e59-ee9e-4b4b-8757-11fe27a05096.png">

**Actual**  

<img width="264" alt="Screen Shot 2021-12-07 at 12 40 27 PM" src="https://user-images.githubusercontent.com/4540684/145007202-c7d94c01-01cd-4b93-8850-771b322837aa.png">

Link to the desired icon  - https://drive.google.com/file/d/1SGLYjADFLEX2oY2d_Yflv99mEE2_9vLP/view?usp=sharing

**Comment by ellykits** [comment]
@f-odhiambo  I used the same svg resource. Same effect.

**Comment by f-odhiambo** [comment]
@f-odhiambo to get a new icons and have it updated

**Comment by f-odhiambo** [comment]
Closing for now
