### ISSUE TITLE
DOB validation  - Date of Birth should be <= today()

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#845]
**Name of feature to enhance**
A client's date of birth should be <= today()

**Description of feature**

1. A person cannot be born in the future 
2. This validation should happen prior to saving a client's details 

Should apply to all DOB fields currently available in 

1. Quest / G6PD
2. LMH e-CBIS

**Comment by f-odhiambo** [comment]
Might be a min-max value that is computed by SDC
1. http://hl7.org/fhir/uv/sdc/2019May/behavior.html



maxValue | Core | date, dateTime, time, decimal, integer | as per question type

This extension is used for questions with simple quantitative types. It does not currently support the Quantity data type. The extension allows establishing the upper bound for an answer. For example, ensuring that birth dates are >= 1990-01-01 or an integer is greater than or equal to 0. (Note that the integer and decimal types both allow negative numbers if not constrained.) This extension can be used together with the cqf-calculatedValue extension to establish a dynamic limit. For example, ensuring that a date of birth will result in a minimum age by setting maxValue with an expression of 'today() - 18 years'.The minValue SHALL be less than or equal to the maxValue, if both are specified.

**Comment by pld** [comment]
Can we do this in the Questionniare and not in code?

**Comment by f-odhiambo** [comment]
> Can we do this in the Questionnaire and not in code?

Yes. This is accurate, We should be able to update the Questionnaire with min/max values and then check if the SDC Lib can be able to translate it correctly or raise an issue if we have any bugs/enhancements for it.

**Comment by f-odhiambo** [comment]
We could add the following extensions for 

**min value**
```
"extension": [
  {
    "url": "http://hl7.org/fhir/StructureDefinition/minValue",
    "valueDate": "2022-05-20"
  }]
```

**& max value**

```
"extension": [
  {
    "url": "http://hl7.org/fhir/StructureDefinition/maxValue",
    "valueDate": "2022-09-20"
  }]
```
and the resulting questionnaire validation 
<img width="387" alt="Screenshot 2021-12-09 at 09 05 43" src="https://user-images.githubusercontent.com/4540684/145955583-7140c840-f21d-44ef-bf78-bd2740fa52fb.png">

**Comment by f-odhiambo** [comment]
@kimigxfoxy I was able to test this separately
<img width="387" alt="Screenshot 2021-12-09 at 09 05 43" src="https://user-images.githubusercontent.com/4540684/145954942-2edb48d6-9af5-4bc8-9d91-7a6c9680cd1f.png">


@ndegwamartin Has alluded to a solution in slack. I will DM you on the same

**Comment by f-odhiambo** [comment]
ill pick this up

**Comment by RaaziaTarique** [comment]
> 

As per the SDK we can add extensions for min-max value validation in the questionnaire but as per my findings we can't make those validations dynamic i.e use current date as maxValue.

**Comment by pld** [comment]
if you haven't yet can you please ask on zulip (I think there's an SDC channel), how people handle dynamic max?

also is there an issue on the sdk repo for this? if not, can yea please create one, thanks!

**Comment by f-odhiambo** [comment]
Yes, @pld. We had a discussion on the Android FHIR SDK call today Jan 13th 2022, will create a ticket on SDK and tag here as well 

cc @Tarun-Bhardwaj @jingtang10

**Comment by jingtang10** [comment]
> if you haven't yet can you please ask on zulip (I think there's an SDC channel), how people handle dynamic max?

https://chat.fhir.org/#narrow/stream/179255-questionnaire

**Comment by jingtang10** [comment]
> Yes, @pld. We had a discussion on the Android FHIR SDK Developers call today Jan 13th 2022, will create a ticket on SDK and tag here as well
> 
> cc @Tarun-Bhardwaj @jingtang10

As discussed there are 2 things to consider in this ticket:

1. to be able to resolve expressions such as `today()` in the min max value extension
2. to use the min max value extension in the actual date picker pop-up. at the moment the pop up dialog allows the user to put in any date and the error message only kicked in once the user has input a date. it would be much better if the date picker already doesn't allow the user to input a date outside the allowed range.
