### ISSUE TITLE
Increase code coverage to >=80% 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#855]
**Describe the Issue**

- [ ] 1. We need to add code coverage reporting for the engine/anc/eir.quest module codebase. 
- [ ] 2. Fix failing test to be able to add/improve coverage percentage 
- [x] 3. Fix ignored tests 
- [x] 4. Go through the individual tests and in some cases refactor the code.
- [ ] 5. Write more tests on the Quest module to increase its code coverage

**Comment by pld** [comment]
For the 1st task, what needs to be done here? It looks we have coverage metrics for these modules, e.g. see https://github.com/opensrp/fhircore/actions/runs/1562709760

For the 2nd task, there are currently no failing tests on main, what is this referring to? See https://app.codecov.io/gh/opensrp/fhircore

We must either check the first 2 as complete or add more detail to clarify what is to be done there

**Comment by f-odhiambo** [comment]
> For the 1st task, what needs to be done here? It looks we have coverage metrics for these modules, e.g. see https://github.com/opensrp/fhircore/actions/runs/1562709760
> 
> For the 2nd task, there are currently no failing tests on main, what is this referring to? See https://app.codecov.io/gh/opensrp/fhircore
> 
> We must either check the first 2 as complete or add more detail to clarify what is to be done there

**Update Dec 14th** 
1. Failing CI test cases
2. Failing Engines tests  for  Measure Evaluate  - I think due to the OutOfMemoryIssue reason the MeasureEvaluate test failing
