### ISSUE TITLE
[Quest] Make Login & app id fields single line.

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#858]
**Describe the bug**
- The current app id and login username & password fields are currently multiline.  
- They should be a single line that will make pressing enter move to the next field instead of moving to the next line. 

**To Reproduce**
1. launch the FHIR core app
2. Fill in the application id then press enter. Notice the cursor moves to the next line instead of the next field. 

**Expected behavior**
1. launch the FHIR core app
2. Fill in the application id then press enter. The cursor should move to the next field instead of moving to the next line

**Screenshots**
![multiline](https://user-images.githubusercontent.com/4817531/145547891-33db9d07-4357-4f8f-9697-fcd7de42e087.gif)

**Additional context**

**Comment by machariamuguku** [comment]
I'd like to try this out
