### ISSUE TITLE
[Quest] App force close if the wrong Application ID is provided on the settings page. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#871]
**Describe the bug**
- Currently, we have some settings that are added on the settings page before login. One of these settings is the `Application ID` which is used to identify which app configs to load for the app. 
- If a wrong application id is entered the app then forces and can't work until the app data is cleared. 

**To Reproduce**
1. Launch the app 
2. This should load the settings page.  For the setting `Application ID` enter the following `nerd` 
3. The app should force close. 

**Expected behavior**

**Screenshots**
- [ ] If the correct `Application ID` is entered then the app should load the required configs and proceed to login. 
- [ ] If the wrong `Application ID` is entered then the app should give the user an error saying _The Application ID entered is not recognized. Please contact your system admin for the correct Application ID._ The following should also happen: - 
     - [ ] The wrong application id should not be saved to the secure shared preferences

**Comment by f-odhiambo** [comment]
@allan-on . Hope you are well, whats the status of this ticket?

**Comment by f-odhiambo** [comment]
Marking this as resolved in the latest check CC @LZRS
