### ISSUE TITLE
[SDC error] Field validation occurs before user enters any data

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#873]
**Describe the bug**
When a form is first opened, all the required fields are validated and highlighted in red before the user enters any data.

**To Reproduce**
1. Open the quest app
2. Click the register patient button
3. When the form opens, there are validation errors for all required fields

**Expected behavior**
No validation should take place when the form is first opened. Validation of each field should only take place after a user enters some data into that field and moves to the next field.

**Screenshots**

<img src="https://user-images.githubusercontent.com/90775548/146182724-115412e2-912c-4b24-9769-1ec5155044b0.png" width="200" height="400" />

**Smartphone (please complete the following information):**
 - Device: Google Pixel XL Emulator 
 - Android version: 10
 - Build number: sdk_gphone_x86-userdebug 10 QSR1.210802.0017603624 dev-keys
 - Version: 29

**Additional context**
This wasn't happening in Quest v0.0.1

**Comment by maimoonak** [comment]
This is coming from SDK as it get validated by questionnaire-viewmodel from data-capture

![Screenshot from 2022-01-05 14-38-37](https://user-images.githubusercontent.com/4829880/148195736-73a3937f-cbab-410d-821c-034780d911fd.png)

**Comment by maimoonak** [comment]
https://github.com/google/android-fhir/issues/1001 SDK issue

**Comment by KhumboLihonga** [comment]
This has been resolved
