### ISSUE TITLE
Quest : Pagination for search results not loading all results  

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#877]
**Describe the bug**
All search results that are above the pagination limit should be displayed on separate pages in the app. Not all results are currently displayed despite viewing the correct search count. See screen shot  

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Quest app 
2. Search for Mussa (Currently has 9 results)
3. Scroll down to on search results page 
4. Only 6 patient can be viewed on the search result page 

**Expected behaviour**
View the correct number of results and if more than the pagination limit vie results on different result pages
 
**Screenshots**
<img src="https://user-images.githubusercontent.com/4540684/146332708-c89d4a9f-1c5a-44b8-b4ee-28f4b25d2237.png" width="200" height="400" />

**Smartphone (please complete the following information):**
 - Physical device or an emulator 

**Additional context**
N/A

**Comment by AbdulWahabMemon** [comment]
@f-odhiambo , I have updated the PR, but just checked the ANC app, register list is also not displaying whole items there, result result showing less items vs displayed count.
@ellykits as the screen UI is divided with activity layout and compose components, I have resize 55% weight to register list for Quest app only, having doubt the other apps wont effected, we need to sync for register list height ratio for all apps.
cc: @maimoonak , @kwasim
