### ISSUE TITLE
Add Location Widget (a.k.a GPS picker) to FHIR Core

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#880]
What's the difference between a location widget and a Geo-widget?
From a tech perspective, they are the same thing. They pick location GPS data but from a UI perspective, they are different. Geo Widget will use the map to pick the location data. Done is FHIR Core https://github.com/opensrp/fhircore/issues/1536 

Location widget can have 2 variants

1. Show a drop-down or location tree. This helps you select the locations already saved on the app. It mostly visualizes the location hierarchy on a form. 
2. This is an input field on a form that will pick the GPS coordinates and fill in LAT & LONG input fields in the form.|

Point 2 can be a simple button that gets the (Lat, Long) when clicked or be what Ona Data did [here](https://ona.io/home/introducing-the-select-location-widget-for-ona-data/)

Opened this ticket to track the SDK issue  - https://github.com/google/android-fhir/issues/800

**Comment by ageryck** [comment]
This is fixed by this #3046
