### ISSUE TITLE
Quest: Refine auto-complete widget in a questionnaire

### ISSUE THREAD

**Issue by KhumboLihonga** [opensrp/fhircore#893]
**Name of feature to enhance**
Auto-complete widget

**Description of feature**
The feature allows the user to type in a text field and by doing so, filters a long list of entries to show a drop-down list of the applicable options.

**Describe the enhancement**
Currently, the auto-complete field works but not very well. Here are some of the problems it has:
1. The field only shows the list of options after two characters have been typed. It would be better if it did this after the first character was entered.
2. If after typing two characters and no results are found, the list of options opens for a fraction of a second and then closes again. This is jarring for the user and it would be better if a drop-down with 'no results found' was displayed.
3. If after typing two characters and results are found, then they are correctly shown in a drop-down list. However, when the user selects their desired option, the UI significantly changes - the border of the field disappears. Furthermore, if you remove the selection, the border doesn't come back. In this regard, it would be nice if at least the border remained to maintain the look and feel of the widget.
4. In addition, once the user selects their desired option, the field seemingly becomes a multi-select field. The selected option is shown as a removable chip but the cursor is placed and continues blinking at the end of the selected chip. This signifies that another field can be selected. However, when the user does type and select another field, it replaces the first selection. I believe it would be better to not allow the user to type once an option has been selected. If they want to replace their selection, they can tap the 'X' on the chip to remove it which would allow the user to type once again.

NOTE: the [SDC Gallery sample app](https://github.com/google/android-fhir) seems to work the same way so I'm not sure if this is a FHIRCore problem per say. I've already noted this [issue](https://github.com/google/android-fhir/issues/978) on the android-fhir page, but if the FHIRCore team does have some say on this, it would be good to look into as this is an important widget.

**Comment by f-odhiambo** [comment]
**Update Jan 10th 2022**

This is the SDK ticket that will resolve this https://github.com/google/android-fhir/issues/978
