### ISSUE TITLE
Quest - Improve the logic to show QuestionnaireResponse labels on QuestPatientDetailScreen

### ISSUE THREAD

**Issue by shoaibmushtaq25** [opensrp/fhircore#895]
**Name of feature to enhance**
Quest - Improve the logic to show QR labels on QuestPatientDetailScreen

**Description of feature**
This is a follow up issue for [issue#737](https://github.com/opensrp/fhircore/issues/737) As per the suggestion of @ekigamba  [here](https://github.com/opensrp/fhircore/issues/737#issuecomment-995513405), we need to improve the logic to show Questionnaire Response labels on QuestPatientDetailScreen in order to make it compliant with FHIR specs.

**Describe the enhancement**
In the current implementation in [PR#863](https://github.com/opensrp/fhircore/pull/863), we are getting the name/title of Questionnaire of a respective QuestionnaireReponse to show as labels of QuestionnaireResponses on QuestPatientDetailScreen. We need to make it more generic in order to conform with FHIR standards to maintain inter-operability

**Comment by RaaziaTarique** [comment]
As per the discussion with @shoaibmushtaq25 and @ekigamba, we will be using the solution proposed by @shoaibmushtaq25  in PR #863.

CC: @ekigamba
