### ISSUE TITLE
Documented research  on SmileCDR capabilities 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#90]
Here are the Smile CDR dedicated test server details for the test
Smile CDR Web Console
https://ona.demo.smilecdr.com/signin
admin
ona1smile
FHIR Endpoint (Anonymous access has been enabled)
I have loaded some sample Synthea data.
https://ona.demo.smilecdr.com/fhir-request
FHIR Web UI
https://ona.demo.smilecdr.com:8001/
Package Registry
https://ona.demo.smilecdr.com/package_registry/swagger-ui.html
SMART Auth Endpoint
https://ona.demo.smilecdr.com/smartauth/.well-known/openid-configuration

Slide decks to SmielCDR [portfolio](https://drive.google.com/drive/folders/1oEwZ0sLCg6CxuIUUGle_7CPu5ggowmMt)

**Comment by f-odhiambo** [comment]
Slide decks to SmielCDR [portfolio](https://drive.google.com/drive/folders/1oEwZ0sLCg6CxuIUUGle_7CPu5ggowmMt)

**Comment by pld** [comment]
I think you can move this into a file in `docs`
