### ISSUE TITLE
Regression bug: Quest edit questionnaire response feature no longer available

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#905]
**Describe the bug**
Quest feature for editing questionnaire no longer seems to be working

**To Reproduce**
1. Open or run the Quest
2. Search and click for patient **Mushtaq Shoaib**
3. Select **G6PD Test Result (25-Nov-2021)**
4. The opened form/page should an **edit button** at the bottom of the page

**Expected behavior**

The opened filled-form should have an **edit** button immediately above the **Done** button. Alternatively, this should be an option in the hamburger menu or there should be a different workflow from the tests results page to get here. None of the other options on the tests results page provide the edit QR workflow.

**Screenshots**
![Screenshot from 2021-12-29 13-37-07](https://user-images.githubusercontent.com/31766075/147653901-f7fb6b19-be1e-439b-b637-eabdb78a2763.png)

**Smartphone (please complete the following information):**
 - Device: Google Nexus 5X Emulator
 - Android version:
 - Build number:
 - Version 28
 

**Additional context**
- The app was run from master commit: d3dd32d13eff03192eb965b1f620f49d62b1e0c1
- The UI code and processing logic seems to have been removed in this PR. https://github.com/opensrp/fhircore/pull/902/files

**Comment by ekigamba** [comment]
@maimoonak I noticed that you were the author of this PR https://github.com/opensrp/fhircore/pull/902/files removing the code for this feature. Is there a good reason for this?

**Comment by maimoonak** [comment]
@ekigamba Sorry for that. I have reverted that code. Kindly review the PR #907 

During testing current changes found another issue with Test results Photo Capture #908  where app is crashing as data type attachment not available (not sure why)

Also wanted to discuss whole edit flow with you in details #900 later (not related to this issue though)

**Comment by f-odhiambo** [comment]
@maimoonak What the status of PR https://github.com/opensrp/fhircore/pull/907

**Comment by f-odhiambo** [comment]
is there a PR for this issue @maimoonak

**Comment by maimoonak** [comment]
its ready now
