### ISSUE TITLE
Enhancement to Extraction of FHIR resources & Generate Observation Resources - Device & DeviceDefinition

### ISSUE THREAD

**Issue by mwkhan1983** [opensrp/fhircore#906]
**Name of feature to enhance**
ref: #599

**Describe the enhancement**
**Step  2** To be done on a separate ticket 
- [x] Create a [ServiceRequest](https://www.hl7.org/fhir/servicerequest.html) and a [DiagnosticReport](https://www.hl7.org/fhir/diagnosticreport.html) 
- [ ] Capture Device Serial number and save to the [Device](https://www.hl7.org/fhir/device.html) resource 
- [ ] Link [DeviceDefinition](http://www.hl7.org/fhir/devicedefinition.html) while saving the [Device](http://hl7.org/fhir/device.html) details 
- [x] Determine how to store data post RIM computation is done, will need to at least have the following resources, **Patient**, **Practitioner**, **Device**, **Observation** and **DiagnosticReport**  created to query a patient record  via https://turn-fhir.smartregister.org/fhir/Patient/XXX/$everything where XXX is PatientID  
- [x] Push data to RIM via [Observation](https://www.hl7.org/fhir/observation.html) resource 

Sample resources to be extracted and generated 

1. Service Request 

```
{
  "resourceType": "ServiceRequest",
  "status": "active",
  "intent": "original-order",
  "subject": {
    "reference": "Patient/3536"
  },
  "basedOn": [
    {
      "reference": "QuestionnaireResponse/XXX"
    }
  ],
  "occurrenceDateTime": "2021-05-12T16:16:00-07:00",
  "reasonCode": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "86859003",
          "display": "Glucose-6-phosphate dehydrogenase deficiency anaemia analysis"
        }
      ],
      "text": "G6PD Test"
    }
  ]
}
```

**Comment by pld** [comment]
Does mean it will save a new Device everytime? I don't know if that's the best approach because the Device resource is meant to track the individual instances of a device, and this approach would create multiple resources for the same individual instance

**Comment by f-odhiambo** [comment]
@mwkhan1983 perhaps we should repurpose this ticket to handle control mode as it will be the one handling device serial/ID. Let's chat about this

**Comment by pld** [comment]
@f-odhiambo let's please create a new ticket for that (and close this if appropriate), it will make the history easier to follow, thanks

**Comment by f-odhiambo** [comment]
> @f-odhiambo let's please create a new ticket for that (and close this if appropriate), it will make the history easier to follow, thanks

Cool will do so . Makes sense

**Comment by f-odhiambo** [comment]
Closing this ticket and will add a Control mode ticket to address 
1.  Capture Device Serial number and save to the Device resource
2.  Link DeviceDefinition while saving the Device details

CC @pld @mwkhan1983
