### ISSUE TITLE
[eCBIS] Add a Pin login set up & confirmation page. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#912]
Context
eCBIS will allow the users to log in using a predefined pin set by the system administrators. This means we will need a screen to set up the new pin credentials for the users to log in with. This screen will be shown immediately after the [pin selection page](https://github.com/opensrp/fhircore/issues/911). 

**Requirements**
- [ ] Add a page to set the pin credentials.  This page should allow the following.  
     - [ ] Have a field to enter the 4 number pin. 
     - [ ] Validate the pin field to avoid it being blank. 
- [ ] Add a page to confirm the pin set up on the previous page.  This page should allow the following.  
     - [ ] Have a field to enter the 4 number pin. 
     - [ ] Validate the pin field to avoid it being blank. 
     - [ ] Validate that this pin set up here is the same as the pin set up previously. 
- [ ] Save this pin in the secure shared preferences. 
- [ ] After saving the pin redirect to the pin login page. 

**Acceptance criteria**
- [ ] Should be able to show the pin set up and pin set up confirmation page
- [ ] Should be able to save the set pin to secure shared preferences.
- [ ] Should be able to validate the pins set up are the same.  

**Blocked by**
[Pin selection page](https://github.com/opensrp/fhircore/issues/911)

**Configuration requirements**
- [ ] The pin login set  & confirmation page should only be shown when **the pin login is enabled** on the view configuration configs

**Comment by HenryRae** [comment]
How are user names set up in this use case? @dubdabasoduba 
or we don't need them?

**Comment by HenryRae** [comment]
For setting a pin for login, we don't need a confirmation page so we can always show/unmask digits entered to ease the setting up of a device by removing and avoid room for errors. 

<img width="673" alt="Screenshot 2022-01-05 at 16 38 25" src="https://user-images.githubusercontent.com/31955469/148226597-d0edcb3e-d72f-47b6-83c9-e74f0b3b1063.png">
cc: @dubdabasoduba @rowo

**Comment by pld** [comment]
can we not show a cursor or a zero? it looks kind of weird and the zero might be confusing, it might seem like a default

**Comment by dubdabasoduba** [comment]
> For setting a pin for login, we don't need a confirmation page so we can always show/unmask digits entered to ease the setting up of a device by removing and avoid room for errors.
> 
> <img alt="Screenshot 2022-01-05 at 16 38 25" width="673" src="https://user-images.githubusercontent.com/31955469/148226597-d0edcb3e-d72f-47b6-83c9-e74f0b3b1063.png">
> 
> cc: @dubdabasoduba @rowo

@HenryRae  The idea of the PIN confirmation page was to make sure the user remembers the PIN they entered. It's some form of reinforced learning ;)

**Comment by dubdabasoduba** [comment]
> How are user names set up in this use case? @dubdabasoduba or we don't need them?

@HenryRae By this time the users are already created via FHIR web. This is where the demographics, username & password are assigned.

**Comment by dubdabasoduba** [comment]
This is now complete.
