### ISSUE TITLE
Display correct details on alert dialog when user enters incorrect user credentials 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#920]
**Name of feature to enhance**
Alert the user if they have entered the wrong username or password  once Keycloak fails to authenticate the user 

**Description of feature**
Add human-readable alert message different from the error log received from the server-side post-authentication mismatch 

**Describe the enhancement**
Add the correct alert dialogue message, when a user  enters the wrong user credentials thus 
1. Invalid credentials 
2. No network connection, prompt user for  Offline login can give an appropriate message if credentials don't match the offline synced credentials 

**Screenshots**
<img src="https://user-images.githubusercontent.com/4540684/147912880-450e3559-50c7-44a0-b860-9723a1a78fa5.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/147912886-18eb0738-899e-4672-9c1c-207487941d59.png" width="200" height="400" />

**Comment by owais-vd** [comment]
I think the message could be `Login failed username or password is invalid`

**Comment by owais-vd** [comment]
and the error message of no network detection could be `Failed to verify credentials from the server. Check your internet connection`

**Comment by f-odhiambo** [comment]
Hi @owais-vd You can proceed create a fix for this
