### ISSUE TITLE
Entering the wrong app ID causes the app to crash and fails to load unless the app cache is cleared or the app reinstalled 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#923]
**Describe the bug**
Entering the wrong app ID causes the app to crash and fails to load unless the app cache is cleared or the app reinstalled 

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch app
2. Enter wrong app ID
3. Press Load configurations
4. See an error

**Expected behaviour**
The app should prompt the user that the App ID does not exist 

**Screenshots/Video**
<img src="https://user-images.githubusercontent.com/4540684/147943122-b4a507ba-45e9-4b4f-82b1-83b4d4f7c5f0.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/4540684/147943128-c4278abb-c565-4908-be22-ec130a6ce754.png" width="200" height="400" />

Video Link  - [here](https://user-images.githubusercontent.com/4540684/147943981-a7536210-2c49-4f9d-9b05-7ebeb39e2d32.mp4)

**Smartphone (please complete the following information):**
 - Device: Emulator or Phycical device 

**Additional context**
N/A

**Comment by ellykits** [comment]
Was able to reproduce and resolve the issue.

**Comment by pld** [comment]
closed by https://github.com/opensrp/fhircore/pull/925
