### ISSUE TITLE
Quest v0.2 / G6PD :  Add Control mode workflow for G6PD

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#946]
**Name of feature to enhance**
As a G6PD app user, I would like to check if the device is properly recalibrated  in either Control Mode 1 or Control Mode 2

**Description of feature**
Add both UI/UX for control mode user journey and leverage current CQL evaluation that can allow us to reuse the current CQL implementation for G6PD evaluation 
Based on a Quest approach added a Questionnaire for test calibration that is independent of the Patient/Clinical workflow.

**Control mode  table** 
<img width="634" alt="Screen Shot 2022-01-13 at 10 19 06 PM" src="https://user-images.githubusercontent.com/4540684/149395158-22a99428-dd1c-4904-a0f2-dd12ffc93945.png">

**Test Kit in normal mode**
<img width="260" alt="Screen Shot 2022-01-13 at 10 23 20 PM" src="https://user-images.githubusercontent.com/4540684/149396047-9c0a51c3-ddd5-4e69-9809-2281396ddac6.png">

**Test kit in control mode** 
<img width="611" alt="Screen Shot 2022-01-13 at 10 25 36 PM" src="https://user-images.githubusercontent.com/4540684/149396063-5b5e8b8d-cf2c-421d-9dfa-e7d3b99a3ae5.png">

More details on testing and control mode can be found here https://www.finddx.org/wp-content/uploads/2020/09/STANDARD-G6PD-test_Training_Bangladesh-FIND-icddr-Menzies_FINAL_26Nov19.pdf 

**Describe the enhancement**

1. Add a menu item to initiate the control mode test 
2. Add a Questionnaire to be able to conduct control mode, similar to the Test Questionnaire, an image of control mode and the 2 entry points for G6PD and Haemoglobin level. This should have the following fields 
> Chip No
> Device Serial number
> G6PD level
> Haemoglobin level 
3. Author and load  a CQL Library evaluation for control mode evaluation 
4. Initiate the control mode evaluation on press submit 
4. Add a test result page for Control mode level 1 or control mode level 2 
5. Terminate control mode flow once the user has calibrated the device

**Comment by f-odhiambo** [comment]
**Updated Jan 13th 2021**
1. Added a control mode questionnaire  - http://turn-fhir.smartregister.org/fhir/Questionnaire/14222 but will need to add the correct SNOMED code for Control mode 1 and Control mode 2 
2. Questionnaire available as in Quest app as G6PD Control mode test, press sync to update

**Comment by maimoonak** [comment]
### CQL

```
//Declare name and version of lib
library TestArtifact version '1'

//FHIR as a data model and version of FHIR
using FHIR version '4.0.1'

//functions to help FHIR vs CQL primitives
include "FHIRHelpers" version '4.0.1' called FHIRHelpers

//System declarations  : Codable concept codes systems
codesystem "SNOMED": 'http://snomed.info/sct'
codesystem "ONA": 'http://fhir.ona.io'

//Code used as identifers
code "G6PD code": '86859003' from "SNOMED" display 'G6PD Enzyme'
code "Haemoglobin code": '259695003' from "SNOMED" display 'Haemoglobin'
code "g6pdResultTypeCode": '000001' from "ONA" display 'G6PD Result Type'
code "g6pdControl1": '410680006' from "SNOMED" display 'Control-mode 1'
code "g6pdControl2": '405358009' from "SNOMED" display 'Control-mode 2'


define "Control1Obs":
  Last([Observation: "g6pdResultTypeCode"] H
    where H.value ~ "g6pdControl1")
    
define "Control2Obs":
  Last([Observation: "g6pdResultTypeCode"] H
    where H.value ~  "g6pdControl2")
    
define "HaemoglobinObs":
  Last([Observation: "Haemoglobin code"] H
    where H.status ~ 'registered')

define "G6PDObs":
  Last([Observation: "G6PD code"] G
    where G.status ~ 'registered')

define "G6PD Value": ToString("G6PDObs".value.value.value)
define "Haemoglobin Value": ToString("HaemoglobinObs".value.value.value)
    
define "G6PD Normal": 
    if "Control1Obs" is not null and "G6PDObs".value.value between 0.0 and 3.0
    	then true
    else if "Control2Obs" is not null and "G6PDObs".value.value between 6.0 and 10.0
    	then true
    else false
  
define "G6PD Conclusion": 
    if "Control1Obs" is not null and "G6PD Normal"
    	then 'Value ('+ "G6PD Value"+') is in Normal G6PD Range 0-3'
    else if "Control2Obs" is not null and "G6PD Normal"
    	then 'Value ('+ "G6PD Value"+') is in Normal G6PD Range 6-12'
    else 'Value('+"G6PD Value"+') is Non Deterministic G6PD result'
      
define "Haemoglobin Normal": 
    if "Control1Obs" is not null and "HaemoglobinObs".value.value between 8.0 and 12.0
    	then true
    else if "Control2Obs" is not null and "HaemoglobinObs".value.value between 13.0 and 17.0
    	then true
    else false
    
define "Haemoglobin Conclusion": 
    if "Control1Obs" is not null and "Haemoglobin Normal"
    	then 'Value ('+ "Haemoglobin Value"+') is in Normal Haemoglobin Range 8-12'
    else if "Control2Obs" is not null and "Haemoglobin Normal"
    	then 'Value ('+ "Haemoglobin Value"+') is in Normal Haemoglobin Range 13-17'
    else 'Value('+"Haemoglobin Value"+') is Non Deterministic Haemoglobin result'

define "Conclusion": 
  if "G6PD Normal" and "Haemoglobin Normal" then 'Correct result'
  else 'Invalid result'
  
define "Conclusion Details": '\nDetails:\n'+ "G6PD Conclusion" + '\n' + "Haemoglobin Conclusion"

        
define "OUTPUT": List { "Conclusion" , "Conclusion Details"}

```

**Comment by maimoonak** [comment]
**Few points to be noted**

- Questionnaire updated 
  - Updated SNOMED url i.e. 'http://snomed.info/sct'
  - **Added boolean property `experimental=true` to questionnaire. This allows to dynamically mark questionnaire able to run into test mode and persist no data**
  - Structure map is same
  - CQL is updated (library id is different in questionnaire) as older one is very different

- Flow provides detailed feedback
- It does not save data
- Navigation added to Bottom as 'Control Test'. 
- Please test the apk shared and provide feedback on where to add the flow and menu i.e. need mockups incase UI needs major changes

<img width=200 height=400 src="https://user-images.githubusercontent.com/4829880/149816294-00760977-20c5-4cfd-83ac-5e2b79b30184.jpg"/> <img width=200 height=400 src="https://user-images.githubusercontent.com/4829880/149816315-6f7ebaa1-d7cd-445b-8622-54f52d51780a.jpg"/> <img width=200 height=400 src="https://user-images.githubusercontent.com/4829880/149816323-0afb2558-35a4-47fd-9da5-88cb668f0d14.jpg"/> <img width=200 height=400 src="https://user-images.githubusercontent.com/4829880/149816328-b2841f26-4560-4613-8fd0-cd1bfe707967.jpg"/>

**Comment by f-odhiambo** [comment]
What's the negative flow for this ? If device is not callibrated

**Comment by f-odhiambo** [comment]
Shared feedback on Slack

**Comment by maimoonak** [comment]
@pld the current version did not support configurable navigation... in current PR it is added today. plz check commit here https://github.com/opensrp/fhircore/pull/956/files#diff-49541e0378d07ee44cd73f8b24816df7b9c7e86c74b303fc54600061d9457943

**Comment by f-odhiambo** [comment]
@maimoonak Do we have a PR linked to this issue ?

**Comment by f-odhiambo** [comment]
This PR will be addressing issues in  this ticket PR #956
