### ISSUE TITLE
Remove Hard-coded App Configurations

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#961]
**Describe the Issue**

Extended generic configuration capabilities to remove this app-specific config processor, https://github.com/opensrp/fhircore/pull/927/files#diff-0db5f979a29b4d4cc746c875ad98de535b6e97c54645a2b624f6215c7d33298c

**Comment by maimoonak** [comment]
We also want to allow opening different activity post questionnaire submission via config. #970 issue handling with proper configuration. For current release it would be handled via hardcoded check

**Comment by f-odhiambo** [comment]
@shoaibmushtaq25 Do we have a PR for this work ? What's the status?

**Comment by pld** [comment]
this also needs to be addressed, https://github.com/opensrp/fhircore/pull/969/files#diff-f25df15caea474a0ceec42bfbc6989a2ddf6cb99ea77897a040e1692699a1e28R166

**Comment by shoaibmushtaq25** [comment]
The latest configurations of patient_details_view_configurations that I am using for this generic approach are here, 
`[
  {
    "appId": "quest",
    "classification": "patient_details_view",
    "contentTitle": "Responses",
    "dynamicRows": []
  },
  {
    "appId": "g6pd",
    "classification": "patient_details_view",
    "valuePrefix": "G6PD ",
    "contentTitle": "TEST RESULTS",
    "dynamicRows": [
      [
        {
          "resourceType": "CONDITION",
          "key": "category",
          "displayableProperty": "code",
          "valueType": "CODEABLECONCEPT",
          "valueCoding": {
            "system": "http://snomed.info/sct",
            "code": "9024005"
          }
        },
        {
          "resourceType": "CONDITION",
          "key": "category",
          "displayableProperty": "recordedDate",
          "valueType": "CODEABLECONCEPT",
          "valuePrefix": " (",
          "valuePostfix": ")",
          "valueCoding": {
            "system": "http://snomed.info/sct",
            "code": "9024005"
          }
        }
      ],
      [
        {
          "resourceType": "OBSERVATION",
          "key": "code",
          "displayableProperty": "value",
          "valueType": "CODEABLECONCEPT",
          "label": "G6PD: ",
          "valueCoding": {
            "system": "http://snomed.info/sct",
            "code": "86859003"
          },
          "properties": {
            "label": {
              "color": "#74787A",
              "textSize": 16
            },
            "value": {
              "color": "#74787A",
              "textSize": 16
            }
          }
        },
        {
          "resourceType": "OBSERVATION",
          "key": "code",
          "displayableProperty": "value",
          "valueType": "CODEABLECONCEPT",
          "label": " - Hb: ",
          "valueCoding": {
            "system": "http://snomed.info/sct",
            "code": "259695003"
          },
          "properties": {
            "label": {
              "color": "#74787A",
              "textSize": 16
            },
            "value": {
              "color": "#74787A",
              "textSize": 16
            }
          }
        }
      ]
    ]
  }
]`

**Comment by shoaibmushtaq25** [comment]
The result output after these configurations shifted to config files are here :point_down: , and next I will be working on this comment https://github.com/opensrp/fhircore/issues/961#issuecomment-1018683657 to handle routing to test details screen.

![Screenshot_1643138809](https://user-images.githubusercontent.com/12672919/151048265-5d649e69-27cf-40eb-afb3-ce8af59ecf41.png)
