### ISSUE TITLE
Add integration tests & automated performance testing

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#97]
We need automated testing for metrics such as speed, response time, reliability, resource usage, and scalability of the app given an expected workload.

**To implement**

- [x] [Espresso](https://developer.android.com/studio/test/espresso-test-recorder) automated integration tests
- [ ] [Apache JMeter ](https://jmeter.apache.org/)- analyzing and measuring the performance on the API
- [x] [Gherkin](https://www.functionize.com/blog/what-is-gherkin-how-do-you-write-gherkin-tests/) tests 

SubTask

- [ ] #682

**Comment by pld** [comment]
Integration test actions here might be useful, https://github.com/google/android-fhir/blob/master/.github/workflows/ci.yml

**Comment by pld** [comment]
@Mstjamush is this the issue related to the gherkin intergation tests?

**Comment by Mstjamush** [comment]
@pld Yes.

**Comment by pld** [comment]
Let's make sure to test high and variable latency connections

**Comment by f-odhiambo** [comment]
**Update Jan 24th 2022**
For this CI pieces, after QA test are written, will need to document the feedback and then add them to the review process , where enhancement/bug fix tickets will be worked on, PRs are raised to address identified issues before  shipping , pushing  pre-release or final release

**Comment by pld** [comment]
I don't see that as related to CI, since that is not automate but more process.

Can we add the CI with a single test for now? Then as we add new tests they'll go into the existing CI process.

**Comment by f-odhiambo** [comment]
**Update Feb 25th, 2022**

LOE estimated to 3 weeks for completion of the implementation

**Comment by pld** [comment]
OK, given that LOE what is the timeline, i.e. what the expected date of completion?
