### ISSUE TITLE
Quest v0.2 / G6PD : Update the workflow for G6PD test to move from Testing , Results then back to profile

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#970]
**Name of feature to enhance**
Update the workflow for the G6PD workflow to be sequenced in the following order i.e 

**Description of feature**
N/A

**Describe the enhancement**
**Current flow** 
Enrol user -> Go to Patient -> Add test - > Complete test questionnaire and submit  ->  Go back to patient profile 

**Desired flow** 
Enrol user -> Go to Patient -> Add test - > Complete test questionnaire and submit  -> View The results  -> Go back to patient profile 

**Screenshots - Desired flow**

1. Go to Patielt List 
<img src="https://user-images.githubusercontent.com/4540684/150290980-dfdb41bd-2144-456a-9354-3b551bee5ec5.png" width="200" height="400" />

2. Enroll Client 
<img src="https://user-images.githubusercontent.com/4540684/150290995-ad777826-fb6a-4d2f-be43-341856198358.png" width="200" height="400" />

3. Select Client and conduct Test 
<img src="https://user-images.githubusercontent.com/4540684/150291003-07bcf1db-4766-4b29-be13-b0abe4c07e8e.png" width="200" height="400" />

4. Open Test Questionnaire 
<img src="https://user-images.githubusercontent.com/4540684/150291028-b6fad868-18d4-4c34-ac50-e89e80ab272c.png" width="200" height="400" />

5. Complete Test Questionnaire 
<img src="https://user-images.githubusercontent.com/4540684/150291032-82d8a608-466c-422c-9d86-3cd45edf42f3.png" width="200" height="400" />

6. On submit , get test results , we can add a 'DONE' button to take you back to Patient Profile 
<img src="https://user-images.githubusercontent.com/4540684/150291042-5dae9c48-3948-4e9f-aef7-67fd94579d53.png" width="200" height="400" />

7. View Patient Priofiule with latest test results 
<img src="https://user-images.githubusercontent.com/4540684/150291057-60edf02a-40ea-47f5-b338-a32fab739dde.png" width="200" height="400" />

8. Go back to Patient List 
<img src="https://user-images.githubusercontent.com/4540684/150291067-8f3e2362-c99f-4326-b84a-04d1b6554afc.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
@maimoonak Do we have a PR linked to this issue ?

**Comment by maimoonak** [comment]
Merged with https://github.com/opensrp/fhircore/pull/969

**Comment by pld** [comment]
closed by #969
