### ISSUE TITLE
Quest v0.2 / G6PD : Multi-Language support update in G6PD app for widgets 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#973]
**Describe the bug**
Not all form widget and test are fully translated post language switching in Quest/G6PD 

**To Reproduce**
1. Go to app setting 
2. Switch from English to Swahili
3. Go to the app menus, or questionnaire , or edit patient profile 

**Expected behavior**
Add language translation for all Text and in widgets (Dropdown select/ Radio buttons)

**Screenshots**
<img src="https://user-images.githubusercontent.com/4540684/150491260-12eb6902-f68b-4751-b55a-05c409681354.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/150491271-5d4438a2-d7ee-4e08-af1d-8276908059ee.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/150491276-50f2d115-213d-46c4-8c58-177b0623e616.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/150491281-74c7f11f-46c7-41d9-91c4-0142711dda2a.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/150491285-0f0ec0d0-8e7c-4b65-bee2-9bd070db69d4.png" width="200" height="400" />

**Smartphone (please complete the following information):**
 - Device: Emulator or Physical device 

**Additional context**
Some related issues on SDK - https://github.com/google/android-fhir/issues?q=author%3Andegwamartin+

**Comment by ndegwamartin** [comment]
@f-odhiambo for this one we only need to translate the Questionnaire on the FHIR server with the translations and the Quest application will automatically pick this up

**Comment by ndegwamartin** [comment]
What is not implemented yet however is internationalisation for the content on the configuration files where some carry human readable texts. We can create a separate ticket around this for tracking discussions and implementation on the way forward there

**Comment by ndegwamartin** [comment]
@f-odhiambo we are currently working with Allan on this broken down in two parts: Bundling the signed APK and Using CI to trigger the process, create a Github tag and upload it as an asset cc @pld

**Comment by pld** [comment]
That's a good point, what existing standards can we follow for i18n of human readable text in config files?

**Comment by ndegwamartin** [comment]
We could potentially implement something similar to what we have on ANC/Native Forms where the configuration files contain place holders while translations are synced as independent files. These would contain the key/values for the different languages.

Alternatively we could explore a FHIR like approach where the translations are embedded within the configuration file itself 

cc @f-odhiambo @ellykits

**Comment by ndegwamartin** [comment]
> We could potentially implement something similar to what we have on ANC/Native Forms where the configuration files contain place holders while translations are synced as independent files. These would contain the key/values for the different languages.
> 
> Alternatively we could explore a FHIR like approach where the translations are embedded within the configuration file itself
> 
> cc @f-odhiambo @ellykits

Discussion on this has moved [here](https://github.com/opensrp/fhircore/issues/987)

**Comment by f-odhiambo** [comment]
Closing this tickets and moving to https://github.com/opensrp/fhircore/issues/987
