### ISSUE TITLE
Quest v0.2 : Add ability to edit pre-conditional check in Edit Patient profile 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#981]
**Name of feature to enhance**
Pre-populate conditional check during edit of patient profile 

**Description of feature**
An example  - "Is Pregnant check", this check is stored as a condition and currently we are unable to pre-populate condition data in the questionnaire.

**Screenshot**
<img src="https://user-images.githubusercontent.com/4540684/150753501-5c49771d-e807-4152-9edf-0f8b04022189.png" width="200" height="400" />

**Acceptance criteria** 
The following fields have been problematic 
- [ ] Gender - Quest
- [ ] Is Pregnant?  - Quest/G6PD
- [ ] Occupation  - Quest/G6PD

**Comment by pld** [comment]
This looks like an error, is this a FHIRCore or an SDC issue?
