### ISSUE TITLE
Quest - Update QR display and edit functionality with performant option

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#991]
Previously, we had to use population just to correctly map the QuestionnaireResponse and Questionnaire due to missing answers. However, this seems to have been fixed [here](https://github.com/google/android-fhir/pull/926) and we can revert to providing the QuestionnaireResponse as it is

**Comment by maimoonak** [comment]
After reafctoring and removing some code on fhircore it is found that ResourceMapper has some code to init fhir-path that is now taking time for first time init. Once First time init is done it works fast.

```
  private val fhirPathEngine: FHIRPathEngine =
    with(FhirContext.forR4()) {
      FHIRPathEngine(HapiWorkerContext(this, DefaultProfileValidationSupport(this)))
    }
```

**Comment by maimoonak** [comment]
SDK -> questionnaire-viewmodel -> L83 -> QuestionnaireResponseValidator -> L104 causes app crash due to assertion which does not handle the case if url is null
```
require(
      questionnaireResponse.questionnaire == null ||
        questionnaire.url == questionnaireResponse.questionnaire
    ) {
      "Mismatching Questionnaire ${questionnaire.url} and QuestionnaireResponse (for Questionnaire ${questionnaireResponse.questionnaire})"
    }
```

**Comment by maimoonak** [comment]
https://github.com/google/android-fhir/pull/1106 PR on SDK to use cached fhir-context in code

**Comment by maimoonak** [comment]
Login screen with app loaded with FhirContext and FhirPathEngine
Total = 591.84 Megabytes
FhirContext = 67+ MB
FhirPathEngine = 100+ MB

![Screenshot from 2022-02-03 23-39-32](https://user-images.githubusercontent.com/4829880/152407681-f04766ce-5720-4ac0-990e-51441eeedee7.png)

**Comment by maimoonak** [comment]
Without FhirPathEngine it is brought down to BUT this means that QuestionnaireActivity would take time
Total = 8.3787 Megabytes
![Screenshot from 2022-02-03 23-51-00](https://user-images.githubusercontent.com/4829880/152409389-cb5b2a54-fdef-41f8-b98c-feeb20565bd8.png)
