### ISSUE TITLE
Add correct spacing and padding for the ANC Patient register and search filtering  of Reports

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#992]
**Name of feature to enhance**
ANC Register and Search filter for mADX patient selection
 
**Description of feature**
Add correct spacing and padding for the ANC Patient register and search filtering views

**Mocks  - desired UX**
<img src="https://user-images.githubusercontent.com/4540684/151353926-998b2592-a2e0-4184-8494-c54aca95ca43.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/151353908-62448715-eb96-455b-8150-6ca79e2f5db4.png" width="200" height="400" />

**Comment by FikriMilano** [comment]
@f-odhiambo do you mean that odd bottom thing?

<img src="https://user-images.githubusercontent.com/62053304/157441057-c4ae8cee-0dd7-4e3d-9058-3aec43a6f5f3.png" width="256">

**Comment by f-odhiambo** [comment]
yes this page is not properly padded and there is an overlap in page resources

**Comment by FikriMilano** [comment]
Okay, got it

**Comment by FikriMilano** [comment]
@f-odhiambo should we remove the `16 RESULT(S)` as well?

<img src="https://user-images.githubusercontent.com/62053304/158100401-b67c44b5-c52d-4317-97ed-de1eebd9a432.png" width="256">

**Comment by f-odhiambo** [comment]
Let's keep it and have something similar to the below mock 

<img src="https://user-images.githubusercontent.com/4540684/158119960-79667bac-d382-4b76-b167-37914e2db1dc.png" width="300" height="300" />

**Comment by FikriMilano** [comment]
Got it, will keep that
