### ISSUE TITLE
[Roadmap] Implementation of P2P Sync

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#995]
Implementation of the P2P Sync  - Wi-Fi Peer to Peer (P2P), commercially known as Wi-Fi Direct, is a recent industry standard that allows user devices to communicate with each other without requiring a Wi-Fi access point or Internet connectivity

<img width="1423" alt="Screen Shot 2022-02-10 at 11 10 32 AM" src="https://user-images.githubusercontent.com/4540684/153364724-ef55021d-400d-4d0a-ab54-564986108911.png">

Editable version of the above diagram  - https://docs.google.com/drawings/d/1Es5jleQbcFb-GQcN2p5C1JR_Ry1GkH3SpqUX5O9GoJ4/edit 

1. Some running notes [here](https://docs.google.com/document/d/1rdRu0_z3KN7fUUoqq9ZuVsUdhjtf70p13axwjT7ZRVU/edit#heading=h.t7nodeerl1nl) from previous check-in calls 
2. [P2P Handover doc](https://docs.google.com/document/d/18_TeXG8LcrVwxBHbIb2RF_Jo30eVq8JEinGuTngCMfY/edit#heading=h.p4x4gfhhirwy)
3. [LMH P2P Sync Requirements](https://docs.google.com/document/d/1az0vN7KNr9I5OqUv_m7FQ5jBc2JViQ2StaUBxdERee0/edit#heading=h.os5lyem3yuxh)
4. SDK Issue being tracked here issue [#258](https://github.com/google/android-fhir/issues/258)
5. https://github.com/opensrp/fhircore/discussions/691
6. Implementation ticket tracked here  : CHW/ANC - Allow for P2P Sync #281
7. https://github.com/google/android-fhir/issues/258

**Additional Context** 

Liberia Location hierarchy: Country>> county>>District>>Health Facility>>Village. 
1. District Health Officer (DHO) - at the district level. 
2. Community Health Services Supervisor (CHSS) - at the Health facility level
3. Community Health Assistant (CHA) - at the community level

**Comment by f-odhiambo** [comment]
**FHIR Core Tickets** 
1. #465  - Add Interface for Sync competition status/ Receipt page 
2. Review  of Wifi Direct Lib - Wi-Fi Direct (peer-to-peer or P2P) [overview](https://developer.android.com/guide/topics/connectivity/wifip2p#api-overview)
3. Implementation of the Wi-Fi Direct P2P Sync Module
3. Implementation of the P2P Sync module with SyncPayload module
3. Implementation of the Sender and Receiver Interfaces  - Sender (SyncSenderSession) module , Receiver (SyncReceiverSession) module
4. Conflict Resolutions mechanism module - ConflictResolutionStrategy vs OursConflictResolutionStrategy  
4. Implementation of the Broadcast Receiver - Sync updates  
5. Changes to SQLite DB tables for sync status 


**SDK Tickets** 
1. Review [P2P Support on SDK ](https://docs.google.com/document/d/1X6_FMGVDxkvP6O28u4TPszObwP4aXgkZLn3fFNO_rBM/edit?resourcekey=0-kwdQoxHaq1Kcl1uobn9RtQ#heading=h.x9snb54sjlu9)
2. Update mechanism from PATCH to PUT  or have a hybrid approach for P2P Sync on FHIR Engine and Sync API

**Comment by f-odhiambo** [comment]
NB. This does not include the current issues plaguing the current P2P sync on OpenSRP 

CC @dubdabasoduba @ndegwamartin

**Comment by dubdabasoduba** [comment]
@f-odhiambo @ndegwamartin We want to do some R&D on this. 

- [ ] How to programmatically shut down mobile networks when p2p is initiated. 
- [ ] Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct.

**Comment by f-odhiambo** [comment]
Related to Tasking & P2P
1. How does information synchronize between the CHW and the facility ? 
2. Do we need to support peer-to-peer sync?
3. Do we need to be able to assign tasks to a particular user in the health facility?

**Comment by f-odhiambo** [comment]
> @f-odhiambo @ndegwamartin We want to do some R&D on this.
> 
> * [ ]  How to programmatically shut down mobile networks when p2p is initiated.
> * [ ]  Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct.

@dubdabasoduba to be done done as part of #998

**Comment by ekigamba** [comment]
![Copy of P2P Sync Architecture (Draft) - Jan 28th 2022](https://user-images.githubusercontent.com/31766075/154007979-3748a4c3-18fb-4048-9e47-c658d9bfddaa.png)

I have updated the diagram with a proposed design based on further discussions. The new design separates FHIR Core implementation specific details from the p2p library making it reusable for other non-FHIRCore specific applications.

I will be updating this further to make it clearer

cc @Rkareko

**Comment by f-odhiambo** [comment]
**Francis**
**Questions**
1. Is it possible to have the P2P sync module to be activated/enabled on demand ?
2. Could we make  bundling of P2P lib/module optional depending on app?
3. How easy would it to decouple P2P module from FHIR Core  in future?


**Ans**. 
    - This is currently not possible as the code need to be bundled on FHIR core . Loading of libraries may introduce more complexity in understanding the codebase  
Using gradle no currently known way to load libs/modules dynamically via Dynamic features - Feature dependent on app. : On demand download of features
         - To be considered in future after app configuration / dynamic workflows are complete
         - There are known issues with writing instrumented test
         - It makes the code complex to understand
        - Implementation of UI will not be done using the conventional way/will not straightforward but via a dynamic mechanism based on a predetermined decision tree/workflow - e.g launching activities 

**Kitoto**
1. The way to build this or approach this would be to 
2. Have P2P Sync module built  as a separate module/library on a separate repo
3. Include it in FHIR Core  as separate lib.
4. The module will only be enabled using app level configs
5. The P2P sync module will be Included in Engine module via gradle

**Declare P2P workflow**
1. Application downloads composition resource
2. Composition resource has workflow points for the app
3. Workflow points has P2P workflow
4. If P2P workflow is present for app it is enabled to start at either side menu or bottom nav

**Comment by pld** [comment]
mvp complete closing
