### ISSUE TITLE
P2P - Review of Wifi Direct Lib - Wi-Fi Direct (peer-to-peer or P2P) overview for Discovery ,Connection & Data transfer

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#998]
**Action items** 
1. Review Wifi Direct Lib - Wi-Fi Direct (peer-to-peer or P2P) [overview](https://developer.android.com/guide/topics/connectivity/wifip2p#api-overview) for Discovery ,Connection &  Data transfer
2. Document Findings here in this ticket 
3. How do we block any other sync/ connection (data/wifi) during p2p sync 
          - How to programmatically shut down mobile/wifi networks when p2p is initiated, to avoid server update
          - Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct

**Next Steps**
1. To integrate and incorporate wifi direct lib that can be loaded via gradle
2. Integrate it to P2P sync module  
3. Add components to FHIR Engine to do 
          - Conflict resolution
          - Broadcasting of messages
          - Error handling
          - Sync  - PUT/PATCH to the Android FHIR Engine Sync module 
          - Auth  - Sync only in same team / location

**Acceptance criteria** 
- [x] Check to see that the previous implementation of  wifi-direct can be able to do discovery , connection and transfer https://github.com/opensrp/p2p. 
- [x] See is we can load the wifi direct lib via gradle and incorporated on demand to a FHIR Core based app - Enabled or Disabled via config

**Comment by f-odhiambo** [comment]
@Rkareko You can check this out https://github.com/opensrp/p2p. Decode had started on this but did not complete it .

**Comment by Rkareko** [comment]
>  How to programmatically shut down mobile networks when p2p is initiated

There does not seem to be a way to do this without user interation i.e [popping up a system setting dialog where users can turn mobile data on or off by themselves](https://stackoverflow.com/a/20700138) with the following code snippet

```
Intent intent = new Intent();
intent.setClassName("com.android.settings",
     "com.android.settings.Settings$DataUsageSummaryActivity");
startActivity(intent);
```

This [quora post](https://qr.ae/pGjyIy) goes on to say `For Android, You cannot access mobile data on/off programmatically above android 4.4. It has been made stopped for security reasons.`

**Comment by Rkareko** [comment]
> Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct

The networkUtils class in client core has an [isNetworkAvailable](https://github.com/opensrp/opensrp-client-core/blob/master/opensrp-app/src/main/java/org/smartregister/util/NetworkUtils.java#L17-L30) function that we could re use for this check.

It's not clear why we need to do this check i.e if the phone is connected to the internet via wifi do we prevent normal client-server sync from happening?

**Comment by f-odhiambo** [comment]
@dubdabasoduba can you briefly expound on this point  - How to programmatically shut down mobile/wifi networks when p2p is initiated, to avoid server update

**Comment by f-odhiambo** [comment]
> @dubdabasoduba can you briefly expound on this point - How to programmatically shut down mobile/wifi networks when p2p is initiated, to avoid server update



> > Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct
> 
> The networkUtils class in client core has an [isNetworkAvailable](https://github.com/opensrp/opensrp-client-core/blob/master/opensrp-app/src/main/java/org/smartregister/util/NetworkUtils.java#L17-L30) function that we could re use for this check.
> 
> It's not clear why we need to do this check i.e if the phone is connected to the internet via wifi do we prevent normal client-server sync from happening?

@dubdabasoduba can you briefly expound on this point - How to programmatically shut down mobile/wifi networks when p2p is initiated, to avoid server update

**Comment by f-odhiambo** [comment]
> > Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct
> 
> The networkUtils class in client core has an [isNetworkAvailable](https://github.com/opensrp/opensrp-client-core/blob/master/opensrp-app/src/main/java/org/smartregister/util/NetworkUtils.java#L17-L30) function that we could re use for this check.
> 
> It's not clear why we need to do this check i.e if the phone is connected to the internet via wifi do we prevent normal client-server sync from happening?

@dubdabasoduba can you briefly expound on this point - How to programmatically shut down mobile/wifi networks when p2p is initiated, to avoid server update

**Comment by Rkareko** [comment]
>  Check to see that the previous implementation of wifi-direct can be able to do discovery , connection and transfer https://github.com/opensrp/p2p.

Tesing with a Samsung Galaxy J5  Android 5.1.1 and a Samsung Galaxy Tab Active Pro tablet running Android 11.
So far the implementation on both devices is able to discover peers as well as connect with each other.

However on a Samsung galaxy A51 running android 11 peer discovery is failing yet on the phone settings wifi-direct is enabled and shows available devices.

**Comment by Rkareko** [comment]
Establishing a connection between the 2 devices is failing with a `Host is unresolved: /192.168.49.1` error. More investigations are required to figure out why it's failing yet the receiver's ip appears to have been correctly captured by the sender device.

**Comment by dubdabasoduba** [comment]
> > Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct
> 
> The networkUtils class in client core has an [isNetworkAvailable](https://github.com/opensrp/opensrp-client-core/blob/master/opensrp-app/src/main/java/org/smartregister/util/NetworkUtils.java#L17-L30) function that we could re use for this check.
> 
> It's not clear why we need to do this check i.e if the phone is connected to the internet via wifi do we prevent normal client-server sync from happening?

@Rkareko @f-odhiambo We need to check for network connection then prevent the server sync by either doing the following

- Closeout any connections (Wireless, mobile network) to prevent sync.
- Disable the automatic/manual sync triggers to the server.

**Comment by Rkareko** [comment]
> > > Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct
> > 
> > 
> > The networkUtils class in client core has an [isNetworkAvailable](https://github.com/opensrp/opensrp-client-core/blob/master/opensrp-app/src/main/java/org/smartregister/util/NetworkUtils.java#L17-L30) function that we could re use for this check.
> > It's not clear why we need to do this check i.e if the phone is connected to the internet via wifi do we prevent normal client-server sync from happening?
> 
> @Rkareko @f-odhiambo We need to check for network connection then prevent the server sync by either doing the following
> 
> * Closeout any connections (Wireless, mobile network) to prevent sync.
> * Disable the automatic/manual sync triggers to the server.

@dubdabasoduba I think we should look into how to Disable the automatic sync to the server when the user initiates the P2P sync workflow. Depending on how the UI is designed it may not be possible to trigger manual sync once P2P workflow is initiated. 

`Closeout any connections (Wireless, mobile network) ` is something that we may not be in control of and there may not be a straightforward way to achieve this for different devices and OS versions

**Comment by Rkareko** [comment]
> However on a Samsung galaxy A51 running android 11 peer discovery is failing yet on the phone settings wifi-direct is enabled and shows available devices.

An interesting finding is that to fix this issue, `Location Services` on the device has to be turned on.

**Comment by f-odhiambo** [comment]
**Francis**
**Questions**
1. Is it possible to have the P2P sync module to be activated/enabled on demand ?
2. Could we make  bundling of P2P lib/module optional depending on app?
3. How easy would it to decouple P2P module from FHIR Core  in future?


**Ans**. 
    - This is currently not possible as the code need to be bundled on FHIR core . Loading of libraries may introduce more complexity in understanding the codebase  
Using gradle no currently known way to load libs/modules dynamically via Dynamic features - Feature dependent on app. : On demand download of features
         - To be considered in future after app configuration / dynamic workflows are complete
         - There are known issues with writing instrumented test
         - It makes the code complex to understand
        - Implementation of UI will not be done using the conventional way/will not straightforward but via a dynamic mechanism based on a predetermined decision tree/workflow - e.g launching activities 

**Kitoto**
1. The way to build this or approach this would be to 
2. Have P2P Sync module built  as a separate module/library on a separate repo
3. Include it in FHIR Core  as separate lib.
4. The module will only be enabled using app level configs
5. The P2P sync module will be Included in Engine module via gradle

**Declare P2P workflow**
1. Application downloads composition resource
2. Composition resource has workflow points for the app
3. Workflow points has P2P workflow
4. If P2P workflow is present for app it is enabled to start at either side menu or bottom nav


CC @Rkareko

**Comment by Rkareko** [comment]
The following issues were encountered during testing of the p2p sync functionality : - 

1. Sync payload serialization was failing. The fix is on this [PR](https://github.com/opensrp/p2p/pull/2)
2. The receiving device was getting an empty string as the sync payload instead of the content sent by the sender device. This is fixed on this [PR](https://github.com/opensrp/p2p/pull/3)
3. After the first socket connection between the peers is established, it appears any subsequent socket connections between the same peers fails. So far the workaround has been to manually  disable the wifi direct peer to peer connection before trying to establish a socket connection that is required for data transfer.

**Comment by dubdabasoduba** [comment]
> > However on a Samsung galaxy A51 running android 11 peer discovery is failing yet on the phone settings wifi-direct is enabled and shows available devices.
> 
> An interesting finding is that to fix this issue, `Location Services` on the device has to be turned on.

Do we need to always check this and alert the user to turn it on? Also just to check we are requesting location

> > > > Confirm if the device is connected to a wifi network with internet access, the app does not try to sync to the server but only does p2p via wifi direct
> > > 
> > > 
> > > The networkUtils class in client core has an [isNetworkAvailable](https://github.com/opensrp/opensrp-client-core/blob/master/opensrp-app/src/main/java/org/smartregister/util/NetworkUtils.java#L17-L30) function that we could re use for this check.
> > > It's not clear why we need to do this check i.e if the phone is connected to the internet via wifi do we prevent normal client-server sync from happening?
> > 
> > 
> > @Rkareko @f-odhiambo We need to check for network connection then prevent the server sync by either doing the following
> > 
> > * Closeout any connections (Wireless, mobile network) to prevent sync.
> > * Disable the automatic/manual sync triggers to the server.
> 
> @dubdabasoduba I think we should look into how to Disable the automatic sync to the server when the user initiates the P2P sync workflow. Depending on how the UI is designed it may not be possible to trigger manual sync once P2P workflow is initiated.
> 
> `Closeout any connections (Wireless, mobile network) ` is something that we may not be in control of and there may not be a straightforward way to achieve this for different devices and OS versions

Makes sense.  Is this something we can use a flag to control i.e When the wifi direct handshake is initiated we disable the server sync? Then when (for any reason) this handshake is deactivated we re-enable the server sync.

**Comment by pld** [comment]
Agree with both these suggestions, I think it's reasonable to require Location Services to be activated, most health projects need to collect GPS anyhow

**Comment by f-odhiambo** [comment]
Marking this as DONE
